Update add_user

diff --git a/usr/local/sbin/add_user b/usr/local/sbin/add_user
--- a/usr/local/sbin/add_user
+++ b/usr/local/sbin/add_user
@@ -16,13 +16,12 @@ exec 2>&1;
 #
 # Script must run as root or via sudo
 #
-# if [ "$(id -un)" != "root" ]; then
-# 	echo "";
-# 	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-# 	sleep 30;
-# 	exit 1;
-# el
-if [ -z "${USER_NAME}" ]; then
+if [ "$(id -un)" != "root" ]; then
+	echo "";
+	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+	sleep 30;
+	exit 1;
+elif [ -z "${USER_NAME}" ]; then
 	echo "";
 	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: No Username defined (Required)";
 	echo "                       |";
