Update certbot_renew_all

diff --git a/usr/local/sbin/certbot_renew_all b/usr/local/sbin/certbot_renew_all
--- a/usr/local/sbin/certbot_renew_all
+++ b/usr/local/sbin/certbot_renew_all
@@ -34,13 +34,6 @@ else
 	# ------------------------------------------------------------
 	# Require that certbot be installed, already
 	if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Command 'certbot' not found";
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Please install certbot, then re-run this script";
-		echo "";
-		exit 1;
-	else
 		# ------------------------------------------------------------
 		if [ -n "$1" ] && [ "$1" == "-y" || "$1" == "--yes" || "$1" == "--force" ]; then
 			# Allow a force-command to skip dry-run mode
@@ -51,7 +44,15 @@ else
 			echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Calling  [ certbot renew --noninteractive --force-renewal --dry-run; ]  ...";
 			certbot renew --noninteractive --force-renewal --dry-run;
 		fi;
-
+	else
+		# ------------------------------------------------------------
+		# Error - certbot command not command
+		echo "";
+		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Command 'certbot' not found";
+		echo "";
+		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Please install certbot, then re-run this script";
+		echo "";
+		exit 1;
 	fi;
 
 fi;
