Update certbot_add_wildcard

diff --git a/usr/local/sbin/certbot_add_wildcard b/usr/local/sbin/certbot_add_wildcard
--- a/usr/local/sbin/certbot_add_wildcard
+++ b/usr/local/sbin/certbot_add_wildcard
@@ -43,34 +43,32 @@ else
 
 		DOMAIN_NAME="$1";
 
-		# ------------------------------------------------------------
-		#
-		#
-		echo "";
-		# echo "Info:  Required package(s):  [ nginx-full, python-certbot-nginx ]";
-		echo "Info:  Required package(s):  [ python-certbot-nginx ]";
-		echo "  |";
-		read -p "  |--> Install/Update these package(s), now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
-		echo "";
-		if [[ $REPLY =~ ^[Yy]$ ]]; then
-		
-			if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
-				# Prep for installation of required package(s)
-				# apt-get -y update;
-				# apt-get -y install dpkg-dev;
-				# apt-get -y install software-properties-common;
-				# add-apt-repository -y ppa:nginx/stable;
-				add-apt-repository -y ppa:certbot/certbot;
-				apt-get -y update;
-				# Install required package(s)
-				apt-get -y install python-certbot-nginx;
-				# apt-get -y install nginx-full;
-				# apt-get -y clean && apt -y autoremove;
-
-				certbot --server https://acme-v02.api.letsencrypt.org/directory -d *.${DOMAIN_NAME} --manual --preferred-challenges dns-01 certonly;
-
+		if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+			# echo "Info:  Required package(s):  [ nginx-full, python-certbot-nginx ]";
+			echo "";
+			echo "Info:  Required package(s):  [ python-certbot-nginx ]";
+			echo "  |";
+			read -p "  |--> Install/Update these package(s), now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
+			echo "";
+			if [[ $REPLY =~ ^[Yy]$ ]]; then
+				if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+					# Prep for installation of required package(s)
+					# apt-get -y update;
+					# apt-get -y install dpkg-dev;
+					# apt-get -y install software-properties-common;
+					# add-apt-repository -y ppa:nginx/stable;
+					add-apt-repository -y ppa:certbot/certbot;
+					apt-get -y update;
+					# Install required package(s)
+					apt-get -y install python-certbot-nginx;
+					# apt-get -y install nginx-full;
+					# apt-get -y clean && apt -y autoremove;
+				fi;
 			fi;
+		fi;
 
+		if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+			certbot --server https://acme-v02.api.letsencrypt.org/directory -d *.${DOMAIN_NAME} --manual --preferred-challenges dns-01 certonly;
 		fi;
 
 	fi;
