Update ddns_ufw_update

diff --git a/usr/local/sbin/ddns_ufw_update b/usr/local/sbin/ddns_ufw_update
--- a/usr/local/sbin/ddns_ufw_update
+++ b/usr/local/sbin/ddns_ufw_update
@@ -303,123 +303,127 @@ else
 								echo "Debug: WHITELIST_HOSTS_COMMA_DELIMITED = [ ${WHITELIST_HOSTS_COMMA_DELIMITED} ]";
 							fi;
 
-							# For each substring in a comma delimited string
-							for WHITELIST_HOST in $(echo ${WHITELIST_HOSTS_COMMA_DELIMITED} | sed "s/,/ /g"); do
+							if [ "${WHITELIST_PROTOCOL}" == "tcp" ] || [ "${WHITELIST_PROTOCOL}" == "udp" ]; then
 
-								if [ ${DEBUG_MODE} -eq 1 ]; then
-									echo "Debug: WHITELIST_HOST = [ ${WHITELIST_HOST} ]";
-								fi;
-
-								RESOLVED_IPv4="";
-								RESOLVED_CIDRv4="";
-
-								if [ "${WHITELIST_HOST}" == "0.0.0.0" ] || [ "${WHITELIST_HOST}" == "0.0.0.0/0" ] || [ "$(echo ${WHITELIST_HOST} | tr '[:upper:]' '[:lower:]';)" == "any" ]; then
-
-									# Allow requests originating from the "default route" (e.g. allow incoming requests from any network address, which is 0.0.0.0/0 in CIDRv4 and ::/0 in CIDRv6)
-									RESOLVED_IPv4="0.0.0.0";
-									RESOLVED_CIDRv4="0.0.0.0/0";
-
-								else
-
-									# Check if host if in IPv4 or CIDRv4 syntax, already
-									
-									if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
-										# Host is formatted using IP or CIDR notation (address resolution not required)
-										if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
-											# Add "/32" to the end of string, if no CIDR notation is found - ex: 192.168.0.1/32
-											RESOLVED_IPv4="${WHITELIST_HOST}";
-											RESOLVED_CIDRv4="${WHITELIST_HOST}/32";
-										else
-											# Valid IPv4 in CIDR Notation - ex: 192.168.0.0/16
-											RESOLVED_IPv4=$(echo ${WHITELIST_HOST} | cut -d"/" -f1);
-											RESOLVED_CIDRv4="${WHITELIST_HOST}";
-										fi;
-									else
-										# Host is NOT formatted using IP or CIDR notation (address resolution is required)
-										HOST_ADDRESS_LOOKUP="$(dig +short "${WHITELIST_HOST}" | tail -n 1 2>'/dev/null';)";
-										if [[ ${HOST_ADDRESS_LOOKUP} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
-											# IPv4 resolved successfully
-											RESOLVED_IPv4="${HOST_ADDRESS_LOOKUP}"; 
-											RESOLVED_CIDRv4="${HOST_ADDRESS_LOOKUP}/32"; 
-											WHITELIST_FQDN="${WHITELIST_HOST}";
-										else
-											# ERROR - Unable to resolve host
-											echo "Error:  Address resolution failed for host \"${WHITELIST_HOST}\"";
-											RESOLVED_IPv4=""
-											RESOLVED_CIDRv4="";
-											WHITELIST_FQDN="";
-										fi;
-
-									fi;
-
-								fi;
-
-								# Verify final CIDRv4 address notation
-								if [ -n "${RESOLVED_CIDRv4}" ] && [[ ${RESOLVED_CIDRv4} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
+								# For each substring in a comma delimited string
+								for WHITELIST_HOST in $(echo ${WHITELIST_HOSTS_COMMA_DELIMITED} | sed "s/,/ /g"); do
 
 									if [ ${DEBUG_MODE} -eq 1 ]; then
-										echo "Debug:  RESOLVED_IPv4 = [ ${RESOLVED_IPv4} ]";
-										echo "Debug:  RESOLVED_CIDRv4 = [ ${RESOLVED_CIDRv4} ]";
+										echo "Debug: WHITELIST_HOST = [ ${WHITELIST_HOST} ]";
 									fi;
 
-									PORT_PROTO="${WHITELIST_PORT}/${WHITELIST_PROTOCOL}";
-
-									if [ ${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]+X} ]; then
-										# Existing array-index (CIDRv4) & value (port(s))
-										#   |--> Another host already resolved to this CIDRv4 --> Use check for match on whitelisted-port (within current array-index's value)
-										if [[ ",${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]}," = *",${PORT_PROTO},"* ]]; then
-											# Another host AND port combo already matches this iteration exactly --> skip adding it to the array as it is merely a duplicate
-											echo "" 1>'/dev/null' 2>&1;  # Do nothing
-										else
-											# CIDRv4 index exists, but new port to-whitelist --> add it to array-index's value using comma delimitation
-											RESOLVED_CIDRv4_ARR["${EACH_CIDRv4}"]="${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]},${PORT_PROTO}";
-										fi;
-									else
-										# New array-index (CIDRv4) & value (port)
-										RESOLVED_CIDRv4_ARR+=(["${EACH_CIDRv4}"]="${PORT_PROTO}");
-									fi;
-
-									# ------------------------------------------------------------
-									# BEGIN NGINX ONLY
-									if [ "${EACH_SERVICE_NAME}" == "nginx" ]; then
-										# Add resolved CIDRv4 addresses (IN NGINX COMPILE-ABLE SYNTAX) to config-directory specifically designated to contain resolved DDNS addresses
-										NEXT_NGINX_LINE="";
-										if [ -n "${WHITELIST_FQDN}" ]; then
-											# DEPRECATED METHODOLOGY - Clean up old host whitelist files out of '/etc/nginx/conf.ddns/...'
-											#   |--> Clean up previous methodology where the nginx whitelists (allowed-rulesets) were stored using WHITELIST_HOST and their basename
-											#   |--> Needed upon update to allow CIDRv4 notation in whitelist files (21-Apr-2020) which required a different approach for nginx-conf filenames, as CIDRv4 strings by-definition contain a forward-slash '/' character
-											if [ -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}" ]; then
-												rm -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}";
-											fi;
-											NEXT_NGINX_LINE="allow ${RESOLVED_CIDRv4};  # ${WHITELIST_HOST}";
-										else
-											NEXT_NGINX_LINE="allow ${RESOLVED_CIDRv4};";
-										fi;
-										# Append this line to the total string of lines to put into the nginx service-config-file
-										if [ -z "${EACH_NGINX_DDNS_RESULTS}" ]; then
-											EACH_NGINX_DDNS_RESULTS="${NEXT_NGINX_LINE}";
-										else
-											EACH_NGINX_DDNS_RESULTS="${EACH_NGINX_DDNS_RESULTS}\n${NEXT_NGINX_LINE}";
-										fi;
-									fi;
-									# END NGINX ONLY
-									# ------------------------------------------------------------
-
-								else
-
-									# IPv4 Unable to be resolved - Remove old IPv4 rule(s)
 									RESOLVED_IPv4="";
 									RESOLVED_CIDRv4="";
-									echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
 
-									# !!!  REMOVE LINE FROM FILE - OLD HOST (RESOLVED ADDRESSES FILE)  !!!
-									# if [ -f ${EACH_RESOLVED_FILE} ]; then
-									# 	sed -i.bak /^${WHITELIST_HOST}*/d ${EACH_RESOLVED_FILE};
-									# fi;
+									if [ "${WHITELIST_HOST}" == "0.0.0.0" ] || [ "${WHITELIST_HOST}" == "0.0.0.0/0" ] || [ "$(echo ${WHITELIST_HOST} | tr '[:upper:]' '[:lower:]';)" == "any" ]; then
 
-								fi;
+										# Allow requests originating from the "default route" (e.g. allow incoming requests from any network address, which is 0.0.0.0/0 in CIDRv4 and ::/0 in CIDRv6)
+										RESOLVED_IPv4="0.0.0.0";
+										RESOLVED_CIDRv4="0.0.0.0/0";
 
-							done;
+									else
+
+										# Check if host if in IPv4 or CIDRv4 syntax, already
+										
+										if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
+											# Host is formatted using IP or CIDR notation (address resolution not required)
+											if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
+												# Add "/32" to the end of string, if no CIDR notation is found - ex: 192.168.0.1/32
+												RESOLVED_IPv4="${WHITELIST_HOST}";
+												RESOLVED_CIDRv4="${WHITELIST_HOST}/32";
+											else
+												# Valid IPv4 in CIDR Notation - ex: 192.168.0.0/16
+												RESOLVED_IPv4=$(echo ${WHITELIST_HOST} | cut -d"/" -f1);
+												RESOLVED_CIDRv4="${WHITELIST_HOST}";
+											fi;
+										else
+											# Host is NOT formatted using IP or CIDR notation (address resolution is required)
+											HOST_ADDRESS_LOOKUP="$(dig +short "${WHITELIST_HOST}" | tail -n 1 2>'/dev/null';)";
+											if [[ ${HOST_ADDRESS_LOOKUP} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
+												# IPv4 resolved successfully
+												RESOLVED_IPv4="${HOST_ADDRESS_LOOKUP}"; 
+												RESOLVED_CIDRv4="${HOST_ADDRESS_LOOKUP}/32"; 
+												WHITELIST_FQDN="${WHITELIST_HOST}";
+											else
+												# ERROR - Unable to resolve host
+												echo "Error:  Address resolution failed for host \"${WHITELIST_HOST}\"";
+												RESOLVED_IPv4=""
+												RESOLVED_CIDRv4="";
+												WHITELIST_FQDN="";
+											fi;
+
+										fi;
+
+									fi;
+
+									# Verify final CIDRv4 address notation
+									if [ -n "${RESOLVED_CIDRv4}" ] && [[ ${RESOLVED_CIDRv4} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
+
+										if [ ${DEBUG_MODE} -eq 1 ]; then
+											echo "Debug:  RESOLVED_IPv4 = [ ${RESOLVED_IPv4} ]";
+											echo "Debug:  RESOLVED_CIDRv4 = [ ${RESOLVED_CIDRv4} ]";
+										fi;
+
+										PORT_PROTO="${WHITELIST_PORT}/${WHITELIST_PROTOCOL}";
+
+										if [ ${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]+X} ]; then
+											# Existing array-index (CIDRv4) & value (port(s))
+											#   |--> Another host already resolved to this CIDRv4 --> Use check for match on whitelisted-port (within current array-index's value)
+											if [[ ",${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]}," = *",${PORT_PROTO},"* ]]; then
+												# Another host AND port combo already matches this iteration exactly --> skip adding it to the array as it is merely a duplicate
+												echo "" 1>'/dev/null' 2>&1;  # Do nothing
+											else
+												# CIDRv4 index exists, but new port to-whitelist --> add it to array-index's value using comma delimitation
+												RESOLVED_CIDRv4_ARR["${EACH_CIDRv4}"]="${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]},${PORT_PROTO}";
+											fi;
+										else
+											# New array-index (CIDRv4) & value (port)
+											RESOLVED_CIDRv4_ARR+=(["${EACH_CIDRv4}"]="${PORT_PROTO}");
+										fi;
+
+										# ------------------------------------------------------------
+										# BEGIN NGINX ONLY
+										if [ "${EACH_SERVICE_NAME}" == "nginx" ]; then
+											# Add resolved CIDRv4 addresses (IN NGINX COMPILE-ABLE SYNTAX) to config-directory specifically designated to contain resolved DDNS addresses
+											NEXT_NGINX_LINE="";
+											if [ -n "${WHITELIST_FQDN}" ]; then
+												# DEPRECATED METHODOLOGY - Clean up old host whitelist files out of '/etc/nginx/conf.ddns/...'
+												#   |--> Clean up previous methodology where the nginx whitelists (allowed-rulesets) were stored using WHITELIST_HOST and their basename
+												#   |--> Needed upon update to allow CIDRv4 notation in whitelist files (21-Apr-2020) which required a different approach for nginx-conf filenames, as CIDRv4 strings by-definition contain a forward-slash '/' character
+												if [ -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}" ]; then
+													rm -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}";
+												fi;
+												NEXT_NGINX_LINE="allow ${RESOLVED_CIDRv4};  # ${WHITELIST_HOST}";
+											else
+												NEXT_NGINX_LINE="allow ${RESOLVED_CIDRv4};";
+											fi;
+											# Append this line to the total string of lines to put into the nginx service-config-file
+											if [ -z "${EACH_NGINX_DDNS_RESULTS}" ]; then
+												EACH_NGINX_DDNS_RESULTS="${NEXT_NGINX_LINE}";
+											else
+												EACH_NGINX_DDNS_RESULTS="${EACH_NGINX_DDNS_RESULTS}\n${NEXT_NGINX_LINE}";
+											fi;
+										fi;
+										# END NGINX ONLY
+										# ------------------------------------------------------------
+
+									else
+
+										# IPv4 Unable to be resolved - Remove old IPv4 rule(s)
+										RESOLVED_IPv4="";
+										RESOLVED_CIDRv4="";
+										echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
+
+										# !!!  REMOVE LINE FROM FILE - OLD HOST (RESOLVED ADDRESSES FILE)  !!!
+										# if [ -f ${EACH_RESOLVED_FILE} ]; then
+										# 	sed -i.bak /^${WHITELIST_HOST}*/d ${EACH_RESOLVED_FILE};
+										# fi;
+
+									fi;
+
+								done;
+
+							fi;
 
 						fi;
 
