Update ddns_ufw_update

diff --git a/usr/local/sbin/ddns_ufw_update b/usr/local/sbin/ddns_ufw_update
--- a/usr/local/sbin/ddns_ufw_update
+++ b/usr/local/sbin/ddns_ufw_update
@@ -201,6 +201,9 @@ else
 	# Array to store store CIDRv4 addresses which are newly-resolved as-of this script's runtime
 	unset RESOLVED_CIDRv4_ARR; declare -A RESOLVED_CIDRv4_ARR; # [Re-]Instantiate bash array
 	
+	# Array to store previously resolved service CIDRv4 addresses and their contents
+	unset PREVIOUSLY_RESOLVED_CONTENTS_ARR; declare -A PREVIOUSLY_RESOLVED_CONTENTS_ARR; # [Re-]Instantiate bash array
+
 	# ------------------------------------------------------------
 	#
 	# Apply Whitelist on a per-service basis
@@ -217,25 +220,20 @@ else
 		EACH_NGINX_DDNS_CONF="${NGINX_CONF_DDNS}/${EACH_SERVICE_NAME}";
 		EACH_NGINX_DDNS_RESULTS="";
 
-		EACH_WHITELIST_FILE="${DIRNAME_LOCAL_CONFIG}/${EACH_SERVICE_NAME}";
 
-		# Define the location of the file to output resolved ipv4's to
-		EACH_RESOLVED_FILE="${EACH_WHITELIST_FILE}.resolved";
-		if [ ! -f "${EACH_RESOLVED_FILE}" ]; then
+		EACH_WHITELIST_FILE="${DIRNAME_LOCAL_CONFIG}/${EACH_SERVICE_NAME}"; # Define the location for the whitelist config-files
+		EACH_RESOLVED_FILE="${EACH_WHITELIST_FILE}.resolved"; # Define the location to save resolve CIDRv4 addresses to
+
+		if [ -f "${EACH_RESOLVED_FILE}" ]; then
+			# Read in previously-resolved addresses on a per-service basis
+			PREVIOUSLY_RESOLVED_CONTENTS_ARR+=(["${EACH_SERVICE_NAME}"]="$(cat ${EACH_RESOLVED_FILE})");
+		else
 			touch "${EACH_RESOLVED_FILE}";
 		fi;
 
 		# Only whitelist services which are in-use by this machine
 		SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${EACH_SERVICE_NAME}.service" | grep "^${EACH_SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
 		if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service exists locally & is currently active
-
-		# ### (DEPRECATED METHODOLOGY) Search for [ specific users ] running [ specific processes ]
-		# test ${DEBUG_MODE} -eq 1 && echo "MATCHED_PROCS_PGREP Call = [ pgrep -u \"${EACH_RUNTIME_USER}\" \"${EACH_SERVICE_NAME}\"; ]";
-		# MATCHED_PROCS_PGREP=$(pgrep -u "${EACH_RUNTIME_USER}" "${EACH_SERVICE_NAME}" 2>/dev/null;);
-		# MATCHED_PROCS_PGREP_TRIMMED="$(echo -e "${MATCHED_PROCS_PGREP}" | tr '\n' ' ' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' 2>/dev/null;)";
-		# if [ -n "${MATCHED_PROCS_PGREP_TRIMMED}" ]; then # Service exists locally
-		# 	test ${DEBUG_MODE} -eq 1 && echo "MATCHED_PROCS_PS Call = [ ps --format \"pid,fname,user,%cpu,%mem,maj_flt,cmd\" --no-headers -p \"${MATCHED_PROCS_PGREP_TRIMMED}\" | wc -l; ]";
-		# 	MATCHED_PROCS_PS=$(ps --format "pid,fname,user,%cpu,%mem,maj_flt,cmd" --no-headers -p "${MATCHED_PROCS_PGREP_TRIMMED}" | wc -l;);
 
 			MATCHED_PROCS_PS=$(ps --format "pid,fname,user,%cpu,%mem,maj_flt,cmd" --no-headers -U "${EACH_RUNTIME_USER}" | wc -l;);
 
@@ -265,6 +263,7 @@ else
 					sed '/^[[:space:]]*$/d' ${EACH_WHITELIST_FILE} | \
 					sed '/^[[:space:]]*#/d' | \
 					while read EACH_WHITELIST_LINE;	do
+
 						if [ -n "${EACH_WHITELIST_LINE}" ]; then
 
 							HAYSTACK_TO_SEARCH="${EACH_WHITELIST_LINE}";
@@ -272,10 +271,18 @@ else
 							ALL_NEEDLES_FOUND="${HAYSTACK_TO_SEARCH//[^${CHAR_DELIMITER}]}"; # Required middleman var
 							NEEDLE_TOTAL_COUNT=${#ALL_NEEDLES_FOUND};
 
-							WHITELIST_PROTOCOL=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 1 ]; then MM="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f1)"; WHITELIST_PROTOCOL="${MM,,}"; fi; # IP Protocol must be a lowercase string matching 'tcp' or 'udp'
+							# IP Protocol must be a lowercase string matching 'tcp' or 'udp'
+							WHITELIST_PROTOCOL=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 1 ]; then MM="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f1)"; WHITELIST_PROTOCOL="${MM,,}"; fi;
+							WHITELIST_PROTOCOL="$(echo -e "${WHITELIST_PROTOCOL}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"; # Trim leading/trailing whitespace
+
 							WHITELIST_PORT=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 2 ]; then WHITELIST_PORT="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f2)"; fi;
-							WHITELIST_HOST=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 3 ]; then WHITELIST_HOST="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f3)"; fi;
+							WHITELIST_PORT="$(echo -e "${WHITELIST_PORT}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"; # Trim leading/trailing whitespace
+
+							WHITELIST_HOSTS_COMMA_DELIMITED=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 3 ]; then WHITELIST_HOSTS_COMMA_DELIMITED="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f3)"; fi;
+							WHITELIST_HOSTS_COMMA_DELIMITED="$(echo -e "${WHITELIST_HOSTS_COMMA_DELIMITED}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"; # Trim leading/trailing whitespace
+
 							WHITELIST_DESCRIPTION=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 4 ]; then WHITELIST_DESCRIPTION="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f4)"; fi;
+							WHITELIST_DESCRIPTION="$(echo -e "${WHITELIST_DESCRIPTION}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"; # Trim leading/trailing whitespace
 
 							WHITELIST_FQDN="";
 
@@ -284,77 +291,80 @@ else
 								echo "Debug: EACH_WHITELIST_LINE = [ ${EACH_WHITELIST_LINE} ]";
 								echo "Debug: WHITELIST_PROTOCOL = [ ${WHITELIST_PROTOCOL} ]";
 								echo "Debug: WHITELIST_PORT = [ ${WHITELIST_PORT} ]";
-								echo "Debug: WHITELIST_HOST = [ ${WHITELIST_HOST} ]";
+								echo "Debug: WHITELIST_HOSTS_COMMA_DELIMITED = [ ${WHITELIST_HOSTS_COMMA_DELIMITED} ]";
 							fi;
 
-							RESOLVED_IPv4="";
-							OLD_RESOLVED_IPV4="";
+							# For each host in the comma delimited whitelist of hosts
+							for WHITELIST_HOST in $(echo ${WHITELIST_HOSTS_COMMA_DELIMITED} | sed "s/,/ /g"); do
 
-							WHITELIST_CIDRv4="";
+								RESOLVED_IPv4="";
+								WHITELIST_CIDRv4="";
 
-							if [ "${WHITELIST_HOST}" == "0.0.0.0" ] || [ "${WHITELIST_HOST}" == "0.0.0.0/0" ] || [ "$(echo ${WHITELIST_HOST} | tr '[:upper:]' '[:lower:]';)" == "any" ]; then
+								if [ "${WHITELIST_HOST}" == "0.0.0.0" ] || [ "${WHITELIST_HOST}" == "0.0.0.0/0" ] || [ "$(echo ${WHITELIST_HOST} | tr '[:upper:]' '[:lower:]';)" == "any" ]; then
 
-								# Allow requests originating from the "default route" (e.g. allow incoming requests from any network address, which is 0.0.0.0/0 in CIDRv4 and ::/0 in CIDRv6)
-								RESOLVED_IPv4="0.0.0.0";
-								RESOLVED_CIDRv4="0.0.0.0/0";
+									# Allow requests originating from the "default route" (e.g. allow incoming requests from any network address, which is 0.0.0.0/0 in CIDRv4 and ::/0 in CIDRv6)
+									RESOLVED_IPv4="0.0.0.0";
+									RESOLVED_CIDRv4="0.0.0.0/0";
 
-							else
+								else
 
-								# Check if host if in IPv4 or CIDRv4 syntax, already
-								
-								if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
-									if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
-										# Add "/32" to the end of string, if no CIDR notation is found - ex: 192.168.0.1/32
-										RESOLVED_IPv4="${WHITELIST_HOST}";
-										RESOLVED_CIDRv4="${WHITELIST_HOST}/32";
+									# Check if host if in IPv4 or CIDRv4 syntax, already
+									
+									if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
+										if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
+											# Add "/32" to the end of string, if no CIDR notation is found - ex: 192.168.0.1/32
+											RESOLVED_IPv4="${WHITELIST_HOST}";
+											RESOLVED_CIDRv4="${WHITELIST_HOST}/32";
+										else
+											# Valid IPv4 in CIDR Notation - ex: 192.168.0.0/16
+											RESOLVED_IPv4=$(echo ${WHITELIST_HOST} | cut -d"/" -f1);
+											RESOLVED_CIDRv4="${WHITELIST_HOST}";
+										fi;
 									else
-										# Valid IPv4 in CIDR Notation - ex: 192.168.0.0/16
-										RESOLVED_IPv4=$(echo ${WHITELIST_HOST} | cut -d"/" -f1);
-										RESOLVED_CIDRv4="${WHITELIST_HOST}";
+										# Attempt to resolve the current IPv4 of target hostname
+										WHITELIST_FQDN="${WHITELIST_HOST}";
+										RESOLVED_IPv4="$(dig +short "${WHITELIST_HOST}" | tail -n 1 2>'/dev/null';)";
 									fi;
-								else
-									# Attempt to resolve the current IPv4 of target hostname
-									WHITELIST_FQDN="${WHITELIST_HOST}";
-									RESOLVED_IPv4="$(dig +short "${WHITELIST_HOST}" | tail -n 1 2>'/dev/null';)";
-								fi;
 
-								if [ -n "${RESOLVED_IPv4}" ]; then
+									if [ -n "${RESOLVED_IPv4}" ]; then
 
-									# NGINX Service Only --> Also add resolved CIDRv4 addresses (IN NGINX COMPILE-ABLE SYNTAX) to config-directory specifically designated to contain resolved DDNS addresses
-									if [ "${EACH_SERVICE_NAME}" == "nginx" ]; then
-										NEXT_NGINX_LINE="";
-										if [ -n "${WHITELIST_FQDN}" ]; then
-											# DEPRECATED METHODOLOGY - Clean up old host whitelist files out of '/etc/nginx/conf.ddns/...'
-											#   |--> Clean up previous methodology where the nginx whitelists (allowed-rulesets) were stored using WHITELIST_HOST and their basename
-											#   |--> Needed upon update to allow CIDRv4 notation in whitelist files (21-Apr-2020) which required a different approach for nginx-conf filenames, as CIDRv4 strings by-definition contain a forward-slash '/' character
-											if [ -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}" ]; then
-												rm -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}";
+										# NGINX Service Only --> Also add resolved CIDRv4 addresses (IN NGINX COMPILE-ABLE SYNTAX) to config-directory specifically designated to contain resolved DDNS addresses
+										if [ "${EACH_SERVICE_NAME}" == "nginx" ]; then
+											NEXT_NGINX_LINE="";
+											if [ -n "${WHITELIST_FQDN}" ]; then
+												# DEPRECATED METHODOLOGY - Clean up old host whitelist files out of '/etc/nginx/conf.ddns/...'
+												#   |--> Clean up previous methodology where the nginx whitelists (allowed-rulesets) were stored using WHITELIST_HOST and their basename
+												#   |--> Needed upon update to allow CIDRv4 notation in whitelist files (21-Apr-2020) which required a different approach for nginx-conf filenames, as CIDRv4 strings by-definition contain a forward-slash '/' character
+												if [ -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}" ]; then
+													rm -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}";
+												fi;
+												NEXT_NGINX_LINE="allow ${RESOLVED_IPv4};  # ${WHITELIST_HOST}";
+											else
+												NEXT_NGINX_LINE="allow ${RESOLVED_IPv4};";
 											fi;
-											NEXT_NGINX_LINE="allow ${RESOLVED_IPv4};  # ${WHITELIST_HOST}";
-										else
-											NEXT_NGINX_LINE="allow ${RESOLVED_IPv4};";
+											# Append this line to the total string of lines to put into the nginx service-config-file
+											if [ -z "${EACH_NGINX_DDNS_RESULTS}" ]; then
+												EACH_NGINX_DDNS_RESULTS="${NEXT_NGINX_LINE}";
+											else
+												EACH_NGINX_DDNS_RESULTS="${EACH_NGINX_DDNS_RESULTS}\n${NEXT_NGINX_LINE}";
+											fi;
 										fi;
-										# Append this line to the total string of lines to put into the nginx service-config-file
-										if [ -z "${EACH_NGINX_DDNS_RESULTS}" ]; then
-											EACH_NGINX_DDNS_RESULTS="${NEXT_NGINX_LINE}";
-										else
-											EACH_NGINX_DDNS_RESULTS="${EACH_NGINX_DDNS_RESULTS}\n${NEXT_NGINX_LINE}";
-										fi;
+
+									else
+
+										# IPv4 Unable to be resolved - Remove old IPv4 rule(s)
+										echo "$(date +'%Y-%m-%d %H:%M:%S') Error: Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
+
 									fi;
-
-								else
-
-									# IPv4 Unable to be resolved - Remove old IPv4 rule(s)
-									echo "$(date +'%Y-%m-%d %H:%M:%S') Error: Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
 
 								fi;
 
-							fi;
+								if [ ${DEBUG_MODE} -eq 1 ]; then
+									echo "Debug:  RESOLVED_IPv4 = [ ${RESOLVED_IPv4} ]";
+									echo "Debug:  RESOLVED_CIDRv4 = [ ${RESOLVED_CIDRv4} ]";
+								fi;
 
-							if [ ${DEBUG_MODE} -eq 1 ]; then
-								echo "Debug:  RESOLVED_IPv4 = [ ${RESOLVED_IPv4} ]";
-								echo "Debug:  OLD_RESOLVED_IPV4 = [ ${OLD_RESOLVED_IPV4} ]";
-							fi;
+							done;
 
 
 							if [ -z "${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]}" ]; then
@@ -367,7 +377,7 @@ else
 									echo "" > '/dev/null';  # Do nothing
 								else
 									# CIDRv4 index exists, but new port to-whitelist --> add it to array-index's value using comma delimitation
-									RESOLVED_CIDRv4_ARR+=(["${EACH_CIDRv4}"]="${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]},${WHITELIST_PORT}");
+									RESOLVED_CIDRv4_ARR["${EACH_CIDRv4}"]="${RESOLVED_CIDRv4_ARR[${EACH_CIDRv4}]},${WHITELIST_PORT}";
 								fi;
 							fi;
 							#
@@ -391,8 +401,8 @@ else
 							##### Add / Append a line containing this current host to the resolved-addresses file
 							# echo "${WHITELIST_HOST}:${RESOLVED_IPv4}" >> ${EACH_RESOLVED_FILE};
 
-
 						fi;
+
 					done;
 
 				fi;
@@ -403,36 +413,55 @@ else
 
 		# Update the NGINX conf.ddns script with final string (containing all resolved hosts for this service)
 		if [ "${EACH_SERVICE_NAME}" == "nginx" ] && [ -d "${NGINX_CONF_DDNS}" ] && [ -n "${EACH_NGINX_DDNS_RESULTS}" ]; then
+			if [ ${DEBUG_MODE} -eq 1 ]; then
+				echo "Debug:  NGINX_CONF_DDNS = [ ${NGINX_CONF_DDNS} ]";
+				echo "Debug:  EACH_NGINX_DDNS_RESULTS = [ ${EACH_NGINX_DDNS_RESULTS} ]";
+			fi;
 			echo -e "${EACH_NGINX_DDNS_RESULTS}" > "${EACH_NGINX_DDNS_CONF}";
 		fi;
 	
 	done;
 
+	# Keep reading lines from file(s), removing newlines as you go, and not worry about it you've read a file in at the start or not
+	# tester=$(echo "$tester"$'\n'"$(cat 1)" | grep '\S');
+	# echo "$tester"
 
 	# Array containing CIDRv4 addresses which are now no-longer-valid
 	#  |--> Whitelist file(s) at some point in time (during a previous runtime) resolved to these CIDRv4 addresses, but since then, either the whitelist was removed or the host has changed network addresses (DDNS, DHCP, etc.)
 	unset DISASSOCIATED_CIDRv4_ARR; declare -A DISASSOCIATED_CIDRv4_ARR; # [Re-]Instantiate bash array
 	DISASSOCIATED_CIDRv4_ARR=();
 	
-	# Show resolved CIDRv4 addresses
-	for EACH_RESOLVED_CIDR in "${!RESOLVED_CIDRv4_ARR[@]}"; do
-		DAT_ITEM="${RESOLVED_CIDRv4_ARR[${DAT_KEY}]}";
-		echo "RESOLVED_CIDRv4_ARR[${DAT_KEY}] = ${DAT_ITEM}";
+	# Combine all previously-resolved CIDRv4 addresses and their services
+	ALL_PREVIOUSLY_RESOLVED_CONTENTS="";
+	for EACH_SERVICE_NAME in "${!ALL_PREVIOUSLY_RESOLVED_CONTENTS[@]}"; do
+		EACH_RESOLVED_CONTENTS="${RESOLVED_CIDRv4_ARR[${EACH_SERVICE_NAME}]}";
 
-		# Get the previously-resolved IPv4 of target hostname (stored from a previous run of this script)
-		OLD_RESOLVED_IPV4=$(cat ${EACH_RESOLVED_FILE} | grep ${WHITELIST_HOST} | cut -d: -f2);
-		if [ -z "${OLD_RESOLVED_IPV4}" ] && [ -n "${WHITELIST_FQDN}" ]; then
-			# DEPRECATED METHODOLOGY --> Used to saved the format of previously-resolved hosts as their original hostname
-			OLD_RESOLVED_IPV4=$(cat ${EACH_RESOLVED_FILE} | grep ${WHITELIST_FQDN} | cut -d: -f2);
+		ALL_PREVIOUSLY_RESOLVED_CONTENTS=$(implode $'\n' "${PREVIOUSLY_RESOLVED_CONTENTS_ARR[@]}" | grep '\S');
+		if [ ${DEBUG_MODE} -eq 1 ]; then
+			echo "Debug:  ALL_PREVIOUSLY_RESOLVED_CONTENTS = [ ${ALL_PREVIOUSLY_RESOLVED_CONTENTS} ]";
 		fi;
+	done;
+
+	# Show resolved CIDRv4 addresses
+	for EACH_RESOLVED_CIDRv4 in "${!RESOLVED_CIDRv4_ARR[@]}"; do
+		EACH_PORT="${RESOLVED_CIDRv4_ARR[${EACH_RESOLVED_CIDRv4}]}";
+		echo "RESOLVED_CIDRv4_ARR[${EACH_RESOLVED_CIDRv4}] = ${DAT_ITEM}";
+
+		# Compare old resolved hosts against currently resolved hosts
+		CIDR_EXISTS_IN_CURRENT_RESOLVED_LIST="";
 
 		# Remove old whitelist rule(s)
-		if [ -n "${OLD_RESOLVED_IPV4}" ] && [ "${RESOLVED_IPv4}" != "${OLD_RESOLVED_IPV4}" ]; then
+		if [ -n "${CIDR_EXISTS_IN_CURRENT_RESOLVED_LIST}" ]; then
 			#
 			#  !!!  REMOVE THE OLD IPv4 FROM FIREWALL'S WHITELIST  !!!
 			#
 			# delete_rule ${WHITELIST_PROTOCOL} ${WHITELIST_PORT} ${OLD_RESOLVED_IPV4};
+			##### Remove / Slice the line beginning with this current host from the resolved-addresses file
+			# if [ -f ${EACH_RESOLVED_FILE} ]; then
+			# 	sed -i.bak /^${WHITELIST_HOST}*/d ${EACH_RESOLVED_FILE};
+			# fi;
 		fi;
+
 	done;
 
 	# Determine which CIDRv4 addresses should no longer be allowed through the firewall
@@ -506,6 +535,8 @@ fi;
 #   notepad2.blogspot.com  |  "My Tech Notes: shell script: update ufw rules for the hosts with dynamic ip addresses"  |  https://notepad2.blogspot.com/2012/06/shell-script-update-ufw-rules-for-hosts.html
 #
 #   superuser.com  |  "linux - UFW rules for specific host / dynamic dns - Super User"  |  https://superuser.com/a/646959
+#
+#   stackoverflow.com  |  "Loop through a comma-separated shell variable - Stack Overflow"  |  https://stackoverflow.com/a/27703327
 #
 #   stackoverflow.com  |  "How can I join elements of an array in Bash? - Stack Overflow"  |  https://stackoverflow.com/a/17841619
 #
