update logs to use UTC times

diff --git a/usr/local/sbin/ddns_ufw_update b/usr/local/sbin/ddns_ufw_update
--- a/usr/local/sbin/ddns_ufw_update
+++ b/usr/local/sbin/ddns_ufw_update
@@ -36,7 +36,7 @@ echo "-- Info:  Start of \"ddns_ufw_update\" runtime at [ ${START_DATETIME} ]";
 #
 if [[ "$(id -un)" != "root" ]]; then
   echo "";
-  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Script must run as user \"root\" or via \"sudo\" command";
+  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error:  Script must run as user \"root\" or via \"sudo\" command";
   exit 1;
 else
   # ------------------------------
@@ -132,12 +132,12 @@ else
       ADD_RULE_SKIPPED=1;
       if [ ${DEBUG_MODE} -eq 1 ]; then
         echo "Debug:  IN FUNCTION [ add_rule() ]";
-        echo "            |-->  time:  [ $(date +'%Y-%m-%d %H:%M:%S') ]";
+        echo "            |-->  time  = [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]";
         echo "            |-->  proto = [ ${proto} ]";
-        echo "            |-->  port = [ ${port} ]";
-        echo "            |-->  ip = [ ${ip} ]";
+        echo "            |-->  port  = [ ${port} ]";
+        echo "            |-->  ip    = [ ${ip} ]";
         echo "            |-->  regex = [ ${regex} ]";
-        echo "            |-->  rule = [ ${rule} ]";
+        echo "            |-->  rule  = [ ${rule} ]";
       fi;
       # If rule doesn't exist, then add (allow) it to UFW's ruleset
       if [ -n "${proto}" ] && [ -n "${port}" ] && [ -n "${ip}" ] && [ -z "${rule}" ]; then
@@ -183,12 +183,12 @@ else
       DELETE_RULE_SKIPPED=1;
       if [ ${DEBUG_MODE} -eq 1 ]; then
         echo "Debug:  IN FUNCTION [ delete_rule() ]";
-        echo "            |-->  time:  [ $(date +'%Y-%m-%d %H:%M:%S') ]";
+        echo "            |-->  time  = [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]";
         echo "            |-->  proto = [ ${proto} ]";
-        echo "            |-->  port = [ ${port} ]";
-        echo "            |-->  ip = [ ${ip} ]";
+        echo "            |-->  port  = [ ${port} ]";
+        echo "            |-->  ip    = [ ${ip} ]";
         echo "            |-->  regex = [ ${regex} ]";
-        echo "            |-->  rule = [ ${rule} ]";
+        echo "            |-->  rule  = [ ${rule} ]";
       fi;
       # If rule exists, then remove (delete) it from UFW's ruleset
       if [ -n "${proto}" ] && [ -n "${port}" ] && [ -n "${ip}" ] && [ -n "${rule}" ]; then
@@ -490,7 +490,7 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
                     # IPv4 Unable to be resolved - Remove old IPv4 rule(s)
                     RESOLVED_IPv4="";
                     RESOLVED_CIDRv4="";
-                    echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
+                    echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error:  Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
 
                   fi;
 
diff --git a/usr/local/sbin/sudoer_status b/usr/local/sbin/sudoer_status
--- a/usr/local/sbin/sudoer_status
+++ b/usr/local/sbin/sudoer_status
@@ -29,7 +29,7 @@ exec 2>&1;
 #
 if [[ "$(id -un)" != "root" ]]; then
   echo "";
-  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
   exit 1;
 else
   # ------------------------------------------------------------
@@ -63,7 +63,7 @@ else
       if [ "${EACH_ARG}" == "--allow" ] || [ "${EACH_ARG}" == "--grant" ] || [ "${EACH_ARG}" == "--add" ] || [ "${EACH_ARG}" == "--deny" ] || [ "${EACH_ARG}" == "--revoke" ] || [ "${EACH_ARG}" == "--remove" ]; then
         if [ -n "${EDIT_ACTION}" ]; then
           # Error: Multiple add/remove actions defined
-          echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Invalid inline-argument(s) detected:   Must not call function with more than one argument out of:  [ \"--allow\"  \"--add\"  \"--revoke\"  \"--remove\" ]"; exit 1;
+          echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error --> Invalid inline-argument(s) detected:   Must not call function with more than one argument out of:  [ \"--allow\"  \"--add\"  \"--revoke\"  \"--remove\" ]"; exit 1;
         elif [ "${EACH_ARG}" == "--allow" ] || [ "${EACH_ARG}" == "--grant" ]  || [ "${EACH_ARG}" == "--add" ]; then
           # Add user as a sudoer
           EDIT_ACTION="ALLOW";
@@ -80,12 +80,12 @@ else
       if [ "${EACH_ARG}" == "--user" ] && [ -n "${NEXT_ARG}" ]; then
         if [ -n "${TARGET_USER}" ]; then
           # Error: Multiple users defined
-          echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; exit 1;
+          echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error --> Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; exit 1;
 
         elif [ $(id -u ${NEXT_ARG} > /dev/null 2>&1; echo $?) -eq 1 ]; then
           # Error: Nonexistent target user
-          echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found as a local user: \"${NEXT_ARG}\"";
-          echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | ${EXAMPLE_VALID_CALL}"; exit 1;
+          echo -e "\n$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error --> User not found as a local user: \"${NEXT_ARG}\"";
+          echo -e "\n$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ${EXAMPLE_VALID_CALL}"; exit 1;
 
         else
           TARGET_USER="${NEXT_ARG}";
@@ -109,14 +109,14 @@ else
   if [ -z "${TARGET_USER}" ]; then 
 
     # Error: Empty/Unset target user
-    echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | Error --> Target user empty / unset";
-    echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | ${EXAMPLE_VALID_CALL}"; exit 1;
+    echo -e "\n$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error --> Target user empty / unset";
+    echo -e "\n$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ${EXAMPLE_VALID_CALL}"; exit 1;
 
   elif [ $(id -u ${TARGET_USER} > /dev/null 2>&1; echo $?) -eq 1 ]; then
 
     # Error: User not found
-    echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found: \"${TARGET_USER}\"";
-    echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | ${EXAMPLE_VALID_CALL}"; exit 1;
+    echo -e "\n$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error --> User not found: \"${TARGET_USER}\"";
+    echo -e "\n$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ${EXAMPLE_VALID_CALL}"; exit 1;
 
   else
 
@@ -175,8 +175,8 @@ else
 
       else
         # Check whether or not a user can masquerade as the root user (via the 'sudo' command)
-        echo "$(date +'%Y-%m-%d %H:%M:%S') | Info --> To grant sudoer privileges, call with: >  sudoer_status --user ${TARGET_USER} --grant";
-        echo "$(date +'%Y-%m-%d %H:%M:%S') | Info --> To revoke sudoer privileges, call with: >  sudoer_status --user ${TARGET_USER} --revoke";
+        echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Info --> To grant sudoer privileges, call with: >  sudoer_status --user ${TARGET_USER} --grant";
+        echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Info --> To revoke sudoer privileges, call with: >  sudoer_status --user ${TARGET_USER} --revoke";
 
       fi;
 
