replace lines starting with tabs with spaces (tab count 10)

diff --git a/usr/local/sbin/ddns_ufw_update b/usr/local/sbin/ddns_ufw_update
--- a/usr/local/sbin/ddns_ufw_update
+++ b/usr/local/sbin/ddns_ufw_update
@@ -331,10 +331,10 @@ else
 								if [ ${NEEDLE_TOTAL_COUNT} -ge 1 ]; then
 									WHITELIST_PORT="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')";
 									if [ ${NEEDLE_TOTAL_COUNT} -ge 2 ]; then
-										WHITELIST_HOSTS_COMMA_DELIMITED="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f3 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')";
-										if [ ${NEEDLE_TOTAL_COUNT} -ge 3 ]; then
+                    WHITELIST_HOSTS_COMMA_DELIMITED="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f3 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')";
+                    if [ ${NEEDLE_TOTAL_COUNT} -ge 3 ]; then
                       WHITELIST_DESCRIPTION="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f4 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')";
-										fi;
+                    fi;
 									fi;
 								fi;
 
@@ -350,7 +350,7 @@ else
 								for WHITELIST_HOST in $(echo ${WHITELIST_HOSTS_COMMA_DELIMITED} | sed "s/,/ /g"); do
 
 									if [ ${DEBUG_MODE} -eq 1 ]; then
-										echo "Debug:  WHITELIST_HOST = [ ${WHITELIST_HOST} ]";
+                    echo "Debug:  WHITELIST_HOST = [ ${WHITELIST_HOST} ]";
 									fi;
 
 									RESOLVED_IPv4="";
@@ -358,15 +358,15 @@ else
 
 									if [ "${WHITELIST_HOST}" == "0.0.0.0" ] || [ "${WHITELIST_HOST}" == "0.0.0.0/0" ] || [ "$(echo ${WHITELIST_HOST} | tr '[:upper:]' '[:lower:]';)" == "any" ]; then
 
-										# Allow requests originating from the "default route" (e.g. allow incoming requests from any network address, which is 0.0.0.0/0 in CIDRv4 and ::/0 in CIDRv6)
-										RESOLVED_IPv4="0.0.0.0";
-										RESOLVED_CIDRv4="0.0.0.0/0";
+                    # Allow requests originating from the "default route" (e.g. allow incoming requests from any network address, which is 0.0.0.0/0 in CIDRv4 and ::/0 in CIDRv6)
+                    RESOLVED_IPv4="0.0.0.0";
+                    RESOLVED_CIDRv4="0.0.0.0/0";
 
 									else
 
-										# Check if host if in IPv4 or CIDRv4 syntax, already
-										
-										if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
+                    # Check if host if in IPv4 or CIDRv4 syntax, already
+                    
+                    if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
                       # Host is formatted using IP or CIDR notation (address resolution not required)
                       if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
                         # Add "/32" to the end of string, if no CIDR notation is found - ex: 192.168.0.1/32
@@ -377,7 +377,7 @@ else
                         RESOLVED_IPv4=$(echo ${WHITELIST_HOST} | cut -d"/" -f1);
                         RESOLVED_CIDRv4="${WHITELIST_HOST}";
                       fi;
-										else
+                    else
                       # Host is NOT formatted using IP or CIDR notation (address resolution is required)
                       HOST_ADDRESS_LOOKUP="$(dig +short "${WHITELIST_HOST}" | tail -n 1 2>'/dev/null';)";
                       if [[ ${HOST_ADDRESS_LOOKUP} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
@@ -393,53 +393,53 @@ else
                         WHITELIST_FQDN="";
                       fi;
 
-										fi;
+                    fi;
 
 									fi;
 
 									# Verify final CIDRv4 address notation
 									if [ -n "${RESOLVED_CIDRv4}" ] && [[ ${RESOLVED_CIDRv4} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
-										
-										RESOLVED_PORT_PROTO="${WHITELIST_PORT}/${WHITELIST_PROTOCOL}";
-										RESOLVED_PORT="$(echo "${RESOLVED_PORT_PROTO}" | cut -d'/' -f1)";
-										RESOLVED_PROTO="$(echo "${RESOLVED_PORT_PROTO}" | cut -d'/' -f2)";
+                    
+                    RESOLVED_PORT_PROTO="${WHITELIST_PORT}/${WHITELIST_PROTOCOL}";
+                    RESOLVED_PORT="$(echo "${RESOLVED_PORT_PROTO}" | cut -d'/' -f1)";
+                    RESOLVED_PROTO="$(echo "${RESOLVED_PORT_PROTO}" | cut -d'/' -f2)";
 
-										RESOLVED_CIDRv4_1D+=("${RESOLVED_CIDRv4}");
-										RESOLVED_HOSTS_1D+=("${WHITELIST_HOST}");
-										RESOLVED_IPv4_1D+=("${RESOLVED_IPv4}");
-										RESOLVED_PORTS_1D+=("${RESOLVED_PORT}");
-										RESOLVED_PROTOS_1D+=("${RESOLVED_PROTO}");
+                    RESOLVED_CIDRv4_1D+=("${RESOLVED_CIDRv4}");
+                    RESOLVED_HOSTS_1D+=("${WHITELIST_HOST}");
+                    RESOLVED_IPv4_1D+=("${RESOLVED_IPv4}");
+                    RESOLVED_PORTS_1D+=("${RESOLVED_PORT}");
+                    RESOLVED_PROTOS_1D+=("${RESOLVED_PROTO}");
 
-										if [ ${DEBUG_MODE} -eq 1 ]; then
+                    if [ ${DEBUG_MODE} -eq 1 ]; then
                       echo "Debug:  RESOLVED_IPv4 = [ ${RESOLVED_IPv4} ]";
                       echo "Debug:  RESOLVED_CIDRv4 = [ ${RESOLVED_CIDRv4} ]";
                       echo "Debug:  RESOLVED_PORT_PROTO = [ ${RESOLVED_PORT_PROTO} ]";
                       echo "Debug:  RESOLVED_PORT = [ ${RESOLVED_PORT} ]";
                       echo "Debug:  RESOLVED_PROTO = [ ${RESOLVED_PROTO} ]";
-										fi;
+                    fi;
 
-										# if [ ${RESOLVED_CIDRv4_ARR[${RESOLVED_CIDRv4}]+X} ]; then
-										# 	# Existing array-index (CIDRv4) & value (port(s))
-										# 	#   |--> Another host already resolved to this CIDRv4 --> Use check for match on whitelisted-port (within current array-index's value)
-										# 	if [[ ",${RESOLVED_CIDRv4_ARR[${RESOLVED_CIDRv4}]}," = *",${RESOLVED_PORT_PROTO},"* ]]; then
-										# 		# Another host AND port combo already matches this iteration exactly --> skip adding it to the array as it is merely a duplicate
-										# 		echo "" 1>'/dev/null' 2>&1;  # Do nothing
-										# 	else
-										# 		# CIDRv4 index exists, but new port to-whitelist --> add it to array-index's value using comma delimitation
-										# 		RESOLVED_CIDRv4_ARR["${RESOLVED_CIDRv4}"]="${RESOLVED_CIDRv4_ARR[${RESOLVED_CIDRv4}]},${RESOLVED_PORT_PROTO}";
-										# 	fi;
-										# else
-										# 	# New array-index (CIDRv4) & value (port)
-										# 	RESOLVED_CIDRv4_ARR+=(["${RESOLVED_CIDRv4}"]="${RESOLVED_PORT_PROTO}");
-										# fi;
+                    # if [ ${RESOLVED_CIDRv4_ARR[${RESOLVED_CIDRv4}]+X} ]; then
+                    # 	# Existing array-index (CIDRv4) & value (port(s))
+                    # 	#   |--> Another host already resolved to this CIDRv4 --> Use check for match on whitelisted-port (within current array-index's value)
+                    # 	if [[ ",${RESOLVED_CIDRv4_ARR[${RESOLVED_CIDRv4}]}," = *",${RESOLVED_PORT_PROTO},"* ]]; then
+                    # 		# Another host AND port combo already matches this iteration exactly --> skip adding it to the array as it is merely a duplicate
+                    # 		echo "" 1>'/dev/null' 2>&1;  # Do nothing
+                    # 	else
+                    # 		# CIDRv4 index exists, but new port to-whitelist --> add it to array-index's value using comma delimitation
+                    # 		RESOLVED_CIDRv4_ARR["${RESOLVED_CIDRv4}"]="${RESOLVED_CIDRv4_ARR[${RESOLVED_CIDRv4}]},${RESOLVED_PORT_PROTO}";
+                    # 	fi;
+                    # else
+                    # 	# New array-index (CIDRv4) & value (port)
+                    # 	RESOLVED_CIDRv4_ARR+=(["${RESOLVED_CIDRv4}"]="${RESOLVED_PORT_PROTO}");
+                    # fi;
 
 # OVERRIDE for logic (below) using finalized arrays and comparing them against existing UFW rules
 #  |--> Add allowed ips & protocols, here.
 add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
 
-										# ------------------------------------------------------------
-										# BEGIN NGINX ONLY
-										if [ "${EACH_SERVICE_NAME}" == "nginx" ]; then
+                    # ------------------------------------------------------------
+                    # BEGIN NGINX ONLY
+                    if [ "${EACH_SERVICE_NAME}" == "nginx" ]; then
                       # Add resolved CIDRv4 addresses (IN NGINX COMPILE-ABLE SYNTAX) to config-directory specifically designated to contain resolved DDNS addresses
                       NEXT_NGINX_LINE="";
                       if [ -n "${WHITELIST_FQDN}" ]; then
@@ -459,16 +459,16 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
                       else
                         NGINX_DDNS_RESULTS="${NGINX_DDNS_RESULTS}\n${NEXT_NGINX_LINE}";
                       fi;
-										fi;
-										# END NGINX ONLY
-										# ------------------------------------------------------------
+                    fi;
+                    # END NGINX ONLY
+                    # ------------------------------------------------------------
 
 									else
 
-										# IPv4 Unable to be resolved - Remove old IPv4 rule(s)
-										RESOLVED_IPv4="";
-										RESOLVED_CIDRv4="";
-										echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
+                    # IPv4 Unable to be resolved - Remove old IPv4 rule(s)
+                    RESOLVED_IPv4="";
+                    RESOLVED_CIDRv4="";
+                    echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
 
 									fi;
 
