ddns

diff --git a/usr/local/sbin/ddns_ufw_update b/usr/local/sbin/ddns_ufw_update
--- a/usr/local/sbin/ddns_ufw_update
+++ b/usr/local/sbin/ddns_ufw_update
@@ -63,15 +63,30 @@ else
 	#           tcp:22:localhost.localdomain
 	#
 	unset RUNTIME_SERVICE_USERS; declare -A RUNTIME_SERVICE_USERS; # [Re-]Instantiate bash array
-	RUNTIME_SERVICE_USERS+=(["sshd"]="root");
-	RUNTIME_SERVICE_USERS+=(["nginx"]="www-data");
-	# RUNTIME_SERVICE_USERS+=(["java"]="jenkins");
+	RUNTIME_SERVICE_USERS+=(["sshd"]="root");       # SSH/OpenSSH listener
+	RUNTIME_SERVICE_USERS+=(["nginx"]="www-data");  # NGINX Web Server
+	RUNTIME_SERVICE_USERS+=(["unifi"]="unifi");  # Unifi Controller
+	# RUNTIME_SERVICE_USERS+=(["jenkins"]="jenkins");    # Jenkins Master
 
 	# Defaults for UFW (out-of-the-box)
-	NGINX_CONF_DDNS="/etc/nginx/conf.ddns";
+	ETC_NGINX="/etc/nginx/conf.ddns";
+	NGINX_CONF_DDNS="${ETC_NGINX}/conf.ddns";
+
+	# Create the DDNS NGINX directory only if the NGINX parent directory already exists
+	if [ -d "${ETC_NGINX}" ] && [ ! -d "${NGINX_CONF_DDNS}" ]; then
+			mkdir -p "${NGINX_CONF_DDNS}";
+	fi;
 
 	# Defaults for UFW (out-of-the-box)
 	UFW_OUT_OF_THE_BOX_DEFAULTS="Default: deny (incoming), allow (outgoing), disabled (routed)";
+
+
+	# ------------------------------------------------------------
+	#
+	# Sub-Function: Takes first argument ($1) as a delimiter, combines all remaining arguments ($2,$3,...,$n) into a string delimited by aforementioned delimiter ($1)
+	#
+	function implode { local IFS="$1"; shift; echo "$*"; }
+
 
 	# ------------------------------------------------------------
 	#
@@ -79,13 +94,11 @@ else
 	#
 	add_rule() {
 		if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
-
 			local proto=$1;
 			local port=$2;
 			local ip=$3;
 			local regex="${port}\/${proto}.*ALLOW.*IN.*${ip}";
 			local rule=$(/usr/sbin/ufw status numbered | grep ${regex});
-
 			if [ ${DEBUG_MODE} -eq 1 ]; then
 				echo "Debug: -> IN FUNCTION [ add_rule()  ]";
 				echo "Debug: -> proto = [ ${proto} ]";
@@ -94,7 +107,6 @@ else
 				echo "Debug: -> regex = [ ${regex} ]";
 				echo "Debug: -> rule = [ ${rule} ]";
 			fi;
-
 			# If rule doesn't exist, then add (allow) it to UFW's ruleset
 			if [ -z "${rule}" ]; then
 				echo -e "\n""Info: Adding Firewall Rule [ ${proto}/${port} ALLOW IN ${ip} ]";
@@ -105,7 +117,6 @@ else
 				#   /usr/sbin/ufw allow proto tcp from 10.0.0.0/8 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
 				#   /usr/sbin/ufw allow proto tcp from 172.16.0.0/12 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
 				#   /usr/sbin/ufw allow proto tcp from 192.168.0.0/16 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
-
 			else
 				if [ ${DEBUG_MODE} -eq 1 ]; then
 					echo "Debug: Rule already exists for [ ${proto}/${port} ALLOW IN ${ip} ]";
@@ -127,7 +138,6 @@ else
 			local ip=$3;
 			local regex="${WHITELIST_PORT}\/${proto}.*ALLOW.*IN.*${ip}";
 			local rule=$(ufw status numbered | grep ${regex});
-
 			if [ ${DEBUG_MODE} -eq 1 ]; then
 				echo "Debug: -> IN FUNCTION [ delete_rule()  ]";
 				echo "Debug: -> proto = [ ${proto} ]";
@@ -136,7 +146,6 @@ else
 				echo "Debug: -> regex = [ ${regex} ]";
 				echo "Debug: -> rule = [ ${rule} ]";
 			fi;
-
 			# If rule exists, then remove (delete) it from UFW's ruleset
 			if [ -n "${rule}" ]; then
 				echo -e "\n""Info: Deleting Firewall Rule [ ${proto}/${port} ALLOW IN ${ip} ]";
@@ -144,14 +153,12 @@ else
 				echo "  |--> Call: [ /usr/sbin/ufw delete allow proto ${proto} from ${ip} to any port ${port}; ]...";
 				/usr/sbin/ufw delete allow proto ${proto} from ${ip} to any port ${port};
 				# Example(s):
-				#   /usr/sbin/ufw delete allow proto tcp from any to any port 80,443
-
+				#   /usr/sbin/ufw delete allow proto tcp from 0.0.0.0/0 to any port 80,443
 			else
 				if [ ${DEBUG_MODE} -eq 1 ]; then
 					echo "Debug: Skipped delete (No rule found to delete): ${proto}/${port} ALLOW IN ${ip}";
 					echo "  |--> Time: [ $(date +'%Y-%m-%d %H:%M:%S') ]";
 				fi;
-
 			fi;
 		fi;
 	}
@@ -195,24 +202,43 @@ else
 	#
 	# Apply Whitelist on a per-service basis
 	#
-	for EACH_SERVICE in "${!RUNTIME_SERVICE_USERS[@]}"; do
+	for EACH_SERVICE_NAME in "${!RUNTIME_SERVICE_USERS[@]}"; do
+
 		# File containing hosts to allow through UFW
 		#  |--> All lines in given whitelist file must be in a specific format/syntax
 		#        |
 		#        |--> Syntax:    tcp/udp:PORT:SUBDOMAIN.DOMAIN.TLD
 		#        |--> Example:   tcp:22:demo.example.com
 		#
-		EACH_RUNTIME_USER="${RUNTIME_SERVICE_USERS[${EACH_SERVICE}]}";
+		EACH_RUNTIME_USER="${RUNTIME_SERVICE_USERS[${EACH_SERVICE_NAME}]}";
+		EACH_NGINX_DDNS_CONF="${NGINX_CONF_DDNS}/${EACH_SERVICE_NAME}";
+		EACH_NGINX_DDNS_CONTENTS="";
 
-		# Only whitelist services which are found to exist, locally
-		test ${DEBUG_MODE} -eq 1 && echo "MATCHED_PROCS_PGREP Call = [ pgrep -u \"${EACH_RUNTIME_USER}\" \"${EACH_SERVICE}\"; ]";
-		MATCHED_PROCS_PGREP=$(pgrep -u "${EACH_RUNTIME_USER}" "${EACH_SERVICE}" 2>/dev/null;);
-		MATCHED_PROCS_PGREP_TRIMMED="$(echo -e "${MATCHED_PROCS_PGREP}" | tr '\n' ' ' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' 2>/dev/null;)";
+		unset EACH_SERVICE_CIDR_ARR; declare -a EACH_SERVICE_CIDR_ARR; # [Re-]Instantiate bash array
+		EACH_SERVICE_CIDR_ARR=();
+		DAT_ARRAY+=("Item-One");
+		DAT_ARRAY+=("Item-One");
+		DAT_ARRAY+=("Item-Two");
+		DAT_ARRAY+=("Item-A");
+		DAT_ARRAY+=("Item-A");
+		DAT_ARRAY+=("Item-B");
+		for DAT_ITEM in "${DAT_ARRAY[@]}"; do
+		echo "${DAT_ITEM}";
+		done;
 
-		if [ -n "${MATCHED_PROCS_PGREP_TRIMMED}" ]; then
+		# Only whitelist services which are in-use by this machine
+		SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${EACH_SERVICE_NAME}.service" | grep "^${EACH_SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+		if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service exists locally & is currently active
 
-			test ${DEBUG_MODE} -eq 1 && echo "MATCHED_PROCS_PS Call = [ ps --format \"pid,fname,user,%cpu,%mem,maj_flt,cmd\" --no-headers -p \"${MATCHED_PROCS_PGREP_TRIMMED}\" | wc -l; ]";
-			MATCHED_PROCS_PS=$(ps --format "pid,fname,user,%cpu,%mem,maj_flt,cmd" --no-headers -p "${MATCHED_PROCS_PGREP_TRIMMED}" | wc -l;);
+		# ### (DEPRECATED METHODOLOGY) Search for [ specific users ] running [ specific processes ]
+		# test ${DEBUG_MODE} -eq 1 && echo "MATCHED_PROCS_PGREP Call = [ pgrep -u \"${EACH_RUNTIME_USER}\" \"${EACH_SERVICE_NAME}\"; ]";
+		# MATCHED_PROCS_PGREP=$(pgrep -u "${EACH_RUNTIME_USER}" "${EACH_SERVICE_NAME}" 2>/dev/null;);
+		# MATCHED_PROCS_PGREP_TRIMMED="$(echo -e "${MATCHED_PROCS_PGREP}" | tr '\n' ' ' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' 2>/dev/null;)";
+		# if [ -n "${MATCHED_PROCS_PGREP_TRIMMED}" ]; then # Service exists locally
+		# 	test ${DEBUG_MODE} -eq 1 && echo "MATCHED_PROCS_PS Call = [ ps --format \"pid,fname,user,%cpu,%mem,maj_flt,cmd\" --no-headers -p \"${MATCHED_PROCS_PGREP_TRIMMED}\" | wc -l; ]";
+		# 	MATCHED_PROCS_PS=$(ps --format "pid,fname,user,%cpu,%mem,maj_flt,cmd" --no-headers -p "${MATCHED_PROCS_PGREP_TRIMMED}" | wc -l;);
+
+			MATCHED_PROCS_PS=$(ps --format "pid,fname,user,%cpu,%mem,maj_flt,cmd" --no-headers -U "${EACH_RUNTIME_USER}" | wc -l;);
 
 			if [ ${DEBUG_MODE} -eq 1 ]; then
 				echo "MATCHED_PROCS_PGREP = [ ${MATCHED_PROCS_PGREP} ]";
@@ -221,42 +247,48 @@ else
 
 			if [ ${MATCHED_PROCS_PS} -eq 0 ]; then
 				# Service does NOT exist locally - do NOT whitelist associated ports/hosts
-				echo -e "\n""Info: Skipping whitelisting for service \"${EACH_SERVICE}\" (not found locally)";
+				echo -e "\n""Info: Skipping whitelisting for service \"${EACH_SERVICE_NAME}\" (not found locally)";
 
 			else
 				# Service DOES exist locally - DO whitelist associated ports/hosts
-				EACH_HOSTS_FILE="${DIRNAME_LOCAL_CONFIG}/${EACH_SERVICE}";
+				EACH_WHITELIST_FILE="${DIRNAME_LOCAL_CONFIG}/${EACH_SERVICE_NAME}";
 
-				if [ ! -f "${EACH_HOSTS_FILE}" ]; then
-					echo -e "\n""Error: Whitelist hosts file for service \"${EACH_SERVICE}\" not found @ filepath \"${EACH_HOSTS_FILE}\"";
-					echo "  |--> Skipping Whitelist for Service \"${EACH_HOSTS_FILE}\"";
+				if [ ! -f "${EACH_WHITELIST_FILE}" ]; then
+					echo "";
+					echo "Error:  Whitelist hosts file for service \"${EACH_SERVICE_NAME}\" not found @ filepath \"${EACH_WHITELIST_FILE}\"";
+					echo "  |--> Skipping Whitelist for Service \"${EACH_WHITELIST_FILE}\"";
 
 				else
 
-					echo -e "\n""Info: Applying Firewall (ufw) Whitelisting for \"${EACH_SERVICE}\" Service";
-					echo "  |-> Using whitelist file \"${EACH_HOSTS_FILE}\"";
+					echo -e "\n""Info: Applying Firewall (ufw) Whitelisting for \"${EACH_SERVICE_NAME}\" Service";
+					echo "  |-> Using whitelist file \"${EACH_WHITELIST_FILE}\"";
 
 					# Iterate-over each line in the whitelist file
-					sed '/^[[:space:]]*$/d' ${EACH_HOSTS_FILE} | \
+					sed '/^[[:space:]]*$/d' ${EACH_WHITELIST_FILE} | \
 					sed '/^[[:space:]]*#/d' | \
 					while read EACH_WHITELIST_LINE;	do
 						if [ -n "${EACH_WHITELIST_LINE}" ]; then
 
 							# Define the location of the file to output resolved ipv4's to
-							EACH_RESOLVED_FILE="${EACH_HOSTS_FILE}.resolved";
+							EACH_RESOLVED_FILE="${EACH_WHITELIST_FILE}.resolved";
 							if [ ! -f "${EACH_RESOLVED_FILE}" ]; then
-								echo -n "" > "${EACH_RESOLVED_FILE}";
+								touch "${EACH_RESOLVED_FILE}";
 							fi;
+
+							HAYSTACK_TO_SEARCH="${EACH_WHITELIST_LINE}";
+							CHAR_DELIMITER="|";
+							ALL_NEEDLES_FOUND="${HAYSTACK_TO_SEARCH//[^${CHAR_DELIMITER}]}"; # Required middleman var
+							NEEDLE_TOTAL_COUNT=${#ALL_NEEDLES_FOUND};
+
+							WHITELIST_PROTOCOL=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 1 ]; then MM="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f1)"; WHITELIST_PROTOCOL="${MM,,}"; fi; # IP Protocol must be a lowercase string matching 'tcp' or 'udp'
+							WHITELIST_PORT=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 2 ]; then WHITELIST_PORT="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f2)"; fi;
+							WHITELIST_HOST=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 3 ]; then WHITELIST_HOST="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f3)"; fi;
+							WHITELIST_DESCRIPTION=""; if [ ${NEEDLE_TOTAL_COUNT} -ge 4 ]; then WHITELIST_DESCRIPTION="$(echo "${EACH_WHITELIST_LINE}" | cut -d${CHAR_DELIMITER} -f4)"; fi;
+
+							WHITELIST_FQDN="";
 
 							if [ ${DEBUG_MODE} -eq 1 ]; then
 								echo -e "\n""------------------------------------------------------------";
-							fi;
-
-							WHITELIST_PROTOCOL=$(echo ${EACH_WHITELIST_LINE} | cut -d: -f1);
-							WHITELIST_PORT=$(echo ${EACH_WHITELIST_LINE} | cut -d: -f2);
-							WHITELIST_HOST=$(echo ${EACH_WHITELIST_LINE} | cut -d: -f3);
-
-							if [ ${DEBUG_MODE} -eq 1 ]; then
 								echo "Debug: EACH_WHITELIST_LINE = [ ${EACH_WHITELIST_LINE} ]";
 								echo "Debug: WHITELIST_PROTOCOL = [ ${WHITELIST_PROTOCOL} ]";
 								echo "Debug: WHITELIST_PORT = [ ${WHITELIST_PORT} ]";
@@ -265,40 +297,96 @@ else
 
 							CURRENT_RESOLVED_IPv4="";
 							OLD_RESOLVED_IPV4="";
-							if [ "$(echo ${WHITELIST_HOST} | tr '[:upper:]' '[:lower:]';)" == "any" ]; then
-								# Allow "Any" host to be used
-								CURRENT_RESOLVED_IPv4="any";
+
+							WHITELIST_CIDRv4="";
+
+							if [ "${WHITELIST_HOST}" == "0.0.0.0" ] || [ "${WHITELIST_HOST}" == "0.0.0.0/0" ] || [ "$(echo ${WHITELIST_HOST} | tr '[:upper:]' '[:lower:]';)" == "any" ]; then
+
+								# Allow requests originating from the "default route" (e.g. allow incoming requests from any network address, which is 0.0.0.0/0 in CIDRv4 and ::/0 in CIDRv6)
+								CURRENT_RESOLVED_IPv4="0.0.0.0";
+								CURRENT_RESOLVED_CIDRv4="0.0.0.0/0";
+
 							else
-								# Determine current & previous IPv4(s) for each hostname
-								CURRENT_RESOLVED_IPv4=$(dig +short ${WHITELIST_HOST} | tail -n 1);
-								OLD_RESOLVED_IPV4=$(cat ${EACH_RESOLVED_FILE} | grep ${WHITELIST_HOST} | cut -d: -f2);
-								if [ -n "${CURRENT_RESOLVED_IPv4}" ]; then
-									if [ -d "${NGINX_CONF_DDNS}" ]; then
-										# IPv4 resolved successfully - Add whitelist rule for NGINX (if NGINX directory exists)
-										echo "allow ${CURRENT_RESOLVED_IPv4}; # ${WHITELIST_HOST}" > "${NGINX_CONF_DDNS}/${WHITELIST_HOST}";
+
+								# Check if host if in IPv4 or CIDRv4 syntax, already
+								
+								if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ ]]; then
+									if [[ ${WHITELIST_HOST} =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(())$ ]]; then
+										# Add "/32" to the end of string, if no CIDR notation is found - ex: 192.168.0.1/32
+										CURRENT_RESOLVED_IPv4="${WHITELIST_HOST}";
+										CURRENT_RESOLVED_CIDRv4="${WHITELIST_HOST}/32";
+									else
+										# Valid IPv4 in CIDR Notation - ex: 192.168.0.0/16
+										CURRENT_RESOLVED_IPv4=$(echo ${WHITELIST_HOST} | cut -d"/" -f1);
+										CURRENT_RESOLVED_CIDRv4="${WHITELIST_HOST}";
 									fi;
 								else
+									# Attempt to resolve the current IPv4 of target hostname
+									WHITELIST_FQDN="${WHITELIST_HOST}";
+									CURRENT_RESOLVED_IPv4="$(dig +short "${WHITELIST_HOST}" | tail -n 1 2>'/dev/null';)";
+								fi;
+
+								# Get the previously-resolved IPv4 of target hostname (stored from a previous run of this script)
+								OLD_RESOLVED_IPV4=$(cat ${EACH_RESOLVED_FILE} | grep ${WHITELIST_HOST} | cut -d: -f2);
+								if [ -z "${OLD_RESOLVED_IPV4}" ]  && [ -n "${WHITELIST_FQDN}" ]; then
+									# DEPRECATED METHODOLOGY --> Used to saved the format of previously-resolved hosts as their original hostname
+									OLD_RESOLVED_IPV4=$(cat ${EACH_RESOLVED_FILE} | grep ${WHITELIST_FQDN} | cut -d: -f2);
+								fi;
+
+								if [ -n "${CURRENT_RESOLVED_IPv4}" ]; then
+
+										# IPv4 resolved successfully - Add whitelist rule for NGINX (if NGINX directory exists)
+										NEXT_NGINX_LINE="";
+										if [ -n "${WHITELIST_FQDN}" ]; then
+											# DEPRECATED METHODOLOGY - Clean up old host whitelist files out of '/etc/nginx/conf.ddns/...'
+											#   |--> Clean up previous methodology where the nginx whitelists (allowed-rulesets) were stored using WHITELIST_HOST and their basename
+											#   |--> Needed upon update to allow CIDRv4 notation in whitelist files (21-Apr-2020) which required a different approach for nginx-conf filenames, as CIDRv4 strings by-definition contain a forward-slash '/' character
+											if [ -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}" ]; then
+												rm -f "${NGINX_CONF_DDNS}/${WHITELIST_FQDN}";
+											fi;
+											NEXT_NGINX_LINE="allow ${CURRENT_RESOLVED_IPv4};  # ${WHITELIST_HOST}";
+										else
+											NEXT_NGINX_LINE="allow ${CURRENT_RESOLVED_IPv4};";
+										fi;
+
+										# Append this line to the total string of lines to put into the nginx service-config-file
+										if [ -n "${EACH_NGINX_DDNS_CONTENTS}" ]; then
+											NEXT_NGINX_LINE="\n${NEXT_NGINX_LINE}";
+										fi;
+										EACH_NGINX_DDNS_CONTENTS="${EACH_NGINX_DDNS_CONTENTS}${NEXT_NGINX_LINE}";
+
+								else
+
 									# IPv4 Unable to be resolved - Remove old IPv4 rule(s)
 									if [ -n "${OLD_RESOLVED_IPV4}" ]; then
+										#
+										#  !!!  REMOVE THE OLD IPv4 FROM FIREWALL'S WHITELIST  !!!
+										#
 										delete_rule ${WHITELIST_PROTOCOL} ${WHITELIST_PORT} ${OLD_RESOLVED_IPV4};
 									fi;
-									echo "$(date +'%Y-%m-%d %H:%M:%S') Error: Hostname resolution failed for \"${WHITELIST_HOST}\" (could not be converted to an IPv4/IPv6 address)" 1>&2;
-									# exit 1;
+									echo "$(date +'%Y-%m-%d %H:%M:%S') Error: Hostname resolution failed for \"${WHITELIST_HOST}\"  (unable to resolve/convert to CIDRv4 notation)" 1>&2;
+
 								fi;
+
 								# Remove old whitelist rule(s)
-								if [ -n "${OLD_RESOLVED_IPV4}" ]; then
-									if [ ${CURRENT_RESOLVED_IPv4} != ${OLD_RESOLVED_IPV4} ]; then
-										delete_rule ${WHITELIST_PROTOCOL} ${WHITELIST_PORT} ${OLD_RESOLVED_IPV4};
-									fi;
+								if [ -n "${OLD_RESOLVED_IPV4}" ] && [ "${CURRENT_RESOLVED_IPv4}" != "${OLD_RESOLVED_IPV4}" ]; then
+									#
+									#  !!!  REMOVE THE OLD IPv4 FROM FIREWALL'S WHITELIST  !!!
+									#
+									delete_rule ${WHITELIST_PROTOCOL} ${WHITELIST_PORT} ${OLD_RESOLVED_IPV4};
 								fi;
+
 							fi;
 
 							if [ ${DEBUG_MODE} -eq 1 ]; then
-								echo "Debug: CURRENT_RESOLVED_IPv4 = [ ${CURRENT_RESOLVED_IPv4} ]";
-								echo "Debug: OLD_RESOLVED_IPV4 = [ ${OLD_RESOLVED_IPV4} ]";
+								echo "Debug:  CURRENT_RESOLVED_IPv4 = [ ${CURRENT_RESOLVED_IPv4} ]";
+								echo "Debug:  OLD_RESOLVED_IPV4 = [ ${OLD_RESOLVED_IPV4} ]";
 							fi;
 
-							add_rule ${WHITELIST_PROTOCOL} ${WHITELIST_PORT} ${CURRENT_RESOLVED_IPv4};
+							#
+							#  !!!  ADD THE NEW IPv4 TO FIREWALL'S WHITELIST  !!!
+							#
+							add_rule "${WHITELIST_PROTOCOL}" ${WHITELIST_PORT} ${CURRENT_RESOLVED_IPv4};
 
 							if [ -f ${EACH_RESOLVED_FILE} ]; then
 								sed -i.bak /^${WHITELIST_HOST}*/d ${EACH_RESOLVED_FILE};
@@ -313,6 +401,11 @@ else
 
 			fi;
 
+		fi;
+
+		# Update the NGINX conf.ddns script with final string (containing all resolved hosts for this service)
+		if [ -d "${NGINX_CONF_DDNS}" ] && [ -n "${EACH_NGINX_DDNS_CONTENTS}" ]; then
+			echo -e "${EACH_NGINX_DDNS_CONTENTS}" > "${EACH_NGINX_DDNS_CONF}";
 		fi;
 
 	done;
@@ -380,6 +473,10 @@ fi;
 #   notepad2.blogspot.com  |  "My Tech Notes: shell script: update ufw rules for the hosts with dynamic ip addresses"  |  https://notepad2.blogspot.com/2012/06/shell-script-update-ufw-rules-for-hosts.html
 #
 #   superuser.com  |  "linux - UFW rules for specific host / dynamic dns - Super User"  |  https://superuser.com/a/646959
+#
+#   stackoverflow.com  |  "How can I join elements of an array in Bash? - Stack Overflow"  |  https://stackoverflow.com/a/17841619
+#
+#   unix.stackexchange.com  |  "text processing - How to count the number of a specific character in each line? - Unix & Linux Stack Exchange"  |  https://unix.stackexchange.com/a/18742
 #
 #   www.digitalocean.com  |  "How To Set Up a Firewall with UFW on Ubuntu 18.04 | DigitalOcean"  |  https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-18-04
 #
