Update install_mongod

diff --git a/usr/local/sbin/install_mongod b/usr/local/sbin/install_mongod
--- a/usr/local/sbin/install_mongod
+++ b/usr/local/sbin/install_mongod
@@ -32,25 +32,34 @@ if [ "$(id -un)" != "root" ]; then
 else
 	# ------------------------------------------------------------
 	# Install package repo & download/install package
+	if [ $(which mongo 2>'/dev/null' | wc -l;) -gt 0 ]; then
+		echo "";
+		echo "Info: Command \"mongo\" already exists at path \"$(which mongo)\"";
+		echo "  |--> Skipping package install";
 
+	else
+		echo "";
+		echo "Info: Command \"mongo\" not found";
+		echo "  |--> Installing pre-required packages, then adding \"mongodb-org\" parent-repo & installing service-package...";
 
-	# Debian distros
-	if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then
-		if [ "$(which gnupg 2>'/dev/null'; echo $?;)" != "1" ]; then
-			apt-get -y update; apt-get -y install "gnupg";
+		# Debian distros
+		if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then
+			if [ "$(which gnupg 2>'/dev/null'; echo $?;)" != "1" ]; then
+				apt-get -y update; apt-get -y install "gnupg";
+			fi;
+			if [ "$(which tee 2>'/dev/null'; echo $?;)" != "1" ]; then
+				apt-get -y update; apt-get -y install "tee";
+			fi;
+			wget -qO - "https://www.mongodb.org/static/pgp/server-4.2.asc" | apt-key add -;
+			echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main" | tee "/etc/apt/sources.list.d/mongodb-org-4.2.list";
+			apt-get -y update; apt-get -y install "mongodb-org";
 		fi;
-		if [ "$(which tee 2>'/dev/null'; echo $?;)" != "1" ]; then
-			apt-get -y update; apt-get -y install "tee";
+
+		# CentOS / RHEL distros
+		if [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then
+			echo -e "[mongodb-org-4.2]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.2/x86_64/\ngpgcheck=1\nenabled=1\ngpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc\n" > "/etc/yum.repos.d/mongodb-org-4.2.repo"; yum check-update; yum install -y mongodb-org;
 		fi;
-		wget -qO - "https://www.mongodb.org/static/pgp/server-4.2.asc" | apt-key add -;
-		echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main" | tee "/etc/apt/sources.list.d/mongodb-org-4.2.list";
-		apt-get -y update; apt-get -y install "mongodb-org";
-	fi;
 
-
-	# CentOS / RHEL distros
-	if [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then
-		echo -e "[mongodb-org-4.2]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.2/x86_64/\ngpgcheck=1\nenabled=1\ngpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc\n" > "/etc/yum.repos.d/mongodb-org-4.2.repo"; yum check-update; yum install -y mongodb-org;
 	fi;
 
 
