replace lines starting with tabs with spaces (tab count 4)

diff --git a/usr/local/sbin/install_unifi b/usr/local/sbin/install_unifi
--- a/usr/local/sbin/install_unifi
+++ b/usr/local/sbin/install_unifi
@@ -52,62 +52,62 @@ else
 			echo "Info:  Testing URL for validity:  [ ${SOURCE_URL} ]";
 			# check whether URL returns an HTTP code of 200 (e.g. if the website exists and responds 'normally')
 			if [ "$(curl -Is ${SOURCE_URL} | head -n 1 | awk '{print $2}')" == "200" ]; then
-				# VALID URL
-				# Install [ specific-revision'ed ] Unifi Controller via Bash convenience script
-				TMP_FILE="/tmp/unifi-install.sh";
-				echo "";
-				echo "Info:  Calling  [ mkdir -p \"/tmp\"; if [ -f \"${TMP_FILE}\" ]; then rm -f \"${TMP_FILE}\"; fi; wget -O \"${TMP_FILE}\" \"${SOURCE_URL}\"; chmod 0700 \"${TMP_FILE}\"; bash \"${TMP_FILE}\"; ]...";
-				mkdir -p "/tmp"; if [ -f "${TMP_FILE}" ]; then rm -f "${TMP_FILE}"; fi; wget -O "${TMP_FILE}" "${SOURCE_URL}"; chmod 0700 "${TMP_FILE}"; bash "${TMP_FILE}";
+        # VALID URL
+        # Install [ specific-revision'ed ] Unifi Controller via Bash convenience script
+        TMP_FILE="/tmp/unifi-install.sh";
+        echo "";
+        echo "Info:  Calling  [ mkdir -p \"/tmp\"; if [ -f \"${TMP_FILE}\" ]; then rm -f \"${TMP_FILE}\"; fi; wget -O \"${TMP_FILE}\" \"${SOURCE_URL}\"; chmod 0700 \"${TMP_FILE}\"; bash \"${TMP_FILE}\"; ]...";
+        mkdir -p "/tmp"; if [ -f "${TMP_FILE}" ]; then rm -f "${TMP_FILE}"; fi; wget -O "${TMP_FILE}" "${SOURCE_URL}"; chmod 0700 "${TMP_FILE}"; bash "${TMP_FILE}";
 
 			else
-				# INVALID URL
-				echo "";
-				echo "Error:  Invalid URL - Failed to return an HTTP code of 200";
-				echo "";
-				echo "Info:  Browse to the following URL to view available bash convenience scripts for installing specific versions of the UniFi Controller";
-				echo "  |";
-				echo "  |-->   https://glennr.nl/s/unifi-network-controller";
-				echo "";
-				echo "Info:  Once you have your desired version of the UniFi controller to install, call this script again with the version as the first inline argument (\$1)";
-				echo "  |";
-				echo "  |-->  Ex) install_unifi 5.10.23";
-				echo "";
-				exit 1;
+        # INVALID URL
+        echo "";
+        echo "Error:  Invalid URL - Failed to return an HTTP code of 200";
+        echo "";
+        echo "Info:  Browse to the following URL to view available bash convenience scripts for installing specific versions of the UniFi Controller";
+        echo "  |";
+        echo "  |-->   https://glennr.nl/s/unifi-network-controller";
+        echo "";
+        echo "Info:  Once you have your desired version of the UniFi controller to install, call this script again with the version as the first inline argument (\$1)";
+        echo "  |";
+        echo "  |-->  Ex) install_unifi 5.10.23";
+        echo "";
+        exit 1;
 			fi;
 
 		else
 		
 			USE_DOCKER_CONTAINER=0;
 			if [ $(which docker 2>'/dev/null' | wc -l;) -gt 0 ]; then
-				if [ $(which docker-compose 2>'/dev/null' | wc -l;) -gt 0 ]; then
+        if [ $(which docker-compose 2>'/dev/null' | wc -l;) -gt 0 ]; then
           # If docker & docker-compose are both already installed, offer to install the service as a docker container
           echo "";
           READ_TIMEOUT=60; read -p "Install/run UniFi from a Docker container? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
           if [ ${RETURN_CODE_READ} -le 128 ] && [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
             USE_DOCKER_CONTAINER=1;
           fi;
-				fi;
+        fi;
 			fi;
 			
 			if [ "${USE_DOCKER_CONTAINER}" == "1" ]; then
-				# Install/run service as a Docker container
+        # Install/run service as a Docker container
 
-				echo "";
-				echo "Info:  Calling  [ mkdir -p \"/var/lib/docker-compose/unifi\"; ]...";
-				mkdir -p "/var/lib/docker-compose/unifi";
+        echo "";
+        echo "Info:  Calling  [ mkdir -p \"/var/lib/docker-compose/unifi\"; ]...";
+        mkdir -p "/var/lib/docker-compose/unifi";
 
-				echo "";
-				echo "Info:  Calling  [ curl -ssL \"https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/var/lib/docker-compose/unifi/docker-compose.yml\" -o \"/var/lib/docker-compose/unifi/docker-compose.yml\"; ]...";
-				curl -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/var/lib/docker-compose/unifi/docker-compose.yml" -o "/var/lib/docker-compose/unifi/docker-compose.yml";
+        echo "";
+        echo "Info:  Calling  [ curl -ssL \"https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/var/lib/docker-compose/unifi/docker-compose.yml\" -o \"/var/lib/docker-compose/unifi/docker-compose.yml\"; ]...";
+        curl -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/var/lib/docker-compose/unifi/docker-compose.yml" -o "/var/lib/docker-compose/unifi/docker-compose.yml";
 
-				echo "";
-				echo "Info:  Calling  [ docker-compose -f \"/var/lib/docker-compose/unifi/docker-compose.yml\" up -d; ]...";
-				docker-compose -f "/var/lib/docker-compose/unifi/docker-compose.yml" up -d;
+        echo "";
+        echo "Info:  Calling  [ docker-compose -f \"/var/lib/docker-compose/unifi/docker-compose.yml\" up -d; ]...";
+        docker-compose -f "/var/lib/docker-compose/unifi/docker-compose.yml" up -d;
 
 			else
-				# Install/run service from Host OS (non-containerized)
+        # Install/run service from Host OS (non-containerized)
 
-				if [ 1 -eq 1 ]; then
+        if [ 1 -eq 1 ]; then
 
           # Install [ latest-version'ed ] Unifi Controller via Bash convenience script
           SOURCE_URL="https://get.glennr.nl/unifi/install/install_latest/unifi-latest.sh";
@@ -118,7 +118,7 @@ else
           echo "Info:  Calling  [ mkdir -p \"/tmp\"; if [ -f \"${TMP_FILE}\" ]; then rm -f \"${TMP_FILE}\"; fi; wget -O \"${TMP_FILE}\" \"${SOURCE_URL}\"; bash \"${TMP_FILE}\"; ]...";
           mkdir -p "/tmp"; if [ -f "${TMP_FILE}" ]; then rm -f "${TMP_FILE}"; fi; wget -O "${TMP_FILE}" "${SOURCE_URL}"; bash "${TMP_FILE}";
 
-				else
+        else
 
           # Install pre-requisite package(s)
           echo "";
@@ -154,8 +154,8 @@ else
           echo "";
           echo "Info:  Calling  [ apt-get -y update; apt-mark hold openjdk-11-*; apt-get -y install unifi; ]...";
           apt-get -y update; apt-mark hold openjdk-11-*; apt-get -y install unifi;
-				
-				fi;
+        
+        fi;
 
 			fi;
 
diff --git a/usr/local/sbin/motd_status b/usr/local/sbin/motd_status
--- a/usr/local/sbin/motd_status
+++ b/usr/local/sbin/motd_status
@@ -42,17 +42,17 @@ else
 		else
 			NEXT_ARG=${ARGS[$((${i}+1))]};
 			if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
-				NEXT_ARG="";
+        NEXT_ARG="";
 			fi;
 		fi;
 		if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
 			# ------------------------------------------------------------
 
 			if [ "${EACH_ARG}" == "--enable" ] || [ "${EACH_ARG}" == "-enable" ] || [ "${EACH_ARG}" == "enable" ]; then
-				ENABLE_MOTD=1;
+        ENABLE_MOTD=1;
 			fi;
 			if [ "${EACH_ARG}" == "--disable" ] || [ "${EACH_ARG}" == "-disable" ] || [ "${EACH_ARG}" == "disable" ]; then
-				DISABLE_MOTD=1;
+        DISABLE_MOTD=1;
 			fi;
 
 			# ------------------------------------------------------------
@@ -84,22 +84,22 @@ else
 			echo "$(date +'%Y-%m-%d %H:%M:%S') | Error -> Please select only enable or disable (and not both) directives";
 
 		elif [ $(find /etc/update-motd.d/*motd-news* 2>'/dev/null' | wc -l) -eq 0 ] && [ $(find /etc/default/*motd-news* 2>'/dev/null' | wc -l) -eq 0 ]; then
-				# ERROR - Missing required file(s)
-				echo "$(date +'%Y-%m-%d %H:%M:%S') | Error -> No file(s) found which match glob-pattern [ /etc/update-motd.d/*motd-news* ] or [ /etc/default/*motd-news* ]";
-				echo -e "${EXAMPLE_VALID_CALL}";
-				exit 1;
+        # ERROR - Missing required file(s)
+        echo "$(date +'%Y-%m-%d %H:%M:%S') | Error -> No file(s) found which match glob-pattern [ /etc/update-motd.d/*motd-news* ] or [ /etc/default/*motd-news* ]";
+        echo -e "${EXAMPLE_VALID_CALL}";
+        exit 1;
 
 		else
 
 			# Success - Update each associated config-file
 			echo "Replacing lines starting with \"ENABLED=\" to, instead, be \"ENABLED=${MOTD_ENABLED_VALUE}\"";
 			for EACH_FILE in /etc/update-motd.d/*motd-news*; do
-				echo "Updating \"${EACH_FILE}\"";
-				sed --in-place -e "/^ENABLED=/c\ENABLED=${MOTD_ENABLED_VALUE}" "${EACH_FILE}";
+        echo "Updating \"${EACH_FILE}\"";
+        sed --in-place -e "/^ENABLED=/c\ENABLED=${MOTD_ENABLED_VALUE}" "${EACH_FILE}";
 			done;
 			for EACH_FILE in /etc/default/motd-news; do
-				echo "Updating \"${EACH_FILE}\"";
-				sed --in-place -e "/^ENABLED=/c\ENABLED=${MOTD_ENABLED_VALUE}" "${EACH_FILE}";
+        echo "Updating \"${EACH_FILE}\"";
+        sed --in-place -e "/^ENABLED=/c\ENABLED=${MOTD_ENABLED_VALUE}" "${EACH_FILE}";
 			done;
 
 		fi;
diff --git a/usr/local/sbin/set_hostname b/usr/local/sbin/set_hostname
--- a/usr/local/sbin/set_hostname
+++ b/usr/local/sbin/set_hostname
@@ -56,7 +56,7 @@ else
 		else
 			NEXT_ARG=${ARGS[$((${i}+1))]};
 			if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
-				NEXT_ARG="";
+        NEXT_ARG="";
 			fi;
 		fi;
 
@@ -64,34 +64,34 @@ else
 
 			# Parse inline hostname
 			if [ ${i} -eq 0 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then # Allow the first argument to be the hostname (without needing --hostname before it)
-				NEXT_ARG="${EACH_ARG}";
-				EACH_ARG="--hostname";
+        NEXT_ARG="${EACH_ARG}";
+        EACH_ARG="--hostname";
 			fi;
 
 			if [ "${EACH_ARG}" == "--name" ] || [ "${EACH_ARG}" == "--hostname" ]; then
-				if [ "${ARGS_HOSTNAME_DEFINED}" == "1" ]; then
+        if [ "${ARGS_HOSTNAME_DEFINED}" == "1" ]; then
           echo "";
           echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Inline parameters contain more than one value for hostname";
           echo "";
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info: Please call again using one, single value";
           exit 1;
-				else
+        else
           ARGS_HOSTNAME_DEFINED=1;
           INPUT_HOSTNAME="${NEXT_ARG}";
-				fi;
+        fi;
 			fi;
 
 			if [ "${EACH_ARG}" == "--wan" ]; then # --force
-				USE_WAN_IPV4=1;
+        USE_WAN_IPV4=1;
 			fi;
 
 			# Parse dry-run / non-dry-run calls
 			if [ "${EACH_ARG}" == "--force" ]; then # --force
-				DRY_RUN="0";
+        DRY_RUN="0";
 			elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "0" ]; then # --dry-run 0
-				DRY_RUN="0";
+        DRY_RUN="0";
 			elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "false" ]; then # --dry-run false
-				DRY_RUN="0";
+        DRY_RUN="0";
 			fi;
 
 		fi;
@@ -132,7 +132,7 @@ else
 			# Hostname includes no periods - use it as-is
 			SET_HOSTNAME="${INPUT_HOSTNAME}";
 			if [ -v CURRENT_DOMAIN ] && [ -n "${CURRENT_DOMAIN}" ]; then
-				SET_DOMAIN="${CURRENT_DOMAIN}";
+        SET_DOMAIN="${CURRENT_DOMAIN}";
 			fi;
 		else
 			# Hostname has at least one period in it --> parse the domain name out from the hostname
@@ -185,14 +185,14 @@ else
 		if [ ${USE_WAN_IPV4} -ne 0 ]; then
 			### Show Resolved WAN IPv4
 			if [ -n "${THIS_WAN_IPV4}" ]; then
-				echo "";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  WAN Outgoing IPv4 resolved to \"${THIS_WAN_IPV4}\"";
+        echo "";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  WAN Outgoing IPv4 resolved to \"${THIS_WAN_IPV4}\"";
 			else
-				echo "";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Unable to resolve outgoing WAN IPv4 Address";
-				echo "";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ env THIS_WAN_IPV4=\"127.0.0.1\" ${0} ]  (replacing 127.0.0.1 with machine's WAN IPv4)";
-				exit 1;
+        echo "";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Unable to resolve outgoing WAN IPv4 Address";
+        echo "";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ env THIS_WAN_IPV4=\"127.0.0.1\" ${0} ]  (replacing 127.0.0.1 with machine's WAN IPv4)";
+        exit 1;
 			fi;
 		else
 			echo "";
@@ -234,10 +234,10 @@ else
 		if [[ "${DRY_RUN}" == "0" ]]; then
 			echo ""; read -p "Update hostname, now? (y/n)  " -n 1 -t 60 -r; echo "";
 			if [[ $REPLY =~ ^[Yy]$ ]]; then
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info: - Confirmed by user - Proceeding with changes to hostname & domain-name...";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info: - Confirmed by user - Proceeding with changes to hostname & domain-name...";
 			else
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info: - Cancelled by user - exiting...";
-				exit 1;
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info: - Cancelled by user - exiting...";
+        exit 1;
 			fi;
 		fi;
 		echo "";
@@ -248,12 +248,12 @@ else
 		HOSTNAME_FILE="/etc/hostname";
 		if [[ -f "${HOSTNAME_FILE}" ]]; then
 			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
-				echo "";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling [ cat \"${HOSTNAME_FILE}\"; ]  (before edits, $(date +'%Y-%m-%d %H:%M:%S'))";
-				echo "------------------------------------------------------------";
-				cat "${HOSTNAME_FILE}";
-				echo "------------------------------------------------------------";
-				if [ "$(cat ${HOSTNAME_FILE})" != "{SET_HOSTNAME}" ]; then # update required for hostname file
+        echo "";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling [ cat \"${HOSTNAME_FILE}\"; ]  (before edits, $(date +'%Y-%m-%d %H:%M:%S'))";
+        echo "------------------------------------------------------------";
+        cat "${HOSTNAME_FILE}";
+        echo "------------------------------------------------------------";
+        if [ "$(cat ${HOSTNAME_FILE})" != "{SET_HOSTNAME}" ]; then # update required for hostname file
           echo "";
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Updating hostname file \"${HOSTNAME_FILE}\" to contain new hostname \"${SET_HOSTNAME}\", instead";
           echo "${SET_HOSTNAME}" > "${HOSTNAME_FILE}";
@@ -262,10 +262,10 @@ else
           echo "------------------------------------------------------------";
           cat "${HOSTNAME_FILE}";
           echo "------------------------------------------------------------";
-				else
+        else
           echo "";
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Skipping update for hostname file \"${HOSTNAME_FILE}\" (already matches desired hostname)";
-				fi;
+        fi;
 			fi;
 		fi;
 
@@ -282,15 +282,15 @@ else
 
 			echo "";
 			if [ ${USE_WAN_IPV4} -ne 0 ]; then
-				SET_HOSTS_IPV4="${THIS_WAN_IPV4}";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Resolving hostname \"${SET_HOSTNAME}\" to WAN IPv4 address \"${THIS_LAN_IPV4}\"";
+        SET_HOSTS_IPV4="${THIS_WAN_IPV4}";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Resolving hostname \"${SET_HOSTNAME}\" to WAN IPv4 address \"${THIS_LAN_IPV4}\"";
 			else
-				# Resolve hostname to LAN IPv4
-				SET_HOSTS_IPV4="${THIS_LAN_IPV4}";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Resolving hostname \"${SET_HOSTNAME}\" to LAN IPv4 address \"${THIS_LAN_IPV4}\"";
-				# Alert user the hostname will NOT be resolved to the WAN IPv4 (but how to do so)
-				echo "";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  To resolve hostname to the current WAN IPv4 \"${THIS_WAN_IPV4}\", instead, call using the \"--wan\" argument (intended for cloud-based servers, where a given WAN IPv4 Address is associated with only one, unique instance of linux)";
+        # Resolve hostname to LAN IPv4
+        SET_HOSTS_IPV4="${THIS_LAN_IPV4}";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Resolving hostname \"${SET_HOSTNAME}\" to LAN IPv4 address \"${THIS_LAN_IPV4}\"";
+        # Alert user the hostname will NOT be resolved to the WAN IPv4 (but how to do so)
+        echo "";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  To resolve hostname to the current WAN IPv4 \"${THIS_WAN_IPV4}\", instead, call using the \"--wan\" argument (intended for cloud-based servers, where a given WAN IPv4 Address is associated with only one, unique instance of linux)";
 			fi;
 
 			echo "";
@@ -306,7 +306,7 @@ else
 			sed -i -e "/^${THIS_LAN_IPV4} /c\\" "${TEMP_HOSTS}";
 
 			if [ ${USE_WAN_IPV4} -ne 0 ]; then # Remove pre-existing WAN-IPV4 hostsfile lines
-				sed -i -e "/^${THIS_WAN_IPV4} /c\\" "${TEMP_HOSTS}";
+        sed -i -e "/^${THIS_WAN_IPV4} /c\\" "${TEMP_HOSTS}";
 			fi;
 
 			sed -i -e "/^::1 /c\\" "${TEMP_HOSTS}"; # Remove pre-existing Loopback-IPv6 line(s)
@@ -315,10 +315,10 @@ else
 			LOOPBACK_IPV4="127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4";
 			LOOPBACK_IPV6="::1 localhost localhost.localdomain localhost6 localhost6.localdomain6";
 			if [ -n "${SET_DOMAIN}" ]; then # Hostname + FQDN (hostname.domainname)
-				sed -i -e "/^127.0.0.1/{" -e "i\\${SET_HOSTS_IPV4} ${SET_HOSTNAME}.${SET_DOMAIN} ${SET_HOSTNAME}" -e "a\\${LOOPBACK_IPV6}" -e "c\\${LOOPBACK_IPV4}" -e "}" "${TEMP_HOSTS}";
+        sed -i -e "/^127.0.0.1/{" -e "i\\${SET_HOSTS_IPV4} ${SET_HOSTNAME}.${SET_DOMAIN} ${SET_HOSTNAME}" -e "a\\${LOOPBACK_IPV6}" -e "c\\${LOOPBACK_IPV4}" -e "}" "${TEMP_HOSTS}";
 
 			else # Hostname only (no FQDN)
-				sed -i -e "/^127.0.0.1/{" -e "i\\${SET_HOSTS_IPV4} ${SET_HOSTNAME}" -e "a\\${LOOPBACK_IPV6}" -e "c\\${LOOPBACK_IPV4}" -e "}" "${TEMP_HOSTS}";
+        sed -i -e "/^127.0.0.1/{" -e "i\\${SET_HOSTS_IPV4} ${SET_HOSTNAME}" -e "a\\${LOOPBACK_IPV6}" -e "c\\${LOOPBACK_IPV4}" -e "}" "${TEMP_HOSTS}";
 
 			fi;
 
@@ -336,8 +336,8 @@ else
 
 
 			if [[ "${DRY_RUN}" == "0" ]]; then
-				# NOT a dry-run -> Overwrite hosts-file
-				cp -f "${TEMP_HOSTS}" "${HOSTS_FILE}";
+        # NOT a dry-run -> Overwrite hosts-file
+        cp -f "${TEMP_HOSTS}" "${HOSTS_FILE}";
 
 			fi;
 			rm -f "${TEMP_HOSTS}";
@@ -350,19 +350,19 @@ else
 		if [[ -f "/etc/sysconfig/network" ]]; then
 			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
 
-				if [ -n "${SET_DOMAIN}" ]; then
+        if [ -n "${SET_DOMAIN}" ]; then
           sed -i -e "/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}.${SET_DOMAIN}" "/etc/sysconfig/network";
-				else
+        else
           sed -i -e "/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}" "/etc/sysconfig/network";
-				fi;
+        fi;
 
 			else # dry-run
-				echo "";
-				if [ -n "${SET_DOMAIN}" ]; then
+        echo "";
+        if [ -n "${SET_DOMAIN}" ]; then
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}.${SET_DOMAIN}\" \"/etc/sysconfig/network\"; ]";
-				else
+        else
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}\" \"/etc/sysconfig/network\"; ]";
-				fi;
+        fi;
 			fi;
 		fi;
 
@@ -371,10 +371,10 @@ else
 		#
 		if [[ -f "/etc/init.d/hostname.sh" ]]; then
 			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
-				/etc/init.d/hostname.sh;
+        /etc/init.d/hostname.sh;
 			else # dry-run
-				echo "";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ /etc/init.d/hostname.sh; ]";
+        echo "";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ /etc/init.d/hostname.sh; ]";
 			fi;
 		fi;
 
@@ -383,10 +383,10 @@ else
 		#
 		if [[ $(hostnamectl | wc -l) -gt 0 ]]; then
 			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
-				hostnamectl set-hostname "${SET_HOSTNAME}";
+        hostnamectl set-hostname "${SET_HOSTNAME}";
 			else # dry-run
-				echo "";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ hostnamectl set-hostname \"${SET_HOSTNAME}\" ]";
+        echo "";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ hostnamectl set-hostname \"${SET_HOSTNAME}\" ]";
 			fi;
 		fi;
 
@@ -402,38 +402,38 @@ else
 		#
 		if [[ -f "/etc/init.d/network" ]]; then # CentOS-RHEL distros
 			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
-				echo "";
-				echo "Network Manager must be restarted to apply changes ( required command  [ /etc/init.d/network restart ]  )";
-				read -p "   |--> Restart Network Manager, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
-				echo "";
-				if [[ $REPLY =~ ^[Yy]$ ]]; then
+        echo "";
+        echo "Network Manager must be restarted to apply changes ( required command  [ /etc/init.d/network restart ]  )";
+        read -p "   |--> Restart Network Manager, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
+        echo "";
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
           echo "";
           echo "$(date +'%Y-%m-%d %H:%M:%S') Restarting Network Manager via command  [ /etc/init.d/network restart ]";
           /etc/init.d/network restart;
-				else
+        else
           echo "";
           echo "$(date +'%Y-%m-%d %H:%M:%S') Postponing Network Manager restart";
           exit 1;
-				fi;
+        fi;
 			else # dry-run
-				echo "";
-				echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping network manager restart";
+        echo "";
+        echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping network manager restart";
 			fi;
 		else # [other] distros
 			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
-				echo "";
-				echo "System restart required to apply changes to hostname";
-				read -p "   |--> Reboot this workstation/server, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
-				echo "";
-				if [[ $REPLY =~ ^[Yy]$ ]]; then
+        echo "";
+        echo "System restart required to apply changes to hostname";
+        read -p "   |--> Reboot this workstation/server, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
+        echo "";
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
           echo "";
           echo "Rebooting...";
           shutdown -r now;
-				else
+        else
           echo "";
           echo "System restart postponed";
           exit 1;
-				fi;
+        fi;
 			# else # dry-run
 			# 	echo "";
 			# 	echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping restart";
diff --git a/usr/local/sbin/update_jenkins_warfile b/usr/local/sbin/update_jenkins_warfile
--- a/usr/local/sbin/update_jenkins_warfile
+++ b/usr/local/sbin/update_jenkins_warfile
@@ -79,11 +79,11 @@ else
 			echo "$(date +'%D  %r')   JENKINS_VERSION_DOWNLOADED = \"${JENKINS_VERSION_DOWNLOADED}\"";
 
 			if [ "${JENKINS_VERSION_DOWNLOADED}" == "2.185" ]; then
-				# Skip buggy Jenkins runtime(s)
-				echo "";
-				echo "$(date +'%D  %r')   NOTICE: Blocking downloaded Jenkins runtime";
-				echo "$(date +'%D  %r')     |-->  Version: ${JENKINS_VERSION_DOWNLOADED}";
-				echo "$(date +'%D  %r')     |-->  Reason: Has a bug (error) in its Java's SSH runtime which breaks ability to SSH into nodes as-intended (all nodes go offline)";
+        # Skip buggy Jenkins runtime(s)
+        echo "";
+        echo "$(date +'%D  %r')   NOTICE: Blocking downloaded Jenkins runtime";
+        echo "$(date +'%D  %r')     |-->  Version: ${JENKINS_VERSION_DOWNLOADED}";
+        echo "$(date +'%D  %r')     |-->  Reason: Has a bug (error) in its Java's SSH runtime which breaks ability to SSH into nodes as-intended (all nodes go offline)";
 
 			# elif [ "${JENKINS_VERSION_DOWNLOADED}" == "OTHER-BUGGY-VERSION" ]; then
 			# 	# Skip buggy Jenkins runtime(s)
@@ -93,44 +93,44 @@ else
 			# 	echo "$(date +'%D  %r')     |-->  Reason: Explanation of why this version is buggy and shouldn't be used in production";
 
 			elif [ "${JENKINS_VERSION_SYSTEM}" == "${JENKINS_VERSION_DOWNLOADED}" ]; then
-				# No update to version #
-				echo "";
-				echo "$(date +'%D  %r')   No update to jenkins version number detected (remained constant @ v${JENKINS_VERSION_SYSTEM})";
+        # No update to version #
+        echo "";
+        echo "$(date +'%D  %r')   No update to jenkins version number detected (remained constant @ v${JENKINS_VERSION_SYSTEM})";
 
 			else
-				# Install the downloaded runtime
+        # Install the downloaded runtime
 
-				# Backup [ a Version-stamped copy ] of [ the current jenkins runtime ]
-				if [ ! -f "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_SYSTEM}" ]; then
+        # Backup [ a Version-stamped copy ] of [ the current jenkins runtime ]
+        if [ ! -f "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_SYSTEM}" ]; then
           cp --verbose --force "${JENKINS_RUNTIME_SYSTEM}" "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_SYSTEM}";
-				fi;
+        fi;
 
-				# Backup [ a Version-stamped copy ] of [ the downloaded runtime ]
-				if [ ! -f "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_DOWNLOADED}" ]; then
+        # Backup [ a Version-stamped copy ] of [ the downloaded runtime ]
+        if [ ! -f "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_DOWNLOADED}" ]; then
           cp --verbose --force "${JENKINS_RUNTIME_DOWNLOADED}" "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_DOWNLOADED}";
-				fi;
+        fi;
 
-				# Stop the Jenkins service (before updating its runtime warfile)
-				SERVICE_NAME="jenkins";
-				echo "";
-				echo "$(date +'%D  %r')   Calling [ /usr/sbin/service \"${SERVICE_NAME}\" stop; ]...";
-				/usr/sbin/service "${SERVICE_NAME}" stop;
+        # Stop the Jenkins service (before updating its runtime warfile)
+        SERVICE_NAME="jenkins";
+        echo "";
+        echo "$(date +'%D  %r')   Calling [ /usr/sbin/service \"${SERVICE_NAME}\" stop; ]...";
+        /usr/sbin/service "${SERVICE_NAME}" stop;
 
-				# Replace Jenkins' runtime warfile with the newly downloaded runtime warfile
-				mv --verbose --force "${JENKINS_RUNTIME_DOWNLOADED}" "${JENKINS_RUNTIME_SYSTEM}";
+        # Replace Jenkins' runtime warfile with the newly downloaded runtime warfile
+        mv --verbose --force "${JENKINS_RUNTIME_DOWNLOADED}" "${JENKINS_RUNTIME_SYSTEM}";
 
-				# Re-Sync to repo/cloud-sync settings
-				if [ $(which sync_cloud_infrastructure 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
+        # Re-Sync to repo/cloud-sync settings
+        if [ $(which sync_cloud_infrastructure 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
           sync_cloud_infrastructure --jenkins;
-				fi;
+        fi;
 
-				# Start the Jenkins service (after updating its runtime warfile)
-				echo "";
-				echo "$(date +'%D  %r')   Calling [ /usr/sbin/service \"${SERVICE_NAME}\" start; ]...";
-				/usr/sbin/service "${SERVICE_NAME}" start;
+        # Start the Jenkins service (after updating its runtime warfile)
+        echo "";
+        echo "$(date +'%D  %r')   Calling [ /usr/sbin/service \"${SERVICE_NAME}\" start; ]...";
+        /usr/sbin/service "${SERVICE_NAME}" start;
 
-				# Reload NGINX (if found locally)
-				if [ $(which nginx 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
+        # Reload NGINX (if found locally)
+        if [ $(which nginx 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
           if [ $(which reload_nginx 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
             echo "";
             echo "$(date +'%D  %r')   Calling [ reload_nginx ]...";
@@ -140,16 +140,16 @@ else
             echo "$(date +'%D  %r')   Calling [ nginx -t && sleep 1 && /usr/sbin/service nginx stop; ]...";
             nginx -t && sleep 1 && /usr/sbin/service nginx stop;
           fi;
-				else
+        else
           echo "";
           echo "$(date +'%D  %r')   Skipping NGINX service-restart (NGINX not found locally, e.g. calling [ which nginx ] returned nothing)";
-				fi;
+        fi;
 
-				# Re-Sync to repo/cloud-sync settings
-				if [ $(which sync_cloud_infrastructure 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
+        # Re-Sync to repo/cloud-sync settings
+        if [ $(which sync_cloud_infrastructure 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
           sleep 30;
           sync_cloud_infrastructure --jenkins;
-				fi;
+        fi;
 
 			fi;
 
diff --git a/usr/local/sbin/update_system b/usr/local/sbin/update_system
--- a/usr/local/sbin/update_system
+++ b/usr/local/sbin/update_system
@@ -44,79 +44,79 @@ else
 			#
 			# apt / apt-get
 			if [ $(which apt 2>'/dev/null' | wc -l;) -eq 0 ]; then
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"apt\" not found";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"apt\" not found";
 			elif [ $(which apt-get 2>'/dev/null' | wc -l;) -eq 0 ]; then
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"apt-get\" not found";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"apt-get\" not found";
 			else
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"apt\" resolved to $(which apt 2>'/dev/null')";
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"apt-get\" resolved to $(which apt-get 2>'/dev/null')";
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt-get -y update";
-				sudo apt-get -y update;
-				if [ $(which update_unifi 2>'/dev/null' | wc -l;) -eq 0 ]; then
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"apt\" resolved to $(which apt 2>'/dev/null')";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"apt-get\" resolved to $(which apt-get 2>'/dev/null')";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt-get -y update";
+        sudo apt-get -y update;
+        if [ $(which update_unifi 2>'/dev/null' | wc -l;) -eq 0 ]; then
           sudo update_unifi;
-				fi;
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt list --upgradable";
-				sudo apt list --upgradable;
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt-get -y dist-upgrade";
-				sudo apt-get -y dist-upgrade;
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt-get -y autoremove";
-				sudo apt-get -y autoremove;
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt-get -y clean";
-				sudo apt-get -y clean;
+        fi;
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt list --upgradable";
+        sudo apt list --upgradable;
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt-get -y dist-upgrade";
+        sudo apt-get -y dist-upgrade;
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt-get -y autoremove";
+        sudo apt-get -y autoremove;
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo apt-get -y clean";
+        sudo apt-get -y clean;
 			fi;
 			echo "------------------------------------------------------------";
 			#
 			# yum
 			if [ -z "$(which yum 2>'/dev/null')" ]; then
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"yum\" not found";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"yum\" not found";
 
 			else
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"yum\" resolved to $(which yum 2>'/dev/null')";
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo yum list --upgradable";
-				sudo yum check-update; RET_CODE_YUM_CHECK_UPDATE=$?;
-				if [ ${RET_CODE_YUM_CHECK_UPDATE} -eq 100 ]; then
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"yum\" resolved to $(which yum 2>'/dev/null')";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo yum list --upgradable";
+        sudo yum check-update; RET_CODE_YUM_CHECK_UPDATE=$?;
+        if [ ${RET_CODE_YUM_CHECK_UPDATE} -eq 100 ]; then
           # Command [ yum check-update ] returns exit value of 100 if there are packages available for an update
           echo "";
           echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo yum -y update";
           sudo yum -y update;
-				fi;
+        fi;
 			fi;
 			echo "------------------------------------------------------------";
 			#
 			# updatedb
 			if [ $(which updatedb 2>'/dev/null' | wc -l;) -eq 0 ]; then
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"updatedb\" not found";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"updatedb\" not found";
 			else
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"updatedb\" resolved to $(which updatedb)";
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo updatedb";
-				sudo updatedb;
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"updatedb\" resolved to $(which updatedb)";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo updatedb";
+        sudo updatedb;
 			fi;
 			echo "------------------------------------------------------------";
 			#
 			# ldconfig
 			if [ $(which ldconfig 2>'/dev/null' | wc -l;) -eq 0 ]; then
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"ldconfig\" not found";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"ldconfig\" not found";
 			else
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"ldconfig\" resolved to $(which ldconfig 2>'/dev/null')";
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo ldconfig";
-				sudo ldconfig;
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"ldconfig\" resolved to $(which ldconfig 2>'/dev/null')";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo ldconfig";
+        sudo ldconfig;
 			fi;
 			echo "------------------------------------------------------------";
 			#
@@ -125,10 +125,10 @@ else
           echo "";
           echo "$(date '+%Y-%m-%d %H:%M:%S') | Skipping \"pip\"";
 			else 
-				if [ $(which pip 2>'/dev/null' | wc -l;) -eq 0 ]; then
+        if [ $(which pip 2>'/dev/null' | wc -l;) -eq 0 ]; then
           echo "";
           echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"pip\" not found";
-				else
+        else
           echo "";
           echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"pip\" resolved to $(which pip 2>'/dev/null')";
           echo "";
@@ -142,41 +142,41 @@ else
           echo "";
           echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo -H pip install -U;";
           sudo pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 sudo -H pip install -U;
-				fi;
+        fi;
 			fi;
 			echo "------------------------------------------------------------";
 			if [ $(which do-release-upgrade 2>'/dev/null' | wc -l;) -eq 0 ]; then
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"do-release-upgrade\" not found";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Command \"do-release-upgrade\" not found";
 			else
-				OS_UPDATES_CHECK="$(do-release-upgrade --check-dist-upgrade-only;)";
-				OS_UPDATES_AVAILABLE="$(echo "${OS_UPDATES_CHECK}" | grep '^New release' | wc -l;)";
-				if [ "${OS_UPDATES_AVAILABLE}" == "1" ]; then
+        OS_UPDATES_CHECK="$(do-release-upgrade --check-dist-upgrade-only;)";
+        OS_UPDATES_AVAILABLE="$(echo "${OS_UPDATES_CHECK}" | grep '^New release' | wc -l;)";
+        if [ "${OS_UPDATES_AVAILABLE}" == "1" ]; then
           echo "";
           echo "!!!  Updates exist for current operating system:";
           echo "${OS_UPDATES_CHECK}" | grep -v '^Check';
-				else
+        else
           echo "";
           echo "No operating system updates found";
-				fi;
+        fi;
 			fi;
 			echo "------------------------------------------------------------";
 			#
 			# Check if reboot is required
 			if [ -f "/var/run/reboot-required" ]; then
-				# The File '/var/run/reboot-required' is an Ubuntu native, and signifies that at least one recent update requires a reboot to fully complete their install/update.
-				# If we find that ^ file on our current host (after running updates), then the system is in the reboot preparation phase -> set it just to restart after 2 minutes
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | REBOOT REQUIRED TO FINALIZE ONE OR MORE UPDATES - SETTING A RESTART FOR 2 MINUTES FROM NOW";
-				# Schedule the system restart/reboot (NOT reset)
-				SCHEDULED_RESTART_TIME=$(date -d "$(date +%H):$(date +%M) 2 minutes" +'%H:%M');
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo shutdown -r \"${SCHEDULED_RESTART_TIME}\"";
-				shutdown -r "${SCHEDULED_RESTART_TIME}";
+        # The File '/var/run/reboot-required' is an Ubuntu native, and signifies that at least one recent update requires a reboot to fully complete their install/update.
+        # If we find that ^ file on our current host (after running updates), then the system is in the reboot preparation phase -> set it just to restart after 2 minutes
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | REBOOT REQUIRED TO FINALIZE ONE OR MORE UPDATES - SETTING A RESTART FOR 2 MINUTES FROM NOW";
+        # Schedule the system restart/reboot (NOT reset)
+        SCHEDULED_RESTART_TIME=$(date -d "$(date +%H):$(date +%M) 2 minutes" +'%H:%M');
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Calling  > sudo shutdown -r \"${SCHEDULED_RESTART_TIME}\"";
+        shutdown -r "${SCHEDULED_RESTART_TIME}";
 			fi;
 		else
-				echo "";
-				echo "$(date '+%Y-%m-%d %H:%M:%S') | Use argument '--now' to run system update";
+        echo "";
+        echo "$(date '+%Y-%m-%d %H:%M:%S') | Use argument '--now' to run system update";
 		fi;
 		if [ -f "/usr/local/bin/get_os" ]&& [ $("/usr/local/bin/get_os" | grep 'WSL' | wc -l;) -eq 1 ]; then
 			#
