Update install_kdump

diff --git a/usr/local/sbin/install_kdump b/usr/local/sbin/install_kdump
--- a/usr/local/sbin/install_kdump
+++ b/usr/local/sbin/install_kdump
@@ -35,7 +35,7 @@ else
 		/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
 	else # Service NOT found locally
 		echo "";
-		echo "Error:  Service \"${SERVICE_NAME}\" not found locally";
+		echo "Warning:  Service \"${SERVICE_NAME}\" not found locally";
 		echo "";
 		echo "Info:  Attempting to install the \"kdump\" package (for kernel crash dump logging) ...";
 		if [ $(which kdump 2>'/dev/null' | wc -l;) -eq 0 ]; then
@@ -48,14 +48,18 @@ else
 	fi;
 
 	# Verify that taget service is enabled
-	if [ "$(systemctl is-enabled ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" != "0" ]; then
-		echo "Error:  Service \"kdump\" not is not enabled --> Enabling it, now...";
+	if [ "$(systemctl is-enabled ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" == "0" ]; then
+		echo "Info:  Service \"kdump\" not is enabled (skipping enable-service)";
+	else
+		echo "Warning:  Service \"kdump\" not is not enabled --> Enabling it, now...";
 		systemctl enable ${SERVICE_NAME};
 	fi;
 
 	# Verify that taget service is active
-	if [ "$(systemctl is-active ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" != "0" ]; then
-		echo "Error:  Service \"kdump\" not is not active --> Starting it, now...";
+	if [ "$(systemctl is-active ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" == "0" ]; then
+		echo "Info:  Service \"kdump\" not is active (skipping start-service)";
+	else
+		echo "Warning:  Service \"kdump\" not is not active --> Starting it, now...";
 		systemctl start ${SERVICE_NAME};
 	fi;
 
