remove wgets

diff --git a/usr/local/sbin/install_ssh_server b/usr/local/sbin/install_ssh_server
--- a/usr/local/sbin/install_ssh_server
+++ b/usr/local/sbin/install_ssh_server
@@ -1,11 +1,11 @@
 #!/bin/bash
 #
-# LOCAL_SBIN="/usr/local/sbin/install_java" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
+# LOCAL_SBIN="/usr/local/sbin/install_ssh_server" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
 #
 # ------------------------------------------------------------
 if [ 0 -eq 1 ]; then  # RUN THIS SCRIPT
 
-curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java?t=$(date +'%s.%N')" | bash;
+curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_ssh_server?t=$(date +'%s.%N')" | bash;
 
 fi;
 #
@@ -23,11 +23,13 @@ else
 	SERVICE_NAME="java";
 
 	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
-		PACKAGE_NAME="openjdk-8-jre-headless"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Distros: Debian, Ubuntu, etc.
-		# PACKAGE_NAME_DEVTOOLS="openjdk-8-jdk-headless"; apt-get -y update; apt-get -y install "${PACKAGE_NAME_DEVTOOLS}"; # Distros: Debian, Ubuntu, etc.
-	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
-		PACKAGE_NAME="java-1.8.0-openjdk-headless"; yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
-		# PACKAGE_NAME_DEVTOOLS="java-1.8.0-openjdk-devel"; yum -y check-update; yum -y install "${PACKAGE_NAME_DEVTOOLS}"; # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
+		PACKAGE_NAME="openssh-server"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Distros: Debian, Ubuntu, etc.
+	# elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+	# 	PACKAGE_NAME="openssh-server"; yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
+	else
+		echo "";
+		echo "Error:  Environment not (yet) supported, exiting...";
+		exit 1;
 	fi;
 
 	# ------------------------------------------------------------
