Update install_vmware_tools

diff --git a/usr/local/sbin/install_vmware_tools b/usr/local/sbin/install_vmware_tools
--- a/usr/local/sbin/install_vmware_tools
+++ b/usr/local/sbin/install_vmware_tools
@@ -1,26 +1,36 @@
 #!/bin/bash
 
+EXIT_CODE=0;
+
 # Install VMware Tools
 if [ $(which vmware-toolbox-cmd 1>/dev/null 2>&1; echo $?) -eq 0 ]; then
 	# Command IS found locally
 	echo "Info:  Package already installed:  VMware Tools v$(vmware-toolbox-cmd -v)";
 else
 	# Command NOT found locally
+	echo "";
 	echo "Info:  Installing VMware Tools package \"open-vm-tools\"";
 	yum -y check-update;
 	yum -y install open-vm-tools;
-	echo "";
-	echo "Info:  Installed package:  VMware Tools v$(vmware-toolbox-cmd -v)";
-	echo "  |";
-	echo "  |--> Manually use VMware Tools via either [ /usr/bin/vmware-user ]  or  [ /usr/bin/vmware-toolbox-cmd ]  commands";
-	echo "";
-	echo "$(date +'%Y-%m-%d_%H-%M-%S')  |  Reboot required to finish installing VMWare-Tools";
-	read -p " --> Reboot, now? (y/n)  " -n 1 -t 60 -r;
-	echo "";
-	if [[ $REPLY =~ ^[Yy]$ ]]; then
-		reboot now;
+	if [ $(which vmware-toolbox-cmd 1>/dev/null 2>&1; echo $?) -eq 0 ]; then
+		echo "";
+		echo "Info:  Installed package:  VMware Tools v$(vmware-toolbox-cmd -v)";
+		echo "  |";
+		echo "  |--> Manually use VMware Tools via either [ /usr/bin/vmware-user ]  or  [ /usr/bin/vmware-toolbox-cmd ]  commands";
+		echo "";
+		echo "$(date +'%Y-%m-%d_%H-%M-%S')  |  Reboot required to finish installing VMWare-Tools";
+		read -p " --> Reboot, now? (y/n)  " -n 1 -t 60 -r;
+		echo "";
+		if [[ $REPLY =~ ^[Yy]$ ]]; then
+			reboot now;
+		fi;
+	else
+		echo "Error during installation of VMware tools, exiting...";
+		EXIT_CODE=1;
 	fi;
 fi;
+
+exit ${EXIT_CODE};
 
 
 # ------------------------------------------------------------
