Update install_docker

diff --git a/usr/local/sbin/install_docker b/usr/local/sbin/install_docker
--- a/usr/local/sbin/install_docker
+++ b/usr/local/sbin/install_docker
@@ -27,55 +27,86 @@ if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)
   echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
   exit 1;
 else
-
   BIN_DOCKER="/usr/bin/docker";
   BIN_DOCKER_COMPOSE="/usr/local/bin/docker-compose";
-
-  # ------------------------------------------------------------
-  if [ 0 -eq 1 ] && [ -n "$(command -v get_os 2>'/dev/null';)" ] && [[ "$(get_os)" == *"Microsoft"* ]]; then
+  if [ -n "$(uname -r 2>&1 | grep -i 'microsoft' 2>&1;)" ]; then # ------------------------------------------------------------
     #
-    # DEPRECATED
-    #  WSL --> Windows (docker forwarding)
-    #   |
-    #   |--> Forward docker cli calls back to the Docker Desktop (Windows Docker) install exe's
-    #   |--> Deprecated 2021-Q4 as Docker Desktop will be a paid software service around 2022-Q1
+    #   WSL OS  -  Install docker
     #
-
-    # Redirect Bash calls to Windows docker-host
-    ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" "${BIN_DOCKER}";
-    ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe" "${BIN_DOCKER_COMPOSE}";
-
-    # Download Docker Desktop (if not found locally)
-    if [ ! -f "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" ]; then
-      echo -e "\n""Error: Must install Docker Desktop (for Windows), which WSL will leverage through direct-calls via WSL 2.0 CLI pass-through""\n";
-      "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" "https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe";
-      exit 1;
+    # Determine if docker is already installed
+    PACKAGE_ALREADY_INSTALLED=$(echo "$(apt list --installed 2>'/dev/null';)" | grep -h "^docker-ce\/" | wc -l);
+    if [[ "${PACKAGE_ALREADY_INSTALLED}" -eq 0 ]] && [ ! -f "${BIN_DOCKER}" ]; then
+      # Ensure that no deprecated versions of docker are installed
+      apt-get -y remove "docker" "docker-engine" "docker.io" "containerd" "runc";
+      # Ensure that docker pre-requisites are installed
+      apt-get -y update; apt-get -y "install" "apt-transport-https" "ca-certificates" "curl" "gnupg" "lsb-release";
+      # Add the docker apt package repository
+      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee "/etc/apt/sources.list.d/docker.list" 1>'/dev/null';
+      # Add the docker apt package repository's assocated GPG key
+      curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor -o "/usr/share/keyrings/docker-archive-keyring.gpg";
+      # Install docker ce (community edition)
+      apt-get -y update; sudo apt-get -y install "docker-ce" "docker-ce-cli" "containerd.io";
     fi;
-
-    # if [ -v SUDO_USER ]; then
-    #   usermod -aG docker "${SUDO_USER}";
+    #
+    #   WSL OS  -  Install docker-compose
+    #
+    # Determine if docker-compose is already installed
+    if [ ! -f "${BIN_DOCKER_COMPOSE}" ]; then
+      # Determine the latest version of docker-compose
+      latest_version=$(curl -fsSL -o /dev/null -w "%{url_effective}" https://github.com/docker/compose-switch/releases/latest | xargs basename);
+      # Download the latest version of the docker-compose binary
+      curl -fL -o "${BIN_DOCKER_COMPOSE}" "https://github.com/docker/compose-switch/releases/download/${latest_version}/docker-compose-linux-$(dpkg --print-architecture)";
+      # Set file permission as-intended
+      chmod 0755 "${BIN_DOCKER_COMPOSE}";
+    fi;
+    #  
+    # ------------------------------  
+    # ###
+    # ###  DEPRECATED - Forward to WSL docker commands to Docker Desktop (installed on local Windows OS)
+    # ###    |
+    # ###    |--> Forward docker cli calls back to the Docker Desktop (Windows Docker) install exe's
+    # ###    |--> Deprecated 2021-Q4 as Docker Desktop will be a paid software service around 2022-Q1
+    # ###
+    # if [ 0 -eq 1 ] && [ -n "$(command -v get_os 2>'/dev/null';)" ] && [[ "$(get_os)" == *"Microsoft"* ]]; then
+    #   # Redirect Bash calls to Windows docker-host
+    #   ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" "${BIN_DOCKER}";
+    #   ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe" "${BIN_DOCKER_COMPOSE}";
+    #   # Download Docker Desktop (if not found locally)
+    #   if [ ! -f "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" ]; then
+    #     echo -e "\n""Error: Must install Docker Desktop (for Windows), which WSL will leverage through direct-calls via WSL 2.0 CLI pass-through""\n";
+    #     "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" "https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe";
+    #     exit 1;
+    #   fi;
+    #   # if [ -v SUDO_USER ]; then
+    #   #   usermod -aG docker "${SUDO_USER}";
+    #   # fi;
+    #   # usermod -aG docker "${USER}";
+    #   # Redirect Bash calls to Windows docker-host
+    #   ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" "${BIN_DOCKER}";
+    #   ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe" "${BIN_DOCKER_COMPOSE}";
     # fi;
-    # usermod -aG docker "${USER}";
-
-    # Redirect Bash calls to Windows docker-host
-    ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" "${BIN_DOCKER}";
-    ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe" "${BIN_DOCKER_COMPOSE}";
-
+    # ###
+    # ###
+    # ###
+    # ------------------------------
+    #
   else # ------------------------------------------------------------
     #
-    # Docker Installation
+    #   Non-WSL OS  -  Install docker
     #
-
-    if [ ! -f "${BIN_DOCKER}" ]; then
+    # Determine if docker is already installed
+    PACKAGE_ALREADY_INSTALLED=$(echo "$(apt list --installed 2>'/dev/null';)" | grep -h "^docker-ce\/" | wc -l);
+    if [[ "${PACKAGE_ALREADY_INSTALLED}" -eq 0 ]] && [ ! -f "${BIN_DOCKER}" ]; then
       curl -sL "https://get.docker.com/" | sh;
     fi;
-
-    SERVICE_NAME="docker";
-    if [ -z "$(/usr/sbin/service ${SERVICE_NAME} status | grep 'Active: active (running)')" ]; then
-      echo "Calling [ /usr/sbin/service \"${SERVICE_NAME}\" start; ]...";
-      /usr/sbin/service "${SERVICE_NAME}" start;
+    if [ -z "$(/usr/sbin/service docker status | grep 'Active: active (running)')" ]; then
+      echo "Calling [ /usr/sbin/service \"docker\" start; ]...";
+      /usr/sbin/service "docker" start;
     fi;
-
+    #
+    #   Non-WSL OS  -  Install docker-compose
+    #
+    # Determine if docker-compose is already installed
     if [ ! -f "${BIN_DOCKER_COMPOSE}" ]; then
 
       if [ -n "$(command -v apk 2>'/dev/null';)" ]; then
@@ -105,18 +136,17 @@ else
         echo "Calling [ python3 -m pip install -IU docker-compose; ]...";
         python3 -m pip install -IU docker-compose;
       fi;
-
+      # Set file permission as-intended
       chmod 0755 "${BIN_DOCKER_COMPOSE}";
-
     fi;
-    
   fi;
-
-  systemctl enable docker --now;
-
+  # Show installed versions of docker & docker-compose
   "${BIN_DOCKER}" --version;
   "${BIN_DOCKER_COMPOSE}" --version;
-
+  # Enable docker locally
+  if [[ "$(systemctl status 1>'/dev/null' 2>&1; echo ${?};)" -eq 0 ]]; then
+    systemctl enable docker --now;
+  fi;
 fi;
 
 
