Update partition_unpartitioned_disks

diff --git a/usr/local/sbin/partition_unpartitioned_disks b/usr/local/sbin/partition_unpartitioned_disks
--- a/usr/local/sbin/partition_unpartitioned_disks
+++ b/usr/local/sbin/partition_unpartitioned_disks
@@ -37,22 +37,44 @@ else
 	EACH_DISK_DEVICE=$(echo "${EACH_LINE}" | cut -d':' -f1;);
 	EACH_DISK_SIZE=$(echo "${EACH_LINE}" | cut -d':' -f2;);
 	EACH_PARTITION_TABLE=$(echo "${EACH_LINE}" | cut -d':' -f6;);
+
 	# Partition un-partitioned disk(s)
 	if [ "${EACH_PARTITION_TABLE}" == "unknown" ]; then
-		echo "Info:  Partitioning  [  ${EACH_DISK_DEVICE}  ]  as 'msdos'...";
-		parted -s "${EACH_DISK_DEVICE}" mklabel 'msdos';
+		echo "";
+		READ_TIMEOUT=60;
+		read -p "CONFIRM:  Do you wish to partition the device  [  ${EACH_DISK_DEVICE}  ] (which is currently unpartitioned) using type [  msdos  ]  , now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
+		echo "";
+		if [ ${RETURN_CODE_READ} -gt 128 ]; then
+			echo "Error:  Response timed out after ${READ_TIMEOUT}s";
+		elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
+			echo "Info:  Confirmed - Calling  [ parted -s \"${EACH_DISK_DEVICE}\" mklabel 'msdos'; ] ...";
+			parted -s "${EACH_DISK_DEVICE}" mklabel 'msdos';
+		else
+			echo "Info:  Denied - Skipping call   [ parted -s \"${EACH_DISK_DEVICE}\" mklabel 'msdos'; ]";
+		fi;
 	else
 		echo "Info:  Skipping disk-partitioning for device  [  ${EACH_DISK_DEVICE}  ]  (already partitioned as ${EACH_PARTITION_TABLE})";
 	fi;
+
 	# Add volume(s) to empty disk(s)
 	EACH_DISK_VOLUME_COUNT="$(parted -s ${EACH_DISK_DEVICE} print 2>&1 | grep -E '^\s+[0-9]\s' | wc -l;)";
 	if [ "${EACH_DISK_VOLUME_COUNT}" == "0" ]; then
-		echo "Info:  Creating volume  [ ${EACH_DISK_SIZE} ] on device  [  ${EACH_DISK_DEVICE}  ]  w/ using filesystem-type  [ ext4 ]...";
-		parted -s "${EACH_DISK_DEVICE}" mkpart "primary" "ext4" 0 "${EACH_DISK_SIZE}";
-		fdisk -l "${EACH_DISK_DEVICE}";
+		echo "";
+		READ_TIMEOUT=60;
+		read -p "CONFIRM:  Do you want to create a  [  ${EACH_DISK_SIZE}  ]  volume on device  [  ${EACH_DISK_DEVICE}  ]  using filesystem-type  [  ext4  ]  , now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
+		echo "";
+		if [ ${RETURN_CODE_READ} -gt 128 ]; then
+			echo "Error:  Response timed out after ${READ_TIMEOUT}s";
+		elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
+			echo "Info:  Confirmed - Calling  [ parted -s \"${EACH_DISK_DEVICE}\" mklabel 'msdos'; fdisk -l \"${EACH_DISK_DEVICE}\"; ] ...";
+			parted -s "${EACH_DISK_DEVICE}" mklabel 'msdos'; fdisk -l "${EACH_DISK_DEVICE}";
+		else
+			echo "Info:  Denied - Skipping call  [ parted -s \"${EACH_DISK_DEVICE}\" mklabel 'msdos'; fdisk -l \"${EACH_DISK_DEVICE}\"; ]";
+		fi;
 	else
-		echo "Info:  Skipping volume-creation for device  [  ${EACH_DISK_DEVICE}  ]  (already contains  [ ${EACH_DISK_VOLUME_COUNT} ]  volume(s))";
+		echo "Info:  Skipping volume-creation for device  [  ${EACH_DISK_DEVICE}  ]  (already contains  [  ${EACH_DISK_VOLUME_COUNT}  ]  volume(s))";
 	fi;
+
 	# Mount un-mounted volume(s)
 	KERNEL_DISK_MOUNTS="/proc/mounts";
 	EACH_DISK_MOUNT_POINTS="$(grep "^${EACH_DISK_DEVICE}" "${KERNEL_DISK_MOUNTS}" 2>'/dev/null' | wc -l;)";
@@ -61,9 +83,18 @@ else
 		if [ -d "${EACH_NEW_MOUNT}" ]; then
 			EACH_NEW_MOUNT="${EACH_NEW_MOUNT}_$(date +'%s')";
 		fi;
-		echo "Info:  Mounting device  [ ${EACH_DISK_DEVICE} ] to filepath  [  ${EACH_NEW_MOUNT}  ]...";
-		mkdir -p "${EACH_NEW_MOUNT}";
-		mount "${EACH_DISK_DEVICE}" "${EACH_NEW_MOUNT}";
+		echo "";
+		READ_TIMEOUT=60;
+		read -p "CONFIRM:  Do you want to mount device  [ ${EACH_DISK_DEVICE} ]  to filepath  [  ${EACH_NEW_MOUNT}  ]  , now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
+		echo "";
+		if [ ${RETURN_CODE_READ} -gt 128 ]; then
+			echo "Error:  Response timed out after ${READ_TIMEOUT}s";
+		elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
+			echo "Info:  Confirmed - Calling  [ mkdir -p \"${EACH_NEW_MOUNT}\"; mount \"${EACH_DISK_DEVICE}\" \"${EACH_NEW_MOUNT}\"; ] ...";
+			mkdir -p "${EACH_NEW_MOUNT}"; mount "${EACH_DISK_DEVICE}" "${EACH_NEW_MOUNT}";
+		else
+			echo "Info:  Denied - Skipping call  [ mkdir -p \"${EACH_NEW_MOUNT}\"; mount \"${EACH_DISK_DEVICE}\" \"${EACH_NEW_MOUNT}\"; ]";
+		fi;
 	else
 		echo "Info:  Skipping disk-mounting for device  [  ${EACH_DISK_DEVICE}  ]  (already mounted @  [ ${EACH_DISK_MOUNT_POINTS} ]  location(s))";
 	fi;
