replace lines starting with tabs with spaces (tab count 5)

diff --git a/usr/local/sbin/set_hostname b/usr/local/sbin/set_hostname
--- a/usr/local/sbin/set_hostname
+++ b/usr/local/sbin/set_hostname
@@ -70,14 +70,14 @@ else
 
 			if [ "${EACH_ARG}" == "--name" ] || [ "${EACH_ARG}" == "--hostname" ]; then
 				if [ "${ARGS_HOSTNAME_DEFINED}" == "1" ]; then
-					echo "";
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Inline parameters contain more than one value for hostname";
-					echo "";
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Info: Please call again using one, single value";
-					exit 1;
+          echo "";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Inline parameters contain more than one value for hostname";
+          echo "";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Info: Please call again using one, single value";
+          exit 1;
 				else
-					ARGS_HOSTNAME_DEFINED=1;
-					INPUT_HOSTNAME="${NEXT_ARG}";
+          ARGS_HOSTNAME_DEFINED=1;
+          INPUT_HOSTNAME="${NEXT_ARG}";
 				fi;
 			fi;
 
@@ -254,17 +254,17 @@ else
 				cat "${HOSTNAME_FILE}";
 				echo "------------------------------------------------------------";
 				if [ "$(cat ${HOSTNAME_FILE})" != "{SET_HOSTNAME}" ]; then # update required for hostname file
-					echo "";
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Updating hostname file \"${HOSTNAME_FILE}\" to contain new hostname \"${SET_HOSTNAME}\", instead";
-					echo "${SET_HOSTNAME}" > "${HOSTNAME_FILE}";
-					echo "";
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling [ cat \"${HOSTNAME_FILE}\"; ]  (after edits, $(date +'%Y-%m-%d %H:%M:%S'))";
-					echo "------------------------------------------------------------";
-					cat "${HOSTNAME_FILE}";
-					echo "------------------------------------------------------------";
+          echo "";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Updating hostname file \"${HOSTNAME_FILE}\" to contain new hostname \"${SET_HOSTNAME}\", instead";
+          echo "${SET_HOSTNAME}" > "${HOSTNAME_FILE}";
+          echo "";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling [ cat \"${HOSTNAME_FILE}\"; ]  (after edits, $(date +'%Y-%m-%d %H:%M:%S'))";
+          echo "------------------------------------------------------------";
+          cat "${HOSTNAME_FILE}";
+          echo "------------------------------------------------------------";
 				else
-					echo "";
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Skipping update for hostname file \"${HOSTNAME_FILE}\" (already matches desired hostname)";
+          echo "";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Skipping update for hostname file \"${HOSTNAME_FILE}\" (already matches desired hostname)";
 				fi;
 			fi;
 		fi;
@@ -351,17 +351,17 @@ else
 			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
 
 				if [ -n "${SET_DOMAIN}" ]; then
-					sed -i -e "/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}.${SET_DOMAIN}" "/etc/sysconfig/network";
+          sed -i -e "/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}.${SET_DOMAIN}" "/etc/sysconfig/network";
 				else
-					sed -i -e "/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}" "/etc/sysconfig/network";
+          sed -i -e "/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}" "/etc/sysconfig/network";
 				fi;
 
 			else # dry-run
 				echo "";
 				if [ -n "${SET_DOMAIN}" ]; then
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}.${SET_DOMAIN}\" \"/etc/sysconfig/network\"; ]";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}.${SET_DOMAIN}\" \"/etc/sysconfig/network\"; ]";
 				else
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}\" \"/etc/sysconfig/network\"; ]";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}\" \"/etc/sysconfig/network\"; ]";
 				fi;
 			fi;
 		fi;
@@ -407,13 +407,13 @@ else
 				read -p "   |--> Restart Network Manager, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
 				echo "";
 				if [[ $REPLY =~ ^[Yy]$ ]]; then
-					echo "";
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Restarting Network Manager via command  [ /etc/init.d/network restart ]";
-					/etc/init.d/network restart;
+          echo "";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Restarting Network Manager via command  [ /etc/init.d/network restart ]";
+          /etc/init.d/network restart;
 				else
-					echo "";
-					echo "$(date +'%Y-%m-%d %H:%M:%S') Postponing Network Manager restart";
-					exit 1;
+          echo "";
+          echo "$(date +'%Y-%m-%d %H:%M:%S') Postponing Network Manager restart";
+          exit 1;
 				fi;
 			else # dry-run
 				echo "";
@@ -426,13 +426,13 @@ else
 				read -p "   |--> Reboot this workstation/server, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
 				echo "";
 				if [[ $REPLY =~ ^[Yy]$ ]]; then
-					echo "";
-					echo "Rebooting...";
-					shutdown -r now;
+          echo "";
+          echo "Rebooting...";
+          shutdown -r now;
 				else
-					echo "";
-					echo "System restart postponed";
-					exit 1;
+          echo "";
+          echo "System restart postponed";
+          exit 1;
 				fi;
 			# else # dry-run
 			# 	echo "";
diff --git a/usr/local/sbin/sudoer_status b/usr/local/sbin/sudoer_status
--- a/usr/local/sbin/sudoer_status
+++ b/usr/local/sbin/sudoer_status
@@ -65,33 +65,33 @@ else
 			# ------------------------------------------------------------
 			if [ "${EACH_ARG}" == "--allow" ] || [ "${EACH_ARG}" == "--grant" ] || [ "${EACH_ARG}" == "--add" ] || [ "${EACH_ARG}" == "--deny" ] || [ "${EACH_ARG}" == "--revoke" ] || [ "${EACH_ARG}" == "--remove" ]; then
 				if [ -n "${EDIT_ACTION}" ]; then
-					# Error: Multiple add/remove actions defined
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Invalid inline-argument(s) detected:   Must not call function with more than one argument out of:  [ \"--allow\"  \"--add\"  \"--revoke\"  \"--remove\" ]"; exit 1;
+          # Error: Multiple add/remove actions defined
+          echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Invalid inline-argument(s) detected:   Must not call function with more than one argument out of:  [ \"--allow\"  \"--add\"  \"--revoke\"  \"--remove\" ]"; exit 1;
 				elif [ "${EACH_ARG}" == "--allow" ] || [ "${EACH_ARG}" == "--grant" ]  || [ "${EACH_ARG}" == "--add" ]; then
-					# Add user as a sudoer
-					EDIT_ACTION="ALLOW";
+          # Add user as a sudoer
+          EDIT_ACTION="ALLOW";
 				elif [ "${EACH_ARG}" == "--deny" ]  || [ "${EACH_ARG}" == "--revoke" ] || [ "${EACH_ARG}" == "--remove" ]; then
-					# Remove user from sudoers
-					EDIT_ACTION="REVOKE";
+          # Remove user from sudoers
+          EDIT_ACTION="REVOKE";
 				else
-					# Show user's sudoer-status
-					EDIT_ACTION="";
+          # Show user's sudoer-status
+          EDIT_ACTION="";
 				fi;
 			fi;
 
 			# ------------------------------------------------------------
 			if [ "${EACH_ARG}" == "--user" ] && [ -n "${NEXT_ARG}" ]; then
 				if [ -n "${TARGET_USER}" ]; then
-					# Error: Multiple users defined
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; exit 1;
+          # Error: Multiple users defined
+          echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; exit 1;
 
 				elif [ $(id -u ${NEXT_ARG} > /dev/null 2>&1; echo $?) -eq 1 ]; then
-					# Error: Non-existent target-user
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found as a local user: \"${NEXT_ARG}\"";
-					echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
+          # Error: Non-existent target-user
+          echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found as a local user: \"${NEXT_ARG}\"";
+          echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
 
 				else
-					TARGET_USER="${NEXT_ARG}";
+          TARGET_USER="${NEXT_ARG}";
 				fi;
 			fi;
 
@@ -142,9 +142,9 @@ else
 
 				SUDOER_FILE_CONTENTS="";
 				if [[ "${SUDO_REQUIRES_USERPASS}" == "1" ]]; then
-					SUDOER_FILE_CONTENTS="${TARGET_USER} ALL=(ALL) ALL";
+          SUDOER_FILE_CONTENTS="${TARGET_USER} ALL=(ALL) ALL";
 				else
-					SUDOER_FILE_CONTENTS="${TARGET_USER} ALL=(ALL) NOPASSWD:ALL";
+          SUDOER_FILE_CONTENTS="${TARGET_USER} ALL=(ALL) NOPASSWD:ALL";
 				fi;
 
 				# Add the user-specific 'sudo' config-file
@@ -156,7 +156,7 @@ else
 				GROUP_SUDOERS="sudo";
 				# Create the group 'sudo' (if it doesn't already exist)
 				if [ -z "$(getent group sudo)" ]; then
-					groupadd "${GROUP_SUDOERS}";
+          groupadd "${GROUP_SUDOERS}";
 				fi;
 
 				# Add the user to the group 'sudo'
@@ -169,7 +169,7 @@ else
 				# Remove the user-specific 'sudo' config-file
 				SUDOER_FILE_FULLPATH="${SUDOERS_D}/${TARGET_USER}";
 				if [ -f "${SUDOER_FILE_FULLPATH}" ]; then
-					rm -f "${SUDOER_FILE_FULLPATH}";
+          rm -f "${SUDOER_FILE_FULLPATH}";
 				fi;
 
 				# Remove the user from the group 'sudo'
diff --git a/usr/local/sbin/update_jenkins_warfile b/usr/local/sbin/update_jenkins_warfile
--- a/usr/local/sbin/update_jenkins_warfile
+++ b/usr/local/sbin/update_jenkins_warfile
@@ -102,12 +102,12 @@ else
 
 				# Backup [ a Version-stamped copy ] of [ the current jenkins runtime ]
 				if [ ! -f "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_SYSTEM}" ]; then
-					cp --verbose --force "${JENKINS_RUNTIME_SYSTEM}" "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_SYSTEM}";
+          cp --verbose --force "${JENKINS_RUNTIME_SYSTEM}" "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_SYSTEM}";
 				fi;
 
 				# Backup [ a Version-stamped copy ] of [ the downloaded runtime ]
 				if [ ! -f "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_DOWNLOADED}" ]; then
-					cp --verbose --force "${JENKINS_RUNTIME_DOWNLOADED}" "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_DOWNLOADED}";
+          cp --verbose --force "${JENKINS_RUNTIME_DOWNLOADED}" "${JENKINS_RUNTIME_SYSTEM}.v${JENKINS_VERSION_DOWNLOADED}";
 				fi;
 
 				# Stop the Jenkins service (before updating its runtime warfile)
@@ -121,7 +121,7 @@ else
 
 				# Re-Sync to repo/cloud-sync settings
 				if [ $(which sync_cloud_infrastructure 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
-					sync_cloud_infrastructure --jenkins;
+          sync_cloud_infrastructure --jenkins;
 				fi;
 
 				# Start the Jenkins service (after updating its runtime warfile)
@@ -131,24 +131,24 @@ else
 
 				# Reload NGINX (if found locally)
 				if [ $(which nginx 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
-					if [ $(which reload_nginx 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
+          if [ $(which reload_nginx 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
             echo "";
             echo "$(date +'%D  %r')   Calling [ reload_nginx ]...";
             reload_nginx;
-					else
+          else
             echo "";
             echo "$(date +'%D  %r')   Calling [ nginx -t && sleep 1 && /usr/sbin/service nginx stop; ]...";
             nginx -t && sleep 1 && /usr/sbin/service nginx stop;
-					fi;
+          fi;
 				else
-					echo "";
-					echo "$(date +'%D  %r')   Skipping NGINX service-restart (NGINX not found locally, e.g. calling [ which nginx ] returned nothing)";
+          echo "";
+          echo "$(date +'%D  %r')   Skipping NGINX service-restart (NGINX not found locally, e.g. calling [ which nginx ] returned nothing)";
 				fi;
 
 				# Re-Sync to repo/cloud-sync settings
 				if [ $(which sync_cloud_infrastructure 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Command exists
-					sleep 30;
-					sync_cloud_infrastructure --jenkins;
+          sleep 30;
+          sync_cloud_infrastructure --jenkins;
 				fi;
 
 			fi;
