Update set_hostname

diff --git a/usr/local/sbin/set_hostname b/usr/local/sbin/set_hostname
--- a/usr/local/sbin/set_hostname
+++ b/usr/local/sbin/set_hostname
@@ -35,9 +35,82 @@ else
 	#	>		set_hostname "localhost.localdomain" "0";
 	#
 
-	if [ -n "${1}" ] && [ -z "${SET_HOSTNAME}" ]; then
-		SET_HOSTNAME="${1}";
-	fi;
+
+	# ------------------------------------------------------------
+	# Parse inline arguments (passed to current script)
+	#
+
+	ARGS=("$@");
+	COUNT_ARGS=${#ARGS[@]};
+	ARGS_HOSTNAME_DEFINED=0;
+	echo "COUNT_ARGS = ${COUNT_ARGS}";
+	for (( i=0;i<$COUNT_ARGS;i++ )); do
+
+		# Walk through any inline-arguments passed to this function
+		EACH_ARG=${ARGS[${i}]};
+		# BASH_ARG_NUMBER=$((${i}+1)); # Bash arg-number is one greater than the ARGS arg-number (because of bash's ${0} containing the entire inline command)
+
+		# Check if this is the last inline-argument or if there are more to follow
+		if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
+			NEXT_ARG="";
+		else
+			NEXT_ARG=${ARGS[$((${i}+1))]};
+		fi;
+
+		if [ -n "${EACH_ARG}" ]; then
+
+			# Parse inline hostname
+			if [ ${i} -eq 0 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then
+				NEXT_ARG="${EACH_ARG}";
+				EACH_ARG="--hostname";
+			fi;
+
+			if [ "${EACH_ARG}" == "--hostname" ]; then
+				if [ "${ARGS_HOSTNAME_DEFINED}" == "1" ]; then
+					echo "";
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error during \"${0}\":";
+					echo "Inline parameters contain multiple hostname values";
+					echo "Please call again using one, single value for ";
+					echo "";
+					exit 1;
+				elif [ -z "${NEXT_ARG}" ]; then
+					echo "";
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error during \"${0}\":";
+					echo "Function called with an empty value for the hostname (or --hostname as the last argument)"
+					echo "Please call again using \"--hostname [VALID_HOSTNAME]\"";
+					echo "";
+					exit 1;
+				elif [ "${NEXT_ARG}" != "$(echo ${NEXT_ARG} | grep --extended-regexp '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$';)" ]; then
+					echo "";
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error during \"${0}\":";
+					echo "Function called with invalid hostname \"${NEXT_ARG}\"";
+					echo "Please call again using a valid hostname string";
+					echo "";
+					exit 1;
+				else
+					ARGS_HOSTNAME_DEFINED=1;
+					SET_HOSTNAME="${NEXT_ARG}";
+					SET_FQDN="${SET_HOSTNAME}.${SET_DOMAIN}";
+				fi;
+			fi;
+
+			# Parse dry-run / non-dry-run calls
+			if [ "${EACH_ARG}" == "--force" ]; then # --force
+				DRY_RUN="0";
+			elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "0" ]; then # --dry-run 0
+				DRY_RUN="0";
+			elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "false" ]; then # --dry-run false
+				DRY_RUN="0";
+			fi;
+
+		fi;
+	done;
+
+	# ------------------------------------------------------------
+
+	# if [ -n "${1}" ] && [ -z "${SET_HOSTNAME}" ]; then
+	# 	SET_HOSTNAME="${1}";
+	# fi;
 
 	if [ -z "${SET_HOSTNAME}" ]; then
 
@@ -72,75 +145,6 @@ else
 		echo " |";
 		echo " |--> FQDN will be: \"${SET_FQDN}\"";
 		echo "";
-
-		# ------------------------------------------------------------
-		# Parse inline arguments (passed to current script)
-		#
-
-		ARGS=("$@");
-		COUNT_ARGS=${#ARGS[@]};
-		ARGS_HOSTNAME_DEFINED=0;
-		echo "COUNT_ARGS = ${COUNT_ARGS}";
-		for (( i=0;i<$COUNT_ARGS;i++ )); do
-
-			# Walk through any inline-arguments passed to this function
-			EACH_ARG=${ARGS[${i}]};
-			BASH_ARG_NUMBER=$((${i}+1)); # Bash arg-number is one greater than the ARGS arg-number (because of bash's ${0} containing the entire inline command)
-
-			# Check if this is the last inline-argument or if there are more to follow
-			if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
-				NEXT_ARG="";
-			else
-				NEXT_ARG=${ARGS[$((${i}+1))]};
-			fi;
-
-			if [ -n "${EACH_ARG}" ]; then
-
-				# Parse inline hostname
-				if [ ${BASH_ARG_NUMBER} -eq 1 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then
-					NEXT_ARG="${EACH_ARG}";
-					EACH_ARG="--hostname";
-				fi;
-				if [ "${EACH_ARG}" == "--hostname" ]; then
-					if [ "${ARGS_HOSTNAME_DEFINED}" == "1" ]; then
-						echo "";
-						echo "$(date +'%Y-%m-%d %H:%M:%S') | Error during \"${0}\":";
-						echo "Inline parameters contain multiple hostname values";
-						echo "Please call again using one, single value for ";
-						echo "";
-						exit 1;
-					elif [ -z "${NEXT_ARG}" ]; then
-						echo "";
-						echo "$(date +'%Y-%m-%d %H:%M:%S') | Error during \"${0}\":";
-						echo "Function called with an empty value for the hostname (or --hostname as the last argument)"
-						echo "Please call again using \"--hostname [VALID_HOSTNAME]\"";
-						echo "";
-						exit 1;
-					elif [ "${NEXT_ARG}" != "$(echo ${NEXT_ARG} | grep --extended-regexp '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$';)" ]; then
-						echo "";
-						echo "$(date +'%Y-%m-%d %H:%M:%S') | Error during \"${0}\":";
-						echo "Function called with invalid hostname \"${NEXT_ARG}\"";
-						echo "Please call again using a valid hostname string";
-						echo "";
-						exit 1;
-					else
-						ARGS_HOSTNAME_DEFINED=1;
-						SET_HOSTNAME="${NEXT_ARG}";
-						SET_FQDN="${SET_HOSTNAME}.${SET_DOMAIN}";
-					fi;
-				fi;
-
-				# Parse dry-run / non-dry-run calls
-				if [ "${EACH_ARG}" == "--force" ]; then # --force
-					DRY_RUN="0";
-				elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "0" ]; then # --dry-run 0
-					DRY_RUN="0";
-				elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "false" ]; then # --dry-run false
-					DRY_RUN="0";
-				fi;
-
-			fi;
-		done;
 
 		if [ -n "${DRY_RUN}" ]; then
 			if [ "${DRY_RUN}" != "1" ] && [ "${DRY_RUN}" != "0" ]; then
