Update set_hostname

diff --git a/usr/local/sbin/set_hostname b/usr/local/sbin/set_hostname
--- a/usr/local/sbin/set_hostname
+++ b/usr/local/sbin/set_hostname
@@ -57,9 +57,11 @@ else
 
 		SET_FQDN="${SET_HOSTNAME}.${SET_DOMAIN}";
 		
+		echo "";
 		echo "Set Hostname: \"${SET_HOSTNAME}\"";
+		echo "       |--> FQDN: \"${SET_FQDN}\"";
 		echo "Set Domain: \"${SET_DOMAIN}\"";
-		echo "Combined (FQDN): \"${SET_FQDN}\"";
+		echo "";
 
 		# ------------------------------------------------------------
 		# Determine Dry-Run mode
@@ -67,6 +69,7 @@ else
 
 		if [ -n "${DRY_RUN}" ]; then
 			if [ "${DRY_RUN}" != "1" ] && [ "${DRY_RUN}" != "0" ]; then
+				echo "";
 				echo "$(date +'%Y-%m-%d %H:%M:%S') | Error - Invalid value given for \$DRY_RUN (\$2==\"${2}\")";
 				echo "Please set to \"1\" for dry-run mode, \"0\" for live-run mode";
 				echo "  ( e.g. set_hostname \"localhost.localdomain\" \"1\"; )";
@@ -76,6 +79,7 @@ else
 			fi;
 		elif [ -n "${2}" ]; then
 			if [ "${2}" != "1" ] && [ "${2}" != "0" ]; then
+				echo "";
 				echo "$(date +'%Y-%m-%d %H:%M:%S') | Warning - Invalid value given for \$DRY_RUN (\$2==\"${2}\")";
 				echo "Please set to \"1\" for dry-run mode, \"0\" for live-run mode";
 				echo "  ( e.g. set_hostname \"localhost.localdomain\" \"1\"; )";
@@ -87,6 +91,7 @@ else
 				DRY_RUN=${2};
 			fi;
 		else
+			echo "";
 			echo "$(date +'%Y-%m-%d %H:%M:%S') | Warning - No value given for \$DRY_RUN (\$2)";
 			echo "Please set to \"1\" for dry-run mode, \"0\" for live-run mode";
 			echo "  ( e.g. set_hostname \"localhost.localdomain\" \"0\"; )";
@@ -122,22 +127,11 @@ else
 		RESOLVER_3="https://ident.me";
 		RESOLVER_4="https://bot.whatismyipaddress.com";
 
-		# Attempt to resolve WAN IPv4
+		### Get WAN IPv4
 		if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_1}"); fi; RESOLVER_USED="${RESOLVER_1}";
 		if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_2}"); fi; RESOLVER_USED="${RESOLVER_2}";
 		if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_3}"); fi; RESOLVER_USED="${RESOLVER_3}";
 		if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_4}"); fi; RESOLVER_USED="${RESOLVER_4}";
-
-		# Verify WAN IPv4
-		if [ -n "${THIS_WAN_IPV4}" ]; then
-			echo "Resolved WAN IPv4 to: \"${THIS_WAN_IPV4}\"";
-		else 
-			echo "$(date +'%Y-%m-%d %H:%M:%S') | Error - Unable to resolve WAN IPv4.";
-			echo "If you wish to manually set it, please set \${THIS_WAN_IPV4} to your desired value and re-run this script.";
-			exit 1;
-		fi;
-
-		# ------------------------------------------------------------
 
 		### Get LAN Gateway IPv4
 		GATEWAY_LAN_IPV4=$(ip route|grep 'default via '|sed --quiet --regexp-extended --expression="s/^default\s+via\s+([0-9a-fA-F\:\.]+)\s+[a-zA-Z0-9]+\s+([a-zA-Z0-9]+).+$/\1/p");
@@ -148,6 +142,17 @@ else
 		### Get LAN IPv4 / IPv6
 		THIS_LAN_IPV4=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\.');
 		THIS_LAN_IPV6=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\:');
+
+		echo "";
+
+		### Show Resolved WAN IPv4
+		if [ -n "${THIS_WAN_IPV4}" ]; then
+			echo "Resolved IPv4 Address (WAN) to: \"${THIS_WAN_IPV4}\"";
+		else 
+			echo "$(date +'%Y-%m-%d %H:%M:%S') | Error - Unable to resolve IPv4 Address (WAN).";
+			echo "If you wish to manually set it, please set \${THIS_WAN_IPV4} to your desired value and re-run this script.";
+			exit 1;
+		fi;
 
 		### Show Resolved Gateway IPv4
 		if [ -n "${GATEWAY_LAN_IPV4}" ]; then
@@ -171,6 +176,8 @@ else
 		else 
 			echo "$(date +'%Y-%m-%d %H:%M:%S') | Warning - Unable to resolve IPv6 Address (LAN).";
 		fi;
+
+		echo "";
 
 		# ------------------------------------------------------------
 		#	If Dry-Run mode is off, require user to confirm changes
