Update sudoer_status

diff --git a/usr/local/sbin/sudoer_status b/usr/local/sbin/sudoer_status
--- a/usr/local/sbin/sudoer_status
+++ b/usr/local/sbin/sudoer_status
@@ -33,7 +33,7 @@ else
 	EDIT_ACTION="";
 	TARGET_USER="";
 	REQUIRE_USERPASS="1";
-	EXAMPLE_VALID_CALL="\n$(date +'%Y-%m-%d %H:%M:%S') | Info → Please specify a valid local user via:  >  sudoer_status --user USERNAME""\n";
+	EXAMPLE_VALID_CALL="\n$(date +'%Y-%m-%d %H:%M:%S') | Info --> Please specify a valid local user via:  >  sudoer_status --user USERNAME""\n";
 
 	# Walk through any inline-arguments passed to this function
 	for (( i=0;i<$COUNT_ARGS;i++ )); do
@@ -56,7 +56,7 @@ else
 			if [ "${EACH_ARG}" == "--allow" ] || [ "${EACH_ARG}" == "--grant" ] || [ "${EACH_ARG}" == "--add" ] || [ "${EACH_ARG}" == "--deny" ] || [ "${EACH_ARG}" == "--revoke" ] || [ "${EACH_ARG}" == "--remove" ]; then
 				if [ -n "${EDIT_ACTION}" ]; then
 					# Error: Multiple add/remove actions defined
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Invalid inline-argument(s) detected:   Must not call function with more than one argument out of:  [ \"--allow\"  \"--add\"  \"--revoke\"  \"--remove\" ]"; exit 1;
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Invalid inline-argument(s) detected:   Must not call function with more than one argument out of:  [ \"--allow\"  \"--add\"  \"--revoke\"  \"--remove\" ]"; exit 1;
 				elif [ "${EACH_ARG}" == "--allow" ] || [ "${EACH_ARG}" == "--grant" ]  || [ "${EACH_ARG}" == "--add" ]; then
 					# Add user as a sudoer
 					EDIT_ACTION="ALLOW";
@@ -73,11 +73,11 @@ else
 			if [ "${EACH_ARG}" == "--user" ] && [ -n "${NEXT_ARG}" ]; then
 				if [ -n "${TARGET_USER}" ]; then
 					# Error: Multiple users defined
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; exit 1;
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; exit 1;
 
 				elif [ $(id -u ${NEXT_ARG} > /dev/null 2>&1; echo $?) -eq 1 ]; then
 					# Error: Non-existent target-user
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → User not found as a local user: \"${NEXT_ARG}\"";
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found as a local user: \"${NEXT_ARG}\"";
 					echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
 
 				else
@@ -102,13 +102,13 @@ else
 	if [ -z "${TARGET_USER}" ]; then 
 
 		# Error: Empty/Unset target-user
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Target-user empty / unset";
+		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Target-user empty / unset";
 		echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
 
 	elif [ $(id -u ${TARGET_USER} > /dev/null 2>&1; echo $?) -eq 1 ]; then
 
 		# Error: User not found
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → User not found: \"${TARGET_USER}\"";
+		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found: \"${TARGET_USER}\"";
 		echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
 
 	else
@@ -155,8 +155,8 @@ else
 
 		else
 			#	Check whether-or-not a user can masquerade as the root user (via the 'sudo' command)
-			echo "$(date +'%Y-%m-%d %H:%M:%S') | Info → To grant sudoer privileges, call with: >  sudoer_status --user ${TARGET_USER} --grant";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') | Info → To revoke sudoer privileges, call with: >  sudoer_status --user ${TARGET_USER} --revoke";
+			echo "$(date +'%Y-%m-%d %H:%M:%S') | Info --> To grant sudoer privileges, call with: >  sudoer_status --user ${TARGET_USER} --grant";
+			echo "$(date +'%Y-%m-%d %H:%M:%S') | Info --> To revoke sudoer privileges, call with: >  sudoer_status --user ${TARGET_USER} --revoke";
 
 		fi;
 		# ------------------------------------------------------------
