Update sudoer_status

diff --git a/usr/local/sbin/sudoer_status b/usr/local/sbin/sudoer_status
--- a/usr/local/sbin/sudoer_status
+++ b/usr/local/sbin/sudoer_status
@@ -33,6 +33,7 @@ else
 	EDIT_ACTION="";
 	TARGET_USER="";
 	REQUIRE_USERPASS="1";
+	ERROR_INVALID_USER="\n$(date +'%Y-%m-%d %H:%M:%S') | Info → Please specify a valid local user via:""\n""  >  sudoer_status --user USERNAME""\n";
 
 	# Walk through any inline-arguments passed to this function
 	for (( i=0;i<$COUNT_ARGS;i++ )); do
@@ -70,9 +71,12 @@ else
 				if [ -n "${TARGET_USER}" ]; then
 					# Error - Multiple users defined
 					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; exit 1;
-				elif [ -z "$(id ${NEXT_ARG} 2>/dev/null)" ]; then
+
+				elif [ $(id -u ${NEXT_ARG} > /dev/null 2>&1; echo $?) -eq 1 ]; then
 					# Error - Non-existent target-user
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → User \"${NEXT_ARG}\" not found to exist"; exit 1;
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → User not found as a local user: \"${TARGET_USER}\")";
+					echo -e "${ERROR_INVALID_USER}"; exit 1;
+
 				else
 					TARGET_USER="${NEXT_ARG}";
 				fi;
@@ -96,13 +100,13 @@ else
 
 		# Error - Empty/Unset target-user
 		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Target-user empty / unset";
-		echo -e "$(date +'%Y-%m-%d %H:%M:%S') | Info → Must specify a valid local-user via:""\n""  >  sudoer_status --user USERNAME""\n"; exit 1;
-		
+		echo -e "${ERROR_INVALID_USER}"; exit 1;
+
 	elif [ $(id -u ${TARGET_USER} > /dev/null 2>&1; echo $?) -eq 1 ]; then
 
 		# Error - User not found
 		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → User not found: \"${TARGET_USER}\")";
-		echo -e "$(date +'%Y-%m-%d %H:%M:%S') | Info → Must specify a valid local-user via:""\n""  >  sudoer_status --user USERNAME""\n"; exit 1;
+		echo -e "${ERROR_INVALID_USER}"; exit 1;
 
 	else
 
