Update sudoer_status

diff --git a/usr/local/sbin/sudoer_status b/usr/local/sbin/sudoer_status
--- a/usr/local/sbin/sudoer_status
+++ b/usr/local/sbin/sudoer_status
@@ -52,6 +52,7 @@ else
 				if [ -n "${EDIT_ACTION}" ]; then
 					# Error - Multiple add/remove actions defined
 					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Invalid inline-argument(s) detected:   Must not call function with more than one argument out of:  [ \"--allow\"  \"--add\"  \"--revoke\"  \"--remove\" ]"; sleep 60; exit 1;
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Invalid inline-argument(s) detected:   Must not call function with more than one argument out of:  [ \"--allow\"  \"--add\"  \"--revoke\"  \"--remove\" ]"; exit 1;
 				elif [ "${EACH_ARG}" == "--allow" ] || [ "${EACH_ARG}" == "--add" ]; then
 					EDIT_ACTION="ALLOW"; # Add user as a sudoer
 				elif [ "${EACH_ARG}" == "--revoke" ] || [ "${EACH_ARG}" == "--remove" ]; then
@@ -65,10 +66,10 @@ else
 			if [ "${EACH_ARG}" == "--user" ] && [ -n "${NEXT_ARG}" ]; then
 				if [ -n "${TARGET_USER}" ]; then
 					# Error - Multiple users defined
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; sleep 60; exit 1;
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Must define one, single user to modify (called with multiple usernames:  \"${NEXT_ARG}\" & \"${NEXT_USER}\")"; exit 1;
 				elif [ -z "$(id ${NEXT_ARG} 2>/dev/null)" ]; then
 					# Error - Non-existent target-user
-					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → User \"${NEXT_ARG}\" not found to exist"; sleep 60; exit 1;
+					echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → User \"${NEXT_ARG}\" not found to exist"; exit 1;
 				else
 					TARGET_USER="${NEXT_ARG}";
 				fi;
@@ -89,7 +90,7 @@ else
 	# ------------------------------------------------------------
 	if [ -z "${TARGET_USER}" ]; then 
 		# Error - Empty/Invalid target-user
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Must define a target-user via:  >  sudoer_status --user USERNAME"; sleep 60; exit 1;
+		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error → Must define a target-user via:  >  sudoer_status --user USERNAME"; exit 1;
 
 	# ------------------------------------------------------------
 	elif [ "${EDIT_ACTION}" == "ALLOW" ]; then 
@@ -131,17 +132,12 @@ else
 		GROUP_SUDOERS="sudo";
 		gpasswd -d "${TARGET_USER}" "${GROUP_SUDOERS}";
 
-
 	else
 		#	Check whether-or-not a user can masquerade as the root user (via the 'sudo' command)
 		sudo --list --other-user="${TARGET_USER}";
 
-
 	fi;
-
 	# ------------------------------------------------------------
-
-
 
 
 fi;
