Update sync_cloud_infrastructure

diff --git a/usr/local/sbin/sync_cloud_infrastructure b/usr/local/sbin/sync_cloud_infrastructure
--- a/usr/local/sbin/sync_cloud_infrastructure
+++ b/usr/local/sbin/sync_cloud_infrastructure
@@ -38,7 +38,7 @@ else
 		echo "";
 		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Non-Debian distro detected";
 		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ set -e; ] (Halt on errors)...";
-		set -e; #     -e  Exit immediately if a command exits with a non-zero status
+		# set -e; #     -e  Exit immediately if a command exits with a non-zero status
 
 		# yum check-update -y;
 
