Update sync_cloud_infrastructure

diff --git a/usr/local/sbin/sync_cloud_infrastructure b/usr/local/sbin/sync_cloud_infrastructure
--- a/usr/local/sbin/sync_cloud_infrastructure
+++ b/usr/local/sbin/sync_cloud_infrastructure
@@ -37,7 +37,7 @@ else
 		# For Non-Debian Distros, halt on errors
 		echo "";
 		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Non-Debian distro detected";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: --> Calling [ set -e; ] (Halt on errors)...";
+		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ set -e; ] (Halt on errors)...";
 		set -e; #     -e  Exit immediately if a command exits with a non-zero status
 
 		# yum update -y;
