Update sync_cloud_infrastructure

diff --git a/usr/local/sbin/sync_cloud_infrastructure b/usr/local/sbin/sync_cloud_infrastructure
--- a/usr/local/sbin/sync_cloud_infrastructure
+++ b/usr/local/sbin/sync_cloud_infrastructure
@@ -459,7 +459,10 @@ else
 
 			# service --status-all 2>/dev/null | grep 'jenkins';
 
-			if [ -n "$(which ssh)" ]; then
+			if [ -z "$(which ssh)" ]; then
+				echo "Info: Skipped SSH-Config Update (command \"ssh\" not found)";
+
+			else
 				
 				# Backup & Update the sshd_config (SSH Server) file
 				SSHD_CONFIG_LIVE="/etc/ssh/sshd_config";
@@ -483,13 +486,13 @@ else
 					SSHD_CONFIG_REPLACEMENT="${SSHD_CONFIG_PASS_AUTH}";
 				fi;
 
-				if [ $(cmp -s "${SSHD_CONFIG_LIVE}" "${SSHD_CONFIG_REPLACEMENT}" 1>&2 2>"/dev/null"; echo $?;) -eq 0 ] && [ $(find "/etc/ssh/authorized_keys" -type f | wc -l;) -eq 0 ]; then
+				if [ $(cmp -s "${SSHD_CONFIG_LIVE}" "${SSHD_CONFIG_REPLACEMENT}" 1>&2 2>"/dev/null"; echo $?;) -eq 0 ]; then
+					# SSH-Config file already fully up-to-date
 					echo -e "\n""Info: Skipping update to \"${SSHD_CONFIG_LIVE}\"";
 					echo "  |--> Checksum already up-to-date with \"$(basename ${SSHD_CONFIG_REPLACEMENT})\"";
 
 				else
-
-					# Tell the user to make sure and open a new SSH terminal to avoid being locked-out of the server
+					# At least one Tell the user to make sure and open a new SSH terminal to avoid being locked-out of the server
 					echo -e "\n""!!! Warning !!!";
 					echo "  |";
 					echo "  |--> Update to SSH Configuration Requested";
@@ -498,11 +501,11 @@ else
 					echo "  |";
 					read -p "  |--> Are you sure you want to continue? (y/n - if you are unsure, choose n)   " -t 20 -r;
 					if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
-						echo -e "\n""Info: Updating \"${SSHD_CONFIG_LIVE}\" with changes from \"${GIT_REPO_NAME}\" repository";
-						echo "  |-> Using file \"${SSHD_CONFIG_REPLACEMENT}\"";
-						BENCHMARK_START=$(date +'%s.%N');
+						echo -e "\n""Info: Updating SSH-Config file \"${SSHD_CONFIG_LIVE}\"";
+						echo "  |-> Using config from file \"${SSHD_CONFIG_REPLACEMENT}\"";
 						
 						# Backup & Update the sshd_config (SSH Server) file
+						BENCHMARK_START=$(date +'%s.%N');
 						mv "${SSHD_CONFIG_LIVE}" "${SSHD_CONFIG_LIVE}.${START_TIMESTAMP}.bak" \
 							&& wget "https://raw.githubusercontent.com/${GIT_REPO_OWNER}/${GIT_REPO_NAME}/master${SSHD_CONFIG_REPLACEMENT}" -O "${SSHD_CONFIG_REPLACEMENT}" -q \
 							&& chmod 0644 "${SSHD_CONFIG_REPLACEMENT}" \
@@ -511,15 +514,12 @@ else
 
 						BENCHMARK_DELTA=$(echo "$(date +'%s.%N') - ${BENCHMARK_START}" | bc);
 						test ${ARGS_DEBUG_MODE} -eq 1 && echo "  |→ Finished after ${BENCHMARK_DELTA}s";
+
 					else
-						echo "Info: Skipped SSH-Config Update";
+						echo "Info: Skipped SSH-Config Update (command \"ssh\" not found)";
 
 					fi;
-
 				fi;
-			else
-				echo "Info: Skipped SSH-Config Update";
-
 			fi;
 		fi;
 
