Update sync_cloud_infrastructure

diff --git a/usr/local/sbin/sync_cloud_infrastructure b/usr/local/sbin/sync_cloud_infrastructure
--- a/usr/local/sbin/sync_cloud_infrastructure
+++ b/usr/local/sbin/sync_cloud_infrastructure
@@ -84,67 +84,6 @@ else
 
 
 	# ------------------------------------------------------------
-	# Make sure prerequisite-packages are installed
-	unset REQUIRED_PKGS_ARRAY; declare -a REQUIRED_PKGS_ARRAY; # [Re-]Instantiate bash array
-	REQUIRED_PKGS_ARRAY=();
-	REQUIRED_PKGS_ARRAY+=("bc");
-	REQUIRED_PKGS_ARRAY+=("dos2unix");
-	REQUIRED_PKGS_ARRAY+=("git");
-	REQUIRED_PKGS_ARRAY+=("rsync");
-	REQUIRED_PKGS_ARRAY+=("vim");
-	REQUIRED_PKGS_ARRAY+=("wget");
-	# Debian-specific packages
-	if [ "$(which apt 2>'/dev/null'; echo $?;)" == "0" ]; then
-		REQUIRED_PKGS_ARRAY+=("cron");
-	fi;
-	# Determine if any required packages are missing
-	NEED_TO_INSTALL_PKGS=0;
-	for EACH_REQUIRED_PKG in "${REQUIRED_PKGS_ARRAY[@]}"; do
-		if [ "$(which ${EACH_REQUIRED_PKG} 2>'/dev/null'; echo $?;)" != "0" ]; then
-			if [ ${ARGS_DEBUG_MODE} -eq 1 ]; then
-				echo -e "\n""Debug: Missing package \"${EACH_REQUIRED_PKG}\"";
-			fi;
-			NEED_TO_INSTALL_PKGS=1;
-		fi;
-	done;
-	if [ "${NEED_TO_INSTALL_PKGS}" == "1" ]; then
-		if [ ${ARGS_DEBUG_MODE} -eq 1 ]; then
-			echo -e "\n""Debug: NEED_TO_INSTALL_PKGS = [ ${NEED_TO_INSTALL_PKGS} ]";
-		fi;
-		# Bulk install all packages
-		if [ -n "$(which apt 2>'/dev/null';)" ]; then
-			apt-get update -y && apt-get install -y ${REQUIRED_PKGS_ARRAY[@]};
-		elif [ -n "$(which yum 2>'/dev/null';)" ]; then
-			yum check-update -y && yum install -y ${REQUIRED_PKGS_ARRAY[@]};
-		elif [ -n "$(which apk 2>'/dev/null';)" ]; then
-			apk update -y && apk add -y ${REQUIRED_PKGS_ARRAY[@]};
-		fi;
-	fi;
-
-
-	# ------------------------------------------------------------
-	# If the local script's checksum is different than the source-script's checksum, then update the local to match the source
-	CHECKSUM_LOCAL=$(if [ -f "/usr/local/sbin/sync_cloud_infrastructure" ]; then cat "/usr/local/sbin/sync_cloud_infrastructure" | cksum | cut -d" " -f1; else echo 0; fi;);
-	CHECKSUM_SOURCE=$(curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/${GIT_REPO_OWNER}/${GIT_REPO_NAME}/master/usr/local/sbin/sync_cloud_infrastructure?t=$(date +'%s.%N')" | cksum | cut -d" " -f1);
-	if [ ${ARGS_DEBUG_MODE} -eq 1 ]; then
-		echo -e "\n""Debug: CHECKSUM_SOURCE = [ ${CHECKSUM_SOURCE} ]";
-		echo -e "\n""Debug: CHECKSUM_LOCAL = [ ${CHECKSUM_LOCAL} ]";
-	fi;
-	if [ "${CHECKSUM_SOURCE}" != "${CHECKSUM_LOCAL}" ]; then
-		#####  Sync 1-liner  →  Pull the raw version of the file directly out of GitHub
-		echo -e "\n""Info: Updating local runtime \"/usr/local/sbin/sync_cloud_infrastructure\" from source \"https://raw.githubusercontent.com/${GIT_REPO_OWNER}/${GIT_REPO_NAME}/master/usr/local/sbin/sync_cloud_infrastructure\"";
-		
-		BENCHMARK_START=$(date +'%s.%N');
-		curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/${GIT_REPO_OWNER}/${GIT_REPO_NAME}/master/usr/local/sbin/sync_cloud_infrastructure?t=$(date +'%s.%N')" -o "/usr/local/sbin/sync_cloud_infrastructure" && chmod 0755 "/usr/local/sbin/sync_cloud_infrastructure";
-		BENCHMARK_DELTA=$(echo "$(date +'%s.%N') - ${BENCHMARK_START}" | bc);
-		echo "  |→ Finished after ${BENCHMARK_DELTA}s";
-
-		"/usr/local/sbin/sync_cloud_infrastructure" $@;
-		exit 0;
-	fi;
-
-
-	# ------------------------------------------------------------
 	# Parse inline arguments (passed to current script)
 
 	ARGS=("$@");
@@ -266,6 +205,68 @@ else
 		echo "Debug:  ARGS_SYNC_UFW = [ ${ARGS_SYNC_UFW} ]";
 
 	fi;
+
+
+	# ------------------------------------------------------------
+	# Make sure prerequisite-packages are installed
+	unset REQUIRED_PKGS_ARRAY; declare -a REQUIRED_PKGS_ARRAY; # [Re-]Instantiate bash array
+	REQUIRED_PKGS_ARRAY=();
+	REQUIRED_PKGS_ARRAY+=("bc");
+	REQUIRED_PKGS_ARRAY+=("dos2unix");
+	REQUIRED_PKGS_ARRAY+=("git");
+	REQUIRED_PKGS_ARRAY+=("rsync");
+	REQUIRED_PKGS_ARRAY+=("vim");
+	REQUIRED_PKGS_ARRAY+=("wget");
+	# Debian-specific packages
+	if [ "$(which apt 2>'/dev/null'; echo $?;)" == "0" ]; then
+		REQUIRED_PKGS_ARRAY+=("cron");
+	fi;
+	# Determine if any required packages are missing
+	NEED_TO_INSTALL_PKGS=0;
+	for EACH_REQUIRED_PKG in "${REQUIRED_PKGS_ARRAY[@]}"; do
+		if [ "$(which ${EACH_REQUIRED_PKG} 2>'/dev/null'; echo $?;)" != "0" ]; then
+			if [ ${ARGS_DEBUG_MODE} -eq 1 ]; then
+				echo -e "\n""Debug: Missing package \"${EACH_REQUIRED_PKG}\"";
+			fi;
+			NEED_TO_INSTALL_PKGS=1;
+		fi;
+	done;
+	if [ "${NEED_TO_INSTALL_PKGS}" == "1" ]; then
+		if [ ${ARGS_DEBUG_MODE} -eq 1 ]; then
+			echo -e "\n""Debug: NEED_TO_INSTALL_PKGS = [ ${NEED_TO_INSTALL_PKGS} ]";
+		fi;
+		# Bulk install all packages
+		if [ -n "$(which apt 2>'/dev/null';)" ]; then
+			apt-get update -y && apt-get install -y ${REQUIRED_PKGS_ARRAY[@]};
+		elif [ -n "$(which yum 2>'/dev/null';)" ]; then
+			yum check-update -y && yum install -y ${REQUIRED_PKGS_ARRAY[@]};
+		elif [ -n "$(which apk 2>'/dev/null';)" ]; then
+			apk update -y && apk add -y ${REQUIRED_PKGS_ARRAY[@]};
+		fi;
+	fi;
+
+
+	# ------------------------------------------------------------
+	# Update-Self - If the local script's checksum is different than the source-script's checksum, then update the local to match the source
+	CHECKSUM_LOCAL=$(if [ -f "/usr/local/sbin/sync_cloud_infrastructure" ]; then cat "/usr/local/sbin/sync_cloud_infrastructure" | cksum | cut -d" " -f1; else echo 0; fi;);
+	CHECKSUM_SOURCE=$(curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/${GIT_REPO_OWNER}/${GIT_REPO_NAME}/master/usr/local/sbin/sync_cloud_infrastructure?t=$(date +'%s.%N')" | cksum | cut -d" " -f1);
+	if [ ${ARGS_DEBUG_MODE} -eq 1 ]; then
+		echo -e "\n""Debug: CHECKSUM_SOURCE = [ ${CHECKSUM_SOURCE} ]";
+		echo -e "\n""Debug: CHECKSUM_LOCAL = [ ${CHECKSUM_LOCAL} ]";
+	fi;
+	if [ "${CHECKSUM_SOURCE}" != "${CHECKSUM_LOCAL}" ]; then
+		#####  Sync 1-liner  →  Pull the raw version of the file directly out of GitHub
+		echo -e "\n""Info: Updating local runtime \"/usr/local/sbin/sync_cloud_infrastructure\" from source \"https://raw.githubusercontent.com/${GIT_REPO_OWNER}/${GIT_REPO_NAME}/master/usr/local/sbin/sync_cloud_infrastructure\"";
+		
+		BENCHMARK_START=$(date +'%s.%N');
+		curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/${GIT_REPO_OWNER}/${GIT_REPO_NAME}/master/usr/local/sbin/sync_cloud_infrastructure?t=$(date +'%s.%N')" -o "/usr/local/sbin/sync_cloud_infrastructure" && chmod 0755 "/usr/local/sbin/sync_cloud_infrastructure";
+		BENCHMARK_DELTA=$(echo "$(date +'%s.%N') - ${BENCHMARK_START}" | bc);
+		echo "  |→ Finished after ${BENCHMARK_DELTA}s";
+
+		"/usr/local/sbin/sync_cloud_infrastructure" $@;
+		exit 0;
+	fi;
+
 
 	# ------------------------------------------------------------
 	# Ensure the (GitHub) Repos directory exists, locally
