Update sync_cloud_infrastructure

diff --git a/usr/local/sbin/sync_cloud_infrastructure b/usr/local/sbin/sync_cloud_infrastructure
--- a/usr/local/sbin/sync_cloud_infrastructure
+++ b/usr/local/sbin/sync_cloud_infrastructure
@@ -224,6 +224,9 @@ else
 	# Determine if any required packages are missing
 	NEED_TO_INSTALL_PKGS=0;
 	for EACH_REQUIRED_PKG in "${REQUIRED_PKGS_ARRAY[@]}"; do
+		if [ ${ARGS_DEBUG_MODE} -eq 1 ]; then
+			echo -e "\n""Debug: \$(which ${EACH_REQUIRED_PKG} 2>&1 2>'/dev/null'; echo \$?;) = $(which ${EACH_REQUIRED_PKG} 2>&1 2>'/dev/null'; echo $?;)";
+		fi;
 		if [ "$(which ${EACH_REQUIRED_PKG} 2>&1 2>'/dev/null'; echo $?;)" != "0" ]; then
 			if [ ${ARGS_DEBUG_MODE} -eq 1 ]; then
 				echo -e "\n""Debug: Missing package \"${EACH_REQUIRED_PKG}\"";
