Update sync_config_gpg_git

diff --git a/usr/local/sbin/sync_config_gpg_git b/usr/local/sbin/sync_config_gpg_git
--- a/usr/local/sbin/sync_config_gpg_git
+++ b/usr/local/sbin/sync_config_gpg_git
@@ -3,7 +3,7 @@
 #
 #	RUN VIA GIT BASH:
 #
-#    cd "${HOME}/Documents/GitHub/CodingPrivate/To move to Coding/git, gnupg/" && "./git + gnupg (gpg) config - ssh-key, pgp-key configuration for all repos.sh" "./git-gnupg-source.conf";
+#    sync_config_gpg_git "${HOME}/Documents/GitHub/CodingPrivate/To move to Coding/git, gnupg/git-gnupg-source.conf";
 #
 # ------------------------------------------------------------
 #
@@ -25,14 +25,17 @@
 # ------------------------------------------------------------
 
 
-if [[ "${OSTYPE}" != "linux-gnu"* ]] && [[ "$(uname -s)" != "Linux" ]] && [[ "${OSTYPE}" != "darwin"* ]]; then OS_IS_WINDOWS=1; else OS_IS_WINDOWS=0; fi;
-if [ ${OS_IS_WINDOWS} -eq 0 ]; then
+if [[ "${OSTYPE}" != "linux-gnu"* ]] && [[ "$(uname -s)" != "Linux" ]] && [[ "${OSTYPE}" != "darwin"* ]]; then
+	OS_IS_WINDOWS=1;
+else
+	OS_IS_WINDOWS=0;
 	echo "";
-	echo "Error | Script must be ran using a Windows Git Bash terminal (+admin-privileges are required, as well)"
+	echo "Error | Script must run in a Windows Git-Bash terminal ( w/ admin-privileges ) to function as-intended";
 	echo "";
+	exit 1;
 fi;
 
-if [[ $(uname -s | grep -i MINGW | wc -l) -gt 0 ]] || [ "${OSTYPE}" == "msys" ]; then echo 1; else echo 0; fi;
+IS_MINGW=$(if [[ $(uname -s | grep -i MINGW | wc -l) -gt 0 ]] || [ "${OSTYPE}" == "msys" ]; then echo 1; else echo 0; fi;);
 
 PERSONAL_PUBLIC_REPOS=(); # Github personal public repos
 
