Update uninstall_jenkins

diff --git a/usr/local/sbin/uninstall_jenkins b/usr/local/sbin/uninstall_jenkins
--- a/usr/local/sbin/uninstall_jenkins
+++ b/usr/local/sbin/uninstall_jenkins
@@ -31,80 +31,90 @@ if [ "$(id -un)" != "root" ]; then
 	exit 1;
 else
 	# ------------------------------------------------------------
-	# Instantiate runtime variables
-	
-	EXIT_CODE=1;
-
-	APT_PKG_JDK="default-jdk-headless";
-	APT_PKG_JRE="default-jre-headless";
-	APT_PKG_JENKINS="jenkins";
-
-	START_SECONDS_NANOSECONDS=$(date +'%s.%N');
-	START_EPOCHSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 1);
-	# START_NANOSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 2 | cut --characters 1-9);
-	# START_MICROSECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-6);
-	# START_MILLISECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-3);
-	START_DATETIME="$(date --date=@${START_EPOCHSECONDS} +'%Y-%m-%d %H:%M:%S')";
-	START_TIMESTAMP="$(date --date=@${START_EPOCHSECONDS} +'%Y%m%d_%H%M%S')";
-
-	# ------------------------------------------------------------
-	# Remove Jenkins' Apt-Package
-	if [ $(apt list --installed 2>/dev/null | grep -h "^${APT_PKG_JENKINS}\/" | wc -l) -gt 0 ]; then
-		echo -e "\n""Info: Removing Jenkins' Apt-Package";
-		read -p "  |--> Are you sure you want to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
-		if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
-			echo "  |--> Calling [ apt-get remove -y jenkins; ]...";
-			apt-get remove -y jenkins;
-		fi;
-	fi;
-
-	# ------------------------------------------------------------
-	# Remove Jenkins' Runtime-User
-	if [ -n "$(getent passwd 'jenkins';)" ]; then
-		echo -e "\n""Info: Removing Jenkins' Runtime-User";
-		read -p "  |--> Are you sure you want to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
-		if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
-			echo "  |--> Calling [ userdel jenkins --force --remove; ]...";
-			userdel jenkins --force --remove;
-		fi;
-	fi;
-
-	# ------------------------------------------------------------
-	# Remove Jenkins' Runtime-Group
-	if [ -n "$(getent group 'jenkins';)" ]; then
-		echo -e "\n""Info: Removing Jenkins' Runtime-Group";
-		read -p "  |--> Are you sure you want to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
-		if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
-			echo "  |--> Calling [ groupdel jenkins; ]...";
-			groupdel jenkins;
-		fi;
-	fi;
-
-	# ------------------------------------------------------------
-	# Remove Jenkins' Service
+	# Uninstall Jenkins CI/CD Server
 	SERVICE_NAME="jenkins";
-	SERVICE_RET_CODE=$(/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
-	if [ ${SERVICE_RET_CODE} -eq 0 ]; then
-		echo -e "\n""Info: Removing Jenkins' Service";
-		read -p "  |--> Are you sure you want to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
+
+
+	# ------------------------------------------------------------
+	# Require user-confirmation to perform this action
+	#
+	echo -e "\n""!! WARNING !! This will completely uninstall service \"${SERVICE_NAME}\" (including associated runtime-user, runtime-group, service)";
+	read -p "     |--> Are you sure you want to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
+	if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
+		read -p "     |--> Are you completely positive you wish to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
 		if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
-			echo "  |--> Calling [ apt-get purge \"jenkins\" ]...";
-			apt-get -y purge "jenkins";
-			echo "  |--> Calling [ /usr/sbin/service \"${SERVICE_NAME}\" stop; ]...";
-			/usr/sbin/service "${SERVICE_NAME}" stop;
-			echo "  |--> Calling [ update-rc.d \"jenkins\" remove -f; ]...";
-			update-rc.d "jenkins" remove -f;
-			echo "  |--> Calling [ /bin/systemctl daemon-reload; ]...";
-			/bin/systemctl daemon-reload;
-			echo "  |--> Calling [ /bin/systemctl reset-failed; ]...";
-			/bin/systemctl reset-failed;
+
+			# ------------------------------------------------------------
+			# Instantiate runtime variables
+			
+			EXIT_CODE=1;
+
+			APT_PKG_JDK="default-jdk-headless";
+			APT_PKG_JRE="default-jre-headless";
+			APT_PKG_JENKINS="jenkins";
+
+			START_SECONDS_NANOSECONDS=$(date +'%s.%N');
+			START_EPOCHSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 1);
+			# START_NANOSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 2 | cut --characters 1-9);
+			# START_MICROSECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-6);
+			# START_MILLISECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-3);
+			START_DATETIME="$(date --date=@${START_EPOCHSECONDS} +'%Y-%m-%d %H:%M:%S')";
+			START_TIMESTAMP="$(date --date=@${START_EPOCHSECONDS} +'%Y%m%d_%H%M%S')";
+
+			# ------------------------------------------------------------
+			# Remove Service's associated package(s)
+			echo -e "\n""Info:  Stopping service \"${SERVICE_NAME}\"";
+			echo "  |--> Calling [ systemctl stop \"${SERVICE_NAME}\"; ]...";
+			systemctl stop "${SERVICE_NAME}";
+		
+			# ------------------------------------------------------------
+			# Remove Service's associated package(s)
+			echo -e "\n""Info:  Removing Jenkins software-package(s)";
+			if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
+				echo "  |--> Calling [ apt-get remove -y \"${SERVICE_NAME}\"; ]...";
+				apt-get remove -y "${SERVICE_NAME}";
+			elif [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
+				echo "  |--> Calling [ yum remove -y \"${SERVICE_NAME}\"; ]...";
+				yum remove -y "${SERVICE_NAME}";
+			fi;
+			
+			# ------------------------------------------------------------
+			# Remove Service's Runtime-User
+			if [ -n "$(getent passwd 'jenkins';)" ]; then
+				echo -e "\n""Info:  Removing Jenkins' Runtime-User";
+				echo "  |--> Calling [ userdel \"${SERVICE_NAME}\" --force --remove; ]...";
+				userdel "${SERVICE_NAME}" --force --remove;
+			fi;
+
+			# ------------------------------------------------------------
+			# Remove Service's Runtime-Group
+			if [ -n "$(getent group 'jenkins';)" ]; then
+				echo -e "\n""Info:  Removing Jenkins' Runtime-Group";
+				echo "  |--> Calling [ groupdel \"${SERVICE_NAME}\"; ]...";
+				groupdel "${SERVICE_NAME}";
+			fi;
+
+			# ------------------------------------------------------------
+			# Remove Service
+			SERVICE_RET_CODE=$(/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
+			if [ ${SERVICE_RET_CODE} -eq 0 ]; then
+				echo "  |--> Calling [ apt-get purge \"${SERVICE_NAME}\" ]...";
+				apt-get -y purge "${SERVICE_NAME}";
+				echo "  |--> Calling [ update-rc.d \"${SERVICE_NAME}\" remove -f; ]...";
+				update-rc.d "${SERVICE_NAME}" remove -f;
+				echo "  |--> Calling [ /bin/systemctl daemon-reload; ]...";
+				/bin/systemctl daemon-reload;
+				echo "  |--> Calling [ /bin/systemctl reset-failed; ]...";
+				/bin/systemctl reset-failed;
+			fi;
+
+		# ------------------------------------------------------------
+
 		fi;
 	fi;
-	
-	# ------------------------------------------------------------
 
 	EXIT_CODE=0;
-	
+
 	exit ${EXIT_CODE};
 
 fi;
