Update update_dns_config

diff --git a/usr/local/sbin/update_dns_config b/usr/local/sbin/update_dns_config
--- a/usr/local/sbin/update_dns_config
+++ b/usr/local/sbin/update_dns_config
@@ -95,6 +95,36 @@ else
 				fi;
 			fi;
 
+			# Primary DNS Server (#1)
+			if [ "${EACH_ARG}" == "--dns1" ]; then
+				if [ -n "${NEXT_ARG}" ]; then
+					USER_DNS_1="${NEXT_ARG}";
+				else
+					echo "Error:  Must specify dns hostname / IPv4 --dns1, e.g. use syntax [ --dns1 I.P.V.4 ]";
+					exit 1;
+				fi;
+			fi;
+
+			# Secondary DNS Server (#2)
+			if [ "${EACH_ARG}" == "--dns2" ]; then
+				if [ -n "${NEXT_ARG}" ]; then
+					USER_DNS_2="${NEXT_ARG}";
+				else
+					echo "Error:  Must specify dns hostname / IPv4 --dns2, e.g. use syntax [ --dns2 I.P.V.4 ]";
+					exit 1;
+				fi;
+			fi;
+
+			# Tertiary DNS Server (#3)
+			if [ "${EACH_ARG}" == "--dns3" ]; then
+				if [ -n "${NEXT_ARG}" ]; then
+					USER_DNS_3="${NEXT_ARG}";
+				else
+					echo "Error:  Must specify dns hostname / IPv4 --dns3, e.g. use syntax [ --dns3 I.P.V.4 ]";
+					exit 1;
+				fi;
+			fi;
+
 		fi;
 	done;
 
@@ -117,6 +147,7 @@ else
 			done;
 		fi;
 	fi;
+
 
 	# ------------------------------------------------------------
 	#
@@ -151,9 +182,9 @@ else
 	#
 	#		SELECTED DNS SERVERS (HOSTS/IPS TO TARGET AS DNS NAMESERVERS)
 
-	DNS_NAMESRVR_1="${DHCP_NAMESRVR_1:-${GOOGLE_DNS_1}}";
-	DNS_NAMESRVR_2="${DHCP_NAMESRVR_2:-${GOOGLE_DNS_2}}";
-	DNS_NAMESRVR_3="${DHCP_NAMESRVR_3:-${CLOUDFARE_DNS_1}}";
+	DNS_NAMESRVR_1="${USER_DNS_1:-${DHCP_NAMESRVR_1:-${GOOGLE_DNS_1}}}";
+	DNS_NAMESRVR_2="${USER_DNS_2:-${DHCP_NAMESRVR_2:-${GOOGLE_DNS_2}}}";
+	DNS_NAMESRVR_3="${USER_DNS_3:-${DHCP_NAMESRVR_3:-${CLOUDFARE_DNS_1}}}";
 	DNS_FALLBACK_1="${OPEN_DNS_1}";
 	DNS_FALLBACK_2="${CLOUDFARE_DNS_2}";
 	DNS_FALLBACK_3="${VERISIGN_DNS_1}";
@@ -219,7 +250,7 @@ else
 				if [[ $REPLY =~ ^[Yy]$ ]]; then
 					# ------------------------------------------------------------
 
-					# Local LAN IPv4 Address
+					# Set Local LAN IPv4 Address
 					if [ $(cat "${NMCLI_CONF}" | grep 'IPADDR=' | wc -l;) -gt 0 ]; then
 						echo "";
 						sed -i -e "/^IPADDR=/c\IPADDR=\"${SET_STATIC_IPV4}\"" "${NMCLI_CONF}";
@@ -228,7 +259,7 @@ else
 						echo "IPADDR=\"${SET_STATIC_IPV4}\"" >> "${NMCLI_CONF}";
 					fi;
 
-					# Gateway LAN IPv4 Address
+					# Set Gateway LAN IPv4 Address
 					if [ $(cat "${NMCLI_CONF}" | grep 'GATEWAY=' | wc -l;) -gt 0 ]; then
 						echo "";
 						sed -i -e "/^GATEWAY=/c\GATEWAY=\"${THIS_GATEWAY_IPV4}\"" "${NMCLI_CONF}";
@@ -237,7 +268,7 @@ else
 						echo "GATEWAY=\"${THIS_GATEWAY_IPV4}\"" >> "${NMCLI_CONF}";
 					fi;
 
-					# LAN Prefix (2-digit representation of Netmask)
+					# Set LAN Prefix (2-digit representation of Netmask)
 					if [ $(cat "${NMCLI_CONF}" | grep 'PREFIX=' | wc -l;) -gt 0 ]; then
 						echo "";
 						sed -i -e "/^PREFIX=/c\PREFIX=\"${THIS_LAN_PREFIX}\"" "${NMCLI_CONF}";
@@ -246,7 +277,7 @@ else
 						echo "PREFIX=\"${THIS_LAN_PREFIX}\"" >> "${NMCLI_CONF}";
 					fi;
 
-					# Boot Protocol
+					# Set Boot Protocol
 					if [ $(cat "${NMCLI_CONF}" | grep 'BOOTPROTO=' | wc -l;) -gt 0 ]; then
 						echo "";
 						sed -i -e "/^BOOTPROTO=/c\BOOTPROTO=\"none\"" "${NMCLI_CONF}";
@@ -255,7 +286,7 @@ else
 						echo "BOOTPROTO=\"none\"" >> "${NMCLI_CONF}";
 					fi;
 
-					# PEERDNS
+					# Set PEERDNS
 					if [ $(cat "${NMCLI_CONF}" | grep 'PEERDNS=' | wc -l;) -gt 0 ]; then
 						echo "";
 						sed -i -e "/^PEERDNS=/c\PEERDNS=\"no\"" "${NMCLI_CONF}";
@@ -264,15 +295,14 @@ else
 						echo "PEERDNS=\"no\"" >> "${NMCLI_CONF}";
 					fi;
 
-					# ------------------------------------------------------------
-					# Hostname
+					# Prep Hostname
 					if [ -n "${DNS_SEARCH_DOMAIN}" ]; then
 						SET_HOSTNAME="$(hostname).${DNS_SEARCH_DOMAIN}";
 					else
 						SET_HOSTNAME="$(hostname)";
 					fi;
 
-					# Hostname -> Device Config
+					# Set Hostname in NIC config
 					if [ $(cat "${NMCLI_CONF}" | grep 'HOSTNAME=' | wc -l;) -gt 0 ]; then
 						echo "";
 						sed -i -e "/^HOSTNAME=/c\HOSTNAME=\"${SET_HOSTNAME}\"" "${NMCLI_CONF}";
@@ -280,7 +310,17 @@ else
 						echo "";
 						echo "HOSTNAME=\"${SET_HOSTNAME}\"" >> "${NMCLI_CONF}";
 					fi;
-					# Domainname -> Device Config
+
+					# Set Hostname in SYSTEM config
+					if [ $(cat "${NETWORK_SYSCONF}" | grep 'HOSTNAME=' | wc -l;) -gt 0 ]; then
+						echo "";
+						sed -i -e "/^HOSTNAME=/c\HOSTNAME=\"${SET_HOSTNAME}\"" "${NETWORK_SYSCONF}";
+					else
+						echo "";
+						echo "HOSTNAME=\"${SET_HOSTNAME}\"" >> "${NETWORK_SYSCONF}";
+					fi;
+
+					# Set Domainname in NIC config
 					if [ $(cat "${NMCLI_CONF}" | grep 'DOMAIN=' | wc -l;) -gt 0 ]; then
 						echo "";
 						sed -i -e "/^DOMAIN=/c\DOMAIN=\"${DNS_SEARCH_DOMAIN}\"" "${NMCLI_CONF}";
@@ -289,15 +329,7 @@ else
 						echo "DOMAIN=\"${DNS_SEARCH_DOMAIN}\"" >> "${NMCLI_CONF}";
 					fi;
 
-					# Hostname -> System Config
-					if [ $(cat "${NETWORK_SYSCONF}" | grep 'HOSTNAME=' | wc -l;) -gt 0 ]; then
-						echo "";
-						sed -i -e "/^HOSTNAME=/c\HOSTNAME=\"${SET_HOSTNAME}\"" "${NETWORK_SYSCONF}";
-					else
-						echo "";
-						echo "HOSTNAME=\"${SET_HOSTNAME}\"" >> "${NETWORK_SYSCONF}";
-					fi;
-					# Domainname -> System Config
+					# Set Domainname in SYSTEM config
 					if [ $(cat "${NETWORK_SYSCONF}" | grep 'DOMAIN=' | wc -l;) -gt 0 ]; then
 						echo "";
 						sed -i -e "/^DOMAIN=/c\DOMAIN=\"${DNS_SEARCH_DOMAIN}\"" "${NETWORK_SYSCONF}";
