Update update_dns_config

diff --git a/usr/local/sbin/update_dns_config b/usr/local/sbin/update_dns_config
--- a/usr/local/sbin/update_dns_config
+++ b/usr/local/sbin/update_dns_config
@@ -101,31 +101,47 @@ else
 	IS_WINDOWS_WSL=$(if [[ "$(< /proc/version)" == *@(Microsoft|WSL)* ]]; then echo 1; else echo 0; fi; );
 	if [ "${IS_LINUX}" != "1" ]; then echo ""; echo "ERROR:  Must run in a Linux-based environment"; exit 1; fi;
 
-	# Network default-filepaths
-
-	RHEL_DNS_BUILDER_BASE=$(find /etc/sysconfig/network-scripts/ -name ifcfg-* -a -not -name ifcfg-lo -printf "%p" | head -n 1 2>'/dev/null';);
-	if [ -n "${RHEL_DNS_BUILDER_BASE}" ]; then
+	# Network config filepaths
+	ETC_RESOLVCONF="/etc/resolv.conf"; # Final output which is-built-from/pulls-from from multiple sources
+	DEBIAN_NETWORK_CONF="/etc/network/interfaces.d/50-cloud-init.cfg"; # AWS default cloud-config
+	RHEL_NETWORK_CONF=$(find /etc/sysconfig/network-scripts/ -name ifcfg-* -a -not -name ifcfg-lo -printf "%p" | head -n 1 2>'/dev/null';);
+	
+	if [ -n "${RHEL_NETWORK_CONF}" ]; then
 
 		# RHEL/CentOS) distros
-		if [ ! -f "${RHEL_DNS_BUILDER_BASE}" ]; then 
+		if [ ! -f "${RHEL_NETWORK_CONF}" ]; then 
 
-			echo "ERROR: DNS Config-File not found @ path \"${RHEL_DNS_BUILDER_BASE}\" - exiting...";
+			echo "ERROR: DNS Config-File not found @ path \"${RHEL_NETWORK_CONF}\" - exiting...";
 			exit 1;
 
 		else
 
 			# DNS Nameserver #1
-			if [ $(cat "${RHEL_DNS_BUILDER_BASE}" | grep 'DNS1=' | wc -l;) -gt 0 ]; then
-				sed -ie "/^DNS1=/c\DNS1=${DNS_NAMESRVR_1}" "${RHEL_DNS_BUILDER_BASE}";
+			if [ $(cat "${RHEL_NETWORK_CONF}" | grep 'DNS1=' | wc -l;) -gt 0 ]; then
+				sed -ie "/^DNS1=/c\DNS1=${DNS_NAMESRVR_1}" "${RHEL_NETWORK_CONF}";
 			else
-				echo "DNS1=${DNS_NAMESRVR_1}" >> "${RHEL_DNS_BUILDER_BASE}";
+				echo "DNS1=${DNS_NAMESRVR_1}" >> "${RHEL_NETWORK_CONF}";
 			fi;
 
 			# DNS Nameserver #2
-			if [ $(cat "${RHEL_DNS_BUILDER_BASE}" | grep 'DNS2=' | wc -l;) -gt 0 ]; then
-				sed -ie "/^DNS2=/c\DNS2=${DNS_NAMESRVR_2}" "${RHEL_DNS_BUILDER_BASE}";
+			if [ $(cat "${RHEL_NETWORK_CONF}" | grep 'DNS2=' | wc -l;) -gt 0 ]; then
+				sed -ie "/^DNS2=/c\DNS2=${DNS_NAMESRVR_2}" "${RHEL_NETWORK_CONF}";
 			else
-				echo "DNS2=${DNS_NAMESRVR_2}" >> "${RHEL_DNS_BUILDER_BASE}";
+				echo "DNS2=${DNS_NAMESRVR_2}" >> "${RHEL_NETWORK_CONF}";
+			fi;
+
+			echo "";
+			echo "Network Manager must be restarted to apply changes ( required command [ /etc/init.d/network restart ] )";
+			read -p "   |--> Restart Network Manager, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
+			echo "";
+			if [[ $REPLY =~ ^[Yy]$ ]]; then
+				echo "";
+				echo "Restarting Network Manager via command [ /etc/init.d/network ]";
+				/etc/init.d/network restart;
+			else
+				echo "";
+				echo "Postponing Network Manager restart";
+				exit 1;
 			fi;
 
 		fi;
@@ -133,12 +149,10 @@ else
 	else # ------------------------------------------------------------
 
 		# Debian distros
-		ETC_RESOLVCONF="/etc/resolv.conf"; # Final output which is-built-from/pulls-from from multiple sources 
 		FILE_DNS_BUILDER_BASE="/etc/resolvconf/resolv.conf.d/base";
 		FILE_DNS_BUILDER_TAIL="/etc/resolvconf/resolv.conf.d/base";
 		FILE_NETWORK_RESOLVER="${FILE_DNS_BUILDER_BASE}";
 		FILE_NETWORK_RESOLVER="${FILE_DNS_BUILDER_TAIL}";
-		FILE_ETH0_BUILDER="/etc/network/interfaces.d/50-cloud-init.cfg"; # AWS default cloud-config
 		if [ "${IS_WINDOWS_WSL}" == "1" ]; then
 			FILE_NETWORK_RESOLVER="${ETC_RESOLVCONF}"; # Windows subsystem for linux - wipe all of resolver (for testing-only as it is rebuilt on WSL-close, or 'shut down' from its perspective)
 		fi;
@@ -161,7 +175,7 @@ else
 			echo ""; echo "Calling [cp -f \"${FILE_TO_BACKUP}\" \"${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak\";]...";
 			cp -f "${FILE_TO_BACKUP}" "${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak";
 		fi;
-		FILE_TO_BACKUP="${FILE_ETH0_BUILDER}";
+		FILE_TO_BACKUP="${DEBIAN_NETWORK_CONF}";
 		if [ -f "${FILE_TO_BACKUP}" ]; then
 			BASENAME_TO_BACKUP=$(basename "${FILE_TO_BACKUP}");
 			echo ""; echo "Calling [cp -f \"${FILE_TO_BACKUP}\" \"${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak\";]...";
@@ -244,10 +258,10 @@ else
 			echo "${DASHES}";
 
 			# Create the eth0 config file (if it is a valid filepath yet doesnt exist)
-			if [ -n "${FILE_ETH0_BUILDER}" ] && [ ! -f "${FILE_ETH0_BUILDER}" ]; then
+			if [ -n "${DEBIAN_NETWORK_CONF}" ] && [ ! -f "${DEBIAN_NETWORK_CONF}" ]; then
 				echo "";
-				echo "Calling [echo \"\" > \"${FILE_ETH0_BUILDER}\";]...";
-				echo "" > "${FILE_ETH0_BUILDER}";
+				echo "Calling [echo \"\" > \"${DEBIAN_NETWORK_CONF}\";]...";
+				echo "" > "${DEBIAN_NETWORK_CONF}";
 			fi;
 
 			DNS_SEARCH_DOMAIN="";
@@ -259,14 +273,14 @@ else
 				fi;
 			fi;
 
-			DNS_LOOKUP_1=$(cat ${FILE_ETH0_BUILDER} | grep ${DNS_NAMESRVR_1});
-			DNS_LOOKUP_2=$(cat ${FILE_ETH0_BUILDER} | grep ${DNS_NAMESRVR_2});
-			DNS_LOOKUP_3=$(cat ${FILE_ETH0_BUILDER} | grep ${DNS_NAMESRVR_3});
+			DNS_LOOKUP_1=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_1});
+			DNS_LOOKUP_2=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_2});
+			DNS_LOOKUP_3=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_3});
 
 			REFRESH_DNS_FILE="0";
 
 			ACTION_DOMAIN_RESOLUTION="";
-			DOMAIN_RESOLUTION_CONFIGURED="$(cat ${FILE_ETH0_BUILDER} | grep 'search ')";
+			DOMAIN_RESOLUTION_CONFIGURED="$(cat ${DEBIAN_NETWORK_CONF} | grep 'search ')";
 			if [ -n "${DNS_SEARCH_DOMAIN}" ]; then
 				DOMAIN_RESOLUTION_CONFIGURED="$(echo ${DOMAIN_RESOLUTION_CONFIGURED} | grep ${DNS_SEARCH_DOMAIN};)";
 				if [ ! -n "${DOMAIN_RESOLUTION_CONFIGURED}" ]; then
@@ -277,25 +291,25 @@ else
 			if [ -n "${DNS_LOOKUP_1}" ] && [ -n "${DNS_LOOKUP_2}" ] && [ -n "${DNS_LOOKUP_3}" ] && [ -n "${ACTION_DOMAIN_RESOLUTION}" ]; then # all variables are not null
 
 				echo "";
-				echo "\"${FILE_ETH0_BUILDER}\"'s DNS settings are up-to-date";
+				echo "\"${DEBIAN_NETWORK_CONF}\"'s DNS settings are up-to-date";
 				
 			else # at least one DNS-IP/Hostname is missing
 
 				echo "";
-				echo "Updating DNS Servers which build out of file \"${FILE_ETH0_BUILDER}\"";
+				echo "Updating DNS Servers which build out of file \"${DEBIAN_NETWORK_CONF}\"";
 				
 				# "dns-search"
 				if [ -n "${DNS_SEARCH_DOMAIN}" ] && [ "${ACTION_DOMAIN_RESOLUTION}" == "SET" ]; then
 					#    verify if any line already contains the "dns-search" directive
-					DNS_SEARCH_LINES_FOUND=$(cat "${FILE_ETH0_BUILDER}" | grep 'dns-search ' | wc -l);
+					DNS_SEARCH_LINES_FOUND=$(cat "${DEBIAN_NETWORK_CONF}" | grep 'dns-search ' | wc -l);
 					DOMAIN_BIND_TO_ETH0="${DNS_SEARCH_DOMAIN}";
 					if [ "${DNS_SEARCH_LINES_FOUND}" == "0" ]; then
 						# add the "dns-search" line
-						echo "dns-search ${DOMAIN_BIND_TO_ETH0}" >>  "${FILE_ETH0_BUILDER}";
+						echo "dns-search ${DOMAIN_BIND_TO_ETH0}" >>  "${DEBIAN_NETWORK_CONF}";
 					else
 						# modify the "dns-search" line
 						SED_DNS_SEARCH="/^dns-search/c\dns-search ${DOMAIN_BIND_TO_ETH0}";
-						sed --in-place --expression="${SED_DNS_SEARCH}" "${FILE_ETH0_BUILDER}";
+						sed --in-place --expression="${SED_DNS_SEARCH}" "${DEBIAN_NETWORK_CONF}";
 					fi;
 
 				else
@@ -308,15 +322,15 @@ else
 				
 				# "dns-nameservers"
 				#    verify if any line already contains the "dns-nameservers" directive
-				DNS_NAMESERVER_LINES_FOUND=$(cat "${FILE_ETH0_BUILDER}" | grep 'dns-nameservers' | wc -l);
+				DNS_NAMESERVER_LINES_FOUND=$(cat "${DEBIAN_NETWORK_CONF}" | grep 'dns-nameservers' | wc -l);
 				DNS_BIND_TO_ETH0="${DNS_NAMESRVR_1} ${DNS_NAMESRVR_2} ${DNS_NAMESRVR_3}";
 				if [ "${DNS_NAMESERVER_LINES_FOUND}" == "0" ]; then
 					# add the "dns-nameservers" line
-					echo "dns-nameservers ${DNS_BIND_TO_ETH0}" >> "${FILE_ETH0_BUILDER}";
+					echo "dns-nameservers ${DNS_BIND_TO_ETH0}" >> "${DEBIAN_NETWORK_CONF}";
 				else
 					# modify the "dns-nameservers" line
 					SED_DNS_NAMESERVERS="/^dns-nameservers/c\dns-nameservers ${DNS_BIND_TO_ETH0}";
-					sed --in-place --expression="${SED_DNS_NAMESERVERS}" "${FILE_ETH0_BUILDER}";
+					sed --in-place --expression="${SED_DNS_NAMESERVERS}" "${DEBIAN_NETWORK_CONF}";
 				fi;
 				
 				REFRESH_DNS_FILE="1";
@@ -408,15 +422,21 @@ else
 	# echo "Calling [ifconfig eth0]...";
 	# echo "${DASHES}"; ifconfig eth0; echo "${DASHES}";
 
-	# show the "/etc/network/interfaces/..." file, which should contain all DNS update logic
-	echo "";
-	echo "Calling [cat \"${FILE_ETH0_BUILDER}\"]";
-	echo "${DASHES}"; cat "${FILE_ETH0_BUILDER}"; echo "${DASHES}";
+	if [ -f "${DEBIAN_NETWORK_CONF}" ]; then
+		echo "";
+		echo "Calling [cat \"${DEBIAN_NETWORK_CONF}\"]";
+		echo "${DASHES}"; cat "${DEBIAN_NETWORK_CONF}"; echo "${DASHES}";
+	elif [ -f "${RHEL_NETWORK_CONF}" ]; then
+		echo "";
+		echo "Calling [cat \"${RHEL_NETWORK_CONF}\"]";
+		echo "${DASHES}"; cat "${RHEL_NETWORK_CONF}"; echo "${DASHES}";
+	fi;
 
-	# show "${ETC_RESOLVCONF}" file, which is the LIVE linux config-file (which is dynamically filled-in by network/interface configs)
-	echo "";
-	echo "Calling [cat \"${ETC_RESOLVCONF}\"]";
-	echo "${DASHES}"; cat "${ETC_RESOLVCONF}"; echo "${DASHES}";
+	if [ -f "${ETC_RESOLVCONF}" ]; then
+		echo "";
+		echo "Calling [cat \"${ETC_RESOLVCONF}\"]";
+		echo "${DASHES}"; cat "${ETC_RESOLVCONF}"; echo "${DASHES}";
+	fi;
 
 fi;
 
