replace lines starting with tabs with spaces (tab count 1)

diff --git a/usr/local/bin/cert_test b/usr/local/bin/cert_test
--- a/usr/local/bin/cert_test
+++ b/usr/local/bin/cert_test
@@ -5,11 +5,11 @@
 # ------------------------------------------------------------
 
 if [ -n "${1}" ]; then
-	openssl s_client -connect "${1}":443 -servername "${1}"
-	exit 0;
+  openssl s_client -connect "${1}":443 -servername "${1}"
+  exit 0;
 else
-	echo "Error: Please specify a hostname to test, such as [  ${0} example.com  ]"
-	exit 1;
+  echo "Error: Please specify a hostname to test, such as [  ${0} example.com  ]"
+  exit 1;
 fi;
 
 
diff --git a/usr/local/bin/docker_create_jenkins b/usr/local/bin/docker_create_jenkins
--- a/usr/local/bin/docker_create_jenkins
+++ b/usr/local/bin/docker_create_jenkins
@@ -8,39 +8,39 @@ REQUIRED_PKG="jq"; if [ -z "$(which ${REQUIRED_PKG} 2>'/dev/null')" ]; then apt-
 DOCKER_IMAGE_NAME="jenkinsci/blueocean";
 DOCKER_IMAGE_TAGS=$(curl -s -S "https://registry.hub.docker.com/v1/repositories/${DOCKER_IMAGE_NAME}/tags" | jq -r ".[].name" 2>"/dev/null";); ERRORS_TAG_LOOKUP=$?;
 if [ ${ERRORS_TAG_LOOKUP} -ne 0 ]; then
-	echo "Error: No docker images found to match \"${DOCKER_IMAGE_NAME}\"";
-	exit 1;
+  echo "Error: No docker images found to match \"${DOCKER_IMAGE_NAME}\"";
+  exit 1;
 else
 
-	echo "";
-	echo "\${#DOCKER_IMAGE_TAGS} = [ ${#DOCKER_IMAGE_TAGS} ]";
-	echo "";
+  echo "";
+  echo "\${#DOCKER_IMAGE_TAGS} = [ ${#DOCKER_IMAGE_TAGS} ]";
+  echo "";
 
-	DOCKER_IMAGE_TAGS_SORTED=$(echo "${DOCKER_IMAGE_TAGS}" | sort -r);
-	DOCKER_IMAGE_TAGS_SORTED_REV=$(echo "${DOCKER_IMAGE_TAGS}" | sort);
+  DOCKER_IMAGE_TAGS_SORTED=$(echo "${DOCKER_IMAGE_TAGS}" | sort -r);
+  DOCKER_IMAGE_TAGS_SORTED_REV=$(echo "${DOCKER_IMAGE_TAGS}" | sort);
 
-	unset ARR_TAG_OPTIONS; declare -A ARR_TAG_OPTIONS; # [Re-]Instantiate bash array
+  unset ARR_TAG_OPTIONS; declare -A ARR_TAG_OPTIONS; # [Re-]Instantiate bash array
 
-	EACH_KEY=0;
-	# MIN_KEY=$((EACH_KEY+1));
-	MIN_KEY=${EACH_KEY};
-	for EACH_TAG in ${DOCKER_IMAGE_TAGS_SORTED[@]}; do
+  EACH_KEY=0;
+  # MIN_KEY=$((EACH_KEY+1));
+  MIN_KEY=${EACH_KEY};
+  for EACH_TAG in ${DOCKER_IMAGE_TAGS_SORTED[@]}; do
     ARR_TAG_OPTIONS+=(["${EACH_KEY}"]="${EACH_TAG}");
     EACH_KEY=$((EACH_KEY+1));
-	done;
-	MAX_KEY=$((${EACH_KEY}-1));
+  done;
+  MAX_KEY=$((${EACH_KEY}-1));
 
-	# MENU_LENGTH=10;
-	# if [ -n "$(which bc 2>'/dev/null')" ] && [ -n "$(which tput 2>'/dev/null')" ]; then
-	# 	MENU_LENGTH=$(echo "$(tput lines) / 2" | bc);
-	# fi;
-	# IMAGES_MENU_OPTIONS=$(echo "${DOCKER_IMAGE_TAGS_SORTED}" | tail -n ${MENU_LENGTH});
-	# echo "IMAGES_MENU_OPTIONS:";
-	# echo "${IMAGES_MENU_OPTIONS}";
+  # MENU_LENGTH=10;
+  # if [ -n "$(which bc 2>'/dev/null')" ] && [ -n "$(which tput 2>'/dev/null')" ]; then
+  # 	MENU_LENGTH=$(echo "$(tput lines) / 2" | bc);
+  # fi;
+  # IMAGES_MENU_OPTIONS=$(echo "${DOCKER_IMAGE_TAGS_SORTED}" | tail -n ${MENU_LENGTH});
+  # echo "IMAGES_MENU_OPTIONS:";
+  # echo "${IMAGES_MENU_OPTIONS}";
 
-	if [ ${CHOICE_KEY} -le 0 ]; then
+  if [ ${CHOICE_KEY} -le 0 ]; then
     echo "Error: No Containers found to be running - Please start a container then rerun \"${0}\"";
-	else
+  else
     
     ARR_TAG_OPTIONS_NO_DUPES=($(echo "${ARR_TAG_OPTIONS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
     for EACH_KEY in "${!ARR_TAG_OPTIONS_NO_DUPES[@]}"; do
@@ -89,14 +89,14 @@ else
       echo -e "Error: Invalid/empty User-input""\n""${ERROR_SUGGEST_HELP}";
 
     fi;
-	fi;
+  fi;
 
-	# docker_name="jenkins_$(date +'%s')";
-	# docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v "jenkins-data:/var/jenkins_home" -v "/var/run/docker.sock:/var/run/docker.sock" --name "${docker_name}" "jenkinsci/blueocean";
-	# docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v "jenkins-data:/var/jenkins_home" -v "/var/run/docker.sock:/var/run/docker.sock" --name "${docker_name}" "jenkinsci/blueocean";
-	# printf "    ===--  Started Docker:  ${docker_name}...\n"
-	# printf "    ===--    Bashing Into:  ${docker_name}...\n"
-	# docker exec -i -t ${docker_name} /bin/bash;
+  # docker_name="jenkins_$(date +'%s')";
+  # docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v "jenkins-data:/var/jenkins_home" -v "/var/run/docker.sock:/var/run/docker.sock" --name "${docker_name}" "jenkinsci/blueocean";
+  # docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v "jenkins-data:/var/jenkins_home" -v "/var/run/docker.sock:/var/run/docker.sock" --name "${docker_name}" "jenkinsci/blueocean";
+  # printf "    ===--  Started Docker:  ${docker_name}...\n"
+  # printf "    ===--    Bashing Into:  ${docker_name}...\n"
+  # docker exec -i -t ${docker_name} /bin/bash;
 
 fi;
 
diff --git a/usr/local/bin/docker_tags_X b/usr/local/bin/docker_tags_X
--- a/usr/local/bin/docker_tags_X
+++ b/usr/local/bin/docker_tags_X
@@ -1,31 +1,31 @@
 #!/bin/bash
 
 if [ ! -v DOCKER_IMAGE ] || [ -z "${DOCKER_IMAGE}" ]; then
-	read -p "Search for Tags on which Docker Image?  " -t 60 -r; READ_RET_CODE=$?;
-	if [ ${READ_RET_CODE} -gt 128 ]; then # From [ read --help ]: "The exit status is greater than 128 if the timeout is exceeded"
+  read -p "Search for Tags on which Docker Image?  " -t 60 -r; READ_RET_CODE=$?;
+  if [ ${READ_RET_CODE} -gt 128 ]; then # From [ read --help ]: "The exit status is greater than 128 if the timeout is exceeded"
     echo -e "Error: Response timed out ";
-	elif [ -n "${REPLY}" ]; then
+  elif [ -n "${REPLY}" ]; then
     DOCKER_IMAGE="${REPLY}";
-	fi;
+  fi;
 fi;
 
 
 if [ ! -v DOCKER_IMAGE ] || [ -z "${DOCKER_IMAGE}" ]; then
-	echo "Error: Empty/unset Docker Image-Name";
-	echo "  |--> Please retry using syntax [ env DOCKER_IMAGE=\"YOUR_IMAGE\" ${0} ]";
-	exit 1;
+  echo "Error: Empty/unset Docker Image-Name";
+  echo "  |--> Please retry using syntax [ env DOCKER_IMAGE=\"YOUR_IMAGE\" ${0} ]";
+  exit 1;
 
 else
 
-	REQUIRED_PKG="jq"; if [ -z "$(which ${REQUIRED_PKG} 2>'/dev/null')" ]; then apt-get update -y; apt-get install -y ${REQUIRED_PKG}; fi;
+  REQUIRED_PKG="jq"; if [ -z "$(which ${REQUIRED_PKG} 2>'/dev/null')" ]; then apt-get update -y; apt-get install -y ${REQUIRED_PKG}; fi;
 
-	DOCKER_IMAGE_NAME="${DOCKER_IMAGE}";
+  DOCKER_IMAGE_NAME="${DOCKER_IMAGE}";
 
-	DOCKER_IMAGE_TAGS=$(curl -s -S "https://registry.hub.docker.com/v1/repositories/${DOCKER_IMAGE_NAME}/tags" | jq -r ".[].name" 2>"/dev/null";); ERRORS_TAG_LOOKUP=$?;
-	if [ ${ERRORS_TAG_LOOKUP} -ne 0 ]; then
+  DOCKER_IMAGE_TAGS=$(curl -s -S "https://registry.hub.docker.com/v1/repositories/${DOCKER_IMAGE_NAME}/tags" | jq -r ".[].name" 2>"/dev/null";); ERRORS_TAG_LOOKUP=$?;
+  if [ ${ERRORS_TAG_LOOKUP} -ne 0 ]; then
     echo "Error: No docker images found to match \"${DOCKER_IMAGE_NAME}\"";
     exit 1;
-	else
+  else
 
     echo "";
     echo "\${#DOCKER_IMAGE_TAGS} = [ ${#DOCKER_IMAGE_TAGS} ]";
@@ -114,7 +114,7 @@ else
       fi;
     fi;
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/bin/get_ipv4_wan b/usr/local/bin/get_ipv4_wan
--- a/usr/local/bin/get_ipv4_wan
+++ b/usr/local/bin/get_ipv4_wan
@@ -37,38 +37,38 @@ LENGTH_WAN_IP=0;
 
 # Get current WAN IPv4
 for EACH_RESOLVER in "${IP_RESOLVERS[@]}"; do
-	if [ -z "${THIS_WAN_IPv4}" ] || [[ ${LENGTH_WAN_IP} -gt 15 ]]; then
+  if [ -z "${THIS_WAN_IPv4}" ] || [[ ${LENGTH_WAN_IP} -gt 15 ]]; then
     THIS_WAN_IPv4=$(curl -L -s "${EACH_RESOLVER}");
     LENGTH_WAN_IP=$(echo -n "${THIS_WAN_IPv4}" | wc -c);
-	fi;
+  fi;
 done;
 
 # Output Status: PASS or FAIL
 if [ -z "${THIS_WAN_IPv4}" ] || (( ${LENGTH_WAN_IP} > 15 )); then
-	# Error: Clear Variables
-	RESPONSE_SRVR="";
-	THIS_WAN_IPv4="";
-	LENGTH_WAN_IP="";
-	# Error: Show Message
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Unable to resolve WAN-IP";
-	# Error: Throw 'bad' return-code
-	exit 1;
+  # Error: Clear Variables
+  RESPONSE_SRVR="";
+  THIS_WAN_IPv4="";
+  LENGTH_WAN_IP="";
+  # Error: Show Message
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Unable to resolve WAN-IP";
+  # Error: Throw 'bad' return-code
+  exit 1;
 else
-	# Success
-	if [ "${1}" == "verbose" ]; then
-	# "Verbose" output
+  # Success
+  if [ "${1}" == "verbose" ]; then
+  # "Verbose" output
     echo "";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Resolved WAN-IP to \"${THIS_WAN_IPv4}\" via \"${RESPONSE_SRVR}\" ";
     echo "";
-	elif [ "$1" == "-q" ] || [ "$1" == "--quiet" ]; then
+  elif [ "$1" == "-q" ] || [ "$1" == "--quiet" ]; then
     # "Quiet" output (NO trailing newline)
     echo -n "${THIS_WAN_IPv4}";
-	else
+  else
     # "Normal" output (output w/ newline)
     echo "${THIS_WAN_IPv4}";
-	fi;
-	# Exit w/ 'good' return-code
-	exit 0;
+  fi;
+  # Exit w/ 'good' return-code
+  exit 0;
 fi;
 
 #------------------------------------------------------------
diff --git a/usr/local/bin/get_subdomains b/usr/local/bin/get_subdomains
--- a/usr/local/bin/get_subdomains
+++ b/usr/local/bin/get_subdomains
@@ -20,27 +20,27 @@ fi;
 
 if [ -z "${1}" ]; then
 
-	echo -e "\nError in call to \"get_subdomains\"\n  --> Expected syntax:     >  get_subdomains HOSTNAME;\n";
-	exit 1;
+  echo -e "\nError in call to \"get_subdomains\"\n  --> Expected syntax:     >  get_subdomains HOSTNAME;\n";
+  exit 1;
 
 else
 
-	shopt -s lastpipe; # If set, and job control is not active, the shell runs the last command of a pipeline not executed in the background in the current shell environment.
-	          # |
-	          # |--> e.g. extends scope of variables which get set/updated during "while ...; do" loop to be referenced AFTER said loop is "done;"
-	          #           (normally, variables set during background tasks are scoped separately, and not able to be referenced afterwards)
+  shopt -s lastpipe; # If set, and job control is not active, the shell runs the last command of a pipeline not executed in the background in the current shell environment.
+            # |
+            # |--> e.g. extends scope of variables which get set/updated during "while ...; do" loop to be referenced AFTER said loop is "done;"
+            #           (normally, variables set during background tasks are scoped separately, and not able to be referenced afterwards)
 
-	REGEX_IPV4='(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))';
-	SED_LINE='s/^(.+),'${REGEX_IPV4}'$/\0/p';
-	SED_FQDN='s/^(.+),'${REGEX_IPV4}'$/\1/p';
-	SED_IPV4='s/^(.+),'${REGEX_IPV4}'$/\2/p';
+  REGEX_IPV4='(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))';
+  SED_LINE='s/^(.+),'${REGEX_IPV4}'$/\0/p';
+  SED_FQDN='s/^(.+),'${REGEX_IPV4}'$/\1/p';
+  SED_IPV4='s/^(.+),'${REGEX_IPV4}'$/\2/p';
 
-	SMOKE_TEST=$(curl -L -s "https://api.hackertarget.com/hostsearch/?q=${1}" | head -n 1;);
-	if [ "${SMOKE_TEST}" == "error check your search parameter" ]; then
+  SMOKE_TEST=$(curl -L -s "https://api.hackertarget.com/hostsearch/?q=${1}" | head -n 1;);
+  if [ "${SMOKE_TEST}" == "error check your search parameter" ]; then
     echo -e "\nError in call to \"get_subdomains\"\n  -->  Hostname not found:  \"${1}\"\n";
     exit 1;
 
-	else
+  else
 
     INDEX_RESULTS_BY="IPV4";
     if [ -n "${2}" ]; then
@@ -94,7 +94,7 @@ else
 
     exit 0;
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/bin/git_init b/usr/local/bin/git_init
--- a/usr/local/bin/git_init
+++ b/usr/local/bin/git_init
@@ -34,7 +34,7 @@ exec 2>&1;
 # ------------------------------------------------------------
 
 if [ -n "${1}" ] && [ -f "${1}" ]; then
-	source "${1}"; # First inline parameter ( $1 ) is the path to another shell script which sets/instantiates all required config variables
+  source "${1}"; # First inline parameter ( $1 ) is the path to another shell script which sets/instantiates all required config variables
 fi;
 
 # ------------------------------------------------------------
@@ -45,12 +45,12 @@ FAIL_MSG="";
 
 # If acting as the "root" user and the "git" module is not installed, then attempt to install git
 if [ -z "$(which git 2>'/dev/null';)" ] && [ "$(id -un)" == "root" ]; then
-	if [ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]; then
+  if [ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]; then
     # Ubuntu
     echo -e "$(date '+%Y-%m-%d %H:%M:%S') | Git not installed (Ubuntu Linux) - Attempting to install via:";
     echo -e "$(date '+%Y-%m-%d %H:%M:%S') | ---> apt -y update && apt -y install --ignore-missing git;";
     apt -qq -y update && apt -qq -y install --ignore-missing git;
-	else
+  else
     if [ $(cat /etc/*release | grep -i debian | wc -l) -gt 0 ]; then
       # Debian
       echo -e "$(date '+%Y-%m-%d %H:%M:%S') | Git not installed (Debian Linux) - Attempting to install via:";
@@ -71,7 +71,7 @@ if [ -z "$(which git 2>'/dev/null';)" ] && [ "$(id -un)" == "root" ]; then
         fi;
       fi;
     fi;
-	fi;
+  fi;
 fi;
 
 echo "";
@@ -81,54 +81,54 @@ echo "";
 # Fail-out if git is not installed & could not be installed
 which git > /dev/null 2>&1; MODULE_FOUND_ERROR_CODE=$?;
 if [ ${MODULE_FOUND_ERROR_CODE} -ne 0 ]; then 
-	FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Git runtime not installed.\n";
+  FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Git runtime not installed.\n";
 fi;
 
 # Verify Repo Host
 if [ -z "${REMOTE_HOST}" ]; then
-	read -p "  Remote Host/IPv4?  (e.g. github.com)  :  " -t 60 -r;
-	REMOTE_HOST="${REPLY}";
-	if [ -z "${REMOTE_HOST}" ]; then
+  read -p "  Remote Host/IPv4?  (e.g. github.com)  :  " -t 60 -r;
+  REMOTE_HOST="${REPLY}";
+  if [ -z "${REMOTE_HOST}" ]; then
     FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_HOST is empty.\n";
-	fi;
+  fi;
 fi;
 
 # Verify Repo Owner
 if [ -z "${REMOTE_OWNER}" ]; then
-	read -p "  Remote Repo's Owner? (username/company-name which owns repo)  :  " -t 60 -r;
-	REMOTE_OWNER="${REPLY}";
-	if [ -z "${REMOTE_OWNER}" ]; then
+  read -p "  Remote Repo's Owner? (username/company-name which owns repo)  :  " -t 60 -r;
+  REMOTE_OWNER="${REPLY}";
+  if [ -z "${REMOTE_OWNER}" ]; then
     FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_OWNER is empty.\n";
-	fi;
+  fi;
 fi;
 
 # Verify Repo Basename
 if [ -z "${REMOTE_REPOSITORY}" ]; then
-	read -p "  Remote Repo's Basename? (e.g. name of the repository)  :  " -t 60 -r;
-	REMOTE_REPOSITORY="${REPLY}";
-	if [ -z "${REMOTE_REPOSITORY}" ]; then
+  read -p "  Remote Repo's Basename? (e.g. name of the repository)  :  " -t 60 -r;
+  REMOTE_REPOSITORY="${REPLY}";
+  if [ -z "${REMOTE_REPOSITORY}" ]; then
     FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_REPOSITORY is empty.\n";
-	fi;
+  fi;
 fi;
 
 # Verify Repo SSH Private-Keys
 REMOTE_PRIVATE_KEY="${REMOTE_PRIVATE_KEY:-${REMOTE_SSH_KEY}}";
 if [ -z "${REMOTE_PRIVATE_KEY}" ]; then
-	read -p "  Private-Key for Remote Repo? (e.g. fullpath to RSA key)  :  " -t 60 -r;
-	REMOTE_PRIVATE_KEY="${REPLY}";
-	if [ -z "${REMOTE_PRIVATE_KEY}" ]; then
+  read -p "  Private-Key for Remote Repo? (e.g. fullpath to RSA key)  :  " -t 60 -r;
+  REMOTE_PRIVATE_KEY="${REPLY}";
+  if [ -z "${REMOTE_PRIVATE_KEY}" ]; then
     FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_PRIVATE_KEY is empty.\n"; 
-	elif [ ! -f "${REMOTE_PRIVATE_KEY}" ]; then
+  elif [ ! -f "${REMOTE_PRIVATE_KEY}" ]; then
     FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: File not found: \$REMOTE_PRIVATE_KEY=\"${REMOTE_PRIVATE_KEY}\".\n";
-	fi;
+  fi;
 fi;
 
 # Fail-out if any startup errors were found
 if [ -n "${FAIL_MSG}" ]; then
-	FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Exiting after 20s...";
-	echo -e "${FAIL_MSG}";
-	sleep 20;
-	exit 1;
+  FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Exiting after 20s...";
+  echo -e "${FAIL_MSG}";
+  sleep 20;
+  exit 1;
 fi;
 
 # Welcome the User
@@ -138,15 +138,15 @@ echo "$(date '+%Y-%m-%d %H:%M:%S') | Git Setup/Config";
 
 # Set default git repos dir
 if [ "$(id -un)" != "root" ]; then
-	ALL_REPOS_DIR="${HOME}/git";
+  ALL_REPOS_DIR="${HOME}/git";
 else
-	ALL_REPOS_DIR="/var/lib/git";
+  ALL_REPOS_DIR="/var/lib/git";
 fi;
 
 # Ensure that the git repo parent dir exists
 if [ ! -d "${ALL_REPOS_DIR}" ]; then
  	echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Creating default Git directory \"${ALL_REPOS_DIR}\"";
-	mkdir -p "${ALL_REPOS_DIR}";
+  mkdir -p "${ALL_REPOS_DIR}";
 fi;
 
 # Determine the default privileges (user:group) to set for other git-repo dirs
@@ -166,9 +166,9 @@ CHECKOUT_BRANCH="${CHECKOUT_BRANCH:-${REPO_BRANCH:-${REMOTE_BRANCH:-${BRANCH}}}}
 # Verify that the git repos-dir has correct ownership & access-privileges set
 if [ -n "${GIT_CHOWN_UID}" ] && [ -n "${GIT_CHOWN_GID}" ] && [ -d "${ALL_REPOS_DIR}" ]; then
  	echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Setting Git parent directory's file permissions to \"0700\"";
-	chmod 0700 "${ALL_REPOS_DIR}";
+  chmod 0700 "${ALL_REPOS_DIR}";
  	echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Setting Git parent directory's file ownership to \"${GIT_CHOWN_UID}:${GIT_CHOWN_GID}\"";
-	chown -R "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${ALL_REPOS_DIR}";
+  chown -R "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${ALL_REPOS_DIR}";
 fi;
 
 # Remove undesired variables from the environment
@@ -189,24 +189,24 @@ if [ -n "${GIT_CONFIG}" ]; then unset GIT_CONFIG; fi; # export GIT_CONFIG="${GIT
 #
 GIT_HOST_DIR="${ALL_REPOS_DIR}/${REMOTE_HOST}";
 if [ ! -d "${GIT_HOST_DIR}" ]; then
-	mkdir -p "${GIT_HOST_DIR}" && chmod 700 "${GIT_HOST_DIR}" && chown "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${GIT_HOST_DIR}";
+  mkdir -p "${GIT_HOST_DIR}" && chmod 700 "${GIT_HOST_DIR}" && chown "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${GIT_HOST_DIR}";
 fi;
 
 GIT_LOCAL_CEILING="${GIT_HOST_DIR}/${REMOTE_OWNER}";
 WINDOWS_GITHUB_LOCAL_CEILING="${HOME}/Documents/GitHub";
 if [ ! -d "${GIT_LOCAL_CEILING}" ]; then
-	mkdir -p "${GIT_LOCAL_CEILING}" && chmod 700 "${GIT_LOCAL_CEILING}" && chown "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${GIT_LOCAL_CEILING}";
+  mkdir -p "${GIT_LOCAL_CEILING}" && chmod 700 "${GIT_LOCAL_CEILING}" && chown "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${GIT_LOCAL_CEILING}";
 fi;
 
 GIT_WORK_TREE="${GIT_LOCAL_CEILING}/${REMOTE_REPOSITORY}";
 WINDOWS_GITHUB_WORK_TREE="${WINDOWS_GITHUB_LOCAL_CEILING}/${REMOTE_REPOSITORY}";
 GIT_WORK_TREE_REL=".";
 if [ ! -d "${GIT_WORK_TREE}" ]; then
-	mkdir -p "${GIT_WORK_TREE}" && chmod 700 "${GIT_WORK_TREE}" && chown "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${GIT_WORK_TREE}";
+  mkdir -p "${GIT_WORK_TREE}" && chmod 700 "${GIT_WORK_TREE}" && chown "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${GIT_WORK_TREE}";
 fi;
 
 GIT_GITDIR="${GIT_WORK_TREE}/.git";
-	GIT_GITDIR_REL="${GIT_WORK_TREE_REL}/.git";
+  GIT_GITDIR_REL="${GIT_WORK_TREE_REL}/.git";
 
 GIT_CLI_NOCONF="git";
 # GIT_CLI_NOCONF="${GIT_CLI_NOCONF} -C ${GIT_LOCAL_CEILING}";
@@ -218,9 +218,9 @@ GIT_CLI="${GIT_CLI} --git-dir=${GIT_GITDIR_REL// /\\ }";
 
 # TARGET REPOSITORY
 if [ "${REMOTE_HOST}" == "ssh.dev.azure.com" ]; then
-	ORIGIN_GIT="git@${REMOTE_HOST}:v3/${REMOTE_OWNER}/${REMOTE_REPOSITORY}"; # Azure Repos (No ".git" appended)
+  ORIGIN_GIT="git@${REMOTE_HOST}:v3/${REMOTE_OWNER}/${REMOTE_REPOSITORY}"; # Azure Repos (No ".git" appended)
 else
-	ORIGIN_GIT="git@${REMOTE_HOST}:${REMOTE_OWNER}/${REMOTE_REPOSITORY}.git"; # Target Repository
+  ORIGIN_GIT="git@${REMOTE_HOST}:${REMOTE_OWNER}/${REMOTE_REPOSITORY}.git"; # Target Repository
 fi;
 
 # Override SSH runtime's default/current config settings (which is what Git connects through) to force RSA key usage
@@ -281,7 +281,7 @@ echo "$(date '+%Y-%m-%d %H:%M:%S') | -------------------------------------------
 
 # Create default-directory for SSH's configs
 if [ ! -d "${HOME}/.ssh" ]; then
-	mkdir -p "${HOME}/.ssh"; chmod 700 "${HOME}/.ssh";
+  mkdir -p "${HOME}/.ssh"; chmod 700 "${HOME}/.ssh";
 fi;
 
 # Gather SSH Public Keys for target Hostname
@@ -292,7 +292,7 @@ ssh -o StrictHostKeyChecking=no -T "${ORIGIN_GIT}"; # Skip checking public-keys
 # Clone repo (if non existent)
 FIRST_CLONE_OF_REPO="0";
 if [ ! -d "${GIT_GITDIR}" ]; then
-	FIRST_CLONE_OF_REPO="1";
+  FIRST_CLONE_OF_REPO="1";
 # 	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI_NOCONF} clone ${ORIGIN_GIT}";
 # 	cd "${GIT_LOCAL_CEILING}";
 # 	export GIT_SSH_COMMAND="ssh -4 -i '${REMOTE_PRIVATE_KEY}' -o StrictHostKeyChecking=no -F /dev/null";
@@ -308,11 +308,11 @@ ${GIT_CLI} init;
 # [config] remote.origin.url
 LOCAL_CURRENT_ORIGINS=$(${GIT_CLI} remote);
 if [ -n "${LOCAL_CURRENT_ORIGINS}" ]; then # remote origin
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git remote set-url origin \"${ORIGIN_GIT}\"";
-	${GIT_CLI} remote set-url origin "${ORIGIN_GIT}";
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git remote set-url origin \"${ORIGIN_GIT}\"";
+  ${GIT_CLI} remote set-url origin "${ORIGIN_GIT}";
 else
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git remote add origin \"${ORIGIN_GIT}\"";
-	${GIT_CLI} remote add origin "${ORIGIN_GIT}";
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git remote add origin \"${ORIGIN_GIT}\"";
+  ${GIT_CLI} remote add origin "${ORIGIN_GIT}";
 fi;
 
 # [config]  core.sshcommand
@@ -322,35 +322,35 @@ ${GIT_CLI} config core.sshcommand "ssh -4 -i '${REMOTE_PRIVATE_KEY}' -o StrictHo
 
 # [config]  core.compression  (UNSET)
 if [ -n "$(${GIT_CLI} config core.compression)" ]; then
-	${GIT_CLI} config --unset core.compression;
+  ${GIT_CLI} config --unset core.compression;
 fi;
 
 # [config]  user.name
 if [ -n "${COMMIT_USER_FULLNAME}" ]; then
-	CURRENT_LOCAL_GIT_FULLNAME=$(${GIT_CLI} config user.name);
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git config user.name \"${COMMIT_USER_FULLNAME}\"";
-	${GIT_CLI} config user.name "${COMMIT_USER_FULLNAME}";
-	if [ "${COMMIT_USER_FULLNAME}" != "${CURRENT_LOCAL_GIT_FULLNAME}" ]; then
+  CURRENT_LOCAL_GIT_FULLNAME=$(${GIT_CLI} config user.name);
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git config user.name \"${COMMIT_USER_FULLNAME}\"";
+  ${GIT_CLI} config user.name "${COMMIT_USER_FULLNAME}";
+  if [ "${COMMIT_USER_FULLNAME}" != "${CURRENT_LOCAL_GIT_FULLNAME}" ]; then
     echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> Info:  Previous value = \"${CURRENT_LOCAL_GIT_FULLNAME}\"";
-	fi;
+  fi;
 fi;
 
 # [config]  user.email
 if [ -n "${COMMIT_USER_EMAIL}" ]; then
-	CURRENT_LOCAL_GIT_USER_EMAIL=$(${GIT_CLI} config user.email);
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git config user.email \"${COMMIT_USER_EMAIL}\"";
-	${GIT_CLI} config user.email "${COMMIT_USER_EMAIL}";
-	if [ "${COMMIT_USER_EMAIL}" != "${CURRENT_LOCAL_GIT_USER_EMAIL}" ]; then
+  CURRENT_LOCAL_GIT_USER_EMAIL=$(${GIT_CLI} config user.email);
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git config user.email \"${COMMIT_USER_EMAIL}\"";
+  ${GIT_CLI} config user.email "${COMMIT_USER_EMAIL}";
+  if [ "${COMMIT_USER_EMAIL}" != "${CURRENT_LOCAL_GIT_USER_EMAIL}" ]; then
     echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> Info:  Previous value = \"${CURRENT_LOCAL_GIT_USER_EMAIL}\"";
-	fi;
+  fi;
 fi;
 
 # [config]  remote.origin.prune  +  auto-pruning (upon fetching / pulling)
 REPO_PRUNE_ACTIVE=$(${GIT_CLI} config remote.origin.prune);
 if [ "${REPO_PRUNE_ACTIVE}" != "true" ]; then
-	# echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} config remote.origin.prune true";
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git config remote.origin.prune true";
-	${GIT_CLI} config remote.origin.prune true;
+  # echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} config remote.origin.prune true";
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git config remote.origin.prune true";
+  ${GIT_CLI} config remote.origin.prune true;
 fi;
 
 # fetch all
@@ -361,9 +361,9 @@ ${GIT_CLI} fetch --all;
 # new clones - automatically checkout default branch, first
 BRANCH_CHECKED_OUT=0;
 if [ "${FIRST_CLONE_OF_REPO}" == "1" ]; then
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> FIRST_CLONE_OF_REPO == 1";
-	# get default branch(es)
-	if [ -n "${CHECKOUT_BRANCH}" ]; then
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> FIRST_CLONE_OF_REPO == 1";
+  # get default branch(es)
+  if [ -n "${CHECKOUT_BRANCH}" ]; then
     TRY_BRANCH="${CHECKOUT_BRANCH}";
     echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
     ${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
@@ -373,8 +373,8 @@ if [ "${FIRST_CLONE_OF_REPO}" == "1" ]; then
     else
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Error: Failed to check out branch \"${TRY_BRANCH}\"";
     fi;
-	fi;
-	if [ ${BRANCH_CHECKED_OUT} -eq 0 ]; then
+  fi;
+  if [ ${BRANCH_CHECKED_OUT} -eq 0 ]; then
     TRY_BRANCH="main";
     echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
     ${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
@@ -386,8 +386,8 @@ if [ "${FIRST_CLONE_OF_REPO}" == "1" ]; then
     else
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Error: Failed to check out branch \"${TRY_BRANCH}\"";
     fi;
-	fi;
-	if [ ${BRANCH_CHECKED_OUT} -eq 0 ]; then
+  fi;
+  if [ ${BRANCH_CHECKED_OUT} -eq 0 ]; then
     TRY_BRANCH="master";
     echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
     ${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
@@ -399,11 +399,11 @@ if [ "${FIRST_CLONE_OF_REPO}" == "1" ]; then
     else
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Error: Failed to check out branch \"${TRY_BRANCH}\"";
     fi;
-	fi;
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Pulling branch \"${CHECKOUT_BRANCH}\"";
-	# echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} pull -v";
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git pull -v";
-	${GIT_CLI} pull -v;
+  fi;
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Pulling branch \"${CHECKOUT_BRANCH}\"";
+  # echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} pull -v";
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git pull -v";
+  ${GIT_CLI} pull -v;
 fi;
 
 # get current branch
@@ -412,8 +412,8 @@ echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git branch | grep '*' | awk '{print \$
 LOCAL_CURRENT_BRANCH=$(${GIT_CLI} branch | grep '*' | awk '{print $2}');
 echo "${LOCAL_CURRENT_BRANCH}";
 if [ -n "${LOCAL_CURRENT_BRANCH}" ]; then
-	REMOTE_BRANCH_EXISTS=$(${GIT_CLI} branch -a | awk '{print $1}' | grep -w remotes/origin/${CHECKOUT_BRANCH});
-	if [ -n "${REMOTE_BRANCH_EXISTS}" ]; then
+  REMOTE_BRANCH_EXISTS=$(${GIT_CLI} branch -a | awk '{print $1}' | grep -w remotes/origin/${CHECKOUT_BRANCH});
+  if [ -n "${REMOTE_BRANCH_EXISTS}" ]; then
     # checkout specific branch if not already on it
     if [ "${CHECKOUT_BRANCH}" != "${LOCAL_CURRENT_BRANCH}" ]; then
       # echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} checkout -f ${CHECKOUT_BRANCH}";
@@ -425,17 +425,17 @@ if [ -n "${LOCAL_CURRENT_BRANCH}" ]; then
     # echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} reset --hard \"origin/${CHECKOUT_BRANCH}\"";
     echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git reset --hard \"origin/${CHECKOUT_BRANCH}\"";
     ${GIT_CLI} reset --hard "origin/${CHECKOUT_BRANCH}";
-	else
+  else
     echo "$(date '+%Y-%m-%d %H:%M:%S') | Error: Branch \"${CHECKOUT_BRANCH}\" not found on remote.";
     echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Exiting after 20s...";
     # ${GIT_CLI} checkout -b "${CHECKOUT_BRANCH}"; <-- CREATES BRANCH
     sleep 20;
     exit 1;
-	fi;
+  fi;
 else
-	# echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} checkout -f ${CHECKOUT_BRANCH}";
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git checkout -f ${CHECKOUT_BRANCH}";
-	${GIT_CLI} checkout -f "${CHECKOUT_BRANCH}";
+  # echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} checkout -f ${CHECKOUT_BRANCH}";
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git checkout -f ${CHECKOUT_BRANCH}";
+  ${GIT_CLI} checkout -f "${CHECKOUT_BRANCH}";
 fi;
 
 # pull the desired branch
@@ -456,19 +456,19 @@ echo "$(date '+%Y-%m-%d %H:%M:%S') | ${LINE_BREAK}";
 
 FINAL_PARENT_DIR="${HOME}/Documents/GitHub";
 if [ -d "${WINDOWS_GITHUB_LOCAL_CEILING}" ]; then
-	if [ ! -d "${WINDOWS_GITHUB_WORK_TREE}" ]; then
+  if [ ! -d "${WINDOWS_GITHUB_WORK_TREE}" ]; then
     echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Attempting to relocate the git repository's root directory...";
     echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> from \"${GIT_WORK_TREE}\"";
     echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> to \"${WINDOWS_GITHUB_WORK_TREE}\"";
     echo "$(date '+%Y-%m-%d %H:%M:%S') | mv \"${GIT_WORK_TREE}\" \"${WINDOWS_GITHUB_WORK_TREE}\"";
     mv "${GIT_WORK_TREE}" "${WINDOWS_GITHUB_WORK_TREE}";
     GIT_WORK_TREE="${WINDOWS_GITHUB_WORK_TREE}";
-	else
+  else
     echo "$(date '+%Y-%m-%d %H:%M:%S') | Error: Directory already exists (unable to relocate git work tree to):";
     echo "$(date '+%Y-%m-%d %H:%M:%S') | --> \"${WINDOWS_GITHUB_WORK_TREE}\"";
 
-	fi;
-	echo "$(date '+%Y-%m-%d %H:%M:%S') | ${LINE_BREAK}";
+  fi;
+  echo "$(date '+%Y-%m-%d %H:%M:%S') | ${LINE_BREAK}";
 fi;
 
 chown -R "${GIT_CHOWN_UID}:${GIT_CHOWN_GID}" "${GIT_WORK_TREE}";
diff --git a/usr/local/bin/openssl_pfx_spc_update b/usr/local/bin/openssl_pfx_spc_update
--- a/usr/local/bin/openssl_pfx_spc_update
+++ b/usr/local/bin/openssl_pfx_spc_update
@@ -10,41 +10,41 @@
 #
 
 if [ -z "$1" ] || [ -z "$2" ]; then
-	echo -e "\n\n";
-	echo "First argument (\$1) should be the old PFX certificate's fullpath";
-	echo "Second argument (\$2) should be the new SPC certificate's fullpath";
-	echo -e "\n\n";
-	exit 1;
+  echo -e "\n\n";
+  echo "First argument (\$1) should be the old PFX certificate's fullpath";
+  echo "Second argument (\$2) should be the new SPC certificate's fullpath";
+  echo -e "\n\n";
+  exit 1;
 elif [ $(which pvk2pfx 1>/dev/null 2>&1; echo $?) -ne 0 ]; then
-	echo -e "\n\n";
-	echo "Error:  Command \"pvk2pfx\" not found";
-	echo "Must install command via \"Windows WDK\" from: https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk";
-	echo -e "\n\n";
-	exit 1;
+  echo -e "\n\n";
+  echo "Error:  Command \"pvk2pfx\" not found";
+  echo "Must install command via \"Windows WDK\" from: https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk";
+  echo -e "\n\n";
+  exit 1;
 else
 
-	WORKING_DIR="${HOME}/.pvk2pfx";
+  WORKING_DIR="${HOME}/.pvk2pfx";
 
-	mkdir -p "${WORKING_DIR}";
-	chmod 0700 "${WORKING_DIR}";
-	cd "${WORKING_DIR}";
+  mkdir -p "${WORKING_DIR}";
+  chmod 0700 "${WORKING_DIR}";
+  cd "${WORKING_DIR}";
 
-	# Convert PFX to PEM
-	openssl.exe pkcs12 -in "$1" -nocerts -out "$1.pem"
+  # Convert PFX to PEM
+  openssl.exe pkcs12 -in "$1" -nocerts -out "$1.pem"
 
-	# Convert the PEM-formatted private key into the PVK format:
-	# pvk.exe -in "$1.pem" -topvk -strong -out "$1.pvk"
+  # Convert the PEM-formatted private key into the PVK format:
+  # pvk.exe -in "$1.pem" -topvk -strong -out "$1.pvk"
   openssl rsa -in "$1.pem" -outform PVK -pvk-strong -out "$1.pvk"
 
-	# Combine the PVK and SPC into PFX:
-	echo -e "\n\n";
-	read -s -p "Enter OLD certificate encryption passphase:  " -n 1 -t 60 -r; OLD_PASS="${REPLY}"; REPLY="";
-	echo -e "\n\n";
-	read -s -p "Enter NEW certificate encryption passphase:  " -n 1 -t 60 -r; NEW_PASS="${REPLY}"; REPLY="";
-	echo -e "\n\n";
-	CERT_PASS="${REPLY}"; REPLY="";
-	mv -f "$1" "$1.$(date +'%Y%m%d_%H%M%S').old";
-	pvk2pfx.exe -pvk "$1.pvk" -pi "${OLD_PASS}" -spc "$2" -pfx "$1" -po "${NEW_PASS}" -f
+  # Combine the PVK and SPC into PFX:
+  echo -e "\n\n";
+  read -s -p "Enter OLD certificate encryption passphase:  " -n 1 -t 60 -r; OLD_PASS="${REPLY}"; REPLY="";
+  echo -e "\n\n";
+  read -s -p "Enter NEW certificate encryption passphase:  " -n 1 -t 60 -r; NEW_PASS="${REPLY}"; REPLY="";
+  echo -e "\n\n";
+  CERT_PASS="${REPLY}"; REPLY="";
+  mv -f "$1" "$1.$(date +'%Y%m%d_%H%M%S').old";
+  pvk2pfx.exe -pvk "$1.pvk" -pi "${OLD_PASS}" -spc "$2" -pfx "$1" -po "${NEW_PASS}" -f
 
 fi;
 
diff --git a/usr/local/bin/openssl_show_cert_info b/usr/local/bin/openssl_show_cert_info
--- a/usr/local/bin/openssl_show_cert_info
+++ b/usr/local/bin/openssl_show_cert_info
@@ -10,13 +10,13 @@ echo -e "\n\n";
 
 if [ -z "$1" ] || [ ! -f "$1" ]; then
 
-	echo "  Error:  First argument (\$1) must contain the filepath of the certificate to show information-of";
+  echo "  Error:  First argument (\$1) must contain the filepath of the certificate to show information-of";
 
 else
 
-	openssl x509 -in "${1}" -text -noout;
+  openssl x509 -in "${1}" -text -noout;
 
-	EXIT_CODE=$?;
+  EXIT_CODE=$?;
 
 fi;
 
diff --git a/usr/local/bin/openssl_test_host_ciphers b/usr/local/bin/openssl_test_host_ciphers
--- a/usr/local/bin/openssl_test_host_ciphers
+++ b/usr/local/bin/openssl_test_host_ciphers
@@ -1,38 +1,38 @@
 #!/usr/bin/env bash
 
 if [ $(which sslscan 2>'/dev/null' | wc -l;) -eq 0 ]; then # Install package "sslscan"
-	if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
+  if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
     apt-get -y update; apt-get -y install sslscan;
-	fi;
+  fi;
 fi;
 
 if [ $(which sslscan 2>'/dev/null' | wc -l;) -eq 0 ]; then
-	echo "";
-	echo "  Please retry this script on a Debian-based Linux distro (Debian, Ubuntu, Raspbian, etc.)";
-	echo "";
-	echo "  Requierd package not found: \"sslscan\"";
-	echo "  Exiting...";
-	exit 1;
+  echo "";
+  echo "  Please retry this script on a Debian-based Linux distro (Debian, Ubuntu, Raspbian, etc.)";
+  echo "";
+  echo "  Requierd package not found: \"sslscan\"";
+  echo "  Exiting...";
+  exit 1;
 else
-	# OpenSSL requires the port number
-	SERVER="";
-	if [ -z "$1" ]; then
+  # OpenSSL requires the port number
+  SERVER="";
+  if [ -z "$1" ]; then
     echo "";
     read -p "HTTP host to test: " -t 60 -r;
     SERVER="${REPLY}";
-	else
+  else
     SERVER="$1";
-	fi;
-	DELAY=1;
+  fi;
+  DELAY=1;
 
-	sslscan "${SERVER}";
+  sslscan "${SERVER}";
 
-	exit;
+  exit;
 
-	ciphers=$(openssl ciphers 'ALL:eNULL' | sed -e 's/:/ /g');
-	echo "Obtaining cipher list from $(openssl version)...";
+  ciphers=$(openssl ciphers 'ALL:eNULL' | sed -e 's/:/ /g');
+  echo "Obtaining cipher list from $(openssl version)...";
 
-	for cipher in ${ciphers[@]}
+  for cipher in ${ciphers[@]}
     do
     echo -n Testing $cipher...
     result=$(echo -n | openssl s_client -cipher "$cipher" -connect $SERVER 2>&1)
@@ -48,6 +48,6 @@ else
       fi;
     fi;
     sleep $DELAY;
-	done;
+  done;
 
 fi;
diff --git a/usr/local/bin/port_sniffer b/usr/local/bin/port_sniffer
--- a/usr/local/bin/port_sniffer
+++ b/usr/local/bin/port_sniffer
@@ -2,15 +2,15 @@
 
 EXIT_CODE=1;
 if [ -z "${1}" ]; then
-	echo "Error: Please specify a hostname or ip-address to detect open ports-on, such as [  ${0} example.com  ]"
-	exit 1;
+  echo "Error: Please specify a hostname or ip-address to detect open ports-on, such as [  ${0} example.com  ]"
+  exit 1;
 fi;
 
 if [ -z "$(which nmap 2>'/dev/null')" ]; then
-	echo "";
-	echo "Error: command \"nmap\" not found";
-	read -p " |-->  Install package \"nmap\", now? (y/n)   " -n 1 -t 60 -r; # Await single keypress
-	if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
+  echo "";
+  echo "Error: command \"nmap\" not found";
+  read -p " |-->  Install package \"nmap\", now? (y/n)   " -n 1 -t 60 -r; # Await single keypress
+  if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
     if [ -n "$(which apt-get 2>'/dev/null';)" ]; then
       sudo apt-get install -y "nmap";
     elif [ -n "$(which yum 2>'/dev/null';)" ]; then
@@ -18,10 +18,10 @@ if [ -z "$(which nmap 2>'/dev/null')" ]; then
     elif [ -n "$(which apk 2>'/dev/null';)" ]; then
       sudo apk install -y "nmap";
     fi;
-	fi;
+  fi;
 fi;
 
 
 if [ -n "$(which nmap 2>'/dev/null';)" ]; then
-	nmap -T Aggressive -A -v "${1}" -p 1-65535;
+  nmap -T Aggressive -A -v "${1}" -p 1-65535;
 fi;
diff --git a/usr/local/sbin/add_user b/usr/local/sbin/add_user
--- a/usr/local/sbin/add_user
+++ b/usr/local/sbin/add_user
@@ -29,73 +29,73 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 
 else
 
-	set -e; # Exit immediately if a command exits with a non-zero status
-	# set -x; # Print commands and their arguments as they are executed
+  set -e; # Exit immediately if a command exits with a non-zero status
+  # set -x; # Print commands and their arguments as they are executed
 
-	# If no username given, ask terminal user for username
-	while [ -z "${USER_NAME}" ]; do
+  # If no username given, ask terminal user for username
+  while [ -z "${USER_NAME}" ]; do
     echo "";
     read -p " Create a user with what username?   " -t 60 -r;
     USER_NAME="${REPLY}";
     if [ -n "${USER_NAME}" ]; then
       break;
     fi;
-	done;
+  done;
 
-	ROLLBACK_IFS="${IFS}";
-	IFS=' '; # Set the global delimiter
+  ROLLBACK_IFS="${IFS}";
+  IFS=' '; # Set the global delimiter
 
-	# USER_NAME="...";
-	# USER_UID="${USER_UID:-NEXT_AVAILABLE_ID}";
-	USER_GNAME="${USER_GNAME:-${USER_NAME}}";
-	# USER_GID="${USER_GID:-NEXT_AVAILABLE_ID}";
-	USER_SHELL="${USER_SHELL:-/bin/bash}";
+  # USER_NAME="...";
+  # USER_UID="${USER_UID:-NEXT_AVAILABLE_ID}";
+  USER_GNAME="${USER_GNAME:-${USER_NAME}}";
+  # USER_GID="${USER_GID:-NEXT_AVAILABLE_ID}";
+  USER_SHELL="${USER_SHELL:-/bin/bash}";
 
-	# User Directory-Info
-	DIR_USER_HOME="${DIR_USER_HOME:-/home/${USER_NAME}}";
-	DIR_USER_SSH="${DIR_USER_SSH:-${DIR_USER_HOME}/.ssh}";
-	
-	CREATE_HOME="${CREATE_HOME:-1}";
-	CREATE_HOME_SSH="${CREATE_HOME_SSH:-1}";
+  # User Directory-Info
+  DIR_USER_HOME="${DIR_USER_HOME:-/home/${USER_NAME}}";
+  DIR_USER_SSH="${DIR_USER_SSH:-${DIR_USER_HOME}/.ssh}";
+  
+  CREATE_HOME="${CREATE_HOME:-1}";
+  CREATE_HOME_SSH="${CREATE_HOME_SSH:-1}";
 
-	# Options - Password
-	SET_USER_PASSWORD="${SET_USER_PASSWORD:-0}";
+  # Options - Password
+  SET_USER_PASSWORD="${SET_USER_PASSWORD:-0}";
 
-	# Set the user as a System User (uses useradd's --system arg)
-	SET_SYSTEM_USER=${SET_SYSTEM_USER:-0};
+  # Set the user as a System User (uses useradd's --system arg)
+  SET_SYSTEM_USER=${SET_SYSTEM_USER:-0};
 
-	# Options - Sudo
-	ADD_USER_TO_SUDOERS="${ADD_USER_TO_SUDOERS:-0}";
-	SUDO_REQUIRES_PASS="${SUDO_REQUIRES_PASS:-1}";
+  # Options - Sudo
+  ADD_USER_TO_SUDOERS="${ADD_USER_TO_SUDOERS:-0}";
+  SUDO_REQUIRES_PASS="${SUDO_REQUIRES_PASS:-1}";
 
-	#	------------------------------------------------------------
-	#	   Values below are based off of the above values
-	# ------------------------------------------------------------
+  #	------------------------------------------------------------
+  #	   Values below are based off of the above values
+  # ------------------------------------------------------------
 
-	if [ -z "${USER_NAME}" ]; then
+  if [ -z "${USER_NAME}" ]; then
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  \$USER_NAME is empty/unset";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
     exit 1;
 
-	elif [ ${SET_SYSTEM_USER} -eq 1 ] && [ -v USER_UID ]; then
+  elif [ ${SET_SYSTEM_USER} -eq 1 ] && [ -v USER_UID ]; then
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Invalid argument combination: [ User ID ] & [ System User ]";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Best practice dictates that the system should allocate User IDs for System users";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
     exit 1;
 
-	elif [ ${SET_SYSTEM_USER} -eq 1 ] && [ -v USER_GID ]; then
+  elif [ ${SET_SYSTEM_USER} -eq 1 ] && [ -v USER_GID ]; then
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Invalid argument combination: [ Group ID ] & [ System User ]";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Best practice dictates that the system should allocate Group IDs for System users";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
     exit 1;
 
-	elif [[ -v USER_NAME ]] \
+  elif [[ -v USER_NAME ]] \
       && [[ -v USER_UID ]] \
       && [[ "${USER_UID}" =~ ^-?[0-9]+$ ]] \
       && [ "$(id -u ${USER_UID} >/dev/null 2>&1; echo $?;)" == "0" ] \
@@ -104,7 +104,7 @@ else
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
     exit 1;
 
-	elif [[ -v USER_GNAME ]] \
+  elif [[ -v USER_GNAME ]] \
       && [[ -v USER_GID ]] \
       && [[ "${USER_GID}" =~ ^-?[0-9]+$ ]] \
       && [ $(getent group ${USER_GID} >/dev/null 2>&1; echo $?;) -eq 0 ] \
@@ -113,13 +113,13 @@ else
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
     exit 1;
 
-	elif [ "${CREATE_HOME}" == "1" ] && [ -d "${DIR_USER_HOME}" ]; then
+  elif [ "${CREATE_HOME}" == "1" ] && [ -d "${DIR_USER_HOME}" ]; then
 
     echo "Home Directory already exists: \"${DIR_USER_HOME}\".";
     echo "If you still want to use this directory, set \$CREATE_HOME to \"0\" and re-run this script.";
     exit 1;
 
-	else
+  else
 
     # ------------------------------------------------------------
     # GROUP-CREATION
@@ -238,8 +238,8 @@ else
 
     exit 0;
 
-	fi;
+  fi;
 
-	IFS="${ROLLBACK_IFS}"; # Restore the global delimiter
+  IFS="${ROLLBACK_IFS}"; # Restore the global delimiter
 
 fi;
diff --git a/usr/local/sbin/archive_logs b/usr/local/sbin/archive_logs
--- a/usr/local/sbin/archive_logs
+++ b/usr/local/sbin/archive_logs
@@ -29,26 +29,26 @@ fi;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	SERVICE_NAME="httpd";
-	GLOB_PATTERN="*_log-*";
-	DIR_LOGS="/var/log";
-	DIR_ARCH="/var/archived_logs";
+  SERVICE_NAME="httpd";
+  GLOB_PATTERN="*_log-*";
+  DIR_LOGS="/var/log";
+  DIR_ARCH="/var/archived_logs";
 
-	if [ ! -d "${DIR_LOGS}/${SERVICE_NAME}" ]; then
+  if [ ! -d "${DIR_LOGS}/${SERVICE_NAME}" ]; then
     echo "";
     echo "ERROR:";
     echo "  Logs-dir not found for service \"${SERVICE_NAME}\" at path \"${DIR_LOGS}/${SERVICE_NAME}\" ";
     echo "";
     exit 1;
-	
+  
 
-	elif [ ! -h "${DIR_ARCH}" ]; then
+  elif [ ! -h "${DIR_ARCH}" ]; then
 
     echo "";
     echo "ERROR:";
@@ -60,7 +60,7 @@ else
     echo "";
     exit 1;
 
-	else
+  else
 
     # Stop the target service
     /usr/sbin/service "${SERVICE_NAME}" stop; RET_CODE=$?;
@@ -101,6 +101,6 @@ else
 
     fi;
 
-	fi;
+  fi;
 
 fi;
diff --git a/usr/local/sbin/certbot_add_wildcard b/usr/local/sbin/certbot_add_wildcard
--- a/usr/local/sbin/certbot_add_wildcard
+++ b/usr/local/sbin/certbot_add_wildcard
@@ -25,19 +25,19 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# 
-	# Use $1 as domain name for wildcard cert
-	#
-	if [ -z "$1" ]; then
+  # ------------------------------------------------------------
+  # 
+  # Use $1 as domain name for wildcard cert
+  #
+  if [ -z "$1" ]; then
     echo "";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Missing domain name - Please try again using first argument (\$1) as domain name";
     exit 1;
-	else
+  else
     DOMAIN_NAME="$1";
     if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
       echo "";
@@ -80,7 +80,7 @@ else
       # echo "Info:  Calling [ certbot certonly --manual --manual-public-ip-logging-ok --server https://acme-v02.api.letsencrypt.org/directory --preferred-challenges dns-01 -d \"${DOMAIN_NAME}\" -d \"*.${DOMAIN_NAME}\"; certbot certificates -d \"${DOMAIN_NAME}\"; test -x \"/usr/local/sbin/reload_nginx\" && /usr/local/sbin/reload_nginx; ]...";
       # certbot certonly --manual --manual-public-ip-logging-ok --server https://acme-v02.api.letsencrypt.org/directory --preferred-challenges dns-01 -d "${DOMAIN_NAME}" -d "*.${DOMAIN_NAME}"; certbot certificates -d "${DOMAIN_NAME}"; test -x "/usr/local/sbin/reload_nginx" && /usr/local/sbin/reload_nginx;
     fi;
-	fi;
+  fi;
 fi;
 
 
diff --git a/usr/local/sbin/certbot_renew_all b/usr/local/sbin/certbot_renew_all
--- a/usr/local/sbin/certbot_renew_all
+++ b/usr/local/sbin/certbot_renew_all
@@ -25,13 +25,13 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Require that certbot be installed, already
-	if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+  # ------------------------------------------------------------
+  # Require that certbot be installed, already
+  if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
     # ------------------------------------------------------------
     if [ -n "$1" ] && [ "$1" == "-y" || "$1" == "--yes" || "$1" == "--force" ]; then
       # Allow a force-command to skip dry-run mode
@@ -48,7 +48,7 @@ else
     if [ -x "/usr/local/sbin/reload_nginx" ]; then
       /usr/local/sbin/reload_nginx;
     fi;
-	else
+  else
     # ------------------------------------------------------------
     # Error - certbot command not command
     echo "";
@@ -57,7 +57,7 @@ else
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Please install certbot, then re-run this script";
     echo "";
     exit 1;
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/certbot_renew_wildcard b/usr/local/sbin/certbot_renew_wildcard
--- a/usr/local/sbin/certbot_renew_wildcard
+++ b/usr/local/sbin/certbot_renew_wildcard
@@ -25,17 +25,17 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	#
-	# !!! REDIRECT TO "certbot_add_wildcard" RUNTIME !!!
-	#      |
-	#      |--> As-of June, 2020 due to certbot not offering any pure-backend methods of simplified wildcard certificate renewal (which can easily automated via a cron-job, etc. without needing to contact other services' additional APIs separately afterwards, etc. (possible for sure just not all packaged nicely through certbot, yet))
-	#           |
-	#           |--> e.g. you have to just recreate the wildcard certificate to renew it
-	#
-	DL="${HOME}"; if [ -w "/usr/local/sbin" ]; then DL="/usr/local/sbin"; fi; RUNSSL="${DL}/certbot_add_wildcard"; if [ ! -x "${RUNSSL}" ]; then wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/certbot_add_wildcard" -O "${RUNSSL}" -q; chmod 0755 "${RUNSSL}"; fi; ${RUNSSL} "${1}"; test -x /usr/local/sbin/reload_nginx && /usr/local/sbin/reload_nginx;
+  #
+  # !!! REDIRECT TO "certbot_add_wildcard" RUNTIME !!!
+  #      |
+  #      |--> As-of June, 2020 due to certbot not offering any pure-backend methods of simplified wildcard certificate renewal (which can easily automated via a cron-job, etc. without needing to contact other services' additional APIs separately afterwards, etc. (possible for sure just not all packaged nicely through certbot, yet))
+  #           |
+  #           |--> e.g. you have to just recreate the wildcard certificate to renew it
+  #
+  DL="${HOME}"; if [ -w "/usr/local/sbin" ]; then DL="/usr/local/sbin"; fi; RUNSSL="${DL}/certbot_add_wildcard"; if [ ! -x "${RUNSSL}" ]; then wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/certbot_add_wildcard" -O "${RUNSSL}" -q; chmod 0755 "${RUNSSL}"; fi; ${RUNSSL} "${1}"; test -x /usr/local/sbin/reload_nginx && /usr/local/sbin/reload_nginx;
 fi;
 
diff --git a/usr/local/sbin/create_ssl_directory b/usr/local/sbin/create_ssl_directory
--- a/usr/local/sbin/create_ssl_directory
+++ b/usr/local/sbin/create_ssl_directory
@@ -32,12 +32,12 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 
-	if [ -z "${1}" ] || [ -z "${2}" ] || [ -z "${3}" ]; then
+  if [ -z "${1}" ] || [ -z "${2}" ] || [ -z "${3}" ]; then
     echo "";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Must call [ create_ssl_directory ] with two arguments:";
     echo "  \$1:  The DNS signing authority for given certificate(s), such as 'letsencrypt' or 'godaddy'";
@@ -46,7 +46,7 @@ else
     echo "";
     exit 1;
 
-	else
+  else
 
     DNS_AUTHORITY="$1";
     DOMAIN_NAME="$2";
@@ -82,11 +82,11 @@ else
     echo "------------------------------------------------------------";
     echo "";
 
-	fi;
+  fi;
 
-	if [ -n "$(which reload_nginx 2>'/dev/null';)" ]; then
+  if [ -n "$(which reload_nginx 2>'/dev/null';)" ]; then
     reload_nginx;
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/ddns_ufw_update b/usr/local/sbin/ddns_ufw_update
--- a/usr/local/sbin/ddns_ufw_update
+++ b/usr/local/sbin/ddns_ufw_update
@@ -26,86 +26,86 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 
-	# LAN OVERRIDE
-	# add_rule "tcp" "22" "10.0.0.0/8";
-	# add_rule "tcp" "22" "172.16.0.0/12";
-	# add_rule "tcp" "22" "192.168.0.0/16";
-	# /usr/sbin/ufw allow proto tcp from 10.0.0.0/8 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
-	# /usr/sbin/ufw allow proto tcp from 172.16.0.0/12 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
-	# /usr/sbin/ufw allow proto tcp from 192.168.0.0/16 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
-	# exit 0;
+  # LAN OVERRIDE
+  # add_rule "tcp" "22" "10.0.0.0/8";
+  # add_rule "tcp" "22" "172.16.0.0/12";
+  # add_rule "tcp" "22" "192.168.0.0/16";
+  # /usr/sbin/ufw allow proto tcp from 10.0.0.0/8 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
+  # /usr/sbin/ufw allow proto tcp from 172.16.0.0/12 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
+  # /usr/sbin/ufw allow proto tcp from 192.168.0.0/16 to any port 22;  # Allow SSH (22) over LAN subnet (defined in RFC-1918)
+  # exit 0;
 
-	# ------------------------------------------------------------
-	# Declare runtime variable(s)
-	
-	shopt -s lastpipe; # extends the current shell into sub-shells (within piped-commands), sharing variables down-into them, as well
+  # ------------------------------------------------------------
+  # Declare runtime variable(s)
+  
+  shopt -s lastpipe; # extends the current shell into sub-shells (within piped-commands), sharing variables down-into them, as well
 
-	# Determine if running in debug-mode (increases verbosity-level of script's output, e.g. shows all info/notices/details/etc. and not just warnings/errors)
-	if [ -n "${DEBUG_MODE}" ] && [[ "${DEBUG_MODE}" =~ ^-?[0-9]+$ ]] && (("${DEBUG_MODE}" >= "1")); then
+  # Determine if running in debug-mode (increases verbosity-level of script's output, e.g. shows all info/notices/details/etc. and not just warnings/errors)
+  if [ -n "${DEBUG_MODE}" ] && [[ "${DEBUG_MODE}" =~ ^-?[0-9]+$ ]] && (("${DEBUG_MODE}" >= "1")); then
     DEBUG_MODE=1;
-	elif [ -n "${VERBOSITY}" ] && [[ "${VERBOSITY}" =~ ^-?[0-9]+$ ]] && (("${VERBOSITY}" >= "1")); then
+  elif [ -n "${VERBOSITY}" ] && [[ "${VERBOSITY}" =~ ^-?[0-9]+$ ]] && (("${VERBOSITY}" >= "1")); then
     DEBUG_MODE=1;
-	elif [ -n "${VERBOSE}" ] && [[ "${VERBOSE}" =~ ^-?[0-9]+$ ]] && (("${VERBOSE}" >= "1")); then
+  elif [ -n "${VERBOSE}" ] && [[ "${VERBOSE}" =~ ^-?[0-9]+$ ]] && (("${VERBOSE}" >= "1")); then
     DEBUG_MODE=1;
-	else
+  else
     DEBUG_MODE=0;
-	fi;
+  fi;
 
-	# Script's working-directory
-	DIRNAME_LOCAL_CONFIG="/etc/whitelist.d"; mkdir -p "${DIRNAME_LOCAL_CONFIG}";
+  # Script's working-directory
+  DIRNAME_LOCAL_CONFIG="/etc/whitelist.d"; mkdir -p "${DIRNAME_LOCAL_CONFIG}";
 
-	# Config pulled-in by UFW (sets default values to block/allow/etc. and more)
-	UFW_CONFIG_FILEPATH="/etc/default/ufw";
+  # Config pulled-in by UFW (sets default values to block/allow/etc. and more)
+  UFW_CONFIG_FILEPATH="/etc/default/ufw";
 
-	# File containing hosts to allow through UFW
-	#  |
-	#  |--> All lines in given whitelist file must be in a specific format/syntax
-	#  |
-	#  |--> Syntax:
-	#  |        [tcp/udp]:[PORT]:[FQDN]
-	#  |
-	#  |
-	#  |--> Example:
-	#           tcp:22:demo.example.com
-	#           tcp:22:localhost.localdomain
-	#
-	unset RUNTIME_SERVICE_USERS; declare -A RUNTIME_SERVICE_USERS; # [Re-]Instantiate bash array
-	RUNTIME_SERVICE_USERS+=(["sshd"]="root");       # SSH/OpenSSH listener
-	RUNTIME_SERVICE_USERS+=(["nginx"]="www-data");  # NGINX Web Server
-	RUNTIME_SERVICE_USERS+=(["unifi"]="unifi");  # Unifi Controller
-	# RUNTIME_SERVICE_USERS+=(["jenkins"]="jenkins");    # Jenkins Master
+  # File containing hosts to allow through UFW
+  #  |
+  #  |--> All lines in given whitelist file must be in a specific format/syntax
+  #  |
+  #  |--> Syntax:
+  #  |        [tcp/udp]:[PORT]:[FQDN]
+  #  |
+  #  |
+  #  |--> Example:
+  #           tcp:22:demo.example.com
+  #           tcp:22:localhost.localdomain
+  #
+  unset RUNTIME_SERVICE_USERS; declare -A RUNTIME_SERVICE_USERS; # [Re-]Instantiate bash array
+  RUNTIME_SERVICE_USERS+=(["sshd"]="root");       # SSH/OpenSSH listener
+  RUNTIME_SERVICE_USERS+=(["nginx"]="www-data");  # NGINX Web Server
+  RUNTIME_SERVICE_USERS+=(["unifi"]="unifi");  # Unifi Controller
+  # RUNTIME_SERVICE_USERS+=(["jenkins"]="jenkins");    # Jenkins Master
 
-	# Defaults for UFW (out-of-the-box)
-	ETC_NGINX="/etc/nginx";
-	NGINX_CONF_DDNS="${ETC_NGINX}/conf.ddns";
+  # Defaults for UFW (out-of-the-box)
+  ETC_NGINX="/etc/nginx";
+  NGINX_CONF_DDNS="${ETC_NGINX}/conf.ddns";
 
-	# Create the DDNS NGINX directory only if the NGINX parent directory already exists
-	if [ -d "${ETC_NGINX}" ] && [ ! -d "${NGINX_CONF_DDNS}" ]; then
+  # Create the DDNS NGINX directory only if the NGINX parent directory already exists
+  if [ -d "${ETC_NGINX}" ] && [ ! -d "${NGINX_CONF_DDNS}" ]; then
     mkdir -p "${NGINX_CONF_DDNS}";
-	fi;
+  fi;
 
-	# Defaults for UFW (out-of-the-box)
-	UFW_OUT_OF_THE_BOX_DEFAULTS="Default: deny (incoming), allow (outgoing), disabled (routed)";
-
-
-	# ------------------------------------------------------------
-	#
-	# Sub-Function: Takes first argument ($1) as a SINGLE-CHARACTER delimiter, combines all remaining arguments ($2,$3,...,$n) into a string delimited by aforementioned delimiter ($1)
-	#
-	function implode { local IFS="$1"; shift; echo "$*"; }
+  # Defaults for UFW (out-of-the-box)
+  UFW_OUT_OF_THE_BOX_DEFAULTS="Default: deny (incoming), allow (outgoing), disabled (routed)";
 
 
-	# ------------------------------------------------------------
-	#
-	# Sub-Function: Adds a rule to UFW
-	#
-	ADD_RULE_SKIPPED=0;
-	add_rule() {
+  # ------------------------------------------------------------
+  #
+  # Sub-Function: Takes first argument ($1) as a SINGLE-CHARACTER delimiter, combines all remaining arguments ($2,$3,...,$n) into a string delimited by aforementioned delimiter ($1)
+  #
+  function implode { local IFS="$1"; shift; echo "$*"; }
+
+
+  # ------------------------------------------------------------
+  #
+  # Sub-Function: Adds a rule to UFW
+  #
+  ADD_RULE_SKIPPED=0;
+  add_rule() {
     if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
       local proto=$1;
       local port=$2;
@@ -142,15 +142,15 @@ else
         echo "            |-->  ADD_RULE_SKIPPED = [ ${ADD_RULE_SKIPPED} ]";
       fi;
     fi;
-	}
+  }
 
 
-	# ------------------------------------------------------------
-	#
-	# Sub-Function: Deletes a rule from UFW
-	#
-	DELETE_RULE_SKIPPED=0;
-	delete_rule() {
+  # ------------------------------------------------------------
+  #
+  # Sub-Function: Deletes a rule from UFW
+  #
+  DELETE_RULE_SKIPPED=0;
+  delete_rule() {
     if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
       local proto=$1;
       local port=$2;
@@ -188,14 +188,14 @@ else
         echo "            |-->  DELETE_RULE_SKIPPED = [ ${DELETE_RULE_SKIPPED} ]";
       fi;
     fi;
-	}
+  }
 
 
-	# ------------------------------------------------------------
-	#
-	# Main Runtime
-	#
-	if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
+  # ------------------------------------------------------------
+  #
+  # Main Runtime
+  #
+  if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
     if [ -f "${UFW_CONFIG_FILEPATH}" ]; then
       
       # Set UFW Defaults --> Incoming Requests
@@ -229,27 +229,27 @@ else
       fi;
 
     fi;
-	fi;
+  fi;
 
-	# Array to store store CIDRv4 addresses which are newly-resolved as-of this script's runtime
-	unset RESOLVED_CIDRv4_ARR; declare -A RESOLVED_CIDRv4_ARR; # [Re-]Instantiate bash array
-	
-	unset RESOLVED_CIDRv4_1D; declare -a RESOLVED_CIDRv4_1D; # [Re-]Instantiate bash array
-	unset RESOLVED_HOSTS_1D; declare -a RESOLVED_HOSTS_1D; # [Re-]Instantiate bash array
-	unset RESOLVED_IPv4_1D; declare -a RESOLVED_IPv4_1D; # [Re-]Instantiate bash array
-	unset RESOLVED_PORTS_1D; declare -a RESOLVED_PORTS_1D; # [Re-]Instantiate bash array
-	unset RESOLVED_PROTOS_1D; declare -a RESOLVED_PROTOS_1D; # [Re-]Instantiate bash array
+  # Array to store store CIDRv4 addresses which are newly-resolved as-of this script's runtime
+  unset RESOLVED_CIDRv4_ARR; declare -A RESOLVED_CIDRv4_ARR; # [Re-]Instantiate bash array
+  
+  unset RESOLVED_CIDRv4_1D; declare -a RESOLVED_CIDRv4_1D; # [Re-]Instantiate bash array
+  unset RESOLVED_HOSTS_1D; declare -a RESOLVED_HOSTS_1D; # [Re-]Instantiate bash array
+  unset RESOLVED_IPv4_1D; declare -a RESOLVED_IPv4_1D; # [Re-]Instantiate bash array
+  unset RESOLVED_PORTS_1D; declare -a RESOLVED_PORTS_1D; # [Re-]Instantiate bash array
+  unset RESOLVED_PROTOS_1D; declare -a RESOLVED_PROTOS_1D; # [Re-]Instantiate bash array
 
-	# HOTFIX (TO-REMOVE-AFTER-2020-05-01) - Cleanup ddns double-deep (duplicated) depth directory
-	if [ -d "/etc/nginx/conf.ddns/conf.ddns" ]; then
+  # HOTFIX (TO-REMOVE-AFTER-2020-05-01) - Cleanup ddns double-deep (duplicated) depth directory
+  if [ -d "/etc/nginx/conf.ddns/conf.ddns" ]; then
     rm -rf "/etc/nginx/conf.ddns/conf.ddns";
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
-	#
-	# Apply Whitelist on a per-service basis
-	#
-	for EACH_SERVICE_NAME in "${!RUNTIME_SERVICE_USERS[@]}"; do
+  # ------------------------------------------------------------
+  #
+  # Apply Whitelist on a per-service basis
+  #
+  for EACH_SERVICE_NAME in "${!RUNTIME_SERVICE_USERS[@]}"; do
 
     # File containing hosts to allow through UFW
     #  |--> All lines in given whitelist file must be in a specific format/syntax
@@ -496,57 +496,57 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
       echo -e "Info:  Calling  [ echo -e \"${NGINX_DDNS_RESULTS}\" > \"${NGINX_DDNS_CONF}\" ]...";
       echo -e "${NGINX_DDNS_RESULTS}" > "${NGINX_DDNS_CONF}";
     fi;
-	
-	done;
+  
+  done;
 
-	# Array containing rules deleted from UFW
-	unset UFW_CHANGES_UNDO_ARR; declare -A UFW_CHANGES_UNDO_ARR; # [Re-]Instantiate bash array
+  # Array containing rules deleted from UFW
+  unset UFW_CHANGES_UNDO_ARR; declare -A UFW_CHANGES_UNDO_ARR; # [Re-]Instantiate bash array
 
-	# Foreach on resolved (valid) CIDRv4 addresses
-	if [ ${DEBUG_MODE} -eq 1 ]; then
+  # Foreach on resolved (valid) CIDRv4 addresses
+  if [ ${DEBUG_MODE} -eq 1 ]; then
     echo "************************************************************";
     echo "Debug:  !RESOLVED_CIDRv4_ARR[@] = [ ${!RESOLVED_CIDRv4_ARR[@]} ]";
     echo "Debug:  RESOLVED_CIDRv4_ARR[@] = [ ${RESOLVED_CIDRv4_ARR[@]} ]";
-	fi;
+  fi;
 
-	# for EACH_RESOLVED_CIDRv4 in "${!RESOLVED_CIDRv4_ARR[@]}"; do
-	# 	EACH_RESOLVED_IPv4="$(echo "${EACH_RESOLVED_CIDRv4}" | cut -d'/' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
-	# 	EACH_PORT_PROTO_W_COMMAS="${RESOLVED_CIDRv4_ARR[${EACH_RESOLVED_CIDRv4}]}";
-	# 	RESOLVED_PORT_PROTO_KEYS_COMMAS_TO_SPACES=($(echo "${EACH_PORT_PROTO_W_COMMAS}" | tr ',' ' '));
-	# 	RESOLVED_PORT_PROTO_KEYS_NO_DUPES=($(echo "${RESOLVED_PORT_PROTO_KEYS_COMMAS_TO_SPACES[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
-	# 	if [ ${DEBUG_MODE} -eq 1 ]; then
-	# 		echo "** Debug:  RESOLVED_CIDRv4_ARR[${EACH_RESOLVED_CIDRv4}] = [ ${EACH_PORT_PROTO_W_COMMAS} ]";
-	# 		echo "Debug:  EACH_RESOLVED_CIDRv4 = [ ${EACH_RESOLVED_CIDRv4} ]";
-	# 		echo "Debug:  EACH_RESOLVED_IPv4 = [ ${EACH_RESOLVED_IPv4} ]";
-	# 		echo "Debug:  EACH_PORT_PROTO_W_COMMAS = [ ${EACH_PORT_PROTO_W_COMMAS} ]";
-	# 		echo "Debug:  RESOLVED_PORT_PROTO_KEYS_COMMAS_TO_SPACES[@] = [ ${RESOLVED_PORT_PROTO_KEYS_COMMAS_TO_SPACES[@]} ]";
-	# 		echo "Debug:  RESOLVED_PORT_PROTO_KEYS_NO_DUPES[@] = [ ${RESOLVED_PORT_PROTO_KEYS_NO_DUPES[@]} ]";
-	# 	fi;
-	# 	for EACH_RESOLVED_PORT_PROTO in "${RESOLVED_PORT_PROTO_KEYS_NO_DUPES[@]}"; do
-	# 		EACH_RESOLVED_PORT="$(echo "${EACH_RESOLVED_PORT_PROTO}" | cut -d'/' -f1)";
-	# 		EACH_RESOLVED_PROTO="$(echo "${EACH_RESOLVED_PORT_PROTO}" | cut -d'/' -f2)";
-	# 		if [ ${DEBUG_MODE} -eq 1 ]; then
-	# 			echo "-- Debug:  EACH_RESOLVED_PORT_PROTO = [ ${EACH_RESOLVED_PORT_PROTO} ]";
-	# 			echo "Debug:  EACH_RESOLVED_PORT = [ ${EACH_RESOLVED_PORT} ]";
-	# 			echo "Debug:  EACH_RESOLVED_PROTO = [ ${EACH_RESOLVED_PROTO} ]";
-	# 		fi;
-	# 		# !!!  ADD THE NEW IPv4 TO FIREWALL'S WHITELIST  !!!
-	# 		if [ ${DEBUG_MODE} -eq 1 ]; then
-	# 			echo "Debug:  Calling  [ add_rule \"${EACH_RESOLVED_PROTO}\" \"${EACH_RESOLVED_PORT}\" \"${EACH_RESOLVED_CIDRv4}\" ]...";
-	# 		fi;
-	# 		ADD_RULE_SKIPPED=0;
-	# 		add_rule "${EACH_RESOLVED_PROTO}" "${EACH_RESOLVED_PORT}" "${EACH_RESOLVED_CIDRv4}";
-	# 		if [ ${ADD_RULE_SKIPPED} -eq 0 ]; then
-	# 			# Add the inverse of new rule to the undo-changes array
-	# 			UFW_CHANGES_UNDO_ARR+=(["/usr/sbin/ufw delete allow proto ${EACH_RESOLVED_PROTO} from ${EACH_RESOLVED_CIDRv4} to any port ${EACH_RESOLVED_PORT};"]="");
-	# 		fi;
-	# 	done;
-	# done;
+  # for EACH_RESOLVED_CIDRv4 in "${!RESOLVED_CIDRv4_ARR[@]}"; do
+  # 	EACH_RESOLVED_IPv4="$(echo "${EACH_RESOLVED_CIDRv4}" | cut -d'/' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
+  # 	EACH_PORT_PROTO_W_COMMAS="${RESOLVED_CIDRv4_ARR[${EACH_RESOLVED_CIDRv4}]}";
+  # 	RESOLVED_PORT_PROTO_KEYS_COMMAS_TO_SPACES=($(echo "${EACH_PORT_PROTO_W_COMMAS}" | tr ',' ' '));
+  # 	RESOLVED_PORT_PROTO_KEYS_NO_DUPES=($(echo "${RESOLVED_PORT_PROTO_KEYS_COMMAS_TO_SPACES[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
+  # 	if [ ${DEBUG_MODE} -eq 1 ]; then
+  # 		echo "** Debug:  RESOLVED_CIDRv4_ARR[${EACH_RESOLVED_CIDRv4}] = [ ${EACH_PORT_PROTO_W_COMMAS} ]";
+  # 		echo "Debug:  EACH_RESOLVED_CIDRv4 = [ ${EACH_RESOLVED_CIDRv4} ]";
+  # 		echo "Debug:  EACH_RESOLVED_IPv4 = [ ${EACH_RESOLVED_IPv4} ]";
+  # 		echo "Debug:  EACH_PORT_PROTO_W_COMMAS = [ ${EACH_PORT_PROTO_W_COMMAS} ]";
+  # 		echo "Debug:  RESOLVED_PORT_PROTO_KEYS_COMMAS_TO_SPACES[@] = [ ${RESOLVED_PORT_PROTO_KEYS_COMMAS_TO_SPACES[@]} ]";
+  # 		echo "Debug:  RESOLVED_PORT_PROTO_KEYS_NO_DUPES[@] = [ ${RESOLVED_PORT_PROTO_KEYS_NO_DUPES[@]} ]";
+  # 	fi;
+  # 	for EACH_RESOLVED_PORT_PROTO in "${RESOLVED_PORT_PROTO_KEYS_NO_DUPES[@]}"; do
+  # 		EACH_RESOLVED_PORT="$(echo "${EACH_RESOLVED_PORT_PROTO}" | cut -d'/' -f1)";
+  # 		EACH_RESOLVED_PROTO="$(echo "${EACH_RESOLVED_PORT_PROTO}" | cut -d'/' -f2)";
+  # 		if [ ${DEBUG_MODE} -eq 1 ]; then
+  # 			echo "-- Debug:  EACH_RESOLVED_PORT_PROTO = [ ${EACH_RESOLVED_PORT_PROTO} ]";
+  # 			echo "Debug:  EACH_RESOLVED_PORT = [ ${EACH_RESOLVED_PORT} ]";
+  # 			echo "Debug:  EACH_RESOLVED_PROTO = [ ${EACH_RESOLVED_PROTO} ]";
+  # 		fi;
+  # 		# !!!  ADD THE NEW IPv4 TO FIREWALL'S WHITELIST  !!!
+  # 		if [ ${DEBUG_MODE} -eq 1 ]; then
+  # 			echo "Debug:  Calling  [ add_rule \"${EACH_RESOLVED_PROTO}\" \"${EACH_RESOLVED_PORT}\" \"${EACH_RESOLVED_CIDRv4}\" ]...";
+  # 		fi;
+  # 		ADD_RULE_SKIPPED=0;
+  # 		add_rule "${EACH_RESOLVED_PROTO}" "${EACH_RESOLVED_PORT}" "${EACH_RESOLVED_CIDRv4}";
+  # 		if [ ${ADD_RULE_SKIPPED} -eq 0 ]; then
+  # 			# Add the inverse of new rule to the undo-changes array
+  # 			UFW_CHANGES_UNDO_ARR+=(["/usr/sbin/ufw delete allow proto ${EACH_RESOLVED_PROTO} from ${EACH_RESOLVED_CIDRv4} to any port ${EACH_RESOLVED_PORT};"]="");
+  # 		fi;
+  # 	done;
+  # done;
 
-	# Determine which rules to keep and which to remove from existing ruleset
-	RULESET_UFW="$(ufw status | sed /^To*/d | sed /^Status*/d | sed /^--*/d | grep '\S';)";
-	ROLLBACK_IFS="${IFS}"; IFS=$'\n';
-	for EACH_UFW_LINE in ${RULESET_UFW}; do
+  # Determine which rules to keep and which to remove from existing ruleset
+  RULESET_UFW="$(ufw status | sed /^To*/d | sed /^Status*/d | sed /^--*/d | grep '\S';)";
+  ROLLBACK_IFS="${IFS}"; IFS=$'\n';
+  for EACH_UFW_LINE in ${RULESET_UFW}; do
     EACH_UFW_CIDRv4="$(echo "${EACH_UFW_LINE}" | awk '{print $3}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
     EACH_UFW_IPv4=$(echo ${EACH_UFW_CIDRv4} | cut -d"/" -f1);
     EACH_UFW_PORT="$(echo "${EACH_UFW_LINE}" | awk '{print $1}' | cut -d'/' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
@@ -650,41 +650,41 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
         echo "Debug:  Keeping existing rule [ ${EACH_UFW_LINE} ] - matched by [ CIDRv4 + Port + Proto ] combination to resolved values";
       fi;
     fi;
-	done;
-	IFS="${ROLLBACK_IFS}";
+  done;
+  IFS="${ROLLBACK_IFS}";
 
-	# Show all undo-commands for this runtime
-	echo "------------------------------------------------------------";
-	echo "----------------------  UNDO COMMANDS  ---------------------";
-	echo " !!  To undo any of the changes-made, please see below  !!  ";
-	echo " !!    list of undo-commands created for this session   !!  ";
-	echo "";
-	for EACH_UNDO_COMMAND in "${!UFW_CHANGES_UNDO_ARR[@]}"; do
+  # Show all undo-commands for this runtime
+  echo "------------------------------------------------------------";
+  echo "----------------------  UNDO COMMANDS  ---------------------";
+  echo " !!  To undo any of the changes-made, please see below  !!  ";
+  echo " !!    list of undo-commands created for this session   !!  ";
+  echo "";
+  for EACH_UNDO_COMMAND in "${!UFW_CHANGES_UNDO_ARR[@]}"; do
     echo "${EACH_UNDO_COMMAND}";
-	done;
-	echo "------------------------------------------------------------";
-	echo "------------------------  UFW STATUS  ----------------------";
-	/bin/systemctl status ufw;
-	echo "------------------------------------------------------------";
+  done;
+  echo "------------------------------------------------------------";
+  echo "------------------------  UFW STATUS  ----------------------";
+  /bin/systemctl status ufw;
+  echo "------------------------------------------------------------";
 
-	# Cleanup log files outside of the retention-policy's max-age
-	if [ -z "${LOGDIR}" ]; then
+  # Cleanup log files outside of the retention-policy's max-age
+  if [ -z "${LOGDIR}" ]; then
     LOGDIR="/var/log/ddns_ufw_update";
-	fi;
-	if [ -d "${LOGDIR}" ]; then
+  fi;
+  if [ -d "${LOGDIR}" ]; then
     # MAX_RETENTION_DAYS=14;
     # find "${LOGDIR}" -type f -mtime +${MAX_RETENTION_DAYS} -exec rm -- "{}" ";";
     echo -e "\n""Info:  Cleaning logs older than 14 days old from directory \"${LOGDIR}\"";
     find "${LOGDIR}" -type f -mtime +14 -exec rm -- '{}' \;;
-	fi;
+  fi;
 
 
-	# Set ownership & privileges for the logging directory & its sub contents
-	if [ $(id "syslog" 1>/dev/null 2>&1; echo $?;) -eq 0 ] && [ $(groups "adm" 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
+  # Set ownership & privileges for the logging directory & its sub contents
+  if [ $(id "syslog" 1>/dev/null 2>&1; echo $?;) -eq 0 ] && [ $(groups "adm" 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
     chown -R "syslog:adm" "${LOGDIR}";
-	fi;
-	find "${LOGDIR}" -type d -print0 | xargs -0 chmod 0750; # directories 
-	find "${LOGDIR}" -type f -print0 | xargs -0 chmod 0640; # files
+  fi;
+  find "${LOGDIR}" -type d -print0 | xargs -0 chmod 0750; # directories 
+  find "${LOGDIR}" -type f -print0 | xargs -0 chmod 0640; # files
 
 fi;
 
diff --git a/usr/local/sbin/disable_ipv6 b/usr/local/sbin/disable_ipv6
--- a/usr/local/sbin/disable_ipv6
+++ b/usr/local/sbin/disable_ipv6
@@ -22,74 +22,74 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	CONF_DISABLE_IPV6="/etc/sysctl.d/99-zero-ipv6-traffic.conf";
+  CONF_DISABLE_IPV6="/etc/sysctl.d/99-zero-ipv6-traffic.conf";
 
-	RELOAD_SYSCTL="";
+  RELOAD_SYSCTL="";
 
-	FORCE_RECREATE_CONFIG="0";
+  FORCE_RECREATE_CONFIG="0";
 
-	APPLY_DISABLE="1";
-	
-	if [ -n "${1}" ]; then
+  APPLY_DISABLE="1";
+  
+  if [ -n "${1}" ]; then
     if [ "${1}" == "revert" ]; then
       APPLY_DISABLE="0";
     fi;
     if [ "${1}" == "force" ]; then
       FORCE_RECREATE_CONFIG="1"; # Force-recreate this runtime's unique config-file
     fi;
-	fi;
+  fi;
 
-	if [ ! -f "${CONF_DISABLE_IPV6}" ]; then
+  if [ ! -f "${CONF_DISABLE_IPV6}" ]; then
     echo "$(date +'%Y-%m-%d %H:%M:%S') Creating sysctl file \"${CONF_DISABLE_IPV6}\"...";
     echo -n "" > "${CONF_DISABLE_IPV6}";
     RELOAD_SYSCTL="1";
-	elif [ "${FORCE_RECREATE_CONFIG}" == "1" ]; then
+  elif [ "${FORCE_RECREATE_CONFIG}" == "1" ]; then
     echo "$(date +'%Y-%m-%d %H:%M:%S') Overwriting sysctl file \"${CONF_DISABLE_IPV6}\"...";
     echo -n "" > "${CONF_DISABLE_IPV6}";
     RELOAD_SYSCTL="1";
-	fi;
+  fi;
 
-	SYSCTL_ALL="$(/sbin/sysctl --all 2>/dev/null;)";
-	SYSCTL_IPV6="$(/sbin/sysctl --system --pattern '^net.ipv6' 2>/dev/null;)";
+  SYSCTL_ALL="$(/sbin/sysctl --all 2>/dev/null;)";
+  SYSCTL_IPV6="$(/sbin/sysctl --system --pattern '^net.ipv6' 2>/dev/null;)";
 
-	# Rules to ensure get applied to sysctl in current environment & on every boot henceforth
-	DISABLE_IPV6_ALL="net.ipv6.conf.all.disable_ipv6";
-	if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_ALL} | grep ${APPLY_DISABLE})" ]; then
+  # Rules to ensure get applied to sysctl in current environment & on every boot henceforth
+  DISABLE_IPV6_ALL="net.ipv6.conf.all.disable_ipv6";
+  if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_ALL} | grep ${APPLY_DISABLE})" ]; then
     echo "$(date +'%Y-%m-%d %H:%M:%S') Adding \"${DISABLE_IPV6_ALL} = ${APPLY_DISABLE}\" to sysctl file \"${CONF_DISABLE_IPV6}\"...";
     echo "${DISABLE_IPV6_ALL} = ${APPLY_DISABLE}" >> "${CONF_DISABLE_IPV6}";
     /sbin/sysctl "${DISABLE_IPV6_ALL}" ${APPLY_DISABLE};
     RELOAD_SYSCTL="1";
-	fi;
+  fi;
 
-	DISABLE_IPV6_DEF="net.ipv6.conf.default.disable_ipv6";
-	if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_DEF} | grep ${APPLY_DISABLE})" ]; then
+  DISABLE_IPV6_DEF="net.ipv6.conf.default.disable_ipv6";
+  if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_DEF} | grep ${APPLY_DISABLE})" ]; then
     echo "$(date +'%Y-%m-%d %H:%M:%S') Adding \"${DISABLE_IPV6_DEF} = ${APPLY_DISABLE}\" to sysctl file \"${CONF_DISABLE_IPV6}\"...";
     echo "${DISABLE_IPV6_DEF} = ${APPLY_DISABLE}" >> "${CONF_DISABLE_IPV6}";
     /sbin/sysctl "${DISABLE_IPV6_DEF}" ${APPLY_DISABLE};
     RELOAD_SYSCTL="1";
-	fi;
+  fi;
 
-	DISABLE_IPV6_LO="net.ipv6.conf.lo.disable_ipv6";
-	if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_LO} | grep ${APPLY_DISABLE})" ]; then
+  DISABLE_IPV6_LO="net.ipv6.conf.lo.disable_ipv6";
+  if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_LO} | grep ${APPLY_DISABLE})" ]; then
     echo "$(date +'%Y-%m-%d %H:%M:%S') Adding \"${DISABLE_IPV6_LO} = ${APPLY_DISABLE}\" to sysctl file \"${CONF_DISABLE_IPV6}\"...";
     echo "${DISABLE_IPV6_LO} = ${APPLY_DISABLE}" >> "${CONF_DISABLE_IPV6}";
     /sbin/sysctl "${DISABLE_IPV6_LO}" ${APPLY_DISABLE};
     RELOAD_SYSCTL="1";
-	fi;
+  fi;
 
-	# If we modified any files, update sysctl's config-values
-	if [ -n "${RELOAD_SYSCTL}" ]; then
+  # If we modified any files, update sysctl's config-values
+  if [ -n "${RELOAD_SYSCTL}" ]; then
     chmod 0644 "${CONF_DISABLE_IPV6}";
     chown root:root "${CONF_DISABLE_IPV6}";
     sysctl --system; # Load settings from all system configuration files.
-	else
+  else
     echo "$(date +'%Y-%m-%d %H:%M:%S') No changes required for sysctl file \"${CONF_DISABLE_IPV6}\" (already up-to-date)";
-	fi;
-	
+  fi;
+  
 fi;
diff --git a/usr/local/sbin/docker_log_limiter b/usr/local/sbin/docker_log_limiter
--- a/usr/local/sbin/docker_log_limiter
+++ b/usr/local/sbin/docker_log_limiter
@@ -26,23 +26,23 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Set the max-filesize for a given docker's logfile
+  # ------------------------------------------------------------
+  # Set the max-filesize for a given docker's logfile
 
-	DOCKER_GLOBAL_CONFIG="/etc/docker/daemon.json";
+  DOCKER_GLOBAL_CONFIG="/etc/docker/daemon.json";
 
-	MAX_LOG_FILESIZE="25m";
+  MAX_LOG_FILESIZE="25m";
 
-	echo "";
-	if [ -f "${DOCKER_GLOBAL_CONFIG}" ]; then
+  echo "";
+  if [ -f "${DOCKER_GLOBAL_CONFIG}" ]; then
     echo -e "Please ensure the following json exists in the docker global-config file found @ \"${DOCKER_GLOBAL_CONFIG}\":\n\n";
     echo -e "{\n  \"log-driver\": \"json-file\",\n  \"log-opts\": {\n    \"max-size\": \"${MAX_LOG_FILESIZE}\",\n    \"max-file\": \"1\",\n    \"compress\": \"false\"\n  }\n}";
     echo -e "\n\n";
-	else
+  else
     echo -e "{\n  \"log-driver\": \"json-file\",\n  \"log-opts\": {\n    \"max-size\": \"${MAX_LOG_FILESIZE}\",\n    \"max-file\": \"1\",\n    \"compress\": \"false\"\n  }\n}" >> "${DOCKER_GLOBAL_CONFIG}";
     echo "Applied filesize-restriction to all docker containers --> max-size: \"${MAX_LOG_FILESIZE}\"";
     echo "";
@@ -51,8 +51,8 @@ else
     systemctl restart docker;
     echo "";
     echo "Done";
-	fi;
-	echo "";
+  fi;
+  echo "";
 
 fi;
 
diff --git a/usr/local/sbin/get_services b/usr/local/sbin/get_services
--- a/usr/local/sbin/get_services
+++ b/usr/local/sbin/get_services
@@ -7,17 +7,17 @@
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 
-	if [ -z "$1" ]; then
+  if [ -z "$1" ]; then
     # Show all services
     # SERVICE_LIST_ALL=$(systemctl list-unit-files --no-legend | awk '{print $1}' | sed -rne 's/^([A-Za-z0-9\.\_\-]+)\.service$/\1/p' | sort 2> '/dev/null');
     /bin/systemctl list-unit-files --no-legend --no-pager --full | awk '{print $1}' | sed -rne 's/^([A-Za-z0-9\.\_\-]+)\.service$/\1/p' | sort 2> '/dev/null';
 
-	else
+  else
     #	Search for one, specific service
     SERVICE_NAME="${1}";
     # SERVICE_RET_CODE=$(/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
@@ -32,10 +32,10 @@ else
       exit 1;
     fi;
 
-	fi;
+  fi;
 
-	###	List only services matching a given state, such as "enabled"
-	### /bin/systemctl list-unit-files --state=enabled --no-legend | awk '{print $1}' | sed -rne 's/^([A-Za-z0-9\.\_\-]+)\.service$/\1/p' | sort 2> '/dev/null';
+  ###	List only services matching a given state, such as "enabled"
+  ### /bin/systemctl list-unit-files --state=enabled --no-legend | awk '{print $1}' | sed -rne 's/^([A-Za-z0-9\.\_\-]+)\.service$/\1/p' | sort 2> '/dev/null';
 
 fi;
 
diff --git a/usr/local/sbin/git_config_all b/usr/local/sbin/git_config_all
--- a/usr/local/sbin/git_config_all
+++ b/usr/local/sbin/git_config_all
@@ -18,36 +18,36 @@ exec 2>&1 1> "${LOGFILE}";
 # Script must run as root or via sudo
 #
 if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	ROLLBACK_IFS="${IFS}";
-	IFS=$'\n'; # Set the global for-loop delimiter to newlines (ignore spaces)
+  ROLLBACK_IFS="${IFS}";
+  IFS=$'\n'; # Set the global for-loop delimiter to newlines (ignore spaces)
 
-	ALL_GIT_EXE_PATHS="${USERPROFILE}/_git_exe_paths.txt";
-	ALL_SYSTEM_CONFIGS="${USERPROFILE}/_git_configs.system.txt";
-	ALL_GLOBAL_CONFIGS="${USERPROFILE}/_git_configs.globals.txt";
+  ALL_GIT_EXE_PATHS="${USERPROFILE}/_git_exe_paths.txt";
+  ALL_SYSTEM_CONFIGS="${USERPROFILE}/_git_configs.system.txt";
+  ALL_GLOBAL_CONFIGS="${USERPROFILE}/_git_configs.globals.txt";
 
-	SEARCH_DIRECTORIES=();
-	SEARCH_DIRECTORIES+=("${LOCALAPPDATA}/");
-	SEARCH_DIRECTORIES+=("${PROGRAMFILES}/");
-	SEARCH_DIRECTORIES+=("${PROGRAMFILES} (x86)/");
+  SEARCH_DIRECTORIES=();
+  SEARCH_DIRECTORIES+=("${LOCALAPPDATA}/");
+  SEARCH_DIRECTORIES+=("${PROGRAMFILES}/");
+  SEARCH_DIRECTORIES+=("${PROGRAMFILES} (x86)/");
 
-	echo -n "" > "${ALL_GIT_EXE_PATHS}";
-	echo -n "" > "${ALL_SYSTEM_CONFIGS}";
-	echo -n "" > "${ALL_GLOBAL_CONFIGS}";
+  echo -n "" > "${ALL_GIT_EXE_PATHS}";
+  echo -n "" > "${ALL_SYSTEM_CONFIGS}";
+  echo -n "" > "${ALL_GLOBAL_CONFIGS}";
 
-	# git contains a hidden config-file on Windows-instances which may be found within the ProgramData directory
-	HIDDEN_CONFIG_WIN32=$(realpath "${PROGRAMDATA:-${ALLUSERSPROFILE}}/Git/config");
-	HIDDEN_CONFIG_LINUX=""; MM="${HIDDEN_CONFIG_WIN32/C:/\/c}"; MM="${MM//\\/\/}"; HIDDEN_CONFIG_LINUX=$(realpath "${MM}");
-	if [ -f "${HIDDEN_CONFIG_LINUX}" ]; then
+  # git contains a hidden config-file on Windows-instances which may be found within the ProgramData directory
+  HIDDEN_CONFIG_WIN32=$(realpath "${PROGRAMDATA:-${ALLUSERSPROFILE}}/Git/config");
+  HIDDEN_CONFIG_LINUX=""; MM="${HIDDEN_CONFIG_WIN32/C:/\/c}"; MM="${MM//\\/\/}"; HIDDEN_CONFIG_LINUX=$(realpath "${MM}");
+  if [ -f "${HIDDEN_CONFIG_LINUX}" ]; then
     echo "${HIDDEN_CONFIG_LINUX}" >> "${ALL_GLOBAL_CONFIGS}";
-	fi;
+  fi;
 
-	for EACH_DIRECTORY in "${SEARCH_DIRECTORIES[@]}"; do
+  for EACH_DIRECTORY in "${SEARCH_DIRECTORIES[@]}"; do
 
     EACH_DIR_REALPATH=$(realpath "${EACH_DIRECTORY}");
 
@@ -79,37 +79,37 @@ else
       fi;
 
     done;
-	done;
-	# ------------------------------------------------------------
+  done;
+  # ------------------------------------------------------------
 
-	# Show all EXE files-found
-	# echo "";
-	# echo "[EXECUTABLE] git.exe file(s) found:";
-	# for EACH_EXE in $(cat "${ALL_GIT_EXE_PATHS}"); do
-	# 	echo "  |";
-	# 	echo "  |--> ${EACH_EXE}";
-	# done;
+  # Show all EXE files-found
+  # echo "";
+  # echo "[EXECUTABLE] git.exe file(s) found:";
+  # for EACH_EXE in $(cat "${ALL_GIT_EXE_PATHS}"); do
+  # 	echo "  |";
+  # 	echo "  |--> ${EACH_EXE}";
+  # done;
 
-	# Show all GLOBAL configuration files-found
-	# echo "";
-	# echo "[GLOBAL] git config file(s) found:";
-	# for EACH_CONFIG in $(cat "${ALL_GLOBAL_CONFIGS}"); do
-	# 	echo "  |";
-	# 	echo "  |--> ${EACH_CONFIG}";
-	# done;
+  # Show all GLOBAL configuration files-found
+  # echo "";
+  # echo "[GLOBAL] git config file(s) found:";
+  # for EACH_CONFIG in $(cat "${ALL_GLOBAL_CONFIGS}"); do
+  # 	echo "  |";
+  # 	echo "  |--> ${EACH_CONFIG}";
+  # done;
 
-	# Show all SYSTEM configuration files-found
-	# echo "";
-	# echo "[SYSTEM] git config file(s) found:";
-	# for EACH_CONFIG in $(cat "${ALL_SYSTEM_CONFIGS}"); do
-	# 	echo "  |";
-	# 	echo "  |--> ${EACH_CONFIG}";
-	# done;
+  # Show all SYSTEM configuration files-found
+  # echo "";
+  # echo "[SYSTEM] git config file(s) found:";
+  # for EACH_CONFIG in $(cat "${ALL_SYSTEM_CONFIGS}"); do
+  # 	echo "  |";
+  # 	echo "  |--> ${EACH_CONFIG}";
+  # done;
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	# Apply a specific [ git config ] value to each file found, call this script with inline-params $1 and $2 as follows:
-	if [ -n "$1" ] && [ -n "$2" ]; then
+  # Apply a specific [ git config ] value to each file found, call this script with inline-params $1 and $2 as follows:
+  if [ -n "$1" ] && [ -n "$2" ]; then
 
     # ------------------------------------------------------------
     # [GLOBAL] SHOW & UPDATE EACH CONFIG-FILE
@@ -175,22 +175,22 @@ else
 
     # ------------------------------------------------------------
 
-	else
+  else
 
     echo "";
     echo "Call with inline params \$1 and \$2 to apply a config-value to every config-file found";
     echo "Example:";
     echo "    > \"$0\" core.autocrlf input";
 
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	echo "";
+  echo "";
 
-	IFS="${ROLLBACK_IFS}"; # Restore the global for-loop delimiter to whatever the value was at the start of this script's runtime
+  IFS="${ROLLBACK_IFS}"; # Restore the global for-loop delimiter to whatever the value was at the start of this script's runtime
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
 fi;
 
diff --git a/usr/local/sbin/gpg_git_config_sync b/usr/local/sbin/gpg_git_config_sync
--- a/usr/local/sbin/gpg_git_config_sync
+++ b/usr/local/sbin/gpg_git_config_sync
@@ -32,13 +32,13 @@ fi;
 # ------------------------------------------------------------
 
 if [[ "${OSTYPE}" != "linux-gnu"* ]] && [[ "$(uname -s)" != "Linux" ]] && [[ "${OSTYPE}" != "darwin"* ]]; then
-	OS_IS_WINDOWS=1;
+  OS_IS_WINDOWS=1;
 else
-	OS_IS_WINDOWS=0;
-	echo "";
-	echo "Error: Script must run in a Windows Git-Bash terminal ( w/ admin-privileges ) to function as-intended";
-	echo "";
-	exit 1;
+  OS_IS_WINDOWS=0;
+  echo "";
+  echo "Error: Script must run in a Windows Git-Bash terminal ( w/ admin-privileges ) to function as-intended";
+  echo "";
+  exit 1;
 fi;
 
 IS_MINGW=$(if [[ $(uname -s | grep -i MINGW | wc -l) -gt 0 ]] || [ "${OSTYPE}" == "msys" ]; then echo 1; else echo 0; fi;);
@@ -101,20 +101,20 @@ GIT_SYNC_CONFIG_FULLPATH="";
 
 # Create parent directory to the main config (if not found to exist)
 if [ ! -d "${DEFAULT_CONFIG_DIRNAME}" ]; then
-	mkdir "${DEFAULT_CONFIG_DIRNAME}";
+  mkdir "${DEFAULT_CONFIG_DIRNAME}";
 fi;
 
 if [ -n "${1}" ] && [ -f "${1}" ]; then
-	GIT_SYNC_CONFIG_FULLPATH="${1}";
-	source "${1}"; # First inline parameter ( $1 ) is the path to another shell script which sets/instantiates all required config variables
+  GIT_SYNC_CONFIG_FULLPATH="${1}";
+  source "${1}"; # First inline parameter ( $1 ) is the path to another shell script which sets/instantiates all required config variables
 elif [ -f "${DEFAULT_CONFIG_FULLPATH}" ]; then
-	GIT_SYNC_CONFIG_FULLPATH="${DEFAULT_CONFIG_FULLPATH}";
-	source "${DEFAULT_CONFIG_FULLPATH}"; # Default shell script which sets/instantiates all required config variables
+  GIT_SYNC_CONFIG_FULLPATH="${DEFAULT_CONFIG_FULLPATH}";
+  source "${DEFAULT_CONFIG_FULLPATH}"; # Default shell script which sets/instantiates all required config variables
 else
-	echo "";
-	echo "Error: FIRST inline parameter ( \$1 ) must point to the filepath of a separate shell script which sets/instantiates all required git + gnupg config variables (see var-names above)";
-	echo "";
-	exit 1;
+  echo "";
+  echo "Error: FIRST inline parameter ( \$1 ) must point to the filepath of a separate shell script which sets/instantiates all required git + gnupg config variables (see var-names above)";
+  echo "";
+  exit 1;
 fi;
 
 
@@ -129,7 +129,7 @@ shopt -s lastpipe; # extends the current shell into sub-shells (within piped-com
 # SHOW_GIT_CONFIG_OUTPUTS=1;
 # SHOW_GIT_CONFIG_OUTPUTS=2;
 if [ ! -v SHOW_GIT_CONFIG_OUTPUTS ]; then
-	SHOW_GIT_CONFIG_OUTPUTS=1;
+  SHOW_GIT_CONFIG_OUTPUTS=1;
 fi;
 
 
@@ -138,7 +138,7 @@ fi;
 # STRICT_HOSTKEY_CHECKING=0;
 # STRICT_HOSTKEY_CHECKING=1;
 if [ ! -v STRICT_HOSTKEY_CHECKING ]; then
-	STRICT_HOSTKEY_CHECKING=1; # 0 to use " -o StrictHostKeyChecking=no"
+  STRICT_HOSTKEY_CHECKING=1; # 0 to use " -o StrictHostKeyChecking=no"
 fi;
 
 
@@ -147,7 +147,7 @@ fi;
 # Additional options to which affect each and every Git call (push, pull, fetch, etc.)
 GIT_SSH_OPTS="";
 if [ ${STRICT_HOSTKEY_CHECKING} -eq 0 ]; then
-	GIT_SSH_OPTS=" -o StrictHostKeyChecking=no";
+  GIT_SSH_OPTS=" -o StrictHostKeyChecking=no";
 fi;
 
 
@@ -210,23 +210,23 @@ GPG4WIN_GPG_EXE_WIN32="${GPG4WIN_EXE_DIR_WIN32}\gpg.exe";
 # Check if running as w/ administrative privileges (or not)
 IS_ADMIN=$(net session > /dev/null 2>&1; if [ "$?" -ne "0" ]; then echo 0; else echo 1; fi;);
 if [ "${IS_ADMIN}" == "0" ]; then
-	echo "";
-	echo "Error: Must \"Run as Administrator\" on the Git Bash terminal";
-	echo "";
-	sleep 60;
-	exit 1;
+  echo "";
+  echo "Error: Must \"Run as Administrator\" on the Git Bash terminal";
+  echo "";
+  sleep 60;
+  exit 1;
 
 elif [ ! -e "${GPG4WIN_GPG_EXE_LINUX}" ]; then
-	#
-	#	Gpg4win --> GnuPG Key Hander
-	#		Make sure that "Gpg4win" is installed, as it both upgrades Git's default "gpg.exe" runtime, and
-	#		also brings along "Kleopatra", a Windows handler for gpg-keys w/ a front-end GUI & server-sync built-in
-	#
-	echo "Error: Unable to locate \"Gpg4win\" directory";
-	echo " |--> Please download & install \"Gpg4win\" via : https://www.gpg4win.org/thanks-for-download.html ";
-	echo " |--> Once Gpg4win is installed, import/create your GnuPG keys using its \"Kleopatra\" included module ";
-	sleep 60;
-	exit 1;
+  #
+  #	Gpg4win --> GnuPG Key Hander
+  #		Make sure that "Gpg4win" is installed, as it both upgrades Git's default "gpg.exe" runtime, and
+  #		also brings along "Kleopatra", a Windows handler for gpg-keys w/ a front-end GUI & server-sync built-in
+  #
+  echo "Error: Unable to locate \"Gpg4win\" directory";
+  echo " |--> Please download & install \"Gpg4win\" via : https://www.gpg4win.org/thanks-for-download.html ";
+  echo " |--> Once Gpg4win is installed, import/create your GnuPG keys using its \"Kleopatra\" included module ";
+  sleep 60;
+  exit 1;
 
 fi;
 
@@ -262,15 +262,15 @@ SEARCH_DIRECTORIES+=("${PROG_FILES_X86_LINUX}/");
 
 for EACH_DIRECTORY in "${SEARCH_DIRECTORIES[@]}"; do
 
-	HAYSTACK=$(realpath "${EACH_DIRECTORY}");
-	NEEDLE="git.exe";
-	echo "Info: Searching haystack \"${HAYSTACK}\" for needle \"${NEEDLE}\"...";
-	find "${HAYSTACK}" \
-	-type f \
-	-name "${NEEDLE}" \
-	-print0 \
-	2>"/dev/null" \
-	| while IFS= read -r -d $'\0' EACH_GIT_EXE; do
+  HAYSTACK=$(realpath "${EACH_DIRECTORY}");
+  NEEDLE="git.exe";
+  echo "Info: Searching haystack \"${HAYSTACK}\" for needle \"${NEEDLE}\"...";
+  find "${HAYSTACK}" \
+  -type f \
+  -name "${NEEDLE}" \
+  -print0 \
+  2>"/dev/null" \
+  | while IFS= read -r -d $'\0' EACH_GIT_EXE; do
 
     EACH_GIT_LINUX=""; MM=$(realpath "${EACH_GIT_EXE}"); MM="${MM/C:/\/c}";     MM="${MM//\\/\/}"; EACH_GIT_LINUX="${MM}";
     EACH_GIT_WIN32=""; MM=$(realpath "${EACH_GIT_EXE}"); MM="${MM/\/c\//C:\\}"; MM="${MM//\//\\}"; EACH_GIT_WIN32="${MM}";
@@ -289,7 +289,7 @@ for EACH_DIRECTORY in "${SEARCH_DIRECTORIES[@]}"; do
       echo "${GLOBAL_CONF_LINUX}" >> "${GIT_CONF_GLOBAL_PATHS_LINUX}";
     fi;
 
-	done;
+  done;
 
 done;
 
@@ -300,7 +300,7 @@ IFS="${ROLLBACK_IFS}";
 # ------------------------------------------------------------
 
 if [ "list gnupg" == "key ids" ]; then
-	gpg --list-keys;
+  gpg --list-keys;
 fi;
 
 #
@@ -333,8 +333,8 @@ echo "Info: GnuPG exe - Gpg4win  (gpg.exe) :  \"${GPG4WIN_GPG_EXE_LINUX}\"";
 echo "Info: GnuPG pinentry exe (pinentry.exe) :  \"${GPG_PINENTRY_EXE}\"";
 
 for EACH_FILE in $(ls "${GPG4WIN_EXE_DIR_LINUX}" | grep .exe); do
-	EACH_FULLPATH="${GPG4WIN_EXE_DIR_LINUX}/${EACH_FILE}";
-	if [ -f "${GPG4WIN_EXE_DIR_LINUX}/${EACH_FILE}" ]; then # 
+  EACH_FULLPATH="${GPG4WIN_EXE_DIR_LINUX}/${EACH_FILE}";
+  if [ -f "${GPG4WIN_EXE_DIR_LINUX}/${EACH_FILE}" ]; then # 
     if [ -L "${GIT_EXE_DIR_LINUX}/${EACH_FILE}" ]; then
       EACH_FILE_OUTPUT=$(ls -al "${GPG4WIN_EXE_DIR_LINUX}" | awk '{print $9,$10,$11}' | grep "${EACH_FILE}");
       # echo "Pass - ${EACH_FILE_OUTPUT}";
@@ -347,7 +347,7 @@ for EACH_FILE in $(ls "${GPG4WIN_EXE_DIR_LINUX}" | grep .exe); do
       echo "";
       echo "MKLINK \"${GIT_EXE_DIR_WIN32}\\${EACH_FILE}\" \"${GPG4WIN_EXE_DIR_WIN32}\\${EACH_FILE}\" " | CMD; # MKLINK Syntax: [ MKLINK "NEW_LINK" "EXISTING_TARGET" ]
     fi;
-	fi;
+  fi;
 done;
 
 #
@@ -395,7 +395,7 @@ echo "Info: GnuPG Default Config-File (Linux): \"${GCONF_PRIMARY_LINUX}\"";
 EACH_CONF="gpg.conf";
 EACH_FULLCONF="${GCONF_PRIMARY_DIR_LINUX}/${EACH_CONF}";
 if [ ! -f "${EACH_FULLCONF}" ]; then
-	echo -n "" > "${EACH_FULLCONF}";
+  echo -n "" > "${EACH_FULLCONF}";
 fi;
 
 # if [ "$(cat ${EACH_FULLCONF} | grep 'pinentry-mode')" == "" ]; then echo "pinentry-mode loopback" >> "${EACH_FULLCONF}"; fi;
@@ -413,7 +413,7 @@ if [ "$(cat ${EACH_FULLCONF} | grep 'no-tty')" == "" ]; then echo "no-tty" >> "$
 EACH_CONF="gpg-agent.conf";
 EACH_FULLCONF="${GCONF_PRIMARY_DIR_LINUX}/${EACH_CONF}";
 if [ ! -f "${EACH_FULLCONF}" ]; then
-	echo -n "" > "${EACH_FULLCONF}";
+  echo -n "" > "${EACH_FULLCONF}";
 fi;
 
 # if [ "$(cat ${EACH_FULLCONF} | grep 'pinentry-timeout')" == "" ]; then echo "pinentry-timeout 0" >> "${EACH_FULLCONF}"; fi;
@@ -429,63 +429,63 @@ if [ "$(cat ${EACH_FULLCONF} | grep 'max-cache-ttl')" == "" ]; then echo "max-ca
 EACH_CONF="gpgconf.conf";
 EACH_FULLCONF="${GCONF_PRIMARY_DIR_LINUX}/${EACH_CONF}";
 if [ ! -f "${EACH_FULLCONF}" ]; then
-	echo -n "" > "${EACH_FULLCONF}";
+  echo -n "" > "${EACH_FULLCONF}";
 fi;
 
 # ------------------------------------------------------------
 
 # [ USERPROFILE ] *.conf - Creation / Symlinking
 if [ "${GCONF_USERPROFILE_LINUX}" == "${GCONF_PRIMARY_LINUX}" ]; then
-	# echo "";
-	# echo "Pass - \"${GCONF_USERPROFILE_LINUX}\" IS the primary GnuPG config-file";
-	MM="";
+  # echo "";
+  # echo "Pass - \"${GCONF_USERPROFILE_LINUX}\" IS the primary GnuPG config-file";
+  MM="";
 else
-	# [ USERPROFILE ] gpg.conf
-	EACH_CONF="gpg.conf";
-	if [ ! -f "${USERPROFILE_GNUPG_LINUX}/${EACH_CONF}" ]; then
+  # [ USERPROFILE ] gpg.conf
+  EACH_CONF="gpg.conf";
+  if [ ! -f "${USERPROFILE_GNUPG_LINUX}/${EACH_CONF}" ]; then
     echo "";
     echo "MKLINK \"${USERPROFILE_GNUPG_WIN32}\\${EACH_CONF}\" \"${GCONF_PRIMARY_DIR_WIN32}\\${EACH_CONF}\" " | CMD; # MKLINK Syntax: [ MKLINK "NEW_LINK" "EXISTING_TARGET" ]
-	fi;
-	# [ USERPROFILE ] gpgconf.conf
-	EACH_CONF="gpgconf.conf";
-	if [ ! -f "${USERPROFILE_GNUPG_LINUX}/${EACH_CONF}" ]; then
+  fi;
+  # [ USERPROFILE ] gpgconf.conf
+  EACH_CONF="gpgconf.conf";
+  if [ ! -f "${USERPROFILE_GNUPG_LINUX}/${EACH_CONF}" ]; then
     echo "";
     echo "MKLINK \"${USERPROFILE_GNUPG_WIN32}\\${EACH_CONF}\" \"${GCONF_PRIMARY_DIR_WIN32}\\${EACH_CONF}\" " | CMD; # MKLINK Syntax: [ MKLINK "NEW_LINK" "EXISTING_TARGET" ]
-	fi;
-	# [ USERPROFILE ] gpg-agent.conf
-	EACH_CONF="gpg-agent.conf";
-	if [ ! -f "${USERPROFILE_GNUPG_LINUX}/${EACH_CONF}" ]; then
+  fi;
+  # [ USERPROFILE ] gpg-agent.conf
+  EACH_CONF="gpg-agent.conf";
+  if [ ! -f "${USERPROFILE_GNUPG_LINUX}/${EACH_CONF}" ]; then
     echo "";
     echo "MKLINK \"${USERPROFILE_GNUPG_WIN32}\\${EACH_CONF}\" \"${GCONF_PRIMARY_DIR_WIN32}\\${EACH_CONF}\" " | CMD; # MKLINK Syntax: [ MKLINK "NEW_LINK" "EXISTING_TARGET" ]
-	fi;
+  fi;
 fi;
 
 # ------------------------------------------------------------
 
 # [ APPDATA ] *.conf - Config File Creation / Symlinking
 if [ "${GCONF_APPDATA_LINUX}" == "${GCONF_PRIMARY_LINUX}" ]; then
-	# echo "";
-	# echo "Pass - \"${GCONF_APPDATA_LINUX}\" IS the primary GnuPG config-file";
-	MM="";
+  # echo "";
+  # echo "Pass - \"${GCONF_APPDATA_LINUX}\" IS the primary GnuPG config-file";
+  MM="";
 else
-	# [ APPDATA ] gpg.conf
-	EACH_CONF="gpg.conf";
-	if [ ! -f "${GCONF_APPDATA_DIR_LINUX}/${EACH_CONF}" ]; then
+  # [ APPDATA ] gpg.conf
+  EACH_CONF="gpg.conf";
+  if [ ! -f "${GCONF_APPDATA_DIR_LINUX}/${EACH_CONF}" ]; then
     echo "";
     echo "MKLINK \"${GCONF_APPDATA_DIR_WIN32}\\${EACH_CONF}\" \"${GCONF_PRIMARY_DIR_WIN32}\\${EACH_CONF}\" " | CMD; # MKLINK Syntax: [ MKLINK "NEW_LINK" "EXISTING_TARGET" ]
-	fi;
-	# [ APPDATA ] gpgconf.conf
-	EACH_CONF="gpgconf.conf";
-	if [ ! -f "${GCONF_APPDATA_DIR_LINUX}/${EACH_CONF}" ]; then
+  fi;
+  # [ APPDATA ] gpgconf.conf
+  EACH_CONF="gpgconf.conf";
+  if [ ! -f "${GCONF_APPDATA_DIR_LINUX}/${EACH_CONF}" ]; then
     echo "";
     echo "MKLINK \"${GCONF_APPDATA_DIR_WIN32}\\${EACH_CONF}\" \"${GCONF_PRIMARY_DIR_WIN32}\\${EACH_CONF}\" " | CMD; # MKLINK Syntax: [ MKLINK "NEW_LINK" "EXISTING_TARGET" ]
-	fi;
-	# [ APPDATA ] gpg-agent.conf
-	EACH_CONF="gpg-agent.conf";
-	if [ ! -f "${GCONF_APPDATA_DIR_LINUX}/${EACH_CONF}" ]; then
+  fi;
+  # [ APPDATA ] gpg-agent.conf
+  EACH_CONF="gpg-agent.conf";
+  if [ ! -f "${GCONF_APPDATA_DIR_LINUX}/${EACH_CONF}" ]; then
     echo "";
     echo "MKLINK \"${GCONF_APPDATA_DIR_WIN32}\\${EACH_CONF}\" \"${GCONF_PRIMARY_DIR_WIN32}\\${EACH_CONF}\" " | CMD; # MKLINK Syntax: [ MKLINK "NEW_LINK" "EXISTING_TARGET" ]
-	fi;
+  fi;
 fi;
 
 # ------------------------------------------------------------
@@ -620,41 +620,41 @@ fi;
 
 # if [ 0 -eq 1 ]; then
 
-	echo "------------------------------------------------------------"
-	echo ""
-	echo "Beginning Exclusions search..."
+  echo "------------------------------------------------------------"
+  echo ""
+  echo "Beginning Exclusions search..."
 
-	unset EXCLUDED_HOMEDIRS; declare -A EXCLUDED_HOMEDIRS; # [Re-]Instantiate bash array
+  unset EXCLUDED_HOMEDIRS; declare -A EXCLUDED_HOMEDIRS; # [Re-]Instantiate bash array
 
-	# AppData
-	if [ -d "${HOME}/AppData" ]; then
+  # AppData
+  if [ -d "${HOME}/AppData" ]; then
     EXCLUDED_HOMEDIRS+=(["${HOME}/AppData"]="");
-	fi;
-	# DropBox
-	if [ -d "${HOME}/Dropbox" ]; then
+  fi;
+  # DropBox
+  if [ -d "${HOME}/Dropbox" ]; then
     EXCLUDED_HOMEDIRS+=(["${HOME}/Dropbox"]="");
-	fi;
-	# Google Drive
-	if [ -d "${HOME}/Google Drive" ]; then
+  fi;
+  # Google Drive
+  if [ -d "${HOME}/Google Drive" ]; then
     EXCLUDED_HOMEDIRS+=(["${HOME}/Google Drive"]="");
-	fi;
-	# iCloud (Apple)
-	if [ -d "${HOME}/iCloudDrive" ]; then
+  fi;
+  # iCloud (Apple)
+  if [ -d "${HOME}/iCloudDrive" ]; then
     EXCLUDED_HOMEDIRS+=(["${HOME}/iCloudDrive"]="");
-	fi;
+  fi;
 
-	#
-	# Exclude OneDrive Dirs
-	#   |--> Note: Running 'find' against OneDrive files causes them to be downloaded (if cloud synced), effectively ruining the functionality of OneDrive's "Files On-Demand" feature
-	#
-	REGKEY_ONEDRIVE_BUSINESS="Registry::HKEY_CURRENT_USER\Software\Microsoft\OneDrive\Accounts\Business1\ScopeIdToMountPointPathCache";  # OneDrive for Business
-	REGKEY_ONEDRIVE_PERSONAL="Registry::HKEY_CURRENT_USER\Software\Microsoft\OneDrive\Accounts\Personal\ScopeIdToMountPointPathCache";   # OneDrive Personal
-	PS1_ONEDRIVE_BUSINESS="(Get-Item ('${REGKEY_ONEDRIVE_BUSINESS}')).Property | ForEach-Object { Get-ItemPropertyValue -Path ('${REGKEY_ONEDRIVE_BUSINESS}') -Name (\$_) -ErrorAction ('SilentlyContinue')}; ";
-	PS1_ONEDRIVE_PERSONAL="(Get-Item ('${REGKEY_ONEDRIVE_PERSONAL}')).Property | ForEach-Object { Get-ItemPropertyValue -Path ('${REGKEY_ONEDRIVE_PERSONAL}') -Name (\$_) -ErrorAction ('SilentlyContinue')}; ";
-	DIRS_ONEDRIVE_BUSINESS=$(PowerShell -Command "${PS1_ONEDRIVE_BUSINESS}";);
-	DIRS_ONEDRIVE_PERSONAL=$(PowerShell -Command "${PS1_ONEDRIVE_PERSONAL}";);
-	
-	echo -e "${DIRS_ONEDRIVE_BUSINESS}""\n""${DIRS_ONEDRIVE_PERSONAL}" | while read -r EACH_PATH; do
+  #
+  # Exclude OneDrive Dirs
+  #   |--> Note: Running 'find' against OneDrive files causes them to be downloaded (if cloud synced), effectively ruining the functionality of OneDrive's "Files On-Demand" feature
+  #
+  REGKEY_ONEDRIVE_BUSINESS="Registry::HKEY_CURRENT_USER\Software\Microsoft\OneDrive\Accounts\Business1\ScopeIdToMountPointPathCache";  # OneDrive for Business
+  REGKEY_ONEDRIVE_PERSONAL="Registry::HKEY_CURRENT_USER\Software\Microsoft\OneDrive\Accounts\Personal\ScopeIdToMountPointPathCache";   # OneDrive Personal
+  PS1_ONEDRIVE_BUSINESS="(Get-Item ('${REGKEY_ONEDRIVE_BUSINESS}')).Property | ForEach-Object { Get-ItemPropertyValue -Path ('${REGKEY_ONEDRIVE_BUSINESS}') -Name (\$_) -ErrorAction ('SilentlyContinue')}; ";
+  PS1_ONEDRIVE_PERSONAL="(Get-Item ('${REGKEY_ONEDRIVE_PERSONAL}')).Property | ForEach-Object { Get-ItemPropertyValue -Path ('${REGKEY_ONEDRIVE_PERSONAL}') -Name (\$_) -ErrorAction ('SilentlyContinue')}; ";
+  DIRS_ONEDRIVE_BUSINESS=$(PowerShell -Command "${PS1_ONEDRIVE_BUSINESS}";);
+  DIRS_ONEDRIVE_PERSONAL=$(PowerShell -Command "${PS1_ONEDRIVE_PERSONAL}";);
+  
+  echo -e "${DIRS_ONEDRIVE_BUSINESS}""\n""${DIRS_ONEDRIVE_PERSONAL}" | while read -r EACH_PATH; do
     # Verify each path exists before excluding it (otherwise it doesn't matter)
     EACH_PATH_WIN32=""; MM=$(realpath "${EACH_PATH}" 2>/dev/null;); MM="${MM/\/c\//C:\\}"; MM="${MM//\//\\}"; EACH_PATH_WIN32="${MM}";
     EACH_PATH_LINUX=""; MM=$(realpath "${EACH_PATH}" 2>/dev/null;); MM="${MM/C:/\/c}";     MM="${MM//\\/\/}"; EACH_PATH_LINUX="${MM}";
@@ -665,18 +665,18 @@ fi;
         EXCLUDED_HOMEDIRS+=(["${DIRNAME_EACHPATH}"]="");
       fi;
     fi;
-	done;
+  done;
 
-	EXCLUDED_HOMEDIRS_NO_DUPES=($(echo "${EXCLUDED_HOMEDIRS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
+  EXCLUDED_HOMEDIRS_NO_DUPES=($(echo "${EXCLUDED_HOMEDIRS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
 
-	unset REPO_FULLPATHS; declare -A REPO_FULLPATHS; # [Re-]Instantiate bash array
+  unset REPO_FULLPATHS; declare -A REPO_FULLPATHS; # [Re-]Instantiate bash array
 
-	echo "------------------------------------------------------------";
-	echo "";
-	echo "Beginning Home-Dir search...";
+  echo "------------------------------------------------------------";
+  echo "";
+  echo "Beginning Home-Dir search...";
 
-	# Get all dirs within current user's home-dir
-	find "${HOME}" -mindepth 1 -maxdepth 1 -type d | while read -r EACH_HOMEDIR; do
+  # Get all dirs within current user's home-dir
+  find "${HOME}" -mindepth 1 -maxdepth 1 -type d | while read -r EACH_HOMEDIR; do
 
     DIR_IS_EXCLUDED=0;
     for EACH_EXCLUDED_DIR in "${!EXCLUDED_HOMEDIRS[@]}"; do
@@ -698,10 +698,10 @@ fi;
         REPO_FULLPATHS+=(["${EACH_REPO_FULLPATH}"]="");
       done;
     fi;
-	done;
+  done;
 
-	# Loop through array of local repository filepaths, attempting to parse their values & set applicable [ git config ... ] settings for each
-	for EACH_REPO_FULLPATH in "${!REPO_FULLPATHS[@]}"; do
+  # Loop through array of local repository filepaths, attempting to parse their values & set applicable [ git config ... ] settings for each
+  for EACH_REPO_FULLPATH in "${!REPO_FULLPATHS[@]}"; do
 
     EACH_REPO_BASENAME=$(basename "${EACH_REPO_FULLPATH}";);
     EACH_REPO_ORIGIN=$(cd "${EACH_REPO_FULLPATH}" && git config --get "remote.origin.url");
@@ -856,8 +856,8 @@ fi;
 
     fi;
 
-	done;
-	
+  done;
+  
 echo "";
 
 exit 0;
diff --git a/usr/local/sbin/install_7z b/usr/local/sbin/install_7z
--- a/usr/local/sbin/install_7z
+++ b/usr/local/sbin/install_7z
@@ -23,14 +23,14 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 # ------------------------------------------------------------
 # Install 7-Zip Package
 
-	if [ $(which 7z 2>'/dev/null' | wc -l;) -eq 0 ]; then
+  if [ $(which 7z 2>'/dev/null' | wc -l;) -eq 0 ]; then
     if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
       apt-get -y update;
       apt-get -y install p7zip-full;
@@ -42,7 +42,7 @@ else
       rm -f "p7zip-16.02-10.el7.x86_64.rpm";
       rm -f "p7zip-plugins-16.02-10.el7.x86_64.rpm";
     fi;
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/install_apt_packages b/usr/local/sbin/install_apt_packages
--- a/usr/local/sbin/install_apt_packages
+++ b/usr/local/sbin/install_apt_packages
@@ -17,38 +17,38 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	APT_PACKAGES=();
+  APT_PACKAGES=();
 
-	APT_PACKAGES+=("apt-rdepends");
-	APT_PACKAGES+=("bc");
-	APT_PACKAGES+=("certbot");
-	APT_PACKAGES+=("default-jdk-headless");
-	APT_PACKAGES+=("default-jre-headless");
-	APT_PACKAGES+=("dos2unix");
-	APT_PACKAGES+=("git");
-	APT_PACKAGES+=("ifupdown");
-	APT_PACKAGES+=("multitail");
-	APT_PACKAGES+=("nginx-full");
-	APT_PACKAGES+=("nmap");
-	APT_PACKAGES+=("python-certbot-nginx");
-	APT_PACKAGES+=("p7zip-full");
-	APT_PACKAGES+=("p7zip-rar");
-	APT_PACKAGES+=("resolvconf");
-	APT_PACKAGES+=("software-properties-common");
-	# APT_PACKAGES+=("sslscan");
-	APT_PACKAGES+=("ufw");
-	APT_PACKAGES+=("vim-common");
-	APT_PACKAGES+=("wget");
-	APT_PACKAGES+=("yui-compressor");
+  APT_PACKAGES+=("apt-rdepends");
+  APT_PACKAGES+=("bc");
+  APT_PACKAGES+=("certbot");
+  APT_PACKAGES+=("default-jdk-headless");
+  APT_PACKAGES+=("default-jre-headless");
+  APT_PACKAGES+=("dos2unix");
+  APT_PACKAGES+=("git");
+  APT_PACKAGES+=("ifupdown");
+  APT_PACKAGES+=("multitail");
+  APT_PACKAGES+=("nginx-full");
+  APT_PACKAGES+=("nmap");
+  APT_PACKAGES+=("python-certbot-nginx");
+  APT_PACKAGES+=("p7zip-full");
+  APT_PACKAGES+=("p7zip-rar");
+  APT_PACKAGES+=("resolvconf");
+  APT_PACKAGES+=("software-properties-common");
+  # APT_PACKAGES+=("sslscan");
+  APT_PACKAGES+=("ufw");
+  APT_PACKAGES+=("vim-common");
+  APT_PACKAGES+=("wget");
+  APT_PACKAGES+=("yui-compressor");
 
-	UNIQUE_APT_PACKAGES=($(echo "${APT_PACKAGES[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
-	for EACH_PKG in "${UNIQUE_APT_PACKAGES[@]}"; do
+  UNIQUE_APT_PACKAGES=($(echo "${APT_PACKAGES[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
+  for EACH_PKG in "${UNIQUE_APT_PACKAGES[@]}"; do
     ALREADY_INSTALLED=$(echo "$(apt list --installed 2>/dev/null;)" | grep -h "^${EACH_PKG}\/" | wc -l);
     if [ "${ALREADY_INSTALLED}" != "0" ]; then
       echo "✓ Package \"${EACH_PKG}\" is already installed";
@@ -71,30 +71,30 @@ else
       fi;
       apt-get install --yes "${EACH_PKG}";
     fi;
-	done;
+  done;
 
-	OPTIONAL_PACKAGES=();
+  OPTIONAL_PACKAGES=();
 
-	# Containers
-	OPTIONAL_PACKAGES+=("python-pip");
-	OPTIONAL_PACKAGES+=("docker");
-	OPTIONAL_PACKAGES+=("docker-compose");
+  # Containers
+  OPTIONAL_PACKAGES+=("python-pip");
+  OPTIONAL_PACKAGES+=("docker");
+  OPTIONAL_PACKAGES+=("docker-compose");
 
-	# CD-CD
-	OPTIONAL_PACKAGES+=("jenkins");
+  # CD-CD
+  OPTIONAL_PACKAGES+=("jenkins");
 
-	# Database
-	OPTIONAL_PACKAGES+=("mysql-client");
-	OPTIONAL_PACKAGES+=("mysql-server");
-	OPTIONAL_PACKAGES+=("mysqldump");
+  # Database
+  OPTIONAL_PACKAGES+=("mysql-client");
+  OPTIONAL_PACKAGES+=("mysql-server");
+  OPTIONAL_PACKAGES+=("mysqldump");
 
-	# SMTP
-	OPTIONAL_PACKAGES+=("sendmail");
+  # SMTP
+  OPTIONAL_PACKAGES+=("sendmail");
 
-	# Node
-	OPTIONAL_PACKAGES+=("nodejs");
-	OPTIONAL_PACKAGES+=("ws"); # Websockets (for NodeJS)
-	OPTIONAL_PACKAGES+=("socket.io"); # Websockets Assist (for Node.JS)
-	OPTIONAL_PACKAGES+=("npm");
+  # Node
+  OPTIONAL_PACKAGES+=("nodejs");
+  OPTIONAL_PACKAGES+=("ws"); # Websockets (for NodeJS)
+  OPTIONAL_PACKAGES+=("socket.io"); # Websockets Assist (for Node.JS)
+  OPTIONAL_PACKAGES+=("npm");
 
 fi;
diff --git a/usr/local/sbin/install_docker b/usr/local/sbin/install_docker
--- a/usr/local/sbin/install_docker
+++ b/usr/local/sbin/install_docker
@@ -23,16 +23,16 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 
-	BIN_DOCKER="/usr/bin/docker";
-	BIN_DOCKER_COMPOSE="/usr/local/bin/docker-compose";
+  BIN_DOCKER="/usr/bin/docker";
+  BIN_DOCKER_COMPOSE="/usr/local/bin/docker-compose";
 
-	# ------------------------------------------------------------
-	if [ -n "$(which get_os 2>'/dev/null';)" ] && [[ "$(get_os)" == *"Microsoft"* ]]; then
+  # ------------------------------------------------------------
+  if [ -n "$(which get_os 2>'/dev/null';)" ] && [[ "$(get_os)" == *"Microsoft"* ]]; then
     #
     # WSL Docker Installation
     #
@@ -57,7 +57,7 @@ else
     ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" "${BIN_DOCKER}";
     ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe" "${BIN_DOCKER_COMPOSE}";
 
-	else # ------------------------------------------------------------
+  else # ------------------------------------------------------------
     #
     # Non-WSL Docker Installation
     #
@@ -106,12 +106,12 @@ else
 
     fi;
     
-	fi;
+  fi;
 
-	systemctl enable docker --now;
+  systemctl enable docker --now;
 
-	"${BIN_DOCKER}" --version;
-	"${BIN_DOCKER_COMPOSE}" --version;
+  "${BIN_DOCKER}" --version;
+  "${BIN_DOCKER_COMPOSE}" --version;
 
 fi;
 
diff --git a/usr/local/sbin/install_dotnet b/usr/local/sbin/install_dotnet
--- a/usr/local/sbin/install_dotnet
+++ b/usr/local/sbin/install_dotnet
@@ -17,13 +17,13 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	
-	if [[ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]]; then
+  # ------------------------------------------------------------
+  
+  if [[ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]]; then
     #
     # UBUNTU Environment
     #
@@ -57,9 +57,9 @@ else
 
     fi;
 
-	fi;
+  fi;
 
-	if [ "$(which dotnet 2>'/dev/null')" == "" ]; then
+  if [ "$(which dotnet 2>'/dev/null')" == "" ]; then
     # UNKNOWN/UNHANDLED OPERATING SYSTEM
     echo "";
     echo "Unhandled version of Linux:";
@@ -70,7 +70,7 @@ else
     echo "Please see Microsoft's tutorial page for installing DotNet Core @:";
     echo " |    ";
     echo " |--> https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current";
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/install_java b/usr/local/sbin/install_java
--- a/usr/local/sbin/install_java
+++ b/usr/local/sbin/install_java
@@ -14,26 +14,26 @@ fi;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Install Java SE8 (Standard Edition 8) "Headless" version (e.g. "CLI" or "Minimal")
-	SERVICE_NAME="java";
+  # ------------------------------------------------------------
+  # Install Java SE8 (Standard Edition 8) "Headless" version (e.g. "CLI" or "Minimal")
+  SERVICE_NAME="java";
 
-	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+  if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
     PACKAGE_NAME="openjdk-8-jre-headless"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Distros: Debian, Ubuntu, etc.
     # PACKAGE_NAME_DEVTOOLS="openjdk-8-jdk-headless"; apt-get -y update; apt-get -y install "${PACKAGE_NAME_DEVTOOLS}"; # Distros: Debian, Ubuntu, etc.
-	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+  elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
     PACKAGE_NAME="java-1.8.0-openjdk-headless"; yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
     # PACKAGE_NAME_DEVTOOLS="java-1.8.0-openjdk-devel"; yum -y check-update; yum -y install "${PACKAGE_NAME_DEVTOOLS}"; # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
-	# Setup Java
-	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	if [ ${SERVICE_RET_CODE} -eq 0 ]; then
+  # ------------------------------------------------------------
+  # Setup Java
+  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  if [ ${SERVICE_RET_CODE} -eq 0 ]; then
 
     # Show local Java runtime's settings/properties
     JAVA_ALL_SETTINGS="$(java -XshowSettings:properties -version 2>&1;)"; echo "JAVA_ALL_SETTINGS = [ ${JAVA_ALL_SETTINGS} ]";  # Note: Java outputs to STDERR (2) by default - Redirect its output to STDOUT (1) by using 2>&1
@@ -85,7 +85,7 @@ else
     echo "Info:  Calling [ chmod 0644 \"${LOCAL_JAVA_FONTCONFIG_PROPS}\"; ]...";
     chmod 0644 "${LOCAL_JAVA_FONTCONFIG_PROPS}";
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/install_jenkins b/usr/local/sbin/install_jenkins
--- a/usr/local/sbin/install_jenkins
+++ b/usr/local/sbin/install_jenkins
@@ -27,53 +27,53 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Install Jenkins CI/CD Server
-	SERVICE_NAME="jenkins";
+  # ------------------------------------------------------------
+  # Install Jenkins CI/CD Server
+  SERVICE_NAME="jenkins";
 
-	# ------------------------------------------------------------
-	#
-	# Docker-based installs:
-	#	"/usr/local/bin/docker_create_jenkins"
-	#  |--> docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean
-	#  |--> docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkins:alpine
-	#
-	# ------------------------------------------------------------
-	#
-	# Instantiate runtime variables
+  # ------------------------------------------------------------
+  #
+  # Docker-based installs:
+  #	"/usr/local/bin/docker_create_jenkins"
+  #  |--> docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean
+  #  |--> docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkins:alpine
+  #
+  # ------------------------------------------------------------
+  #
+  # Instantiate runtime variables
 
-	SERVICE_LOGFILE="/var/log/jenkins/jenkins.log";
+  SERVICE_LOGFILE="/var/log/jenkins/jenkins.log";
 
-	SERVICE_TOKEN_FILEPATH="/var/lib/jenkins/secrets/initialAdminPassword";
+  SERVICE_TOKEN_FILEPATH="/var/lib/jenkins/secrets/initialAdminPassword";
 
-	SERVICE_RESTART_REQD=0;
-	
-	EXIT_CODE=1; # Default to error-ing out. Only return success if every check passes
+  SERVICE_RESTART_REQD=0;
+  
+  EXIT_CODE=1; # Default to error-ing out. Only return success if every check passes
 
-	START_SECONDS_NANOSECONDS=$(date +'%s.%N');
-	START_EPOCHSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 1);
-	# START_NANOSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 2 | cut --characters 1-9);
-	# START_MICROSECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-6);
-	# START_MILLISECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-3);
-	START_DATETIME="$(date --date=@${START_EPOCHSECONDS} +'%Y-%m-%d %H:%M:%S')";
-	START_TIMESTAMP="$(date --date=@${START_EPOCHSECONDS} +'%Y%m%d_%H%M%S')";
+  START_SECONDS_NANOSECONDS=$(date +'%s.%N');
+  START_EPOCHSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 1);
+  # START_NANOSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 2 | cut --characters 1-9);
+  # START_MICROSECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-6);
+  # START_MILLISECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-3);
+  START_DATETIME="$(date --date=@${START_EPOCHSECONDS} +'%Y-%m-%d %H:%M:%S')";
+  START_TIMESTAMP="$(date --date=@${START_EPOCHSECONDS} +'%Y%m%d_%H%M%S')";
 
-	BENCHMARK_START=${START_SECONDS_NANOSECONDS};
+  BENCHMARK_START=${START_SECONDS_NANOSECONDS};
 
-	# ------------------------------------------------------------
-	# Parse inline arguments (passed to current script)
+  # ------------------------------------------------------------
+  # Parse inline arguments (passed to current script)
 
-	ARGS=("$@");
-	ARGS_COUNT=${#ARGS[@]};
+  ARGS=("$@");
+  ARGS_COUNT=${#ARGS[@]};
 
-	ARGS_FORCE_AGREE=0;
-	
-	# Walk through any inline-arguments passed to this function
-	for (( i=0;i<$ARGS_COUNT;i++ )); do
+  ARGS_FORCE_AGREE=0;
+  
+  # Walk through any inline-arguments passed to this function
+  for (( i=0;i<$ARGS_COUNT;i++ )); do
 
     EACH_ARG=${ARGS[${i}]};
 
@@ -95,9 +95,9 @@ else
 
     fi;
 
-	done;
+  done;
 
-	if [ ${ARGS_FORCE_AGREE} -eq 0 ]; then
+  if [ ${ARGS_FORCE_AGREE} -eq 0 ]; then
     echo "------------------------------------------------------------";
     echo "";
     echo "Info:  This will install the Jenkins CI/CD service";
@@ -115,18 +115,18 @@ else
       echo "Denied - Skipping the \"${SERVICE_NAME}\" service install";
       exit 1;
     fi;
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
-	# Check for the Jenkins service locally
-	# SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	# if [ ${SERVICE_RET_CODE} -eq 0 ]; then
-	# 	# Jenkins is already installed
-	# 	echo -e "\n""Info:  Skipping Jenkins package-install (service already exists locally)";
-	# else
+  # ------------------------------------------------------------
+  # Check for the Jenkins service locally
+  # SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  # if [ ${SERVICE_RET_CODE} -eq 0 ]; then
+  # 	# Jenkins is already installed
+  # 	echo -e "\n""Info:  Skipping Jenkins package-install (service already exists locally)";
+  # else
 
-	# ------------------------------------------------------------
-	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Distros: Debian, Ubuntu, etc.
+  # ------------------------------------------------------------
+  if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Distros: Debian, Ubuntu, etc.
 
     # ------------------------------------------------------------
     # Install Java
@@ -148,7 +148,7 @@ else
     PACKAGE_APT="jenkins"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Jenkins
 
 
-	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
+  elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
 
     # ------------------------------------------------------------
     # Install Java
@@ -189,26 +189,26 @@ else
       yum -y check-update; yum -y install "${PACKAGE_YUM}"; # Install Jenkins
     fi;
 
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
-	# Autostart the service on bootup (as well as right now)
-	#
-	if \
+  # ------------------------------------------------------------
+  # Autostart the service on bootup (as well as right now)
+  #
+  if \
     [ "$(systemctl is-enabled ${SERVICE_NAME}.service 2>/dev/null;)" != "enabled" ] || \
     [ "$(systemctl is-active ${SERVICE_NAME}.service 2>/dev/null;)" != "active" ] || \
     [ $(systemctl is-enabled ${SERVICE_NAME}.service 1>/dev/null 2>&1; echo $?;) -ne 0 ] || \
     [ $(systemctl is-active ${SERVICE_NAME}.service 1>/dev/null 2>&1; echo $?;) -ne 0 ]; \
-	then
+  then
     echo "Info:  Service \"${SERVICE_NAME}\" is not both \"enabled\" and \"active\", currently";
     echo "Info:  Calling  [ systemctl enable \"${SERVICE_NAME}.service\" --now; ]  ...";
     systemctl enable "${SERVICE_NAME}.service" --now; # "enable --now" autostarts service at bootup && starts service immediately
-	fi;
+  fi;
 
 
-	# ------------------------------------------------------------
-	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	if [ ${SERVICE_RET_CODE} -eq 0 ]; then
+  # ------------------------------------------------------------
+  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  if [ ${SERVICE_RET_CODE} -eq 0 ]; then
     EXIT_CODE=0;
 
     # Show Jenkins' service status
@@ -260,24 +260,24 @@ else
       fi;
     fi;
 
-	else
+  else
     EXIT_CODE=1;
     # ERROR - Jenkins Service STILL not detected after install-attempt
     echo -e "\n""Error:  Jenkins service not detected after install attempt";
 
-	fi;
+  fi;
 
 
-	# ------------------------------------------------------------
-	# Sync jenkins-config to cloud-infrastructure repo (require user confirmation)
-	JENKINS_CONFIG_PATH="";
-	if [ -f "/etc/default/jenkins" ]; then
+  # ------------------------------------------------------------
+  # Sync jenkins-config to cloud-infrastructure repo (require user confirmation)
+  JENKINS_CONFIG_PATH="";
+  if [ -f "/etc/default/jenkins" ]; then
     JENKINS_CONFIG_PATH="/etc/default/jenkins";
-	elif [ -f "/etc/sysconfig/jenkins" ]; then
+  elif [ -f "/etc/sysconfig/jenkins" ]; then
     JENKINS_CONFIG_PATH="/etc/sysconfig/jenkins";
-	fi;
+  fi;
 
-	if [ -n "${JENKINS_CONFIG_PATH}" ]; then
+  if [ -n "${JENKINS_CONFIG_PATH}" ]; then
     if [ ${ARGS_FORCE_AGREE} -eq 0 ]; then
       # Not Forced
       echo "";
@@ -300,68 +300,68 @@ else
     else
       echo "Denied - Skipping Jenkins config-file sync";
     fi;
-	fi;
+  fi;
 
-	# Start/Restart the service (will build the Jenkins service from the ground-up if it was just installed)
-	/usr/sbin/service "${SERVICE_NAME}" restart;
-	### /usr/sbin/service "${SERVICE_NAME}" status;
+  # Start/Restart the service (will build the Jenkins service from the ground-up if it was just installed)
+  /usr/sbin/service "${SERVICE_NAME}" restart;
+  ### /usr/sbin/service "${SERVICE_NAME}" status;
 
-	# ------------------------------------------------------------
-	#
-	# ESCAPED_ASTERISKS="\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*";
-	# echo "*************************************************************";
-	# echo "*************************************************************";
-	# echo "*************************************************************";
-	# Wait until the Jenkins Logfile contains the Admin Password required for the user to log-in with for the first time
-	# if [ -z "$(cat ${SERVICE_LOGFILE} | grep ${ESCAPED_ASTERISKS};)" ]; then
-	# 	SED_TAIL_UNTIL="/${ESCAPED_ASTERISKS}/ q";
-	# 	tail -n +1 -f "${SERVICE_LOGFILE}" | sed "${SED_TAIL_UNTIL}";
-	# 	sleep 1;
-	# fi;
-	# while [ -z "$(cat ${SERVICE_LOGFILE} | grep ${ESCAPED_ASTERISKS};)" ]; do
-	# 	sleep 2;
-	# 	echo "Waiting 2s for \"${SERVICE_LOGFILE}\" to contain Admin Password";
-	# done;
-	#
+  # ------------------------------------------------------------
+  #
+  # ESCAPED_ASTERISKS="\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*";
+  # echo "*************************************************************";
+  # echo "*************************************************************";
+  # echo "*************************************************************";
+  # Wait until the Jenkins Logfile contains the Admin Password required for the user to log-in with for the first time
+  # if [ -z "$(cat ${SERVICE_LOGFILE} | grep ${ESCAPED_ASTERISKS};)" ]; then
+  # 	SED_TAIL_UNTIL="/${ESCAPED_ASTERISKS}/ q";
+  # 	tail -n +1 -f "${SERVICE_LOGFILE}" | sed "${SED_TAIL_UNTIL}";
+  # 	sleep 1;
+  # fi;
+  # while [ -z "$(cat ${SERVICE_LOGFILE} | grep ${ESCAPED_ASTERISKS};)" ]; do
+  # 	sleep 2;
+  # 	echo "Waiting 2s for \"${SERVICE_LOGFILE}\" to contain Admin Password";
+  # done;
+  #
 
-	echo "";
-	echo "Jenkins installed!";
-	echo "";
-	echo "Waiting for \"${SERVICE_TOKEN_FILEPATH}\" to be created w/ initial Jenkins admin token (password)";
-	echo "  ( Cancel with Ctrl+C )";
-	
-	CURRENT_WAIT_DURATION=0;
-	
-	MAX_WAIT_DURATION=30;
-	
-	ESCAPED_ASTERISKS="\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*";
+  echo "";
+  echo "Jenkins installed!";
+  echo "";
+  echo "Waiting for \"${SERVICE_TOKEN_FILEPATH}\" to be created w/ initial Jenkins admin token (password)";
+  echo "  ( Cancel with Ctrl+C )";
+  
+  CURRENT_WAIT_DURATION=0;
+  
+  MAX_WAIT_DURATION=30;
+  
+  ESCAPED_ASTERISKS="\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*";
 
-	while [ ! -f "${SERVICE_TOKEN_FILEPATH}" ] && [ ${CURRENT_WAIT_DURATION} -lt ${MAX_WAIT_DURATION} ]; do
+  while [ ! -f "${SERVICE_TOKEN_FILEPATH}" ] && [ ${CURRENT_WAIT_DURATION} -lt ${MAX_WAIT_DURATION} ]; do
     CURRENT_WAIT_DURATION=$((${CURRENT_WAIT_DURATION}+1));
     sleep 1;
-	done;
-	sleep 1;
+  done;
+  sleep 1;
 
-	clear;
-	
-	SERVICE_INITIAL_TOKEN="";
-	SERVICE_TOKEN_ECHO="";
-	if [ -f "${SERVICE_TOKEN_FILEPATH}" ]; then
+  clear;
+  
+  SERVICE_INITIAL_TOKEN="";
+  SERVICE_TOKEN_ECHO="";
+  if [ -f "${SERVICE_TOKEN_FILEPATH}" ]; then
     # Read-in the initial token
     SERVICE_INITIAL_TOKEN=$(cat "${SERVICE_TOKEN_FILEPATH}");
     SERVICE_TOKEN_ECHO="
 Contents of \"${SERVICE_TOKEN_FILEPATH}\":
 ${SERVICE_INITIAL_TOKEN}
 ";
-	elif [ -n "$(cat ${SERVICE_LOGFILE} | grep ${ESCAPED_ASTERISKS};)" ]; then
+  elif [ -n "$(cat ${SERVICE_LOGFILE} | grep ${ESCAPED_ASTERISKS};)" ]; then
     # Attempt to parse the token from Jenkins' logfile
     JENKINS_LOG_SETUP_FIRST_LINE=$(cat -n "${SERVICE_LOGFILE}" | grep ${ESCAPED_ASTERISKS} | awk '{print $1}' | head -n 1;);
     JENKINS_LOG_SETUP_LAST_LINE=$(cat -n "${SERVICE_LOGFILE}" |  grep ${ESCAPED_ASTERISKS} | awk '{print $1}' | tail -n 1;);
     SERVICE_TOKEN_ECHO="$(sed -n ${JENKINS_LOG_SETUP_FIRST_LINE},${JENKINS_LOG_SETUP_LAST_LINE}p ${SERVICE_LOGFILE};)";
     # SERVICE_INITIAL_TOKEN="$(sed -n ${JENKINS_LOG_SETUP_FIRST_LINE},${JENKINS_LOG_SETUP_LAST_LINE}p ${SERVICE_LOGFILE};)";
-	fi;
+  fi;
 
-	if [ -n "${SERVICE_TOKEN_ECHO}" ]; then
+  if [ -n "${SERVICE_TOKEN_ECHO}" ]; then
 
     # ------------------------------------------------------------
     # Display the IPv4 of this server as a suggestion to help the user to get logged into Jenkins
@@ -377,20 +377,20 @@ ${SERVICE_INITIAL_TOKEN}
     echo "Initial admin token (required to activate new Jenkins service):";
     echo -e "${SERVICE_TOKEN_ECHO}";
     echo "";
-	else
+  else
     EXIT_CODE=1;
     # ERROR - Jenkins initial admin token not found
     echo -e "\n""Error:  Unable to locate jenkins token (required to activate new Jenkins service)";
 
-	fi;
+  fi;
 
 
-	echo "*************************************************************";
-	echo "";
-	BENCHMARK_DELTA=$(echo "scale=4; ($(date +'%s.%N') - ${BENCHMARK_START})/1" | bc -l);
-	echo "End of Line - Net runtime was ${BENCHMARK_DELTA}s";
-	echo "";
-	exit ${EXIT_CODE};
+  echo "*************************************************************";
+  echo "";
+  BENCHMARK_DELTA=$(echo "scale=4; ($(date +'%s.%N') - ${BENCHMARK_START})/1" | bc -l);
+  echo "End of Line - Net runtime was ${BENCHMARK_DELTA}s";
+  echo "";
+  exit ${EXIT_CODE};
 
 fi;
 
diff --git a/usr/local/sbin/install_jenkins_plugins b/usr/local/sbin/install_jenkins_plugins
--- a/usr/local/sbin/install_jenkins_plugins
+++ b/usr/local/sbin/install_jenkins_plugins
@@ -18,45 +18,45 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Instantiate runtime variables
-	
-	if [ -n "$1" ]; then
+  # ------------------------------------------------------------
+  # Instantiate runtime variables
+  
+  if [ -n "$1" ]; then
     java -jar jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin "$1";
-	else
+  else
     echo "Error: Please include plugin name as first parameter (\$1)";
-	fi;
+  fi;
 
-	# # Log all shell output & error output to Logfile
-	# THIS_SCRIPT=$(basename "${0}")
-	# THIS_DIR=$(dirname "${0}")
-	# LOGFILE="${THIS_DIR}/logfile__${THIS_SCRIPT}" && touch "${LOGFILE}" && chmod 600 "${LOGFILE}"
-	# exec > >(tee -a "${LOGFILE}" )
-	# exec 2>&1
-	# echo "===== ------------------------------------------------------------ ====="
-	# echo "$(date +'%D  %r')   Starting ${THIS_SCRIPT}..."
+  # # Log all shell output & error output to Logfile
+  # THIS_SCRIPT=$(basename "${0}")
+  # THIS_DIR=$(dirname "${0}")
+  # LOGFILE="${THIS_DIR}/logfile__${THIS_SCRIPT}" && touch "${LOGFILE}" && chmod 600 "${LOGFILE}"
+  # exec > >(tee -a "${LOGFILE}" )
+  # exec 2>&1
+  # echo "===== ------------------------------------------------------------ ====="
+  # echo "$(date +'%D  %r')   Starting ${THIS_SCRIPT}..."
 
-	# # SCRIPT TO UPDATE ALL JENKINS PLUGINS
-	# JENKINS_CLI_PATH="/var/cache/jenkins/war/WEB-INF/jenkins-cli.jar";
-	# CREDENTIALS="/var/lib/db_conn/shell_credentials_jenkins_localtrigger.conf";
-	# SERVER="http://127.0.0.1:8080/";
-	# source "${CREDENTIALS}";
-	# PLUGIN_UPDATE_LIST=$( java -jar "${JENKINS_CLI_PATH}" -auth "${USER}:${SECRET}" -s "${SERVER}" list-plugins | grep -e ')$' | awk '{ print $1 }' );
-	# if [ ! -z "${PLUGIN_UPDATE_LIST}" ]; then 
-	#   echo "$(date +'%D  %r') Updating Jenkins Plugins: [${PLUGIN_UPDATE_LIST}] ...";
-	#   java -jar "${JENKINS_CLI_PATH}" -auth "${USER}:${SECRET}" -s "${SERVER}" install-plugin "${PLUGIN_UPDATE_LIST}";
-	# 	echo "$(date +'%D  %r') Plugin Updates Finished, Restarting Jenkins ..."
-	#   java -jar "${JENKINS_CLI_PATH}" -auth "${USER}:${SECRET}" -s "${SERVER}" safe-restart;
-	# else
-	# 	echo "$(date +'%D  %r') No Plugins to Update";
-	# fi
+  # # SCRIPT TO UPDATE ALL JENKINS PLUGINS
+  # JENKINS_CLI_PATH="/var/cache/jenkins/war/WEB-INF/jenkins-cli.jar";
+  # CREDENTIALS="/var/lib/db_conn/shell_credentials_jenkins_localtrigger.conf";
+  # SERVER="http://127.0.0.1:8080/";
+  # source "${CREDENTIALS}";
+  # PLUGIN_UPDATE_LIST=$( java -jar "${JENKINS_CLI_PATH}" -auth "${USER}:${SECRET}" -s "${SERVER}" list-plugins | grep -e ')$' | awk '{ print $1 }' );
+  # if [ ! -z "${PLUGIN_UPDATE_LIST}" ]; then 
+  #   echo "$(date +'%D  %r') Updating Jenkins Plugins: [${PLUGIN_UPDATE_LIST}] ...";
+  #   java -jar "${JENKINS_CLI_PATH}" -auth "${USER}:${SECRET}" -s "${SERVER}" install-plugin "${PLUGIN_UPDATE_LIST}";
+  # 	echo "$(date +'%D  %r') Plugin Updates Finished, Restarting Jenkins ..."
+  #   java -jar "${JENKINS_CLI_PATH}" -auth "${USER}:${SECRET}" -s "${SERVER}" safe-restart;
+  # else
+  # 	echo "$(date +'%D  %r') No Plugins to Update";
+  # fi
 
-	# echo "$(date +'%D  %r') Finished ${THIS_SCRIPT}";
-	# exit 0;
+  # echo "$(date +'%D  %r') Finished ${THIS_SCRIPT}";
+  # exit 0;
 
 fi;
 
@@ -90,143 +90,143 @@ fi;
 ### Output from [  java -jar "${JENKINS_CLI_PATH}" -auth "${USER}:${SECRET}" -s "${SERVER}"  ]:
 #
 # add-job-to-view
-	# Adds jobs to view.
+  # Adds jobs to view.
 # build
-	# Builds a job, and optionally waits until its completion.
+  # Builds a job, and optionally waits until its completion.
 # cancel-quiet-down
-	# Cancel the effect of the "quiet-down" command.
+  # Cancel the effect of the "quiet-down" command.
 # clear-queue
-	# Clears the build queue.
+  # Clears the build queue.
 # connect-node
-	# Reconnect to a node(s)
+  # Reconnect to a node(s)
 # console
-	# Retrieves console output of a build.
+  # Retrieves console output of a build.
 # copy-job
-	# Copies a job.
+  # Copies a job.
 # create-credentials-by-xml
-	# Create Credential by XML
+  # Create Credential by XML
 # create-credentials-domain-by-xml
-	# Create Credentials Domain by XML
+  # Create Credentials Domain by XML
 # create-job
-	# Creates a new job by reading stdin as a configuration XML file.
+  # Creates a new job by reading stdin as a configuration XML file.
 # create-node
-	# Creates a new node by reading stdin as a XML configuration.
+  # Creates a new node by reading stdin as a XML configuration.
 # create-view
-	# Creates a new view by reading stdin as a XML configuration.
+  # Creates a new view by reading stdin as a XML configuration.
 # declarative-linter
-	# Validate a Jenkinsfile containing a Declarative Pipeline
+  # Validate a Jenkinsfile containing a Declarative Pipeline
 # delete-builds
-	# Deletes build record(s).
+  # Deletes build record(s).
 # delete-credentials
-	# Delete a Credential
+  # Delete a Credential
 # delete-credentials-domain
-	# Delete a Credentials Domain
+  # Delete a Credentials Domain
 # delete-job
-	# Deletes job(s).
+  # Deletes job(s).
 # delete-node
-	# Deletes node(s)
+  # Deletes node(s)
 # delete-view
-	# Deletes view(s).
+  # Deletes view(s).
 # disable-job
-	# Disables a job.
+  # Disables a job.
 # disconnect-node
-	# Disconnects from a node.
+  # Disconnects from a node.
 # enable-job
-	# Enables a job.
+  # Enables a job.
 # get-credentials-as-xml
-	# Get a Credentials as XML (secrets redacted)
+  # Get a Credentials as XML (secrets redacted)
 # get-credentials-domain-as-xml
-	# Get a Credentials Domain as XML
+  # Get a Credentials Domain as XML
 # get-gradle
-	# List available gradle installations
+  # List available gradle installations
 # get-job
-	# Dumps the job definition XML to stdout.
+  # Dumps the job definition XML to stdout.
 # get-node
-	# Dumps the node definition XML to stdout.
+  # Dumps the node definition XML to stdout.
 # get-view
-	# Dumps the view definition XML to stdout.
+  # Dumps the view definition XML to stdout.
 # groovy
-	# Executes the specified Groovy script.
+  # Executes the specified Groovy script.
 # groovysh
-	# Runs an interactive groovy shell.
+  # Runs an interactive groovy shell.
 # help
-	# Lists all the available commands or a detailed description of single command.
+  # Lists all the available commands or a detailed description of single command.
 # install-plugin
-	# Installs a plugin either from a file, an URL, or from update center.
+  # Installs a plugin either from a file, an URL, or from update center.
 # install-tool
-	# Performs automatic tool installation, and print its location to stdout. Can be only called from inside a build. [deprecated]
+  # Performs automatic tool installation, and print its location to stdout. Can be only called from inside a build. [deprecated]
 # keep-build
-	# Mark the build to keep the build forever.
+  # Mark the build to keep the build forever.
 # list-changes
-	# Dumps the changelog for the specified build(s).
+  # Dumps the changelog for the specified build(s).
 # list-credentials
-	# Lists the Credentials in a specific Store
+  # Lists the Credentials in a specific Store
 # list-credentials-context-resolvers
-	# List Credentials Context Resolvers
+  # List Credentials Context Resolvers
 # list-credentials-providers
-	# List Credentials Providers
+  # List Credentials Providers
 # list-jobs
-	# Lists all jobs in a specific view or item group.
+  # Lists all jobs in a specific view or item group.
 # list-plugins
-	# Outputs a list of installed plugins.
+  # Outputs a list of installed plugins.
 # login
-	# Saves the current credentials to allow future commands to run without explicit credential information. [deprecated]
+  # Saves the current credentials to allow future commands to run without explicit credential information. [deprecated]
 # logout
-	# Deletes the credentials stored with the login command. [deprecated]
+  # Deletes the credentials stored with the login command. [deprecated]
 # mail
-	# Reads stdin and sends that out as an e-mail.
+  # Reads stdin and sends that out as an e-mail.
 # offline-node
-	# Stop using a node for performing builds temporarily, until the next "online-node" command.
+  # Stop using a node for performing builds temporarily, until the next "online-node" command.
 # online-node
-	# Resume using a node for performing builds, to cancel out the earlier "offline-node" command.
+  # Resume using a node for performing builds, to cancel out the earlier "offline-node" command.
 # quiet-down
-	# Quiet down Jenkins, in preparation for a restart. Don’t start any builds.
+  # Quiet down Jenkins, in preparation for a restart. Don’t start any builds.
 # reload-configuration
-	# Discard all the loaded data in memory and reload everything from file system. Useful when you modified config files directly on disk.
+  # Discard all the loaded data in memory and reload everything from file system. Useful when you modified config files directly on disk.
 # reload-job
-	# Reload job(s)
+  # Reload job(s)
 # remove-job-from-view
-	# Removes jobs from view.
+  # Removes jobs from view.
 # replay-pipeline
-	# Replay a Pipeline build with edited script taken from standard input
+  # Replay a Pipeline build with edited script taken from standard input
 # restart
-	# Restart Jenkins.
+  # Restart Jenkins.
 # safe-restart
-	# Safely restart Jenkins.
+  # Safely restart Jenkins.
 # safe-shutdown
-	# Puts Jenkins into the quiet mode, wait for existing builds to be completed, and then shut down Jenkins.
+  # Puts Jenkins into the quiet mode, wait for existing builds to be completed, and then shut down Jenkins.
 # session-id
-	# Outputs the session ID, which changes every time Jenkins restarts.
+  # Outputs the session ID, which changes every time Jenkins restarts.
 # set-build-description
-	# Sets the description of a build.
+  # Sets the description of a build.
 # set-build-display-name
-	# Sets the displayName of a build.
+  # Sets the displayName of a build.
 # set-build-parameter
-	# Update/set the build parameter of the current build in progress. [deprecated]
+  # Update/set the build parameter of the current build in progress. [deprecated]
 # set-build-result
-	# Sets the result of the current build. Works only if invoked from within a build. [deprecated]
+  # Sets the result of the current build. Works only if invoked from within a build. [deprecated]
 # set-external-build-result
-	# Set external monitor job result.
+  # Set external monitor job result.
 # shutdown
-	# Immediately shuts down Jenkins server.
+  # Immediately shuts down Jenkins server.
 # update-credentials-by-xml
-	# Update Credentials by XML
+  # Update Credentials by XML
 # update-credentials-domain-by-xml
-	# Update Credentials Domain by XML
+  # Update Credentials Domain by XML
 # update-job
-	# Updates the job definition XML from stdin. The opposite of the get-job command.
+  # Updates the job definition XML from stdin. The opposite of the get-job command.
 # update-node
-	# Updates the node definition XML from stdin. The opposite of the get-node command.
+  # Updates the node definition XML from stdin. The opposite of the get-node command.
 # update-view
-	# Updates the view definition XML from stdin. The opposite of the get-view command.
+  # Updates the view definition XML from stdin. The opposite of the get-view command.
 # version
-	# Outputs the current version.
+  # Outputs the current version.
 # wait-node-offline
-	# Wait for a node to become offline.
+  # Wait for a node to become offline.
 # wait-node-online
-	# Wait for a node to become online.
+  # Wait for a node to become online.
 # who-am-i
-	# Reports your credential and permissions.
+  # Reports your credential and permissions.
 #
 # ------------------------------------------------------------
 # Citation(s)
diff --git a/usr/local/sbin/install_kdump b/usr/local/sbin/install_kdump
--- a/usr/local/sbin/install_kdump
+++ b/usr/local/sbin/install_kdump
@@ -13,24 +13,24 @@ fi;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	# Install/setup kernel crash dump logging for use during RCA auditing workflows
-	#
-	SERVICE_NAME="kdump";
+  # ------------------------------------------------------------
+  #
+  # Install/setup kernel crash dump logging for use during RCA auditing workflows
+  #
+  SERVICE_NAME="kdump";
 
-	#	Search for one, specific service
-	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	echo "------------------------------------------------------------";
-	if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service FOUND locally
+  #	Search for one, specific service
+  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  echo "------------------------------------------------------------";
+  if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service FOUND locally
     echo "";
     echo "Info:  Service \"kdump\" found to exist locally (skipping package-install)";
     /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
-	else # Service NOT found locally
+  else # Service NOT found locally
     echo "";
     echo "Warning:  Service \"${SERVICE_NAME}\" not found locally";
     echo "";
@@ -42,10 +42,10 @@ else
         yum -y install kexec-tools;
       fi;
     fi;
-	fi;
+  fi;
 
 
-	if [ -f "/etc/default/grub" ]; then
+  if [ -f "/etc/default/grub" ]; then
     #
     # Enabling Grub2's "crashkernel" setting
     #
@@ -59,10 +59,10 @@ else
       # Add inline argument "... crashkernel=auto ..." to grub startup options
       sed -i".$(date +'%Y%m%d_%H%M%S').bak" -re "s/^(GRUB_CMDLINE_LINUX=\".+)\"\$/\1 crashkernel=auto\"/" "/etc/default/grub";
     fi;
-	fi;
+  fi;
 
 
-	if [ -f "/etc/kdump.conf" ]; then
+  if [ -f "/etc/kdump.conf" ]; then
     #
     # Enabling KDump's "path" setting
     #
@@ -92,24 +92,24 @@ else
       # Add inline argument "... crashkernel=auto ..." to grub startup options
       echo "default dump_to_rootfs" > "/etc/kdump.conf";
     fi;
-	fi;
+  fi;
 
-	
-	# Verify that taget service is enabled
-	if [ "$(systemctl is-enabled ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" == "0" ]; then
+  
+  # Verify that taget service is enabled
+  if [ "$(systemctl is-enabled ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" == "0" ]; then
     echo "Info:  Service \"kdump\" is enabled (skipping enable-service)";
-	else
+  else
     echo "Warning:  Service \"kdump\" is not enabled --> Enabling it, now...";
     systemctl enable ${SERVICE_NAME};
-	fi;
+  fi;
 
-	# Verify that taget service is active
-	if [ "$(systemctl is-active ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" == "0" ]; then
+  # Verify that taget service is active
+  if [ "$(systemctl is-active ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" == "0" ]; then
     echo "Info:  Service \"kdump\" is active (skipping start-service)";
-	else
+  else
     echo "Warning:  Service \"kdump\" is not active --> Starting it, now...";
     systemctl start ${SERVICE_NAME};
-	fi;
+  fi;
 
 
 fi;
diff --git a/usr/local/sbin/install_minio b/usr/local/sbin/install_minio
--- a/usr/local/sbin/install_minio
+++ b/usr/local/sbin/install_minio
@@ -23,33 +23,33 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	RET_CODE=1;
-	if [ -n "$(which mc)" ]; then
+  RET_CODE=1;
+  if [ -n "$(which mc)" ]; then
     echo "Info: Skipping install of [ mc ] command - Calling [ which mc ] returned [ $(which mc) ";
 
-	elif [ -f "/usr/local/bin/mc" ]; then
+  elif [ -f "/usr/local/bin/mc" ]; then
     echo "Info: Skipping install of [ mc ] command - File \"/usr/local/bin/mc\" already exists";
 
-	else
+  else
     # Download MC (as-per reccommend by MinIO Guide ( see Citation(s), below )
     echo "Info: Adding MinIO management package - Call using command [ mc ]";
     curl -ssL "https://dl.min.io/client/mc/release/linux-amd64/mc" -o "/usr/local/bin/mc" && chmod 0755 "/usr/local/bin/mc";
 
-	fi;
+  fi;
 
-	# Ensure that docker is installed
-	curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_docker?t=$(date +'%s.%N')" | bash;
+  # Ensure that docker is installed
+  curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_docker?t=$(date +'%s.%N')" | bash;
 
-	# Ensure the docker-service is started
-	SERVICE_NAME="docker";
-	/usr/sbin/service "${SERVICE_NAME}" start;
+  # Ensure the docker-service is started
+  SERVICE_NAME="docker";
+  /usr/sbin/service "${SERVICE_NAME}" start;
 
-	# Pull & Spin-up the MINIO server as a docker container ( pulls from https://hub.docker.com/r/minio/minio/ )
-	PORT_MINIO="9000"; DIR_MINIO_DATA="/data"; docker run -d --name "minio" -p "${PORT_MINIO}:9000" "minio/minio" "server" "${DIR_MINIO_DATA}";
+  # Pull & Spin-up the MINIO server as a docker container ( pulls from https://hub.docker.com/r/minio/minio/ )
+  PORT_MINIO="9000"; DIR_MINIO_DATA="/data"; docker run -d --name "minio" -p "${PORT_MINIO}:9000" "minio/minio" "server" "${DIR_MINIO_DATA}";
 
 # Locate Min-IO Config file(s)
 find \
diff --git a/usr/local/sbin/install_mongo b/usr/local/sbin/install_mongo
--- a/usr/local/sbin/install_mongo
+++ b/usr/local/sbin/install_mongo
@@ -24,18 +24,18 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Install package repo & download/install package
-	if [ $(which mongo 2>'/dev/null' | wc -l;) -gt 0 ]; then
+  # ------------------------------------------------------------
+  # Install package repo & download/install package
+  if [ $(which mongo 2>'/dev/null' | wc -l;) -gt 0 ]; then
     echo "";
     echo "Info: Command \"mongo\" already exists at path \"$(which mongo)\"";
     echo "  |--> Skipping package install";
 
-	else
+  else
     echo "";
     echo "Info: Command \"mongo\" not found";
     echo "  |--> Installing pre-required packages, then adding \"mongodb-org\" parent-repo & installing service-package...";
@@ -58,16 +58,16 @@ else
       echo -e "[mongodb-org-4.2]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.2/x86_64/\ngpgcheck=1\nenabled=1\ngpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc\n" > "/etc/yum.repos.d/mongodb-org-4.2.repo"; yum check-update; yum install -y mongodb-org;
     fi;
 
-	fi;
+  fi;
 
 
-	# ------------------------------------------------------------
-	MONGO_USER_ROW=$(echo "$(id mongod 2>'/dev/null' || id mongodb 2>'/dev/null';)" | awk '{print $1}');
-	MONGO_UID=$(echo "${MONGO_USER_ROW}" | sed -rne 's/^uid=([0-9]+)\(.+\)$/\1/p';);
-	MONGO_UNAME=$(id -un "${MONGO_UID}");
-	MONGO_GNAME=$(id -gn "${MONGO_UNAME}");
+  # ------------------------------------------------------------
+  MONGO_USER_ROW=$(echo "$(id mongod 2>'/dev/null' || id mongodb 2>'/dev/null';)" | awk '{print $1}');
+  MONGO_UID=$(echo "${MONGO_USER_ROW}" | sed -rne 's/^uid=([0-9]+)\(.+\)$/\1/p';);
+  MONGO_UNAME=$(id -un "${MONGO_UID}");
+  MONGO_GNAME=$(id -gn "${MONGO_UNAME}");
 
-	if [ -n "$(id ${MONGO_UNAME} 2>'/dev/null';)" ]; then
+  if [ -n "$(id ${MONGO_UNAME} 2>'/dev/null';)" ]; then
 
     # Setup MongoDB directories
     mkdir -p "/var/lib/mongo";
@@ -169,20 +169,20 @@ security:
 # 		fi;
 
 
-	# ------------------------------------------------------------
-	# Removing/Downgrading MongoDB
-	if [ 0 -eq 1 ]; then
+  # ------------------------------------------------------------
+  # Removing/Downgrading MongoDB
+  if [ 0 -eq 1 ]; then
     yum -y remove mongodb-org;
     yum -y remove mongodb-org-shell;
     yum -y remove mongodb-org-tools;
     yum -y remove mongodb-org-mongos;
     yum -y remove mongodb-org-server;
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
 
-	fi;
+  fi;
 fi;
 
 
diff --git a/usr/local/sbin/install_nginx b/usr/local/sbin/install_nginx
--- a/usr/local/sbin/install_nginx
+++ b/usr/local/sbin/install_nginx
@@ -14,43 +14,43 @@ fi;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Install NGINX Web Server
-	SERVICE_NAME="nginx";
+  # ------------------------------------------------------------
+  # Install NGINX Web Server
+  SERVICE_NAME="nginx";
 
-	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then  # Distros: Debian, Ubuntu, etc.
+  if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then  # Distros: Debian, Ubuntu, etc.
     apt-get -y update; apt-get -y install "dpkg-dev";
     add-apt-repository "ppa:nginx/stable";
     apt-get -y update; apt-get -y install "nginx-full";
-	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then  # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
+  elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then  # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
     yum -y check-update; yum -y install "epel-release";
     yum -y check-update; yum -y install "nginx";
-	fi;
+  fi;
 
 
-	# ------------------------------------------------------------
-	# Autostart the service on bootup (as well as right now)
-	#
-	if \
+  # ------------------------------------------------------------
+  # Autostart the service on bootup (as well as right now)
+  #
+  if \
     [ "$(systemctl is-enabled ${SERVICE_NAME}.service 2>/dev/null;)" != "enabled" ] || \
     [ "$(systemctl is-active ${SERVICE_NAME}.service 2>/dev/null;)" != "active" ] || \
     [ $(systemctl is-enabled ${SERVICE_NAME}.service 1>/dev/null 2>&1; echo $?;) -ne 0 ] || \
     [ $(systemctl is-active ${SERVICE_NAME}.service 1>/dev/null 2>&1; echo $?;) -ne 0 ]; \
-	then
+  then
     echo "Info:  Service \"${SERVICE_NAME}\" is not both \"enabled\" and \"active\", currently";
     echo "Info:  Calling  [ systemctl enable \"${SERVICE_NAME}.service\" --now; ]  ...";
     systemctl enable "${SERVICE_NAME}.service" --now; # "enable --now" autostarts service at bootup && starts service immediately
-	fi;
+  fi;
 
 
-	# ------------------------------------------------------------
-	# Setup NGINX
-	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	if [ ${SERVICE_RET_CODE} -eq 0 ]; then
+  # ------------------------------------------------------------
+  # Setup NGINX
+  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  if [ ${SERVICE_RET_CODE} -eq 0 ]; then
 
     # ------------------------------------------------------------
     # Check the NGINX service's status
@@ -116,7 +116,7 @@ else
       fi;
     fi;
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/install_ntp b/usr/local/sbin/install_ntp
--- a/usr/local/sbin/install_ntp
+++ b/usr/local/sbin/install_ntp
@@ -14,18 +14,18 @@ fi;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	# Install NTP (Time Sync) package "chrony"
-	#
-	echo "";
-	read -p "$(date +'%Y-%m-%d %H:%M:%S') Sync to NTP server(s), now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
-	echo "";
-	if [[ $REPLY =~ ^[Yy]$ ]]; then
+  # ------------------------------------------------------------
+  #
+  # Install NTP (Time Sync) package "chrony"
+  #
+  echo "";
+  read -p "$(date +'%Y-%m-%d %H:%M:%S') Sync to NTP server(s), now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
+  echo "";
+  if [[ $REPLY =~ ^[Yy]$ ]]; then
     # ------------------------------------------------------------
     #
     # Sync the system clock to NTP Server(s)
@@ -88,7 +88,7 @@ else
     timedatectl status;
     echo "------------------------------------------------------------";
     # ------------------------------------------------------------
-	fi;
+  fi;
 fi;
 
 
diff --git a/usr/local/sbin/install_pwsh b/usr/local/sbin/install_pwsh
--- a/usr/local/sbin/install_pwsh
+++ b/usr/local/sbin/install_pwsh
@@ -17,13 +17,13 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	
-	if [[ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]]; then
+  # ------------------------------------------------------------
+  
+  if [[ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]]; then
     #
     # UBUNTU Environment
     #
@@ -62,10 +62,10 @@ else
 
     fi;
 
-	fi;
+  fi;
 
 
-	if [ "$(which pwsh 2>'/dev/null')" == "" ]; then
+  if [ "$(which pwsh 2>'/dev/null')" == "" ]; then
     # UNKNOWN/UNHANDLED OPERATING SYSTEM
     echo "";
     echo "Unhandled version of Linux:";
@@ -76,16 +76,16 @@ else
     echo "Please see Microsoft's tutorial page for installing PowerShell Core @:";
     echo " |    ";
     echo " |--> https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux";
-	else
+  else
     echo "";
     echo "Testing PowerShell Core by calling [ pwsh -Command \"get-childitem env:\" ]...";
     echo "------------------------------------------------------------";
     pwsh -Command "get-childitem env:"
     echo "------------------------------------------------------------";
     echo "";
-	fi;
+  fi;
 
-	# pwsh; # Start PowerShell
+  # pwsh; # Start PowerShell
 
 fi;
 
diff --git a/usr/local/sbin/install_rclone b/usr/local/sbin/install_rclone
--- a/usr/local/sbin/install_rclone
+++ b/usr/local/sbin/install_rclone
@@ -23,43 +23,43 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 
-	curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_7z?t=$(date +'%s.%N')" | bash;
+  curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_7z?t=$(date +'%s.%N')" | bash;
 
-	curl "https://rclone.org/install.sh" | bash;
-	
-	echo "";
-	echo "View rclone s3 storage server (minio) setup/usage guide:";
-	echo "  >  https://docs.minio.io/docs/rclone-with-minio-server";
-	echo "";
-	echo "Edit rclone config via GUI tool (add/edit server connections, etc.):";
-	echo "  >  rclone config";
-	echo "";
-	echo "Edit rclone config directly:";
-	echo "  >  vi ~/.config/rclone/rclone.conf";
-	echo "";
-	echo "List s3 buckets:";
-	echo "  >  rclone lsd SERVER_ALIAS:";
-	echo "";
-	echo "List s3 bucket-files:";
-	echo "  >  rclone ls SERVER_ALIAS:BUCKET_NAME";
-	echo "";
-	echo "Print the total size and number of objects in s3 bucket:";
-	echo "  >  rclone size SERVER_ALIAS:BUCKET_NAME";
-	echo "";
-	echo "Sync one bucket to another:";
-	echo "  >  rclone sync SOURCE_ALIAS:BUCKET_NAME DESTINATION_ALIAS:BUCKET_NAME";
-	echo "";
-	echo "Sync recent items (<=2 days old) from one s3 bucket to another:";
-	echo "  >  rclone sync -v --max-age 2d SOURCE_ALIAS:BUCKET_NAME DESTINATION_ALIAS:BUCKET_NAME";
-	echo "";
-	echo "Run a background job to sync one bucket to another (limiting to 40 MBps, which is 320 Mbps):";
-	echo "  >  nohup rclone sync -v --bwlimit 40M SOURCE_ALIAS:BUCKET_NAME DESTINATION_ALIAS:BUCKET_NAME > ~/rclone.$(date +'%Y%m%d_%H%M%S').log 2>&1 &";
-	echo "";
+  curl "https://rclone.org/install.sh" | bash;
+  
+  echo "";
+  echo "View rclone s3 storage server (minio) setup/usage guide:";
+  echo "  >  https://docs.minio.io/docs/rclone-with-minio-server";
+  echo "";
+  echo "Edit rclone config via GUI tool (add/edit server connections, etc.):";
+  echo "  >  rclone config";
+  echo "";
+  echo "Edit rclone config directly:";
+  echo "  >  vi ~/.config/rclone/rclone.conf";
+  echo "";
+  echo "List s3 buckets:";
+  echo "  >  rclone lsd SERVER_ALIAS:";
+  echo "";
+  echo "List s3 bucket-files:";
+  echo "  >  rclone ls SERVER_ALIAS:BUCKET_NAME";
+  echo "";
+  echo "Print the total size and number of objects in s3 bucket:";
+  echo "  >  rclone size SERVER_ALIAS:BUCKET_NAME";
+  echo "";
+  echo "Sync one bucket to another:";
+  echo "  >  rclone sync SOURCE_ALIAS:BUCKET_NAME DESTINATION_ALIAS:BUCKET_NAME";
+  echo "";
+  echo "Sync recent items (<=2 days old) from one s3 bucket to another:";
+  echo "  >  rclone sync -v --max-age 2d SOURCE_ALIAS:BUCKET_NAME DESTINATION_ALIAS:BUCKET_NAME";
+  echo "";
+  echo "Run a background job to sync one bucket to another (limiting to 40 MBps, which is 320 Mbps):";
+  echo "  >  nohup rclone sync -v --bwlimit 40M SOURCE_ALIAS:BUCKET_NAME DESTINATION_ALIAS:BUCKET_NAME > ~/rclone.$(date +'%Y%m%d_%H%M%S').log 2>&1 &";
+  echo "";
 
 fi;
 
diff --git a/usr/local/sbin/install_rundeck b/usr/local/sbin/install_rundeck
--- a/usr/local/sbin/install_rundeck
+++ b/usr/local/sbin/install_rundeck
@@ -27,33 +27,33 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	# Install Docker for Linux
-	#
-	curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_docker?t=$(date +'%s.%N')" | bash;
+  # ------------------------------------------------------------
+  #
+  # Install Docker for Linux
+  #
+  curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_docker?t=$(date +'%s.%N')" | bash;
 
 
-	# ------------------------------------------------------------
-	#
-	# Install RunDeck CI/CD Server (as a docker)
-	#
+  # ------------------------------------------------------------
+  #
+  # Install RunDeck CI/CD Server (as a docker)
+  #
 
-	if [ ! -d "/rundeck/data" ]; then
+  if [ ! -d "/rundeck/data" ]; then
     mkdir -p "/rundeck/data";
-	fi;
+  fi;
 
-	if [ ! -f "/rundeck/docker-compose.yml" ]; then
+  if [ ! -f "/rundeck/docker-compose.yml" ]; then
     curl -o "/rundeck/docker-compose.yml" "https://raw.githubusercontent.com/rundeck/docker-zoo/master/basic/docker-compose.yml";
-	fi;
+  fi;
 
-	docker-compose -f "/rundeck/docker-compose.yml" up -d;
+  docker-compose -f "/rundeck/docker-compose.yml" up -d;
 
-	exit ${EXIT_CODE};
+  exit ${EXIT_CODE};
 
 fi;
 
diff --git a/usr/local/sbin/install_snmp b/usr/local/sbin/install_snmp
--- a/usr/local/sbin/install_snmp
+++ b/usr/local/sbin/install_snmp
@@ -23,34 +23,34 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Install SNMP & SNMP Utilities
+  # ------------------------------------------------------------
+  # Install SNMP & SNMP Utilities
 
-	if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then
+  if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then
     # Debian distros (Ubuntu, Raspbian, etc.)
     # echo -e "\n""Info:  Calling [ apt-get update -y && apt-get install -y ${MISSING_PKGS_ARRAY[@]}; ]...";
     # apt-get -y update; apt-get -y install ${MISSING_PKGS_ARRAY[@]};
     echo "Ubuntu SNMP installation not yet implemented";
     exit 1;
 
-	elif [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then
+  elif [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then
     # RHEL, CentOS
     echo -e "\n""Info:  Calling [ yum check-update -y; yum -y install net-snmp net-snmp-utils; ]...";
     yum check-update -y; yum -y install net-snmp net-snmp-utils;
     snmpconf -g basic_setup
 
-	elif [ $(which apk 2>'/dev/null' | wc -l;) -gt 0 ]; then
+  elif [ $(which apk 2>'/dev/null' | wc -l;) -gt 0 ]; then
     # Alpine
     # echo -e "\n""Info:  Calling [ apk update -y && apk add -y ${MISSING_PKGS_ARRAY[@]}; ]...";
     # apk update -y; apk add -y ${MISSING_PKGS_ARRAY[@]};
     echo "Alpine SNMP installation not yet implemented";
     exit 1;
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/install_ssh_server b/usr/local/sbin/install_ssh_server
--- a/usr/local/sbin/install_ssh_server
+++ b/usr/local/sbin/install_ssh_server
@@ -14,27 +14,27 @@ fi;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Install Java SE8 (Standard Edition 8) "Headless" version (e.g. "CLI" or "Minimal")
-	SERVICE_NAME="java";
+  # ------------------------------------------------------------
+  # Install Java SE8 (Standard Edition 8) "Headless" version (e.g. "CLI" or "Minimal")
+  SERVICE_NAME="java";
 
-	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+  if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
     PACKAGE_NAME="openssh-server"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Distros: Debian, Ubuntu, etc.
-	# elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
-	# 	PACKAGE_NAME="openssh-server"; yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
-	else
+  # elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+  # 	PACKAGE_NAME="openssh-server"; yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
+  else
     echo "";
     echo "Error:  Environment not (yet) supported, exiting...";
     exit 1;
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
-	# Setup Firewall
-	curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/sync_cloud_infrastructure?t=$(date +'%s.%N')" | bash -s -- --ufw;
+  # ------------------------------------------------------------
+  # Setup Firewall
+  curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/sync_cloud_infrastructure?t=$(date +'%s.%N')" | bash -s -- --ufw;
 
 
 fi;
diff --git a/usr/local/sbin/install_sysstat b/usr/local/sbin/install_sysstat
--- a/usr/local/sbin/install_sysstat
+++ b/usr/local/sbin/install_sysstat
@@ -14,31 +14,31 @@ fi;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Install SysStat
-	SERVICE_NAME="sysstat";
+  # ------------------------------------------------------------
+  # Install SysStat
+  SERVICE_NAME="sysstat";
 
-	if [ $(which sar 2>'/dev/null' | wc -l;) -eq 0 ]; then
+  if [ $(which sar 2>'/dev/null' | wc -l;) -eq 0 ]; then
     if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
       PACKAGE_NAME="sysstat"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}";
     elif [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
       PACKAGE_NAME="sysstat"; yum -y check-update; yum -y install "${PACKAGE_NAME}";
     fi;
-	fi;
+  fi;
 
-	# Verify that taget service is enabled
-	if [ "$(systemctl is-enabled ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" != "0" ]; then
+  # Verify that taget service is enabled
+  if [ "$(systemctl is-enabled ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" != "0" ]; then
     systemctl enable ${SERVICE_NAME};
-	fi;
+  fi;
 
-	# Verify that taget service is active
-	if [ "$(systemctl is-active ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" != "0" ]; then
+  # Verify that taget service is active
+  if [ "$(systemctl is-active ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" != "0" ]; then
     systemctl start ${SERVICE_NAME};
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/install_unifi b/usr/local/sbin/install_unifi
--- a/usr/local/sbin/install_unifi
+++ b/usr/local/sbin/install_unifi
@@ -25,19 +25,19 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Instantiate runtime variables
+  # ------------------------------------------------------------
+  # Instantiate runtime variables
 
-	echo "";
-	READ_TIMEOUT=60; read -p "Install Unifi service, now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
-	echo "";
-	if [ ${RETURN_CODE_READ} -gt 128 ]; then
+  echo "";
+  READ_TIMEOUT=60; read -p "Install Unifi service, now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
+  echo "";
+  if [ ${RETURN_CODE_READ} -gt 128 ]; then
     echo "Response timed out after ${READ_TIMEOUT}s";
-	elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
+  elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
 
     if [ -n "${1}" ]; then
       #
@@ -187,10 +187,10 @@ else
     echo "";
     echo "------------------------------------------------------------";
 
-	else
+  else
     echo "";
     echo "Denied - Skipping command";
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/install_vmware_tools b/usr/local/sbin/install_vmware_tools
--- a/usr/local/sbin/install_vmware_tools
+++ b/usr/local/sbin/install_vmware_tools
@@ -24,16 +24,16 @@ exec 2>&1;
 #
 EXIT_CODE=0;
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	EXIT_CODE=1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  EXIT_CODE=1;
 else
-	# ------------------------------------------------------------
-	# Install VMware Tools
-	if [ $(which vmware-toolbox-cmd 1>/dev/null 2>&1; echo $?) -eq 0 ]; then
+  # ------------------------------------------------------------
+  # Install VMware Tools
+  if [ $(which vmware-toolbox-cmd 1>/dev/null 2>&1; echo $?) -eq 0 ]; then
     # Command IS found locally
     echo "Info:  Package already installed - VMware Tools v$(vmware-toolbox-cmd -v)";
-	else
+  else
     # Command NOT found locally
     echo "";
     echo "Info:  Installing VMware Tools package \"open-vm-tools\"";
@@ -55,7 +55,7 @@ else
       echo "Error during installation of VMware tools, exiting...";
       EXIT_CODE=1;
     fi;
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/jenkins_diag_info b/usr/local/sbin/jenkins_diag_info
--- a/usr/local/sbin/jenkins_diag_info
+++ b/usr/local/sbin/jenkins_diag_info
@@ -17,17 +17,17 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	# Required:  Java Development Toolkit
-	#  |
-	#  |--> Many of these commands are tools which may be found in the Java Developer's Toolkit
-	#
-	if [ -z "$(which jcmd 2>'/dev/null')" ] || [ -z "$(which jps 2>'/dev/null')" ] || [ -z "$(which jmap 2>'/dev/null')" ]; then
+  # ------------------------------------------------------------
+  #
+  # Required:  Java Development Toolkit
+  #  |
+  #  |--> Many of these commands are tools which may be found in the Java Developer's Toolkit
+  #
+  if [ -z "$(which jcmd 2>'/dev/null')" ] || [ -z "$(which jps 2>'/dev/null')" ] || [ -z "$(which jmap 2>'/dev/null')" ]; then
     READ_TIMEOUT=60;
     echo "";
     echo "Error:  One or more required commands from the 'Java Development Toolkit' were not found, locally";
@@ -45,15 +45,15 @@ else
       echo "Info:  Required package-install denied  -->  Exiting...";
       exit 1;
     fi;
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
-	#
-	# Get diagnostic info about the Jenkins service
-	#
+  # ------------------------------------------------------------
+  #
+  # Get diagnostic info about the Jenkins service
+  #
 
-	#   jcmd  -->  Sends diagnostic command requests to a running Java Virtual Machine (JVM).
-	if [ 1 ]; then
+  #   jcmd  -->  Sends diagnostic command requests to a running Java Virtual Machine (JVM).
+  if [ 1 ]; then
     # Note: In Cent-OS7, (as-of Apr-2020), YOU MUST CALL jcmd WHILST EITHER LOGGED-IS-AS OR MASQUERADING-AS THE SERVICE USER
     SERVICE_USER="jenkins";
     # Note: Command 'VM.system_properties' seems to sum things up nicely without TOO much extra info (athough it's still a lot of info)
@@ -77,13 +77,13 @@ else
     # DIAG_REQUEST="ManagementAgent.status";
     DIAG_OUTPUT="$(sudo -u ${SERVICE_USER} jcmd $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}') ${DIAG_REQUEST})";
     echo -e "\n${DIAG_OUTPUT}\n";
-	fi;
+  fi;
 
 
-	# ------------------------------------------------------------
-	#
-	#   jmap  -->  Prints shared object memory maps or heap memory details for a process, core file, or remote debug server. This command is experimental and unsupported.
-	#
+  # ------------------------------------------------------------
+  #
+  #   jmap  -->  Prints shared object memory maps or heap memory details for a process, core file, or remote debug server. This command is experimental and unsupported.
+  #
   #      -heap           Prints a heap summary of the garbage collection used, the head configuration, and generation-wise heap usage. In addition, the number and size of interned Strings are printed.
   #
   #      -histo[:live]   Prints a histogram of the heap. For each Java class, the number of objects, memory size in bytes, and the fully qualified class names are printed. The JVM internal class names are printed with an asterisk (*) prefix. If the live suboption is specified, then only active objects are counted.
@@ -94,38 +94,38 @@ else
   #
 
 
-	# WARNING:  CLSTATS OFTEN LOCKS UP THE MACHINE & ITS SERVICE(S)
-	if [ 0 -eq 1 ]; then
+  # WARNING:  CLSTATS OFTEN LOCKS UP THE MACHINE & ITS SERVICE(S)
+  if [ 0 -eq 1 ]; then
     echo "Info:  Calling  [ jmap -clstats ]  which  [ Prints class loader wise statistics of Java heap. For each class loader, its name, how active it is, address, parent class loader, and the number and size of classes it has loaded are printed. ]";
     SERVICE_USER="jenkins";
     JMAP_CLSTATS="$(jmap -clstats -F $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}');)";
     echo "${JMAP_CLSTATS}";
-	fi;
+  fi;
 
-	# WARNING:  HISTO OFTEN LOCKS UP THE MACHINE & ITS SERVICE(S)
-	if [ 0 -eq 1 ]; then
+  # WARNING:  HISTO OFTEN LOCKS UP THE MACHINE & ITS SERVICE(S)
+  if [ 0 -eq 1 ]; then
     echo "Info:  Calling  [ jmap -histo ]  which  [ Prints a histogram of the heap. For each Java class, the number of objects, memory size in bytes, and the fully qualified class names are printed. The JVM internal class names are printed with an asterisk (*) prefix. ]";
     SERVICE_USER="jenkins";
     JMAP_HISTO="$(jmap -histo -F $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}');)";
     echo "${JMAP_HISTO}";
-	fi;
-	
+  fi;
+  
 
-	echo "Info:  Calling  [ jmap -heap ]  which  [ Prints a heap summary of the garbage collection used, the head configuration, and generation-wise heap usage. In addition, the number and size of interned Strings are printed. ]";
-	SERVICE_USER="jenkins";
-	JMAP_HEAP="$(jmap -heap -F $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}');)";
-	echo "${JMAP_HEAP}";
-
-
-	# ------------------------------------------------------------
+  echo "Info:  Calling  [ jmap -heap ]  which  [ Prints a heap summary of the garbage collection used, the head configuration, and generation-wise heap usage. In addition, the number and size of interned Strings are printed. ]";
+  SERVICE_USER="jenkins";
+  JMAP_HEAP="$(jmap -heap -F $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}');)";
+  echo "${JMAP_HEAP}";
 
 
-	echo "";
-	echo "Logfile:  \"${LOGFILE}\"";
-	echo "";
+  # ------------------------------------------------------------
 
 
-	# ------------------------------------------------------------
+  echo "";
+  echo "Logfile:  \"${LOGFILE}\"";
+  echo "";
+
+
+  # ------------------------------------------------------------
 
 fi;
 
diff --git a/usr/local/sbin/jenkins_export_config b/usr/local/sbin/jenkins_export_config
--- a/usr/local/sbin/jenkins_export_config
+++ b/usr/local/sbin/jenkins_export_config
@@ -17,33 +17,33 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	exit 1;
+  exit 1;
 
-	# DISABLED AS-OF 2019-10-24_05-12-02 (unused)
+  # DISABLED AS-OF 2019-10-24_05-12-02 (unused)
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	START_TIMESTAMP="$(date +'%Y-%m-%d_%H-%M-%S')";
+  START_TIMESTAMP="$(date +'%Y-%m-%d_%H-%M-%S')";
 
-	USERNAME_JENKINS="jenkins";
+  USERNAME_JENKINS="jenkins";
 
-	REPO_CREDS="${HOME}/.ssh/jenkins-config.push";
+  REPO_CREDS="${HOME}/.ssh/jenkins-config.push";
 
-	shopt -s "globstar";
+  shopt -s "globstar";
 
-	# Determine user's home-directory location
-	if [ -z "${JENKINS_HOME}" ] || [  ! -d "${JENKINS_HOME}" ]; then
+  # Determine user's home-directory location
+  if [ -z "${JENKINS_HOME}" ] || [  ! -d "${JENKINS_HOME}" ]; then
     JENKINS_HOME=$(getent passwd "${USERNAME_JENKINS}" | cut --delimiter=: --fields=6);
-	fi;
+  fi;
 
-	if [ -n "${JENKINS_HOME}" ] && [ -d "${JENKINS_HOME}" ]; then
+  if [ -n "${JENKINS_HOME}" ] && [ -d "${JENKINS_HOME}" ]; then
 
     # ------------------------------------------------------------
     # Export all 'config.xml' (jenkins-config) files
@@ -222,7 +222,7 @@ else
       # ------------------------------------------------------------
     fi;
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/jenkins_log_cleanup b/usr/local/sbin/jenkins_log_cleanup
--- a/usr/local/sbin/jenkins_log_cleanup
+++ b/usr/local/sbin/jenkins_log_cleanup
@@ -17,35 +17,35 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	
-	SUDO_USER_HOMEDIR="$(getent passwd ${SUDO_USER} | cut --delimiter=: --fields=6)"; # Sudo-User's Home dir
+  # ------------------------------------------------------------
+  
+  SUDO_USER_HOMEDIR="$(getent passwd ${SUDO_USER} | cut --delimiter=: --fields=6)"; # Sudo-User's Home dir
 
-	PS_AUX_CONTAINS="jenkins.war";
-	# PS_AUX_CONTAINS="^jenkins ";
+  PS_AUX_CONTAINS="jenkins.war";
+  # PS_AUX_CONTAINS="^jenkins ";
 
-	# MAX_AGE_DAYS=14;
-	MAX_AGE_DAYS=90;
+  # MAX_AGE_DAYS=14;
+  MAX_AGE_DAYS=90;
 
-	# JENKINS_UNAME=$(ps aux | grep -v grep | grep '/usr/bin/daemon' | grep "${PS_AUX_CONTAINS}" | awk {'print $1'});
-	JENKINS_UNAME=$(ps aux | grep -v grep | grep "${PS_AUX_CONTAINS}" | awk {'print $1'});
+  # JENKINS_UNAME=$(ps aux | grep -v grep | grep '/usr/bin/daemon' | grep "${PS_AUX_CONTAINS}" | awk {'print $1'});
+  JENKINS_UNAME=$(ps aux | grep -v grep | grep "${PS_AUX_CONTAINS}" | awk {'print $1'});
 
-	DASHES="------------------------------------------------------------";
-	echo -e "\n\n${DASHES}\n";
+  DASHES="------------------------------------------------------------";
+  echo -e "\n\n${DASHES}\n";
 
-	if [ -z "${JENKINS_UNAME}" ]; then # jenkins process not found
+  if [ -z "${JENKINS_UNAME}" ]; then # jenkins process not found
     echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - No processes found which match text \"${PS_AUX_CONTAINS}\"";
     exit 1;
     
-	elif [ -n "$(id -u ${JENKINS_UNAME} | grep 'no such user')" ]; then # jenkins user not found
+  elif [ -n "$(id -u ${JENKINS_UNAME} | grep 'no such user')" ]; then # jenkins user not found
     echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - No users found with name \"${JENKINS_UNAME}\"";
     exit 1;
 
-	else
+  else
     
     JENKINS_UHOME=$(getent passwd ${JENKINS_UNAME} | cut --delimiter=: --fields=6);
 
@@ -72,35 +72,35 @@ else
 
     fi;
 
-	fi;
+  fi;
 
-	FIND_PARENT="/var/log";
-	echo -e "\n\n${DASHES}\n";
-	echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nDeleting files matching the following constraint(s):";
-	echo "  File hasn't been modified for at least ${MAX_AGE_DAYS} days";
-	echo "  Filepath starts with: \"${FIND_PARENT}\"";
+  FIND_PARENT="/var/log";
+  echo -e "\n\n${DASHES}\n";
+  echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nDeleting files matching the following constraint(s):";
+  echo "  File hasn't been modified for at least ${MAX_AGE_DAYS} days";
+  echo "  Filepath starts with: \"${FIND_PARENT}\"";
 
-	find "${FIND_PARENT}" \
+  find "${FIND_PARENT}" \
     -mindepth 1 \
     -maxdepth 10 \
     -mtime +${MAX_AGE_DAYS} \
     -exec rm -rf -- '{}' \;
 
 
-	# # NGINX - Reload
-	# echo -e "\n\n$(date +'%D  %r') Calling [ /usr/sbin/service \"${SERVICE_NAME}\" reload; ]...";
-	# SERVICE_NAME="nginx";
-	# /usr/sbin/service "${SERVICE_NAME}" reload;
+  # # NGINX - Reload
+  # echo -e "\n\n$(date +'%D  %r') Calling [ /usr/sbin/service \"${SERVICE_NAME}\" reload; ]...";
+  # SERVICE_NAME="nginx";
+  # /usr/sbin/service "${SERVICE_NAME}" reload;
 
-	# # Jenkins - Reload
-	# RESTART_JENKINS_SERVICE="Yes";
-	# if [ -n "${RESTART_JENKINS_SERVICE}" ]; then
-	# 	if [ "${RESTART_JENKINS_SERVICE}" == "Yes" ]; then
-	# 		DELAY_SECONDS=30;
-	# 		SERVICE_NAME="jenkins";
-	# 		(sleep ${DELAY_SECONDS}; /usr/sbin/service "${SERVICE_NAME}" force-reload ) & \
-	# 		echo -e "\n\n$(date +'%D  %r') Creating parallel/background task: [ sleep ${DELAY_SECONDS}; /usr/sbin/service \"${SERVICE_NAME}\" force-reload; ]...";
-	# 	fi;
-	# fi;
+  # # Jenkins - Reload
+  # RESTART_JENKINS_SERVICE="Yes";
+  # if [ -n "${RESTART_JENKINS_SERVICE}" ]; then
+  # 	if [ "${RESTART_JENKINS_SERVICE}" == "Yes" ]; then
+  # 		DELAY_SECONDS=30;
+  # 		SERVICE_NAME="jenkins";
+  # 		(sleep ${DELAY_SECONDS}; /usr/sbin/service "${SERVICE_NAME}" force-reload ) & \
+  # 		echo -e "\n\n$(date +'%D  %r') Creating parallel/background task: [ sleep ${DELAY_SECONDS}; /usr/sbin/service \"${SERVICE_NAME}\" force-reload; ]...";
+  # 	fi;
+  # fi;
 
 fi;
diff --git a/usr/local/sbin/mail_disable_alerts b/usr/local/sbin/mail_disable_alerts
--- a/usr/local/sbin/mail_disable_alerts
+++ b/usr/local/sbin/mail_disable_alerts
@@ -23,15 +23,15 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	# Bash - Disable  "You have mail in ..."  &&   "You have new mail in /var/spool/mail/..."  alerts
-	#
-	if [ $(sed -rne 's/^MAIL=""$/\0/p' '/etc/profile' | wc -l 2>'/dev/null';) -eq 0 ]; then
+  # ------------------------------------------------------------
+  #
+  # Bash - Disable  "You have mail in ..."  &&   "You have new mail in /var/spool/mail/..."  alerts
+  #
+  if [ $(sed -rne 's/^MAIL=""$/\0/p' '/etc/profile' | wc -l 2>'/dev/null';) -eq 0 ]; then
     if [ $(sed -rne 's/^(\s*export ?.*)( MAIL)( ?.*)$/\0/p' '/etc/profile' | wc -l 2>'/dev/null';) -gt 0 ]; then
       BENCHMARK_START=$(date +'%s.%N');
       echo -e "\n""Info:  Disabling \"You have new mail in ...\" alerts (commenting MAIL=... in \"/etc/profile\")";
@@ -40,7 +40,7 @@ else
       BENCHMARK_DELTA=$(echo "scale=4; ($(date +'%s.%N') - ${BENCHMARK_START})/1" | bc -l);
       test ${ARGS_DEBUG_MODE} -eq 1 && echo "  |--> Finished after ${BENCHMARK_DELTA}s";
     fi;
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/motd_status b/usr/local/sbin/motd_status
--- a/usr/local/sbin/motd_status
+++ b/usr/local/sbin/motd_status
@@ -21,20 +21,20 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Parse inline arguments (passed to current script)
-	ARGS=("$@");
-	COUNT_ARGS=${#ARGS[@]};
-	
-	DISABLE_MOTD=0;
-	ENABLE_MOTD=0;
+  # ------------------------------------------------------------
+  # Parse inline arguments (passed to current script)
+  ARGS=("$@");
+  COUNT_ARGS=${#ARGS[@]};
+  
+  DISABLE_MOTD=0;
+  ENABLE_MOTD=0;
 
-	# Walk through any inline-arguments passed to this function
-	for (( i=0;i<$COUNT_ARGS;i++ )); do
+  # Walk through any inline-arguments passed to this function
+  for (( i=0;i<$COUNT_ARGS;i++ )); do
     EACH_ARG=${ARGS[${i}]};
     # Check if this is the last inline-argument or if there are more to follow
     if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
@@ -58,15 +58,15 @@ else
       # ------------------------------------------------------------
     fi;
 
-	done;
+  done;
 
-	if [ -z "$(which sed 2>'/dev/null';)" ]; then
+  if [ -z "$(which sed 2>'/dev/null';)" ]; then
     # Missing required package
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error -> Package not found: \"sed\" - Please install this package, then re-run this script";
     echo -e "${EXAMPLE_VALID_CALL}";
     exit 1;
 
-	else
+  else
 
     if [ ${ENABLE_MOTD} -eq 1 ]; then
       MOTD_ENABLED_VALUE=1;
@@ -104,7 +104,7 @@ else
 
     fi;
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/mysql_create_admin b/usr/local/sbin/mysql_create_admin
--- a/usr/local/sbin/mysql_create_admin
+++ b/usr/local/sbin/mysql_create_admin
@@ -17,55 +17,55 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 
-	# Get the new admin's username
-	PATH_ADMIN_NAME="${HOME}/mysql_admin_user";
-	if [ ! -f "${PATH_ADMIN_NAME}" ]; then
+  # Get the new admin's username
+  PATH_ADMIN_NAME="${HOME}/mysql_admin_user";
+  if [ ! -f "${PATH_ADMIN_NAME}" ]; then
     echo "To create a new MySQL admin, place their username in filepath \"${PATH_ADMIN_NAME}\" as one single line of text (no newlines)";
     exit 1;
-	elif [ $(cat "${PATH_ADMIN_NAME}" | wc -l;) -gt 1 ]; then
+  elif [ $(cat "${PATH_ADMIN_NAME}" | wc -l;) -gt 1 ]; then
     echo "To create a new MySQL admin, place their username in filepath \"${PATH_ADMIN_NAME}\" as ONE SINGLE LINE of text (no newlines)";
     exit 1;
-	fi;
-	chmod 0400 "${PATH_ADMIN_NAME}";
-	ADMIN_NAME=$(cat "${PATH_ADMIN_NAME}");
+  fi;
+  chmod 0400 "${PATH_ADMIN_NAME}";
+  ADMIN_NAME=$(cat "${PATH_ADMIN_NAME}");
 
-	# Get the new admin's password
-	PATH_ADMIN_PASS="${HOME}/mysql_admin_pass";
-	if [ ! -f "${PATH_ADMIN_PASS}" ]; then
+  # Get the new admin's password
+  PATH_ADMIN_PASS="${HOME}/mysql_admin_pass";
+  if [ ! -f "${PATH_ADMIN_PASS}" ]; then
     echo "To create a new MySQL admin, place their password in filepath \"${PATH_ADMIN_PASS}\" as one single line of text (no newlines)";
     exit 1;
-	elif [ $(cat "${PATH_ADMIN_PASS}" | wc -l;) -gt 1 ]; then
+  elif [ $(cat "${PATH_ADMIN_PASS}" | wc -l;) -gt 1 ]; then
     echo "To create a new MySQL admin, place their password in filepath \"${PATH_ADMIN_PASS}\" as ONE SINGLE LINE of text (no newlines)";
     exit 1;
-	fi;
-	chmod 0400 "${PATH_ADMIN_PASS}";
-	ADMIN_PASS=$(cat "${PATH_ADMIN_PASS}");
+  fi;
+  chmod 0400 "${PATH_ADMIN_PASS}";
+  ADMIN_PASS=$(cat "${PATH_ADMIN_PASS}");
 
-	# ADMIN_IPv4="%";
-	ADMIN_IPv4="localhost";
+  # ADMIN_IPv4="%";
+  ADMIN_IPv4="localhost";
 
-	# Prep the file to start mysql with
-	MYSQL_INIT_PATH="${HOME}/mysql-init";
+  # Prep the file to start mysql with
+  MYSQL_INIT_PATH="${HOME}/mysql-init";
 
-	# MYSQL_CREATE_ADMIN_COMMAND="CREATE USER '${ADMIN_NAME}'@'${ADMIN_IPv4}' IDENTIFIED BY '${ADMIN_PASS}'; GRANT ALL PRIVILEGES ON *.* TO '${ADMIN_NAME}'@'${ADMIN_IPv4}' WITH GRANT OPTION; FLUSH PRIVILEGES;";
-	MYSQL_CREATE_ADMIN_COMMAND="GRANT ALL PRIVILEGES ON *.* TO '${ADMIN_NAME}'@'${ADMIN_IPv4}' IDENTIFIED BY '${ADMIN_PASS}' WITH GRANT OPTION; FLUSH PRIVILEGES; FLUSH PRIVILEGES;";
+  # MYSQL_CREATE_ADMIN_COMMAND="CREATE USER '${ADMIN_NAME}'@'${ADMIN_IPv4}' IDENTIFIED BY '${ADMIN_PASS}'; GRANT ALL PRIVILEGES ON *.* TO '${ADMIN_NAME}'@'${ADMIN_IPv4}' WITH GRANT OPTION; FLUSH PRIVILEGES;";
+  MYSQL_CREATE_ADMIN_COMMAND="GRANT ALL PRIVILEGES ON *.* TO '${ADMIN_NAME}'@'${ADMIN_IPv4}' IDENTIFIED BY '${ADMIN_PASS}' WITH GRANT OPTION; FLUSH PRIVILEGES; FLUSH PRIVILEGES;";
 
-	echo "${MYSQL_CREATE_ADMIN_COMMAND}" > "${MYSQL_INIT_PATH}";
-	chmod 0440 "${MYSQL_INIT_PATH}";
-	chown "root:mysql" "${MYSQL_INIT_PATH}";
+  echo "${MYSQL_CREATE_ADMIN_COMMAND}" > "${MYSQL_INIT_PATH}";
+  chmod 0440 "${MYSQL_INIT_PATH}";
+  chown "root:mysql" "${MYSQL_INIT_PATH}";
 
-	# Require user confirmation to proceed
-	echo -e "\n";
-	read -p "Are you ready to create new MySQL admin-user \"${ADMIN_NAME}\"? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
-	echo "";
-	if [ ${RETURN_CODE_READ} -gt 128 ]; then
+  # Require user confirmation to proceed
+  echo -e "\n";
+  read -p "Are you ready to create new MySQL admin-user \"${ADMIN_NAME}\"? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
+  echo "";
+  if [ ${RETURN_CODE_READ} -gt 128 ]; then
     echo -e "Response timed out";
-	elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
+  elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
     echo -e "\n""Info: Confirmed - Attempting to create new MySQL admin-user \"${ADMIN_NAME}\"...""\n";
 
     exit 0;
@@ -84,9 +84,9 @@ else
     service mysqld start;
     sleep 1;
 
-	else
+  else
     echo "Denied - Skipping command";
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/partition_unpartitioned_disks b/usr/local/sbin/partition_unpartitioned_disks
--- a/usr/local/sbin/partition_unpartitioned_disks
+++ b/usr/local/sbin/partition_unpartitioned_disks
@@ -35,23 +35,23 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Install helper package(s)
-	if [ $(which kdump 2>'/dev/null' | wc -l;) -eq 0 ]; then
+  # ------------------------------------------------------------
+  # Install helper package(s)
+  if [ $(which kdump 2>'/dev/null' | wc -l;) -eq 0 ]; then
     if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
       apt-get -y install nfs-common;
     elif [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
       yum -y install nfs-utils cifs-utils samba-client samba-common;
     fi;
-	fi;
+  fi;
 
-	# Partition un-partitioned disk(s), add volume(s) to empty disk(s), & mount unmounted volume(s)
-	ROLLBACK_IFS="${IFS}"; IFS=$'\n';
-	for EACH_LINE in $(parted -lms 2>&1 | grep -i ^/;); do
+  # Partition un-partitioned disk(s), add volume(s) to empty disk(s), & mount unmounted volume(s)
+  ROLLBACK_IFS="${IFS}"; IFS=$'\n';
+  for EACH_LINE in $(parted -lms 2>&1 | grep -i ^/;); do
     echo "------------------------------------------------------------";
     EACH_DISK_DEVICE=$(echo "${EACH_LINE}" | cut -d':' -f1;);
     EACH_DISK_BASENAME=$(basename "${EACH_DISK_DEVICE}");
@@ -131,7 +131,7 @@ else
       fi;
     done; # IFS="${ROLLBACK_IFS}";
 
-	done; IFS="${ROLLBACK_IFS}";
+  done; IFS="${ROLLBACK_IFS}";
 
 fi;
 
diff --git a/usr/local/sbin/reload_httpd b/usr/local/sbin/reload_httpd
--- a/usr/local/sbin/reload_httpd
+++ b/usr/local/sbin/reload_httpd
@@ -17,21 +17,21 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	# Reload Httpd (Apache/Aapache2) service
-	#
-	SERVICE_NAME="httpd";
-	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	if [ ${SERVICE_RET_CODE} -ne 0 ]; then
+  # ------------------------------------------------------------
+  #
+  # Reload Httpd (Apache/Aapache2) service
+  #
+  SERVICE_NAME="httpd";
+  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  if [ ${SERVICE_RET_CODE} -ne 0 ]; then
     # Service NOT found to exist locally
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Service \"${SERVICE_NAME}\" not found amongst local services";
 
-	else
+  else
     # Service EXISTS locally
     if [ -f "/etc/init.d/apache2" ]; then
       echo "$(date +'%Y-%m-%d %H:%M:%S') | $(basename ${0}): Reloading Apache2 (httpd) via command  [ /etc/init.d/apache2 reload; ]...";
@@ -44,7 +44,7 @@ else
       echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Apache runtime \"httpd\" not found";
     fi;
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/reload_nginx b/usr/local/sbin/reload_nginx
--- a/usr/local/sbin/reload_nginx
+++ b/usr/local/sbin/reload_nginx
@@ -17,18 +17,18 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	SERVICE_NAME="nginx";
-	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	if [ ${SERVICE_RET_CODE} -eq 1 ]; then
+  # ------------------------------------------------------------
+  SERVICE_NAME="nginx";
+  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  if [ ${SERVICE_RET_CODE} -eq 1 ]; then
     # Service NOT found to exist locally
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Service \"${SERVICE_NAME}\" not found amongst local services";
 
-	else
+  else
     if [ ${SERVICE_RET_CODE} -ne 0 ]; then
       echo "$(date +'%Y-%m-%d %H:%M:%S') | $(basename ${0}): NGINX Service not started - Starting it, now...";
       /usr/sbin/service "${SERVICE_NAME}" restart;
@@ -58,5 +58,5 @@ else
     # echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ /usr/sbin/service \"${SERVICE_NAME}\" status; ] (after reload)...";
     # /usr/sbin/service "${SERVICE_NAME}" status;
 
-	fi;
+  fi;
 fi;
diff --git a/usr/local/sbin/remove_package b/usr/local/sbin/remove_package
--- a/usr/local/sbin/remove_package
+++ b/usr/local/sbin/remove_package
@@ -17,16 +17,16 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	#	Remove package(s)
-	#
+  # ------------------------------------------------------------
+  #
+  #	Remove package(s)
+  #
 
-	if [ -z "${1}" ]; then
+  if [ -z "${1}" ]; then
 
     # Required variable empty
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: No value given for first parameter (\$1)";
@@ -35,7 +35,7 @@ else
     echo "";
     exit 1;
 
-	else
+  else
 
     PACKAGE_NAME="$1";
 
@@ -67,8 +67,8 @@ else
     echo "";
     exit;
     
-	fi;
+  fi;
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
 fi;
diff --git a/usr/local/sbin/selinux_config b/usr/local/sbin/selinux_config
--- a/usr/local/sbin/selinux_config
+++ b/usr/local/sbin/selinux_config
@@ -34,22 +34,22 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# SELinux - Disable, Enable, Get-Status, Troubleshoot
-	
-	EXIT_CODE=1; # Default to error-ing out. Only return success if every check passes
+  # ------------------------------------------------------------
+  # SELinux - Disable, Enable, Get-Status, Troubleshoot
+  
+  EXIT_CODE=1; # Default to error-ing out. Only return success if every check passes
 
-	# Only run in SELinux-compatible environments
-	if [ $(which getenforce 1>'/dev/null' 2>&1; echo $?;) -ne 0 ] || [ $(which setenforce 1>'/dev/null' 2>&1; echo $?;) -ne 0 ] || [ $(which selinuxenabled 1>'/dev/null' 2>&1; echo $?;) -ne 0 ]; then
+  # Only run in SELinux-compatible environments
+  if [ $(which getenforce 1>'/dev/null' 2>&1; echo $?;) -ne 0 ] || [ $(which setenforce 1>'/dev/null' 2>&1; echo $?;) -ne 0 ] || [ $(which selinuxenabled 1>'/dev/null' 2>&1; echo $?;) -ne 0 ]; then
     # ERROR - SELinux not detected
     echo -e "\n""Error:  SELinux not detected""\n";
     EXIT_CODE=1;
-	
-	else
+  
+  else
     # ------------------------------------------------------------
     # Instantiate runtime variables
 
@@ -109,11 +109,11 @@ else
         if [ "${EACH_ARG}" == "-e" ] || [ "${EACH_ARG}" == "--enable" ]; then
           ARGS_SELINUX_ENABLE=1; # Enable SELinux
         fi;
-	
+  
         if [ "${EACH_ARG}" == "-s" ] || [ "${EACH_ARG}" == "--status" ]; then
           ARGS_SELINUX_STATUS=1; # Get SELinux status
         fi;
-	
+  
       fi;
 
     done;
@@ -324,9 +324,9 @@ else
       fi;
     fi;
 
-	fi;
+  fi;
 
-	exit ${EXIT_CODE};
+  exit ${EXIT_CODE};
 
 fi;
 
diff --git a/usr/local/sbin/set_hostname b/usr/local/sbin/set_hostname
--- a/usr/local/sbin/set_hostname
+++ b/usr/local/sbin/set_hostname
@@ -17,35 +17,35 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	# This script modifies a Linux instance's host & domain name(s)
-	#
-	#	Instantiate this command-line utility:
-	#	>		vi "/usr/local/sbin/set_hostname"; chmod 0755 "/usr/local/sbin/set_hostname";
-	#
-	### Run using "DRY-RUN" mode:
-	#	>		set_hostname "localhost.localdomain" --dry-run "1";
-	#
-	### Run using "LIVE" mode:
-	#	>		set_hostname "localhost.localdomain" --dry-run "0";
-	#
-	#
-	# ------------------------------------------------------------
-	# Parse inline arguments (passed to current script)
-	#
+  # ------------------------------------------------------------
+  #
+  # This script modifies a Linux instance's host & domain name(s)
+  #
+  #	Instantiate this command-line utility:
+  #	>		vi "/usr/local/sbin/set_hostname"; chmod 0755 "/usr/local/sbin/set_hostname";
+  #
+  ### Run using "DRY-RUN" mode:
+  #	>		set_hostname "localhost.localdomain" --dry-run "1";
+  #
+  ### Run using "LIVE" mode:
+  #	>		set_hostname "localhost.localdomain" --dry-run "0";
+  #
+  #
+  # ------------------------------------------------------------
+  # Parse inline arguments (passed to current script)
+  #
 
-	ARGS=("$@");
-	COUNT_ARGS=${#ARGS[@]};
-	ARGS_HOSTNAME_DEFINED=0;
-	USE_WAN_IPV4=0;
-	DRY_RUN=1;
-	# Walk through any inline-arguments passed to this function
-	for (( i=0;i<$COUNT_ARGS;i++ )); do
+  ARGS=("$@");
+  COUNT_ARGS=${#ARGS[@]};
+  ARGS_HOSTNAME_DEFINED=0;
+  USE_WAN_IPV4=0;
+  DRY_RUN=1;
+  # Walk through any inline-arguments passed to this function
+  for (( i=0;i<$COUNT_ARGS;i++ )); do
 
     EACH_ARG=${ARGS[${i}]};
     # BASH_ARG_NUMBER=$((${i}+1)); # Bash arg-number is one greater than the ARGS arg-number -> this is due-to bash's ${0} arg, which contains the base-command
@@ -95,20 +95,20 @@ else
       fi;
 
     fi;
-	done;
+  done;
 
-	# ------------------------------------------------------------
-	# Get status of hostname/domainname before edits
-	#
-	CURRENT_HOSTNAME="$(hostname)";
-	CURRENT_LAN_IPV4="$(hostname -i | awk '{print $1}')";
-	if [ "$(hostname -d;)" != "(none)" ]; then
+  # ------------------------------------------------------------
+  # Get status of hostname/domainname before edits
+  #
+  CURRENT_HOSTNAME="$(hostname)";
+  CURRENT_LAN_IPV4="$(hostname -i | awk '{print $1}')";
+  if [ "$(hostname -d;)" != "(none)" ]; then
     CURRENT_DOMAIN="$(hostname -d;)";
-	fi;
+  fi;
 
 
-	# ------------------------------------------------------------
-	if [ -z "${INPUT_HOSTNAME}" ]; then
+  # ------------------------------------------------------------
+  if [ -z "${INPUT_HOSTNAME}" ]; then
     # Error - Required variable empty: INPUT_HOSTNAME
     echo "";
     echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Command \"$(realpath ${0};)\" called with empty hostname";
@@ -116,7 +116,7 @@ else
     echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --hostname FQDN ]";
     exit 1;
 
-	elif [ "${INPUT_HOSTNAME}" != "$(echo ${INPUT_HOSTNAME} | grep --extended-regexp '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$';)" ]; then
+  elif [ "${INPUT_HOSTNAME}" != "$(echo ${INPUT_HOSTNAME} | grep --extended-regexp '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$';)" ]; then
     # Error - Hostname contains one or more invalid characters
     echo "";
     echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Command \"$(realpath ${0};)\" called with invalid hostname:  \"${INPUT_HOSTNAME}\"";
@@ -124,7 +124,7 @@ else
     echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --hostname VALID-HOSTNAME ]";
     exit 1;
 
-	else
+  else
 
     SUBSTRING_ONLY_PERIODS="${INPUT_HOSTNAME//[^.]}";
     FQDN_COUNT_PERIODS="${#SUBSTRING_ONLY_PERIODS}";
@@ -441,7 +441,7 @@ else
     fi;
     echo "";
 
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/sudoer_status b/usr/local/sbin/sudoer_status
--- a/usr/local/sbin/sudoer_status
+++ b/usr/local/sbin/sudoer_status
@@ -31,22 +31,22 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	# Parse inline arguments (passed to current script)
-	ARGS=("$@");
-	COUNT_ARGS=${#ARGS[@]};
-	
-	EDIT_ACTION="";
-	TARGET_USER="";
-	SUDO_REQUIRES_USERPASS="1";
-	EXAMPLE_VALID_CALL="\n$(date +'%Y-%m-%d %H:%M:%S') | Info --> Please specify a valid local user via:  >  sudoer_status --user USERNAME""\n";
+  # ------------------------------------------------------------
+  # Parse inline arguments (passed to current script)
+  ARGS=("$@");
+  COUNT_ARGS=${#ARGS[@]};
+  
+  EDIT_ACTION="";
+  TARGET_USER="";
+  SUDO_REQUIRES_USERPASS="1";
+  EXAMPLE_VALID_CALL="\n$(date +'%Y-%m-%d %H:%M:%S') | Info --> Please specify a valid local user via:  >  sudoer_status --user USERNAME""\n";
 
-	# Walk through any inline-arguments passed to this function
-	for (( i=0;i<$COUNT_ARGS;i++ )); do
+  # Walk through any inline-arguments passed to this function
+  for (( i=0;i<$COUNT_ARGS;i++ )); do
 
     EACH_ARG=${ARGS[${i}]};
 
@@ -105,23 +105,23 @@ else
 
     fi;
 
-	done;
+  done;
 
 
-	# Verify validity of argument(s) passed to script
-	if [ -z "${TARGET_USER}" ]; then 
+  # Verify validity of argument(s) passed to script
+  if [ -z "${TARGET_USER}" ]; then 
 
     # Error: Empty/Unset target-user
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Target-user empty / unset";
     echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
 
-	elif [ $(id -u ${TARGET_USER} > /dev/null 2>&1; echo $?) -eq 1 ]; then
+  elif [ $(id -u ${TARGET_USER} > /dev/null 2>&1; echo $?) -eq 1 ]; then
 
     # Error: User not found
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found: \"${TARGET_USER}\"";
     echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
 
-	else
+  else
 
     SUDOERS_D="";
     if [ -d "/etc/sudoers.d" ]; then
@@ -191,7 +191,7 @@ else
 
 
     # ------------------------------------------------------------
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/ufw_ipv6_setup b/usr/local/sbin/ufw_ipv6_setup
--- a/usr/local/sbin/ufw_ipv6_setup
+++ b/usr/local/sbin/ufw_ipv6_setup
@@ -17,20 +17,20 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	RESTART_SERVICE_UFW=0;
-	# ------------------------------------------------------------
-	#
-	# UFW | Service Check
-	#  |--> Fail-out if UFW does NOT exist as local service
-	#
-	SERVICE_NAME="ufw";
-	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	if [ ${SERVICE_RET_CODE} -eq 0 ]; then
+  # ------------------------------------------------------------
+  RESTART_SERVICE_UFW=0;
+  # ------------------------------------------------------------
+  #
+  # UFW | Service Check
+  #  |--> Fail-out if UFW does NOT exist as local service
+  #
+  SERVICE_NAME="ufw";
+  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  if [ ${SERVICE_RET_CODE} -eq 0 ]; then
     # ------------------------------------------------------------
     #
     # UFW | IPv6 Pinging
@@ -102,10 +102,10 @@ else
       /usr/sbin/service "${SERVICE_NAME}" restart;
       # /usr/sbin/service "${SERVICE_NAME}" status;
     fi;
-	else
+  else
     echo "Error: Service \"${SERVICE_NAME}\" NOT found as a local service";
     exit 1;
-	fi;
+  fi;
 fi;
 
 # ------------------------------------------------------------
diff --git a/usr/local/sbin/uninstall_jenkins b/usr/local/sbin/uninstall_jenkins
--- a/usr/local/sbin/uninstall_jenkins
+++ b/usr/local/sbin/uninstall_jenkins
@@ -25,24 +25,24 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	#
-	# Uninstall Jenkins CI/CD Server
-	#
-	SERVICE_NAME="jenkins";
+  # ------------------------------------------------------------
+  #
+  # Uninstall Jenkins CI/CD Server
+  #
+  SERVICE_NAME="jenkins";
 
-	# ------------------------------------------------------------
-	#
-	# Require user-confirmation to perform this action
-	#
-	echo -e "\n""!! WARNING !! This will completely uninstall service \"${SERVICE_NAME}\" (including associated runtime user, usergroup, service(s), etc.)";
-	read -p "     |--> Are you sure you want to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
-	echo "";
-	if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
+  # ------------------------------------------------------------
+  #
+  # Require user-confirmation to perform this action
+  #
+  echo -e "\n""!! WARNING !! This will completely uninstall service \"${SERVICE_NAME}\" (including associated runtime user, usergroup, service(s), etc.)";
+  read -p "     |--> Are you sure you want to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
+  echo "";
+  if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
     read -p "     |--> Are you completely positive you wish to continue? (y/n)  " -n 1 -t 60 -r; # Await single keypress
     echo "";
     if [ -n "${REPLY}" ] && [ "$(echo ${REPLY} | tr '[:lower:]' '[:upper:]';)" == "Y" ]; then
@@ -181,11 +181,11 @@ else
       /bin/systemctl reset-failed;
 
     fi;
-	fi;
+  fi;
 
-	EXIT_CODE=0;
+  EXIT_CODE=0;
 
-	exit ${EXIT_CODE};
+  exit ${EXIT_CODE};
 
 fi;
 
diff --git a/usr/local/sbin/update_dns_config b/usr/local/sbin/update_dns_config
--- a/usr/local/sbin/update_dns_config
+++ b/usr/local/sbin/update_dns_config
@@ -25,31 +25,31 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo -e "\n""$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo -e "\n""$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
 
-	# ------------------------------------------------------------
-	# Parse inline arguments (passed to current script)
-	#
+  # ------------------------------------------------------------
+  # Parse inline arguments (passed to current script)
+  #
 
-	ARGS=("$@");
-	COUNT_ARGS=${#ARGS[@]};
-	ARGS_HOSTNAME_DEFINED=0;
-	USE_WAN_IPV4=0;
-	USE_SEARCH_DOMAIN=0;
-	USE_STATIC_IPV4=0;
-	DRY_RUN=1;
+  ARGS=("$@");
+  COUNT_ARGS=${#ARGS[@]};
+  ARGS_HOSTNAME_DEFINED=0;
+  USE_WAN_IPV4=0;
+  USE_SEARCH_DOMAIN=0;
+  USE_STATIC_IPV4=0;
+  DRY_RUN=1;
 
-	#
-	# DNS "SEARCH": TAKES A SET OF ONE OR MORE DOMAINS AND TRIES CONCATENATING EACH OF THEM WITH THE LOCAL ENVIRONMENT'S HOSTNAME (to try and resolve dns query) BEFORE REVERTING TO GOING EXTERNAL FOR RESOLUTION OF THE DNS QUERY IN_QUESTION
-	#
-	# MAX IS 6 DOMAINS TOTALING 256 OR LESS CHARACTERS)
-	#
-	DNS_SEARCH_DOMAIN="";
+  #
+  # DNS "SEARCH": TAKES A SET OF ONE OR MORE DOMAINS AND TRIES CONCATENATING EACH OF THEM WITH THE LOCAL ENVIRONMENT'S HOSTNAME (to try and resolve dns query) BEFORE REVERTING TO GOING EXTERNAL FOR RESOLUTION OF THE DNS QUERY IN_QUESTION
+  #
+  # MAX IS 6 DOMAINS TOTALING 256 OR LESS CHARACTERS)
+  #
+  DNS_SEARCH_DOMAIN="";
 
-	# Walk through any inline-arguments passed to this function
-	for (( i=0;i<$COUNT_ARGS;i++ )); do
+  # Walk through any inline-arguments passed to this function
+  for (( i=0;i<$COUNT_ARGS;i++ )); do
 
     EACH_ARG=${ARGS[${i}]};
     # BASH_ARG_NUMBER=$((${i}+1)); # Bash arg-number is one greater than the ARGS arg-number -> this is due-to bash's ${0} arg, which contains the base-command
@@ -126,11 +126,11 @@ else
       fi;
 
     fi;
-	done;
+  done;
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	if [ $(which nmcli 2>'/dev/null' | wc -l;) -gt 0 ]; then
+  if [ $(which nmcli 2>'/dev/null' | wc -l;) -gt 0 ]; then
     #
     # Prioritize DHCP DNS Nameservers from nmcli (NetworkManager), where available
     #
@@ -146,79 +146,79 @@ else
         fi;
       done;
     fi;
-	fi;
+  fi;
 
 
-	# ------------------------------------------------------------
-	#
-	#		DNS SERVER OPTIONS
-	#
+  # ------------------------------------------------------------
+  #
+  #		DNS SERVER OPTIONS
+  #
 
-	GOOGLE_DNS_1="8.8.8.8";       # https://developers.google.com/speed/public-dns/docs/using
-	GOOGLE_DNS_2="8.8.4.4";       # https://developers.google.com/speed/public-dns/docs/using
+  GOOGLE_DNS_1="8.8.8.8";       # https://developers.google.com/speed/public-dns/docs/using
+  GOOGLE_DNS_2="8.8.4.4";       # https://developers.google.com/speed/public-dns/docs/using
 
-	GOOGLE_DNSv6_1="2001:4860:4860::8888";       # https://developers.google.com/speed/public-dns/docs/using
-	GOOGLE_DNSv6_2="2001:4860:4860::8844";       # https://developers.google.com/speed/public-dns/docs/using
+  GOOGLE_DNSv6_1="2001:4860:4860::8888";       # https://developers.google.com/speed/public-dns/docs/using
+  GOOGLE_DNSv6_2="2001:4860:4860::8844";       # https://developers.google.com/speed/public-dns/docs/using
 
-	CLOUDFARE_DNS_1="1.1.1.1";    # https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
-	CLOUDFARE_DNS_2="1.0.0.1";    # https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
+  CLOUDFARE_DNS_1="1.1.1.1";    # https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
+  CLOUDFARE_DNS_2="1.0.0.1";    # https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
 
-	CLOUDFARE_DNSv6_1="2606:4700:4700::1111";       # https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
-	CLOUDFARE_DNSv6_2="2606:4700:4700::1001";       # https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
+  CLOUDFARE_DNSv6_1="2606:4700:4700::1111";       # https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
+  CLOUDFARE_DNSv6_2="2606:4700:4700::1001";       # https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
 
-	OPEN_DNS_1="208.67.222.222";  # https://use.opendns.com
-	OPEN_DNS_2="208.67.220.220";  # https://use.opendns.com
+  OPEN_DNS_1="208.67.222.222";  # https://use.opendns.com
+  OPEN_DNS_2="208.67.220.220";  # https://use.opendns.com
 
-	OPEN_DNSv6_1="2620:119:35::35";  # https://www.opendns.com/about/innovations/ipv6
-	OPEN_DNSv6_2="2620:119:53::53";  # https://www.opendns.com/about/innovations/ipv6
+  OPEN_DNSv6_1="2620:119:35::35";  # https://www.opendns.com/about/innovations/ipv6
+  OPEN_DNSv6_2="2620:119:53::53";  # https://www.opendns.com/about/innovations/ipv6
 
-	VERISIGN_DNS_1="64.6.64.6";   # https://www.verisign.com/en_US/security-services/public-dns/index.xhtml
-	VERISIGN_DNS_2="64.6.65.6";   # https://www.verisign.com/en_US/security-services/public-dns/index.xhtml
+  VERISIGN_DNS_1="64.6.64.6";   # https://www.verisign.com/en_US/security-services/public-dns/index.xhtml
+  VERISIGN_DNS_2="64.6.65.6";   # https://www.verisign.com/en_US/security-services/public-dns/index.xhtml
 
-	VERISIGN_DNSv6_1="2620:74:1b::1:1";   # https://publicdnsforum.verisign.com/discussion/13/verisign-public-dns-set-up-configuration-instructions
-	VERISIGN_DNSv6_2="2620:74:1c::2:2";   # https://publicdnsforum.verisign.com/discussion/13/verisign-public-dns-set-up-configuration-instructions
+  VERISIGN_DNSv6_1="2620:74:1b::1:1";   # https://publicdnsforum.verisign.com/discussion/13/verisign-public-dns-set-up-configuration-instructions
+  VERISIGN_DNSv6_2="2620:74:1c::2:2";   # https://publicdnsforum.verisign.com/discussion/13/verisign-public-dns-set-up-configuration-instructions
 
-	# ------------------------------------------------------------
-	#
-	#		SELECTED DNS SERVERS (HOSTS/IPS TO TARGET AS DNS NAMESERVERS)
+  # ------------------------------------------------------------
+  #
+  #		SELECTED DNS SERVERS (HOSTS/IPS TO TARGET AS DNS NAMESERVERS)
 
-	DNS_NAMESRVR_1="${USER_DNS_1:-${DHCP_NAMESRVR_1:-${GOOGLE_DNS_1}}}";
-	DNS_NAMESRVR_2="${USER_DNS_2:-${DHCP_NAMESRVR_2:-${GOOGLE_DNS_2}}}";
-	DNS_NAMESRVR_3="${USER_DNS_3:-${DHCP_NAMESRVR_3:-${CLOUDFARE_DNS_1}}}";
-	DNS_FALLBACK_1="${OPEN_DNS_1}";
-	DNS_FALLBACK_2="${CLOUDFARE_DNS_2}";
-	DNS_FALLBACK_3="${VERISIGN_DNS_1}";
+  DNS_NAMESRVR_1="${USER_DNS_1:-${DHCP_NAMESRVR_1:-${GOOGLE_DNS_1}}}";
+  DNS_NAMESRVR_2="${USER_DNS_2:-${DHCP_NAMESRVR_2:-${GOOGLE_DNS_2}}}";
+  DNS_NAMESRVR_3="${USER_DNS_3:-${DHCP_NAMESRVR_3:-${CLOUDFARE_DNS_1}}}";
+  DNS_FALLBACK_1="${OPEN_DNS_1}";
+  DNS_FALLBACK_2="${CLOUDFARE_DNS_2}";
+  DNS_FALLBACK_3="${VERISIGN_DNS_1}";
 
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	# Dingbats, intuitive logging chars/info
-	BOX_CHECK="☑";
-	BOX_XMARK="☒":
-	DASHES="-----------------------------------------------------------------------";
-	START_TIMESTAMP="$(date +'%Y%m%d_%H%M%S')";
+  # Dingbats, intuitive logging chars/info
+  BOX_CHECK="☑";
+  BOX_XMARK="☒":
+  DASHES="-----------------------------------------------------------------------";
+  START_TIMESTAMP="$(date +'%Y%m%d_%H%M%S')";
 
-	# Detect current IP Config
-	THIS_LAN_SUBNET=$(ip route | grep -v '169.254.0.0/16' | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ([a-zA-Z0-9]+) [a-zA-Z0-9 ]* (((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))( [a-zA-Z0-9 ]*)?$/\2/p" | head -n 1;);
-	THIS_LAN_BROADCAST=$(ip route | grep -v '169.254.0.0/16' | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ([a-zA-Z0-9]+) [a-zA-Z0-9 ]* (((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))( [a-zA-Z0-9 ]*)?$/\3/p" | head -n 1;);
-	THIS_LAN_PREFIX=$(ip route | grep -v '169.254.0.0/16' | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ([a-zA-Z0-9]+) [a-zA-Z0-9 ]* (((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))( [a-zA-Z0-9 ]*)?$/\7/p" | head -n 1;);
-	THIS_LAN_IPV4=$(ip route | grep -v '169.254.0.0/16' | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ([a-zA-Z0-9]+) [a-zA-Z0-9 ]* (((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))( [a-zA-Z0-9 ]*)?$/\9/p" | head -n 1;);
-	THIS_GATEWAY_IPV4=$(ip route | grep 'default via '| sed -rne "s/^([a-zA-Z0-9]* )*default +via +([0-9a-fA-F\:\.]+) +[a-zA-Z0-9]+ +([a-zA-Z0-9]+).+$/\2/p" | head -n 1;);
-	THIS_LAN_NIC=$(ip route | grep 'default via '| sed -rne "s/^([a-zA-Z0-9]* )*default +via +([0-9a-fA-F\:\.]+) +[a-zA-Z0-9]+ +([a-zA-Z0-9]+).+$/\3/p" | head -n 1;);
-	test -z "${THIS_LAN_IPV4}" && THIS_LAN_IPV4=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\.' | head -n 1 2>'/dev/null';);
-	test -z "${THIS_LAN_PREFIX}" && THIS_LAN_PREFIX=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/^.*\///' | head -n 1 2>'/dev/null';);
-	test -z "${THIS_LAN_SUBNET}" && THIS_LAN_SUBNET=$(ip route | grep "$(echo ${THIS_LAN_IPV4} | cut -d. -f1-2)" | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ${THIS_LAN_NIC}.*$/\2/p" | head -n 1;);
-	test -z "${THIS_LAN_BROADCAST}" && THIS_LAN_BROADCAST=$(ip route | grep "$(echo ${THIS_LAN_IPV4} | cut -d. -f1-2)" | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ${THIS_LAN_NIC}.*$/\3/p" | head -n 1;);
-	test -z "${THIS_LAN_NETMASK}" && THIS_LAN_NETMASK=$(M=$(( 0xffffffff ^ ((1 << (32-${THIS_LAN_PREFIX})) -1) )) 2>'/dev/null'; echo "$(( (M>>24) & 0xff )).$(( (M>>16) & 0xff )).$(( (M>>8) & 0xff )).$(( M & 0xff ))" 2>'/dev/null';);
+  # Detect current IP Config
+  THIS_LAN_SUBNET=$(ip route | grep -v '169.254.0.0/16' | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ([a-zA-Z0-9]+) [a-zA-Z0-9 ]* (((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))( [a-zA-Z0-9 ]*)?$/\2/p" | head -n 1;);
+  THIS_LAN_BROADCAST=$(ip route | grep -v '169.254.0.0/16' | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ([a-zA-Z0-9]+) [a-zA-Z0-9 ]* (((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))( [a-zA-Z0-9 ]*)?$/\3/p" | head -n 1;);
+  THIS_LAN_PREFIX=$(ip route | grep -v '169.254.0.0/16' | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ([a-zA-Z0-9]+) [a-zA-Z0-9 ]* (((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))( [a-zA-Z0-9 ]*)?$/\7/p" | head -n 1;);
+  THIS_LAN_IPV4=$(ip route | grep -v '169.254.0.0/16' | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ([a-zA-Z0-9]+) [a-zA-Z0-9 ]* (((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))( [a-zA-Z0-9 ]*)?$/\9/p" | head -n 1;);
+  THIS_GATEWAY_IPV4=$(ip route | grep 'default via '| sed -rne "s/^([a-zA-Z0-9]* )*default +via +([0-9a-fA-F\:\.]+) +[a-zA-Z0-9]+ +([a-zA-Z0-9]+).+$/\2/p" | head -n 1;);
+  THIS_LAN_NIC=$(ip route | grep 'default via '| sed -rne "s/^([a-zA-Z0-9]* )*default +via +([0-9a-fA-F\:\.]+) +[a-zA-Z0-9]+ +([a-zA-Z0-9]+).+$/\3/p" | head -n 1;);
+  test -z "${THIS_LAN_IPV4}" && THIS_LAN_IPV4=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\.' | head -n 1 2>'/dev/null';);
+  test -z "${THIS_LAN_PREFIX}" && THIS_LAN_PREFIX=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/^.*\///' | head -n 1 2>'/dev/null';);
+  test -z "${THIS_LAN_SUBNET}" && THIS_LAN_SUBNET=$(ip route | grep "$(echo ${THIS_LAN_IPV4} | cut -d. -f1-2)" | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ${THIS_LAN_NIC}.*$/\2/p" | head -n 1;);
+  test -z "${THIS_LAN_BROADCAST}" && THIS_LAN_BROADCAST=$(ip route | grep "$(echo ${THIS_LAN_IPV4} | cut -d. -f1-2)" | sed -rne "s/^([a-zA-Z0-9]* )*((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\/([0-9]+)) dev ${THIS_LAN_NIC}.*$/\3/p" | head -n 1;);
+  test -z "${THIS_LAN_NETMASK}" && THIS_LAN_NETMASK=$(M=$(( 0xffffffff ^ ((1 << (32-${THIS_LAN_PREFIX})) -1) )) 2>'/dev/null'; echo "$(( (M>>24) & 0xff )).$(( (M>>16) & 0xff )).$(( (M>>8) & 0xff )).$(( M & 0xff ))" 2>'/dev/null';);
 
 
-	# Kernel-Info
-	IS_LINUX=$(if [[ $(uname -s | grep Linux | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
-	IS_WINDOWS_WSL=$(if [[ "$(< /proc/version)" == *@(Microsoft|WSL)* ]]; then echo 1; else echo 0; fi; );
-	if [ "${IS_LINUX}" != "1" ]; then
+  # Kernel-Info
+  IS_LINUX=$(if [[ $(uname -s | grep Linux | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
+  IS_WINDOWS_WSL=$(if [[ "$(< /proc/version)" == *@(Microsoft|WSL)* ]]; then echo 1; else echo 0; fi; );
+  if [ "${IS_LINUX}" != "1" ]; then
     echo -e "\n""Error:  Must run in a Linux-based environment";
     exit 1;
 
-	elif [ "${IS_WINDOWS_WSL}" != "1" ]; then
+  elif [ "${IS_WINDOWS_WSL}" != "1" ]; then
     if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
 
       #
@@ -268,19 +268,19 @@ else
       echo "Error:  Linux kernel/distro not supported";
       exit 1;
     fi;
-	fi;
+  fi;
 
-	# Network config filepaths
-	ETC_DHCPCD_CONF="/etc/dhcpcd.conf"; # DHCPCD Service Config-File
-	DEBIAN_NETWORK_CONF="/etc/network/interfaces.d/999-update_dns_config.cfg";
-	NMCLI_CONF=$(find '/etc/sysconfig/network-scripts/' -name "ifcfg-${THIS_LAN_NIC}" | head -n 1 2>'/dev/null';);
-	NETWORK_SYSCONF="/etc/sysconfig/network";
-	ETC_RESOLVCONF="/etc/resolv.conf"; # Final output which is-built-from/pulls-from from multiple sources
+  # Network config filepaths
+  ETC_DHCPCD_CONF="/etc/dhcpcd.conf"; # DHCPCD Service Config-File
+  DEBIAN_NETWORK_CONF="/etc/network/interfaces.d/999-update_dns_config.cfg";
+  NMCLI_CONF=$(find '/etc/sysconfig/network-scripts/' -name "ifcfg-${THIS_LAN_NIC}" | head -n 1 2>'/dev/null';);
+  NETWORK_SYSCONF="/etc/sysconfig/network";
+  ETC_RESOLVCONF="/etc/resolv.conf"; # Final output which is-built-from/pulls-from from multiple sources
 
-	# Rename/Remove old network config filepath
-	OLD_DEBIAN_CONF="/etc/network/interfaces.d/50-cloud-init.cfg"; if [ -f "${OLD_DEBIAN_CONF}" ]; then if [ -f "${DEBIAN_NETWORK_CONF}"]; then rm -f "${OLD_DEBIAN_CONF}"; else mv -f "${OLD_DEBIAN_CONF}" "${DEBIAN_NETWORK_CONF}"; fi; fi;
+  # Rename/Remove old network config filepath
+  OLD_DEBIAN_CONF="/etc/network/interfaces.d/50-cloud-init.cfg"; if [ -f "${OLD_DEBIAN_CONF}" ]; then if [ -f "${DEBIAN_NETWORK_CONF}"]; then rm -f "${OLD_DEBIAN_CONF}"; else mv -f "${OLD_DEBIAN_CONF}" "${DEBIAN_NETWORK_CONF}"; fi; fi;
 
-	if [ -n "${NMCLI_CONF}" ]; then
+  if [ -n "${NMCLI_CONF}" ]; then
 
     # NetworkManager Device Configuration
 
@@ -461,7 +461,7 @@ else
 
     fi;
 
-	else # ------------------------------------------------------------
+  else # ------------------------------------------------------------
 
     /usr/bin/networkctl status;
 
@@ -715,33 +715,33 @@ else
       fi;
 
     fi;
-	
-	fi;
+  
+  fi;
 
-	# ------------------------------------------------------------
-	#
-	# Show the final network configuration
-	#
+  # ------------------------------------------------------------
+  #
+  # Show the final network configuration
+  #
 
-	# verify the configuration tied to eth0
-	# echo "";
-	# echo "Calling [ifconfig eth0]...";
-	# echo "${DASHES}"; ifconfig eth0; echo "${DASHES}";
+  # verify the configuration tied to eth0
+  # echo "";
+  # echo "Calling [ifconfig eth0]...";
+  # echo "${DASHES}"; ifconfig eth0; echo "${DASHES}";
 
-	sleep 2;
+  sleep 2;
 
-	if [ -f "${DEBIAN_NETWORK_CONF}" ]; then
+  if [ -f "${DEBIAN_NETWORK_CONF}" ]; then
     echo -e "\n""Info:  Calling [cat \"${DEBIAN_NETWORK_CONF}\"]";
     echo "${DASHES}"; cat "${DEBIAN_NETWORK_CONF}"; echo "${DASHES}";
-	elif [ -f "${NMCLI_CONF}" ]; then
+  elif [ -f "${NMCLI_CONF}" ]; then
     echo -e "\n""Info:  Calling [cat \"${NMCLI_CONF}\"]";
     echo "${DASHES}"; cat "${NMCLI_CONF}"; echo "${DASHES}";
-	fi;
+  fi;
 
-	if [ -f "${ETC_RESOLVCONF}" ]; then
+  if [ -f "${ETC_RESOLVCONF}" ]; then
     echo -e "\n""Info:  Calling [cat \"${ETC_RESOLVCONF}\"]";
     echo "${DASHES}"; cat "${ETC_RESOLVCONF}"; echo "${DASHES}";
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/update_from_git_repo b/usr/local/sbin/update_from_git_repo
--- a/usr/local/sbin/update_from_git_repo
+++ b/usr/local/sbin/update_from_git_repo
@@ -17,28 +17,28 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	
-	EXIT_CODE=1;
+  # ------------------------------------------------------------
+  
+  EXIT_CODE=1;
 
-	# Make sure required runtime(s) are installed
-	if [ -z "$(which dos2unix 2>'/dev/null')" ]; then
+  # Make sure required runtime(s) are installed
+  if [ -z "$(which dos2unix 2>'/dev/null')" ]; then
     apt-get-update -y; apt-get install -y dos2unix;
-	fi;
-	
-	DIR_REPO_BASE="";
+  fi;
+  
+  DIR_REPO_BASE="";
 
-	# Detect & handle WSL instance(s)
-	WSL_CHECK_EXISTS=$(which get_username_windows_wsl 2>'/dev/null');
-	if [ -n "${WSL_CHECK_EXISTS}" ]; then
+  # Detect & handle WSL instance(s)
+  WSL_CHECK_EXISTS=$(which get_username_windows_wsl 2>'/dev/null');
+  if [ -n "${WSL_CHECK_EXISTS}" ]; then
     WIN32_USERNAME=$(get_username_windows_wsl);
     WIN32_USER_ERRORS="$?";
-	fi;
-	if [ -n "${WIN32_USER_ERRORS}" ] && [ "${WIN32_USER_ERRORS}" == "0" ]; then
+  fi;
+  if [ -n "${WIN32_USER_ERRORS}" ] && [ "${WIN32_USER_ERRORS}" == "0" ]; then
     #  Windows OS running WSL (Windows Subsystem for Linux) - Locate source directory from amongst Win32-Host-User's files
     WIN32_HOMEDIR=$(find /mnt/*/Users/${WIN32_USERNAME} -mindepth 0 -maxdepth 0 -type d);
     WIN32_USR_LOCAL=$(find ${WIN32_HOMEDIR}/Documents -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
@@ -51,7 +51,7 @@ else
       DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
     fi;
 
-	else
+  else
 
     WHOAMI_HOME_DIR="$(getent passwd $(id -un) | cut --delimiter=: --fields=6)";
     WHOAMI_USR_LOCAL=$(find ${WHOAMI_HOME_DIR} -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
@@ -67,17 +67,17 @@ else
       DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
       SOURCE_DIR_ERRS=$?;
     fi;
-	
-	fi;
+  
+  fi;
 
-	if [ -z "${DIR_REPO_BASE}" ]; then
+  if [ -z "${DIR_REPO_BASE}" ]; then
     # Error-out if any required variable(s) are empty/unset
     EXIT_CODE=1;
 
     echo "";
     echo "Error: Required variable found to be empty/unset: \${DIR_REPO_BASE}";
 
-	elif [ ! -d "${DIR_REPO_BASE}/usr/local/bin/" ] || [ ! -d "${DIR_REPO_BASE}/usr/local/sbin/" ]; then
+  elif [ ! -d "${DIR_REPO_BASE}/usr/local/bin/" ] || [ ! -d "${DIR_REPO_BASE}/usr/local/sbin/" ]; then
     # Error-out if any required source directories are missing
     EXIT_CODE=1;
 
@@ -90,7 +90,7 @@ else
       echo "Error: Directory not-found: [ ${DIR_REPO_BASE}/usr/local/sbin/ ]";
     fi;
 
-	else
+  else
     # Required source directories exist - Update local runtimes from them
     EXIT_CODE=0;
 
@@ -179,8 +179,8 @@ else
     TO_DEL="/usr/local/sbin/jenkins_war_update"; if [ -f "${TO_DEL}" ] && [ ! -h "${TO_DEL}" ]; then rm -f "${TO_DEL}"; fi;
 
 
-	fi;
+  fi;
 
-	exit ${EXIT_CODE};
+  exit ${EXIT_CODE};
 
 fi;
diff --git a/usr/local/sbin/update_jenkins_warfile b/usr/local/sbin/update_jenkins_warfile
--- a/usr/local/sbin/update_jenkins_warfile
+++ b/usr/local/sbin/update_jenkins_warfile
@@ -17,23 +17,23 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	
-	# Base-directory for Jenkins ".war" file
-	JENKINS_DIRNAME_A="/usr/share/jenkins";
-	JENKINS_DIRNAME_B="/usr/lib/jenkins";
+  # ------------------------------------------------------------
+  
+  # Base-directory for Jenkins ".war" file
+  JENKINS_DIRNAME_A="/usr/share/jenkins";
+  JENKINS_DIRNAME_B="/usr/lib/jenkins";
 
-	if [ -f "${JENKINS_DIRNAME_A}/jenkins.war" ]; then
+  if [ -f "${JENKINS_DIRNAME_A}/jenkins.war" ]; then
     JENKINS_RUNTIME_SYSTEM="${JENKINS_DIRNAME_A}/jenkins.war";
-	elif [ -f "${JENKINS_DIRNAME_B}/jenkins.war" ]; then
+  elif [ -f "${JENKINS_DIRNAME_B}/jenkins.war" ]; then
     JENKINS_RUNTIME_SYSTEM="${JENKINS_DIRNAME_B}/jenkins.war";
-	fi;
+  fi;
 
-	if [ -v JENKINS_RUNTIME_SYSTEM ] && [ -n "${JENKINS_RUNTIME_SYSTEM}" ] && [ -f "${JENKINS_RUNTIME_SYSTEM}" ]; then
+  if [ -v JENKINS_RUNTIME_SYSTEM ] && [ -n "${JENKINS_RUNTIME_SYSTEM}" ] && [ -f "${JENKINS_RUNTIME_SYSTEM}" ]; then
 
     # Backup the current Jenkins main-executable (jenkins.war)
     JENKINS_RUNTIME_BACKUP="${JENKINS_RUNTIME_SYSTEM}.$(date +'%Y%m%d_%H%M%S').bak";
@@ -160,10 +160,10 @@ else
     echo "$(date +'%D  %r')   Finished ${0}";
     exit 0;
 
-	else
+  else
     # Error:  File Not Found: Jenkins Warfile (System Runtime File)
     echo "Error:  File Not Found: Jenkins Warfile (System Runtime File)";
     exit 1;
 
-	fi;
+  fi;
 fi;
diff --git a/usr/local/sbin/update_system b/usr/local/sbin/update_system
--- a/usr/local/sbin/update_system
+++ b/usr/local/sbin/update_system
@@ -17,19 +17,19 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
-	if [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then
+  # ------------------------------------------------------------
+  if [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then
     #
     # Disabled for Fedora distros (RHEL/CentOS)
     #
     echo "System-Update disabled for Fedora-based distros (RHEL, CentOS, etc.)";
     exit 1;
 
-	else
+  else
     #
     #  Linux - Fetch, Pull, & Install updates (system & package)
     #
@@ -190,5 +190,5 @@ else
     echo "$(date '+%Y-%m-%d %H:%M:%S') | Finished \"${THIS_SCRIPT}\"";
     echo "------------------------------------------------------------";
     exit 0;
-	fi;
+  fi;
 fi;
diff --git a/usr/local/sbin/update_text_editor b/usr/local/sbin/update_text_editor
--- a/usr/local/sbin/update_text_editor
+++ b/usr/local/sbin/update_text_editor
@@ -17,24 +17,24 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	SYSTEM_EDITOR_1_PATH="/usr/bin/editor";
-	SYSTEM_EDITOR_2_PATH="/etc/alternatives/editor";
+  SYSTEM_EDITOR_1_PATH="/usr/bin/editor";
+  SYSTEM_EDITOR_2_PATH="/etc/alternatives/editor";
 
-	DESIRED_EDITOR_NAME="vi";
-	
-	if [ -z "$(which ${DESIRED_EDITOR_NAME} 2>'/dev/null' 2>'/dev/null')" ]; then
+  DESIRED_EDITOR_NAME="vi";
+  
+  if [ -z "$(which ${DESIRED_EDITOR_NAME} 2>'/dev/null' 2>'/dev/null')" ]; then
     # Desired editor NOT installed --> Attempt to install it
     apt-get update -y;
     apt-get install -y "${DESIRED_EDITOR_NAME}";
-	fi;
+  fi;
 
-	if [ -z "$(which ${DESIRED_EDITOR_NAME} 2>'/dev/null' 2>'/dev/null')" ]; then
+  if [ -z "$(which ${DESIRED_EDITOR_NAME} 2>'/dev/null' 2>'/dev/null')" ]; then
     # Desired editor STILL not installed (unable to be installed)
     echo "";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Unable to install \"${DESIRED_EDITOR_NAME}\"";
@@ -42,7 +42,7 @@ else
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Global editor setting \"${SYSTEM_EDITOR_2_PATH}\" will remain set to: \"${SYSTEM_EDITOR_2_RESOLVED}\"";
     exit 1;
 
-	else
+  else
     # Desired editor IS installed
     declare -a EDITOR_PATHS_TO_UPDATE=( \
       "${SYSTEM_EDITOR_1_PATH}" \
@@ -83,5 +83,5 @@ else
     echo "";
     exit 0;
 
-	fi;
+  fi;
 fi;
diff --git a/usr/local/sbin/update_unifi b/usr/local/sbin/update_unifi
--- a/usr/local/sbin/update_unifi
+++ b/usr/local/sbin/update_unifi
@@ -17,15 +17,15 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	# ------------------------------------------------------------
+  # ------------------------------------------------------------
 
-	SERVICE_NAME="unifi";
-	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-	if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service exists locally
+  SERVICE_NAME="unifi";
+  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+  if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service exists locally
 
     # Show service status
     echo "";
@@ -65,10 +65,10 @@ else
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ /usr/sbin/service \"${SERVICE_NAME}\" status --no-pager --full; ] (after potential update)...";
     /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
 
-	else # Service NOT found to exist as a local service
+  else # Service NOT found to exist as a local service
     echo "";
     echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Update Skipped - Service \"${SERVICE_NAME}\" not found amongst local services";
-	fi;
+  fi;
 
 fi;
 
diff --git a/usr/local/sbin/wsl_shutdown b/usr/local/sbin/wsl_shutdown
--- a/usr/local/sbin/wsl_shutdown
+++ b/usr/local/sbin/wsl_shutdown
@@ -17,16 +17,16 @@ exec 2>&1;
 # Script must run as root or via sudo
 #
 if [ "$(id -un)" != "root" ]; then
-	echo "";
-	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
-	exit 1;
+  echo "";
+  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
+  exit 1;
 else
-	#
-	# WSL (Windows Subsystem for Linux)
-	#  |--> To shutdown WSL, manually create above file via  [ sudo touch /var/run/reboot-required ]  when closing
-	#       terminals, otherwise the linux environment persists the background as a service (essentially hidden)
-	#
-	if [ -f "/usr/local/bin/get_os" ] && [ $("/usr/local/bin/get_os" | grep 'WSL' | wc -l;) -eq 1 ]; then
+  #
+  # WSL (Windows Subsystem for Linux)
+  #  |--> To shutdown WSL, manually create above file via  [ sudo touch /var/run/reboot-required ]  when closing
+  #       terminals, otherwise the linux environment persists the background as a service (essentially hidden)
+  #
+  if [ -f "/usr/local/bin/get_os" ] && [ $("/usr/local/bin/get_os" | grep 'WSL' | wc -l;) -eq 1 ]; then
     source /usr/local/bin/get_os 1>'/dev/null' 2>&1;
 
     echo "";
@@ -37,12 +37,12 @@ else
     echo "Info:  Press CTRL+D (may need to press more than once) to finish WSL shutdown";
     echo "";
 
-	else
+  else
     # Non-WSL Environment detected
     echo "";
     echo "Info:  Skipping shutdown (unable to detect WSL environment)";
     echo "";
     exit 1;
 
-	fi;
+  fi;
 fi;
