replace lines starting with tabs with spaces (tab count 3)

diff --git a/usr/local/bin/ddns_setup b/usr/local/bin/ddns_setup
--- a/usr/local/bin/ddns_setup
+++ b/usr/local/bin/ddns_setup
@@ -29,26 +29,26 @@ if [ ! -f "${NAMECHEAP_SECRET}" ]; then
 		# Namecheap Subdomain
 		REPLY=""; read -p "Enter Namecheap Subdomain (WITHOUT domain):   " -t 120 -r; NAMECHEAP_SUBDOMAIN="$(echo ${REPLY} | tr '[:upper:]' '[:lower:]';)";
 		if [ -z "${NAMECHEAP_SUBDOMAIN}" ]; then
-			echo "Error: Invalid/empty Subdomain entered";
-			exit 1;
+      echo "Error: Invalid/empty Subdomain entered";
+      exit 1;
 		fi;
 
 		# Namecheap Domain
 		REPLY=""; read -p "Enter Namecheap Domain (WITHOUT subdomain):   " -t 120 -r; NAMECHEAP_DOMAIN="$(echo ${REPLY} | tr '[:upper:]' '[:lower:]';)";
 		if [ -z "${NAMECHEAP_DOMAIN}" ]; then
-			echo "Error: Invalid/empty Domain entered";
-			exit 1;
+      echo "Error: Invalid/empty Domain entered";
+      exit 1;
 		fi;
 
 		# Namecheap Auth-Token
 		REPLY=""; read -p "Enter Namecheap Authentication Token (Pass):  " -t 120 -r; NAMECHEAP_TOKEN="$(echo ${REPLY} | tr '[:upper:]' '[:lower:]';)";
 		if [ -z "${NAMECHEAP_TOKEN}" ]; then
-			echo "Error: Invalid/empty Authentication Token entered";
-			exit 1;
+      echo "Error: Invalid/empty Authentication Token entered";
+      exit 1;
 		fi;
 
 		if [ ! -d "$(dirname ${NAMECHEAP_SECRET})" ]; then
-			mkdir -p "$(dirname ${NAMECHEAP_SECRET})";
+      mkdir -p "$(dirname ${NAMECHEAP_SECRET})";
 		fi;
 		# Output the base64-encoded string to the output file which will be pulled-in by the ddns_updater script (via cronjob)
 		echo -n "https://dynamicdns.park-your-domain.com/update?host=${NAMECHEAP_SUBDOMAIN}&domain=${NAMECHEAP_DOMAIN}&password=${NAMECHEAP_TOKEN}&ip=" | base64 --wrap=0 > "${NAMECHEAP_SECRET}";
diff --git a/usr/local/bin/get_username_windows_wsl b/usr/local/bin/get_username_windows_wsl
--- a/usr/local/bin/get_username_windows_wsl
+++ b/usr/local/bin/get_username_windows_wsl
@@ -16,29 +16,29 @@ else
 
 		Invalid_UsersFile="/tmp/invalid_wsl_hosts_$(date +'%s%N')";
 		if [ -f "${Invalid_UsersFile}" ]; then
-			rm -f "${Invalid_UsersFile}";
+      rm -f "${Invalid_UsersFile}";
 		fi;
 
 		Potential_UsersFile="/tmp/potential_wsl_hosts_$(date +'%s%N')";
 		if [ -f "${Potential_UsersFile}" ]; then
-			rm -f "${Potential_UsersFile}";
+      rm -f "${Potential_UsersFile}";
 		fi;
 
 		WSL_HostUser_File="/tmp/valid_wsl_hosts_$(date +'%s%N')";
 		if [ -f "${Valid_UsersFile}" ]; then
-			rm -f "${Valid_UsersFile}";
+      rm -f "${Valid_UsersFile}";
 		fi;
 		
 		# Make sure required runtime(s) are installed
 		if [ -z "$(which bc 2>'/dev/null';)" ]; then
-			apt-get-update -y; apt-get install -y bc;
+      apt-get-update -y; apt-get install -y bc;
 		fi;
 
 		if [ "${1}" == "verbose" ]; then
-			echo "";
-			echo "Invalid_UsersFile=\"${Invalid_UsersFile}\"";
-			echo "Potential_UsersFile=\"${Potential_UsersFile}\"";
-			echo "WSL_HostUser_File=\"${WSL_HostUser_File}\"";
+      echo "";
+      echo "Invalid_UsersFile=\"${Invalid_UsersFile}\"";
+      echo "Potential_UsersFile=\"${Potential_UsersFile}\"";
+      echo "WSL_HostUser_File=\"${WSL_HostUser_File}\"";
 		fi;
 
 		find "${DIR_WIN32_USERS}" \
@@ -50,39 +50,39 @@ else
 		-not -path "${DIR_WIN32_USERS}/Public" \
 		-print0 \
 		| while IFS= read -r -d $'\0' EachUserDir; do
-			LastExitCode=$([[ -r "${EachUserDir}/Documents" ]]; echo $?);
-			if [ "${LastExitCode}" == "0" ]; then
+      LastExitCode=$([[ -r "${EachUserDir}/Documents" ]]; echo $?);
+      if [ "${LastExitCode}" == "0" ]; then
         if [ "${1}" == "verbose" ]; then echo ""; echo "✓ PASS ✓ Can read \"${EachUserDir}\" - Current session has sufficient privilege(s)"; fi;
         echo $(basename "${EachUserDir}") >> "${Potential_UsersFile}";
-			else
+      else
         if [ "${1}" == "verbose" ]; then echo ""; echo "× FAIL × Cannot read \"${EachUserDir}\" - Current session lacks sufficient privilege(s)"; fi;
         echo $(basename "${EachUserDir}") >> "${Invalid_UsersFile}";
-			fi;
+      fi;
 		done;
 		
 		if [ -f "${Potential_UsersFile}" ]; then
-			CountMatchedUsers="$(cat ${Potential_UsersFile} | wc -l)";
+      CountMatchedUsers="$(cat ${Potential_UsersFile} | wc -l)";
 		else
-			CountMatchedUsers="0";
+      CountMatchedUsers="0";
 		fi;
 		
 		if [ $(echo "${CountMatchedUsers} == 1" | bc) -eq 1 ]; then # Matched exactly 1 user
-			if [ "${1}" == "verbose" ]; then
+      if [ "${1}" == "verbose" ]; then
         echo "";
         echo "Found [ ${CountMatchedUsers} ] potential WSL hosts-user(s):";
-			fi;
-			cat "${Potential_UsersFile}";
-			exit 0;
+      fi;
+      cat "${Potential_UsersFile}";
+      exit 0;
 		elif [ $(echo "${CountMatchedUsers} > 1" | bc) -eq 1 ]; then # Matched more than 1 user
 
-			if [ "${1}" == "verbose" ]; then
+      if [ "${1}" == "verbose" ]; then
         echo "";
         echo "Found [ ${CountMatchedUsers} ] potential WSL hosts-user(s): ";
         cat "${Potential_UsersFile}";
-			fi;
+      fi;
 
-			First_WSL_User="";
-			cat "${Potential_UsersFile}" | while read -r EachMatchedUser; do
+      First_WSL_User="";
+      cat "${Potential_UsersFile}" | while read -r EachMatchedUser; do
         DIR_WSL_UBUNTU_ROOTFS=$(find "/mnt/"*"/Users/${EachMatchedUser}/AppData/Local/Packages/"*"Ubuntu"*"/LocalState/rootfs" -mindepth 0 -maxdepth 0 -type d 2> /dev/null);
         if [ -n "${DIR_WSL_UBUNTU_ROOTFS}" ] && [ -d "${DIR_WSL_UBUNTU_ROOTFS}" ]; then
           if [ "${1}" == "verbose" ]; then
@@ -94,25 +94,25 @@ else
             echo -n "${EachMatchedUser}" > "${WSL_HostUser_File}"; # output the first WSL user to-be-identified
           fi;
         fi;
-			done;
+      done;
 
-			if [ -f "${WSL_HostUser_File}" ]; then
+      if [ -f "${WSL_HostUser_File}" ]; then
         cat "${WSL_HostUser_File}";
-			fi;
-			if [ "${1}" == "verbose" ]; then
+      fi;
+      if [ "${1}" == "verbose" ]; then
         echo "";
-			fi;
+      fi;
 
-			exit 0;
+      exit 0;
 
 		else
-			echo "";
-			echo "Error: No directories found matching [ ${DIR_WIN32_USERS}/*/Documents ]";
-			exit 1;
+      echo "";
+      echo "Error: No directories found matching [ ${DIR_WIN32_USERS}/*/Documents ]";
+      exit 1;
 
 		fi;
 		if [ "${1}" == "verbose" ]; then
-			echo "";
+      echo "";
 		fi;
 
 	else
diff --git a/usr/local/sbin/archive_logs b/usr/local/sbin/archive_logs
--- a/usr/local/sbin/archive_logs
+++ b/usr/local/sbin/archive_logs
@@ -65,39 +65,39 @@ else
 		# Stop the target service
 		/usr/sbin/service "${SERVICE_NAME}" stop; RET_CODE=$?;
 		if [ "${RET_CODE}" != "0" ]; then
-			echo "";
-			echo "ERROR:";
-			echo "  Unable to stop service \"${SERVICE_NAME}\" - Exiting...";
-			echo "";
-			exit 1;
+      echo "";
+      echo "ERROR:";
+      echo "  Unable to stop service \"${SERVICE_NAME}\" - Exiting...";
+      echo "";
+      exit 1;
 		
 		else
-			# Create the new logs dir
-			if [ ! -d "${DIR_ARCH}/${SERVICE_NAME}" ]; then
+      # Create the new logs dir
+      if [ ! -d "${DIR_ARCH}/${SERVICE_NAME}" ]; then
         mkdir -p "${DIR_ARCH}/${SERVICE_NAME}";
         chmod 0700 "${DIR_ARCH}/${SERVICE_NAME}";
-			fi;
-			# Migrate all logs to new logs dir
-			mv ${DIR_LOGS}/${SERVICE_NAME}/* ${DIR_ARCH}/${SERVICE_NAME}/.;
-			# Remove old (now empty) logs dir
-			rmdir ${DIR_LOGS}/${SERVICE_NAME};
-			# Link the old logs dir to the new logs dir with a symbolic link
-			ln -sf "${DIR_ARCH}/${SERVICE_NAME}" "${DIR_LOGS}/${SERVICE_NAME}";
-			# Start the target service
-			/usr/sbin/service "${SERVICE_NAME}" start;
+      fi;
+      # Migrate all logs to new logs dir
+      mv ${DIR_LOGS}/${SERVICE_NAME}/* ${DIR_ARCH}/${SERVICE_NAME}/.;
+      # Remove old (now empty) logs dir
+      rmdir ${DIR_LOGS}/${SERVICE_NAME};
+      # Link the old logs dir to the new logs dir with a symbolic link
+      ln -sf "${DIR_ARCH}/${SERVICE_NAME}" "${DIR_LOGS}/${SERVICE_NAME}";
+      # Start the target service
+      /usr/sbin/service "${SERVICE_NAME}" start;
 
-			### Archive each log-file found (which is not the latest logfile, as-to avoid collisions with application file-access)
-			# for EACH_FILE in $(find "${DIR_LOGS}/${SERVICE_NAME}/" -type f -name "${GLOB_PATTERN}"); do
-			# 	BASENAME=$(basename "${EACH_FILE}");
-			# 	PATH_LOGS="${DIR_LOGS}/${SERVICE_NAME}/${BASENAME}"; 
-			# 	PATH_ARCH="${DIR_ARCH}/${SERVICE_NAME}/${BASENAME}";
-			# 	if [ -e "${PATH_LOGS}" ] && [ ! -e "${PATH_ARCH}" ]; then
-			# 		echo "Archiving log file  [ ${PATH_LOGS} ]  to path  [${PATH_ARCH} ]  ...";
-			# 		mv "${PATH_LOGS}" "${PATH_ARCH}";
-			# 		chmod 0400 "${PATH_ARCH}";
-			# 		ln -sf "${PATH_ARCH}" "${PATH_LOGS}";
-			# 	fi;
-			# done;
+      ### Archive each log-file found (which is not the latest logfile, as-to avoid collisions with application file-access)
+      # for EACH_FILE in $(find "${DIR_LOGS}/${SERVICE_NAME}/" -type f -name "${GLOB_PATTERN}"); do
+      # 	BASENAME=$(basename "${EACH_FILE}");
+      # 	PATH_LOGS="${DIR_LOGS}/${SERVICE_NAME}/${BASENAME}"; 
+      # 	PATH_ARCH="${DIR_ARCH}/${SERVICE_NAME}/${BASENAME}";
+      # 	if [ -e "${PATH_LOGS}" ] && [ ! -e "${PATH_ARCH}" ]; then
+      # 		echo "Archiving log file  [ ${PATH_LOGS} ]  to path  [${PATH_ARCH} ]  ...";
+      # 		mv "${PATH_LOGS}" "${PATH_ARCH}";
+      # 		chmod 0400 "${PATH_ARCH}";
+      # 		ln -sf "${PATH_ARCH}" "${PATH_LOGS}";
+      # 	fi;
+      # done;
 
 		fi;
 
diff --git a/usr/local/sbin/get_services b/usr/local/sbin/get_services
--- a/usr/local/sbin/get_services
+++ b/usr/local/sbin/get_services
@@ -23,13 +23,13 @@ else
 		# SERVICE_RET_CODE=$(/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
 		SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
 		if [ ${SERVICE_RET_CODE} -eq 0 ]; then
-			# If service IS found: Show service & exit with return-code 0
-			/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
-			exit 0;
+      # If service IS found: Show service & exit with return-code 0
+      /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
+      exit 0;
 		else
-			# If service is NOT found: Alert user & exit with return-code 1
-			echo "Error:  Service \"${1}\" not found locally";
-			exit 1;
+      # If service is NOT found: Alert user & exit with return-code 1
+      echo "Error:  Service \"${1}\" not found locally";
+      exit 1;
 		fi;
 
 	fi;
diff --git a/usr/local/sbin/install_docker b/usr/local/sbin/install_docker
--- a/usr/local/sbin/install_docker
+++ b/usr/local/sbin/install_docker
@@ -43,9 +43,9 @@ else
 
 		# Download Docker Desktop (if not found locally)
 		if [ ! -f "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" ]; then
-			echo -e "\n""Error: Must install Docker Desktop (for Windows), which WSL will leverage through direct-calls via WSL 2.0 CLI pass-through""\n";
-			"/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" "https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe";
-			exit 1;
+      echo -e "\n""Error: Must install Docker Desktop (for Windows), which WSL will leverage through direct-calls via WSL 2.0 CLI pass-through""\n";
+      "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" "https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe";
+      exit 1;
 		fi;
 
 		# if [ -v SUDO_USER ]; then
@@ -63,29 +63,29 @@ else
 		#
 
 		if [ ! -f "${BIN_DOCKER}" ]; then
-			curl -ssL "https://get.docker.com/" | sh;
+      curl -ssL "https://get.docker.com/" | sh;
 		fi;
 
 		SERVICE_NAME="docker";
 		if [ -z "$(/usr/sbin/service ${SERVICE_NAME} status | grep 'Active: active (running)')" ]; then
-			echo "Calling [ /usr/sbin/service \"${SERVICE_NAME}\" start; ]...";
-			/usr/sbin/service "${SERVICE_NAME}" start;
+      echo "Calling [ /usr/sbin/service \"${SERVICE_NAME}\" start; ]...";
+      /usr/sbin/service "${SERVICE_NAME}" start;
 		fi;
 
 		if [ ! -f "${BIN_DOCKER_COMPOSE}" ]; then
 
-			if [ -n "$(which apk 2>/dev/null)" ]; then
+      if [ -n "$(which apk 2>/dev/null)" ]; then
         # Alpine Distro(s) --> Install Prerequisite-Packages [ py-pip, python-dev, libffi-dev, openssl-dev, gcc, libc-dev, & make ]
         apk update && apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make;
-			fi;
-			if [ "$(uname -m)" == "x86_64" ]; then
+      fi;
+      if [ "$(uname -m)" == "x86_64" ]; then
         #
         # Docker-Compose Installer --> x86_64 CPUs
         #  |--> Reference: [ https://docs.docker.com/compose/install ]
         #
         curl -ssL "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o "${BIN_DOCKER_COMPOSE}";
         # curl -ssL "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64" -o "${BIN_DOCKER_COMPOSE}";
-			else
+      else
         #
         # Docker-Compose Installer --> Non-x86_64 CPUs (namely Raspberry Pis, which have ARM64 ("aarch64" machine hardware name) CPUs)
         #  |--> Reference: [ https://github.com/docker/compose/issues/6831#issuecomment-558865087 ]
@@ -100,9 +100,9 @@ else
         pip3 install --upgrade pip;
         echo "Calling [ python3 -m pip install -IU docker-compose; ]...";
         python3 -m pip install -IU docker-compose;
-			fi;
+      fi;
 
-			chmod 0755 "${BIN_DOCKER_COMPOSE}";
+      chmod 0755 "${BIN_DOCKER_COMPOSE}";
 
 		fi;
 		
diff --git a/usr/local/sbin/jenkins_diag_info b/usr/local/sbin/jenkins_diag_info
--- a/usr/local/sbin/jenkins_diag_info
+++ b/usr/local/sbin/jenkins_diag_info
@@ -36,14 +36,14 @@ else
 		read -p "Install the Java Developer Toolkit, now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
 		echo "";
 		if [ ${RETURN_CODE_READ} -gt 128 ]; then
-			echo "Error:  Response timed out after ${READ_TIMEOUT}s";
-			exit 1;
+      echo "Error:  Response timed out after ${READ_TIMEOUT}s";
+      exit 1;
 		elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
-			# install_java - Instals Java + Java Developer Toolkit
-			curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java?t=$(date +'%s.%N')" | bash;
+      # install_java - Instals Java + Java Developer Toolkit
+      curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java?t=$(date +'%s.%N')" | bash;
 		else
-			echo "Info:  Required package-install denied  -->  Exiting...";
-			exit 1;
+      echo "Info:  Required package-install denied  -->  Exiting...";
+      exit 1;
 		fi;
 	fi;
 
diff --git a/usr/local/sbin/jenkins_log_cleanup b/usr/local/sbin/jenkins_log_cleanup
--- a/usr/local/sbin/jenkins_log_cleanup
+++ b/usr/local/sbin/jenkins_log_cleanup
@@ -50,20 +50,20 @@ else
 		JENKINS_UHOME=$(getent passwd ${JENKINS_UNAME} | cut --delimiter=: --fields=6);
 
 		if [ ! -d "${JENKINS_UHOME}" ]; then # jenkins home-dir not found
-			echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - Jenkins home-directory not found: \"${JENKINS_UHOME}\"";
-			exit 1;
+      echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - Jenkins home-directory not found: \"${JENKINS_UHOME}\"";
+      exit 1;
 
 		else # good to go - begin deleting dirs
 
-			FIND_PARENT="${JENKINS_UHOME}/jobs/";
-			FIND_REGEX="^${FIND_PARENT}.+/builds/[0-9]+$";
+      FIND_PARENT="${JENKINS_UHOME}/jobs/";
+      FIND_REGEX="^${FIND_PARENT}.+/builds/[0-9]+$";
 
-			echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nDeleting files matching the following constraint(s):";
-			echo "  File hasn't been modified for at least ${MAX_AGE_DAYS} days";
-			echo "  Filepath starts with: \"${FIND_PARENT}\"";
-			echo "  Filepath matches regex: \"${FIND_REGEX}\"...";
+      echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nDeleting files matching the following constraint(s):";
+      echo "  File hasn't been modified for at least ${MAX_AGE_DAYS} days";
+      echo "  Filepath starts with: \"${FIND_PARENT}\"";
+      echo "  Filepath matches regex: \"${FIND_REGEX}\"...";
 
-			find "${FIND_PARENT}" \
+      find "${FIND_PARENT}" \
         -maxdepth 3 \
         -type d \
         -regex "${FIND_REGEX}" \
diff --git a/usr/local/sbin/set_hostname b/usr/local/sbin/set_hostname
--- a/usr/local/sbin/set_hostname
+++ b/usr/local/sbin/set_hostname
@@ -52,23 +52,23 @@ else
 
 		# Check if this is the last inline-argument or if there are more to follow
 		if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
-			NEXT_ARG="";
+      NEXT_ARG="";
 		else
-			NEXT_ARG=${ARGS[$((${i}+1))]};
-			if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
+      NEXT_ARG=${ARGS[$((${i}+1))]};
+      if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
         NEXT_ARG="";
-			fi;
+      fi;
 		fi;
 
 		if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
 
-			# Parse inline hostname
-			if [ ${i} -eq 0 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then # Allow the first argument to be the hostname (without needing --hostname before it)
+      # Parse inline hostname
+      if [ ${i} -eq 0 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then # Allow the first argument to be the hostname (without needing --hostname before it)
         NEXT_ARG="${EACH_ARG}";
         EACH_ARG="--hostname";
-			fi;
+      fi;
 
-			if [ "${EACH_ARG}" == "--name" ] || [ "${EACH_ARG}" == "--hostname" ]; then
+      if [ "${EACH_ARG}" == "--name" ] || [ "${EACH_ARG}" == "--hostname" ]; then
         if [ "${ARGS_HOSTNAME_DEFINED}" == "1" ]; then
           echo "";
           echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Inline parameters contain more than one value for hostname";
@@ -79,20 +79,20 @@ else
           ARGS_HOSTNAME_DEFINED=1;
           INPUT_HOSTNAME="${NEXT_ARG}";
         fi;
-			fi;
+      fi;
 
-			if [ "${EACH_ARG}" == "--wan" ]; then # --force
+      if [ "${EACH_ARG}" == "--wan" ]; then # --force
         USE_WAN_IPV4=1;
-			fi;
+      fi;
 
-			# Parse dry-run / non-dry-run calls
-			if [ "${EACH_ARG}" == "--force" ]; then # --force
+      # Parse dry-run / non-dry-run calls
+      if [ "${EACH_ARG}" == "--force" ]; then # --force
         DRY_RUN="0";
-			elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "0" ]; then # --dry-run 0
+      elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "0" ]; then # --dry-run 0
         DRY_RUN="0";
-			elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "false" ]; then # --dry-run false
+      elif [ "${EACH_ARG}" == "--dry-run" ] && [ -n "${NEXT_ARG}" ] && [ "${NEXT_ARG}" == "false" ]; then # --dry-run false
         DRY_RUN="0";
-			fi;
+      fi;
 
 		fi;
 	done;
@@ -129,15 +129,15 @@ else
 		SUBSTRING_ONLY_PERIODS="${INPUT_HOSTNAME//[^.]}";
 		FQDN_COUNT_PERIODS="${#SUBSTRING_ONLY_PERIODS}";
 		if [ "${FQDN_COUNT_PERIODS}" == "0" ]; then
-			# Hostname includes no periods - use it as-is
-			SET_HOSTNAME="${INPUT_HOSTNAME}";
-			if [ -v CURRENT_DOMAIN ] && [ -n "${CURRENT_DOMAIN}" ]; then
+      # Hostname includes no periods - use it as-is
+      SET_HOSTNAME="${INPUT_HOSTNAME}";
+      if [ -v CURRENT_DOMAIN ] && [ -n "${CURRENT_DOMAIN}" ]; then
         SET_DOMAIN="${CURRENT_DOMAIN}";
-			fi;
+      fi;
 		else
-			# Hostname has at least one period in it --> parse the domain name out from the hostname
-			SET_HOSTNAME=$(echo "${INPUT_HOSTNAME}" | cut --delimiter="." --fields=1 --only-delimited;);
-			SET_DOMAIN=$(echo "${INPUT_HOSTNAME}" | cut --delimiter="." --fields=1 --complement --only-delimited;);
+      # Hostname has at least one period in it --> parse the domain name out from the hostname
+      SET_HOSTNAME=$(echo "${INPUT_HOSTNAME}" | cut --delimiter="." --fields=1 --only-delimited;);
+      SET_DOMAIN=$(echo "${INPUT_HOSTNAME}" | cut --delimiter="." --fields=1 --complement --only-delimited;);
 		fi;
 
 		echo "";
@@ -178,53 +178,53 @@ else
 		### Get LAN-Local IPv4, as well as LAN-Local IPv6 (if exists)
 		THIS_LAN_IPV4=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\.' 2>'/dev/null';);
 		if [ -z "${THIS_LAN_IPV4}" ]; then
-			THIS_LAN_IPV4=$(hostname -i | awk '{print $1}' 2>'/dev/null';);
+      THIS_LAN_IPV4=$(hostname -i | awk '{print $1}' 2>'/dev/null';);
 		fi;
 		THIS_LAN_IPV6=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\:' 2>'/dev/null';);
 
 		if [ ${USE_WAN_IPV4} -ne 0 ]; then
-			### Show Resolved WAN IPv4
-			if [ -n "${THIS_WAN_IPV4}" ]; then
+      ### Show Resolved WAN IPv4
+      if [ -n "${THIS_WAN_IPV4}" ]; then
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  WAN Outgoing IPv4 resolved to \"${THIS_WAN_IPV4}\"";
-			else
+      else
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Unable to resolve outgoing WAN IPv4 Address";
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ env THIS_WAN_IPV4=\"127.0.0.1\" ${0} ]  (replacing 127.0.0.1 with machine's WAN IPv4)";
         exit 1;
-			fi;
+      fi;
 		else
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Optional) Resolve hostname requests to WAN IPv4 (instead of LAN) using syntax  [ ${0} --wan ]";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Optional) Resolve hostname requests to WAN IPv4 (instead of LAN) using syntax  [ ${0} --wan ]";
 		fi;
 
 		### Show Resolved Gateway IPv4
 		if [ -n "${THIS_GATEWAY_IPV4}" ]; then
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Gateway IPv4 resolved to \"${THIS_GATEWAY_IPV4}\"";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Gateway IPv4 resolved to \"${THIS_GATEWAY_IPV4}\"";
 		else 
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Warning:  Unable to resolve LAN's Gateway-IPv4.";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Warning:  Unable to resolve LAN's Gateway-IPv4.";
 		fi;
 
 		### Show Resolved LAN IPv4
 		if [ -n "${THIS_LAN_IPV4}" ]; then
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Local IPv4 resolved to \"${THIS_LAN_IPV4}\"";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Local IPv4 resolved to \"${THIS_LAN_IPV4}\"";
 		else 
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Error: Unable to resolve LAN Local IPv4 Address  - If you wish to manually set it, please set \${THIS_LAN_IPV4} to your desired value, then re-run this script";
-			exit 1;
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Error: Unable to resolve LAN Local IPv4 Address  - If you wish to manually set it, please set \${THIS_LAN_IPV4} to your desired value, then re-run this script";
+      exit 1;
 		fi;
 
 		### Show Resolved LAN IPv6
 		if [ -n "${THIS_LAN_IPV6}" ]; then
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Local IPv6 resolved to \"${THIS_LAN_IPV6}\"";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Local IPv6 resolved to \"${THIS_LAN_IPV6}\"";
 		else 
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Warning:  Unable to resolve LAN Local IPv6 Address";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Warning:  Unable to resolve LAN Local IPv6 Address";
 		fi;
 
 		# ------------------------------------------------------------
@@ -232,13 +232,13 @@ else
 		#
 
 		if [[ "${DRY_RUN}" == "0" ]]; then
-			echo ""; read -p "Update hostname, now? (y/n)  " -n 1 -t 60 -r; echo "";
-			if [[ $REPLY =~ ^[Yy]$ ]]; then
+      echo ""; read -p "Update hostname, now? (y/n)  " -n 1 -t 60 -r; echo "";
+      if [[ $REPLY =~ ^[Yy]$ ]]; then
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info: - Confirmed by user - Proceeding with changes to hostname & domain-name...";
-			else
+      else
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info: - Cancelled by user - exiting...";
         exit 1;
-			fi;
+      fi;
 		fi;
 		echo "";
 
@@ -247,7 +247,7 @@ else
 		#
 		HOSTNAME_FILE="/etc/hostname";
 		if [[ -f "${HOSTNAME_FILE}" ]]; then
-			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
+      if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling [ cat \"${HOSTNAME_FILE}\"; ]  (before edits, $(date +'%Y-%m-%d %H:%M:%S'))";
         echo "------------------------------------------------------------";
@@ -266,7 +266,7 @@ else
           echo "";
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Skipping update for hostname file \"${HOSTNAME_FILE}\" (already matches desired hostname)";
         fi;
-			fi;
+      fi;
 		fi;
 
 		# ------------------------------------------------------------
@@ -280,75 +280,75 @@ else
 		HOSTS_FILE="/etc/hosts";
 		if [[ -f "${HOSTS_FILE}" ]]; then
 
-			echo "";
-			if [ ${USE_WAN_IPV4} -ne 0 ]; then
+      echo "";
+      if [ ${USE_WAN_IPV4} -ne 0 ]; then
         SET_HOSTS_IPV4="${THIS_WAN_IPV4}";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Resolving hostname \"${SET_HOSTNAME}\" to WAN IPv4 address \"${THIS_LAN_IPV4}\"";
-			else
+      else
         # Resolve hostname to LAN IPv4
         SET_HOSTS_IPV4="${THIS_LAN_IPV4}";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Resolving hostname \"${SET_HOSTNAME}\" to LAN IPv4 address \"${THIS_LAN_IPV4}\"";
         # Alert user the hostname will NOT be resolved to the WAN IPv4 (but how to do so)
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  To resolve hostname to the current WAN IPv4 \"${THIS_WAN_IPV4}\", instead, call using the \"--wan\" argument (intended for cloud-based servers, where a given WAN IPv4 Address is associated with only one, unique instance of linux)";
-			fi;
+      fi;
 
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling [ cat \"${HOSTS_FILE}\"; ]  (before edits, $(date +'%Y-%m-%d %H:%M:%S'))";
-			echo "------------------------------------------------------------";
-			cat "${HOSTS_FILE}";
-			echo "------------------------------------------------------------";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling [ cat \"${HOSTS_FILE}\"; ]  (before edits, $(date +'%Y-%m-%d %H:%M:%S'))";
+      echo "------------------------------------------------------------";
+      cat "${HOSTS_FILE}";
+      echo "------------------------------------------------------------";
 
-			TEMP_HOSTS="${HOSTS_FILE}.$(date +'%s.%N').tmp";
-			cp -f "${HOSTS_FILE}" "${TEMP_HOSTS}";
+      TEMP_HOSTS="${HOSTS_FILE}.$(date +'%s.%N').tmp";
+      cp -f "${HOSTS_FILE}" "${TEMP_HOSTS}";
 
-			# Remove pre-existing LAN-IPV4 hostsfile lines (leave loopback IPv5 line unaffected)
-			sed -i -e "/^${THIS_LAN_IPV4} /c\\" "${TEMP_HOSTS}";
+      # Remove pre-existing LAN-IPV4 hostsfile lines (leave loopback IPv5 line unaffected)
+      sed -i -e "/^${THIS_LAN_IPV4} /c\\" "${TEMP_HOSTS}";
 
-			if [ ${USE_WAN_IPV4} -ne 0 ]; then # Remove pre-existing WAN-IPV4 hostsfile lines
+      if [ ${USE_WAN_IPV4} -ne 0 ]; then # Remove pre-existing WAN-IPV4 hostsfile lines
         sed -i -e "/^${THIS_WAN_IPV4} /c\\" "${TEMP_HOSTS}";
-			fi;
+      fi;
 
-			sed -i -e "/^::1 /c\\" "${TEMP_HOSTS}"; # Remove pre-existing Loopback-IPv6 line(s)
+      sed -i -e "/^::1 /c\\" "${TEMP_HOSTS}"; # Remove pre-existing Loopback-IPv6 line(s)
 
-			# Update hostname resolution
-			LOOPBACK_IPV4="127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4";
-			LOOPBACK_IPV6="::1 localhost localhost.localdomain localhost6 localhost6.localdomain6";
-			if [ -n "${SET_DOMAIN}" ]; then # Hostname + FQDN (hostname.domainname)
+      # Update hostname resolution
+      LOOPBACK_IPV4="127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4";
+      LOOPBACK_IPV6="::1 localhost localhost.localdomain localhost6 localhost6.localdomain6";
+      if [ -n "${SET_DOMAIN}" ]; then # Hostname + FQDN (hostname.domainname)
         sed -i -e "/^127.0.0.1/{" -e "i\\${SET_HOSTS_IPV4} ${SET_HOSTNAME}.${SET_DOMAIN} ${SET_HOSTNAME}" -e "a\\${LOOPBACK_IPV6}" -e "c\\${LOOPBACK_IPV4}" -e "}" "${TEMP_HOSTS}";
 
-			else # Hostname only (no FQDN)
+      else # Hostname only (no FQDN)
         sed -i -e "/^127.0.0.1/{" -e "i\\${SET_HOSTS_IPV4} ${SET_HOSTNAME}" -e "a\\${LOOPBACK_IPV6}" -e "c\\${LOOPBACK_IPV4}" -e "}" "${TEMP_HOSTS}";
 
-			fi;
+      fi;
 
-			# Remove empty (or whitespace-only) lines
-			sed -i -e '/^\s*$/d' "${TEMP_HOSTS}";
+      # Remove empty (or whitespace-only) lines
+      sed -i -e '/^\s*$/d' "${TEMP_HOSTS}";
 
-			# Trim spaces/tabs off the start of each line
-			sed -i -e 's/^\s*//g' "${TEMP_HOSTS}";
+      # Trim spaces/tabs off the start of each line
+      sed -i -e 's/^\s*//g' "${TEMP_HOSTS}";
 
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling  [ cat \"${TEMP_HOSTS}\"; ]  (after edits, $(date +'%Y-%m-%d %H:%M:%S'))";
-			echo "------------------------------------------------------------";
-			cat "${TEMP_HOSTS}";
-			echo "------------------------------------------------------------";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling  [ cat \"${TEMP_HOSTS}\"; ]  (after edits, $(date +'%Y-%m-%d %H:%M:%S'))";
+      echo "------------------------------------------------------------";
+      cat "${TEMP_HOSTS}";
+      echo "------------------------------------------------------------";
 
 
-			if [[ "${DRY_RUN}" == "0" ]]; then
+      if [[ "${DRY_RUN}" == "0" ]]; then
         # NOT a dry-run -> Overwrite hosts-file
         cp -f "${TEMP_HOSTS}" "${HOSTS_FILE}";
 
-			fi;
-			rm -f "${TEMP_HOSTS}";
-			
+      fi;
+      rm -f "${TEMP_HOSTS}";
+      
 		fi;
 
 		# ------------------------------------------------------------
 		# centos 6
 		#
 		if [[ -f "/etc/sysconfig/network" ]]; then
-			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
+      if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
 
         if [ -n "${SET_DOMAIN}" ]; then
           sed -i -e "/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}.${SET_DOMAIN}" "/etc/sysconfig/network";
@@ -356,52 +356,52 @@ else
           sed -i -e "/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}" "/etc/sysconfig/network";
         fi;
 
-			else # dry-run
+      else # dry-run
         echo "";
         if [ -n "${SET_DOMAIN}" ]; then
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}.${SET_DOMAIN}\" \"/etc/sysconfig/network\"; ]";
         else
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}\" \"/etc/sysconfig/network\"; ]";
         fi;
-			fi;
+      fi;
 		fi;
 
 		# ------------------------------------------------------------
 		# debian 7 / slackware / ubuntu 14.04
 		#
 		if [[ -f "/etc/init.d/hostname.sh" ]]; then
-			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
+      if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         /etc/init.d/hostname.sh;
-			else # dry-run
+      else # dry-run
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ /etc/init.d/hostname.sh; ]";
-			fi;
+      fi;
 		fi;
 
 		# ------------------------------------------------------------
 		# arch / centos 7 / debian 8 / fedora / ubuntu 16.04 and above
 		#
 		if [[ $(hostnamectl | wc -l) -gt 0 ]]; then
-			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
+      if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         hostnamectl set-hostname "${SET_HOSTNAME}";
-			else # dry-run
+      else # dry-run
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ hostnamectl set-hostname \"${SET_HOSTNAME}\" ]";
-			fi;
+      fi;
 		fi;
 
 		if [ ${DRY_RUN} -eq 1 ]; then
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Dry-Run mode is ON - No changes will be made to existing network settings or stored configurations";
-			echo "";
-			echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --dry-run 0 ]  or  [ ${0} --force ]";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Dry-Run mode is ON - No changes will be made to existing network settings or stored configurations";
+      echo "";
+      echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --dry-run 0 ]  or  [ ${0} --force ]";
 		fi;
 
 		# ------------------------------------------------------------
 		# Apply Changes
 		#
 		if [[ -f "/etc/init.d/network" ]]; then # CentOS-RHEL distros
-			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
+      if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         echo "";
         echo "Network Manager must be restarted to apply changes ( required command  [ /etc/init.d/network restart ]  )";
         read -p "   |--> Restart Network Manager, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
@@ -415,12 +415,12 @@ else
           echo "$(date +'%Y-%m-%d %H:%M:%S') Postponing Network Manager restart";
           exit 1;
         fi;
-			else # dry-run
+      else # dry-run
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping network manager restart";
-			fi;
+      fi;
 		else # [other] distros
-			if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
+      if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         echo "";
         echo "System restart required to apply changes to hostname";
         read -p "   |--> Reboot this workstation/server, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
@@ -434,10 +434,10 @@ else
           echo "System restart postponed";
           exit 1;
         fi;
-			# else # dry-run
-			# 	echo "";
-			# 	echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping restart";
-			fi;
+      # else # dry-run
+      # 	echo "";
+      # 	echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping restart";
+      fi;
 		fi;
 		echo "";
 
diff --git a/usr/local/sbin/update_dns_config b/usr/local/sbin/update_dns_config
--- a/usr/local/sbin/update_dns_config
+++ b/usr/local/sbin/update_dns_config
@@ -56,36 +56,36 @@ else
 
 		# Check if this is the last inline-argument or if there are more to follow
 		if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
-			NEXT_ARG="";
+      NEXT_ARG="";
 		else
-			NEXT_ARG=${ARGS[$((${i}+1))]};
-			if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
+      NEXT_ARG=${ARGS[$((${i}+1))]};
+      if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
         NEXT_ARG="";
-			fi;
+      fi;
 		fi;
 
 		if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
 
-			# Parse inline hostname
-			if [ ${i} -eq 0 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then # Allow the first argument to be the hostname (without needing --hostname before it)
+      # Parse inline hostname
+      if [ ${i} -eq 0 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then # Allow the first argument to be the hostname (without needing --hostname before it)
         NEXT_ARG="${EACH_ARG}";
         EACH_ARG="--hostname";
-			fi;
+      fi;
 
-			if [ "${EACH_ARG}" == "--wan" ]; then # --force
+      if [ "${EACH_ARG}" == "--wan" ]; then # --force
         USE_WAN_IPV4=1;
-			fi;
+      fi;
 
-			# Static-IP
-			if [ "${EACH_ARG}" == "--static-ip" ]; then
+      # Static-IP
+      if [ "${EACH_ARG}" == "--static-ip" ]; then
         USE_STATIC_IPV4=1;
         if [ -n "${NEXT_ARG}" ]; then
           SET_STATIC_IPV4="${NEXT_ARG}";
         fi;
-			fi;
+      fi;
 
-			# Domain Name
-			if [ "${EACH_ARG}" == "--domain" ]; then
+      # Domain Name
+      if [ "${EACH_ARG}" == "--domain" ]; then
         USE_SEARCH_DOMAIN=1;
         if [ -n "${NEXT_ARG}" ]; then
           DNS_SEARCH_DOMAIN="${NEXT_ARG}";
@@ -93,37 +93,37 @@ else
           echo "Error:  Must specify domain-name to set after argument --domain, e.g. use syntax [ --domain DOMAIN.TLD ]";
           exit 1;
         fi;
-			fi;
+      fi;
 
-			# Primary DNS Server (#1)
-			if [ "${EACH_ARG}" == "--dns1" ]; then
+      # Primary DNS Server (#1)
+      if [ "${EACH_ARG}" == "--dns1" ]; then
         if [ -n "${NEXT_ARG}" ]; then
           USER_DNS_1="${NEXT_ARG}";
         else
           echo "Error:  Must specify dns hostname / IPv4 --dns1, e.g. use syntax [ --dns1 I.P.V.4 ]";
           exit 1;
         fi;
-			fi;
+      fi;
 
-			# Secondary DNS Server (#2)
-			if [ "${EACH_ARG}" == "--dns2" ]; then
+      # Secondary DNS Server (#2)
+      if [ "${EACH_ARG}" == "--dns2" ]; then
         if [ -n "${NEXT_ARG}" ]; then
           USER_DNS_2="${NEXT_ARG}";
         else
           echo "Error:  Must specify dns hostname / IPv4 --dns2, e.g. use syntax [ --dns2 I.P.V.4 ]";
           exit 1;
         fi;
-			fi;
+      fi;
 
-			# Tertiary DNS Server (#3)
-			if [ "${EACH_ARG}" == "--dns3" ]; then
+      # Tertiary DNS Server (#3)
+      if [ "${EACH_ARG}" == "--dns3" ]; then
         if [ -n "${NEXT_ARG}" ]; then
           USER_DNS_3="${NEXT_ARG}";
         else
           echo "Error:  Must specify dns hostname / IPv4 --dns3, e.g. use syntax [ --dns3 I.P.V.4 ]";
           exit 1;
         fi;
-			fi;
+      fi;
 
 		fi;
 	done;
@@ -136,7 +136,7 @@ else
 		#
 		DNSV4_SERVERS=$(nmcli device show | grep 'IP4.DNS' | awk '{print $2}');
 		if [ -n "${DNSV4_SERVERS}" ]; then
-			for EACH_DNSV4_SERVER in ${DNSV4_SERVERS}; do
+      for EACH_DNSV4_SERVER in ${DNSV4_SERVERS}; do
         if [ -z "${DHCP_NAMESRVR_1}" ]; then
           DHCP_NAMESRVR_1="${EACH_DNSV4_SERVER}"; # Set primary DNS Server
         elif [ -z "${DHCP_NAMESRVR_2}" ]; then
@@ -144,7 +144,7 @@ else
         elif [ -z "${DHCP_NAMESRVR_3}" ]; then
           DHCP_NAMESRVR_3="${EACH_DNSV4_SERVER}"; # Set tertiary DNS Server
         fi;
-			done;
+      done;
 		fi;
 	fi;
 
@@ -221,52 +221,52 @@ else
 	elif [ "${IS_WINDOWS_WSL}" != "1" ]; then
 		if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
 
-			#
-			# Required package:
-			#   resolvconf
-			#
-			# Method(s) used:
-			#   > resolvconf   ### manage nameserver information
-			#
-			REQUIRED_PACKAGE_NAME="resolvconf";
-			REQUIRED_METHOD_NAME="resolvconf";
-			if [ -n "$(which ${REQUIRED_METHOD_NAME} 2>'/dev/null')" ]; then
+      #
+      # Required package:
+      #   resolvconf
+      #
+      # Method(s) used:
+      #   > resolvconf   ### manage nameserver information
+      #
+      REQUIRED_PACKAGE_NAME="resolvconf";
+      REQUIRED_METHOD_NAME="resolvconf";
+      if [ -n "$(which ${REQUIRED_METHOD_NAME} 2>'/dev/null')" ]; then
         echo -e "\n""Info:  Resolved package \"${REQUIRED_METHOD_NAME}\" to path \"$(which ${REQUIRED_METHOD_NAME})\"";
-			else
+      else
         echo -e "\n""Error:  Package \"${REQUIRED_METHOD_NAME}\" not found locally";
         echo -e "\n""Info:  Please install required package via:";
         echo "  |--> apt-get -y update; apt-get -y install \"${REQUIRED_PACKAGE_NAME}\"; reboot;";
         echo ""; exit 1;
-			fi;
+      fi;
 
-			#
-			# Required package:
-			#   ifupdown
-			#
-			# Method(s) used:
-			#   > ifup        ### bring a network interface up
-			#   > ifdown      ### take a network interface down
-			#
-			REQUIRED_PACKAGE_NAME="ifupdown";
-			REQUIRED_METHOD_NAME="ifup";
-			if [ -z "$(which ${REQUIRED_METHOD_NAME} 2>'/dev/null')" ]; then
+      #
+      # Required package:
+      #   ifupdown
+      #
+      # Method(s) used:
+      #   > ifup        ### bring a network interface up
+      #   > ifdown      ### take a network interface down
+      #
+      REQUIRED_PACKAGE_NAME="ifupdown";
+      REQUIRED_METHOD_NAME="ifup";
+      if [ -z "$(which ${REQUIRED_METHOD_NAME} 2>'/dev/null')" ]; then
         echo -e "\n""Error:  Package \"${REQUIRED_METHOD_NAME}\" not found locally";
         echo -e "\n""Info:  Please install required package via:";
         echo "  |--> apt-get -y update; apt-get -y install \"${REQUIRED_PACKAGE_NAME}\"; reboot;";
         echo ""; exit 1;
-			fi;
-			REQUIRED_PACKAGE_NAME="ifupdown";
-			REQUIRED_METHOD_NAME="ifdown";
-			if [ -z "$(which ${REQUIRED_METHOD_NAME} 2>'/dev/null')" ]; then
+      fi;
+      REQUIRED_PACKAGE_NAME="ifupdown";
+      REQUIRED_METHOD_NAME="ifdown";
+      if [ -z "$(which ${REQUIRED_METHOD_NAME} 2>'/dev/null')" ]; then
         echo -e "\n""Error:  Package \"${REQUIRED_METHOD_NAME}\" not found locally";
         echo -e "\n""Info:  Please install required package via:";
         echo "  |--> apt-get -y update; apt-get -y install \"${REQUIRED_PACKAGE_NAME}\"; reboot;";
         echo ""; exit 1;
-			fi;
+      fi;
 
 		else
-			echo "Error:  Linux kernel/distro not supported";
-			exit 1;
+      echo "Error:  Linux kernel/distro not supported";
+      exit 1;
 		fi;
 	fi;
 
@@ -286,12 +286,12 @@ else
 
 		if [ ! -f "${NMCLI_CONF}" ]; then 
 
-			echo "ERROR: DNS Config-File not found @ path \"${NMCLI_CONF}\" - exiting...";
-			exit 1;
+      echo "ERROR: DNS Config-File not found @ path \"${NMCLI_CONF}\" - exiting...";
+      exit 1;
 
 		else
 
-			if [ ${USE_STATIC_IPV4} -eq 1 ]; then
+      if [ ${USE_STATIC_IPV4} -eq 1 ]; then
 
         if [ -z "${SET_STATIC_IPV4}" ]; then
           SET_STATIC_IPV4="${THIS_LAN_IPV4}";
@@ -395,11 +395,11 @@ else
 
           # ------------------------------------------------------------
         fi;
-			fi;
+      fi;
 
 
-			# Set DNS Nameserver(s)
-			if [ -v SET_STATIC_IPV4 ] && [ -n "${SET_STATIC_IPV4}" ]; then
+      # Set DNS Nameserver(s)
+      if [ -v SET_STATIC_IPV4 ] && [ -n "${SET_STATIC_IPV4}" ]; then
         echo -e "\n";
         echo "Info: Request to set DNS NameServers to \"${DNS_NAMESRVR_1}\" (Primary) & \"${DNS_NAMESRVR_2}\" (Secondary)";
         read -p "  |--> Set DNS Nameservers, now? (y/n)  " -n 1 -t 60 -r; # Await single keypress
@@ -445,19 +445,19 @@ else
 
           # ------------------------------------------------------------
         fi;
-			fi;
+      fi;
 
-			echo -e "\n""NetworkManager must be restarted to apply changes ( required command [ nmcli connection reload; /etc/init.d/network restart; ] )";
-			read -p "  |--> Restart NetworkManager, now? (y/n)  " -n 1 -t 60 -r; echo ""; # Await single keypress
-			if [[ $REPLY =~ ^[Yy]$ ]]; then
+      echo -e "\n""NetworkManager must be restarted to apply changes ( required command [ nmcli connection reload; /etc/init.d/network restart; ] )";
+      read -p "  |--> Restart NetworkManager, now? (y/n)  " -n 1 -t 60 -r; echo ""; # Await single keypress
+      if [[ $REPLY =~ ^[Yy]$ ]]; then
         echo -e "\n""Info:  Restarting NetworkManager via command [ nmcli connection reload; /etc/init.d/network restart; ]";
         nmcli connection reload;
         /etc/init.d/network restart;
         # service NetworkManager restart;
-			else
+      else
         echo -e "\n""Info:  Postponing NetworkManager restart";
         exit 1;
-			fi;
+      fi;
 
 		fi;
 
@@ -472,32 +472,32 @@ else
 		FILE_NETWORK_RESOLVER="${FILE_DNS_BUILDER_BASE}";
 		FILE_NETWORK_RESOLVER="${FILE_DNS_BUILDER_TAIL}";
 		if [ "${IS_WINDOWS_WSL}" == "1" ]; then
-			FILE_NETWORK_RESOLVER="${ETC_RESOLVCONF}"; # Windows subsystem for linux - wipe all of resolver (for testing-only as it is rebuilt on WSL-close, or 'shut down' from its perspective)
+      FILE_NETWORK_RESOLVER="${ETC_RESOLVCONF}"; # Windows subsystem for linux - wipe all of resolver (for testing-only as it is rebuilt on WSL-close, or 'shut down' from its perspective)
 		fi;
 
 		# Backup-filepaths
 		BACKUP_CONFIGS_DIR="/root/backup/update_dns_config";
 		OLD_BACKUP_CONFIGS_DIR="/root/backup_network_configs";
 		if [ -d "${OLD_BACKUP_CONFIGS_DIR}" ]; then
-			mkdir -p $(dirname "${BACKUP_CONFIGS_DIR}");
-			mv "${OLD_BACKUP_CONFIGS_DIR}" "${BACKUP_CONFIGS_DIR}";
+      mkdir -p $(dirname "${BACKUP_CONFIGS_DIR}");
+      mv "${OLD_BACKUP_CONFIGS_DIR}" "${BACKUP_CONFIGS_DIR}";
 		else
-			mkdir -p "${BACKUP_CONFIGS_DIR}";
+      mkdir -p "${BACKUP_CONFIGS_DIR}";
 		fi;
 		chmod 700 "${BACKUP_CONFIGS_DIR}"; chown "root:root" "${BACKUP_CONFIGS_DIR}";
 
 		# Backup necesarry config file(s), if-existent
 		FILE_TO_BACKUP="${ETC_RESOLVCONF}";
 		if [ -f "${FILE_TO_BACKUP}" ]; then
-			BASENAME_TO_BACKUP=$(basename "${FILE_TO_BACKUP}");
-			echo -e "\n""Info:  Calling [ cp -f \"${FILE_TO_BACKUP}\" \"${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak\"; ]...";
-			cp -f "${FILE_TO_BACKUP}" "${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak";
+      BASENAME_TO_BACKUP=$(basename "${FILE_TO_BACKUP}");
+      echo -e "\n""Info:  Calling [ cp -f \"${FILE_TO_BACKUP}\" \"${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak\"; ]...";
+      cp -f "${FILE_TO_BACKUP}" "${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak";
 		fi;
 		FILE_TO_BACKUP="${DEBIAN_NETWORK_CONF}";
 		if [ -f "${FILE_TO_BACKUP}" ]; then
-			BASENAME_TO_BACKUP=$(basename "${FILE_TO_BACKUP}");
-			echo -e "\n""Info:  Calling [ cp -f \"${FILE_TO_BACKUP}\" \"${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak\"; ]...";
-			cp -f "${FILE_TO_BACKUP}" "${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak";
+      BASENAME_TO_BACKUP=$(basename "${FILE_TO_BACKUP}");
+      echo -e "\n""Info:  Calling [ cp -f \"${FILE_TO_BACKUP}\" \"${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak\"; ]...";
+      cp -f "${FILE_TO_BACKUP}" "${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak";
 		fi;
 
 		# Setup the nameserver info to make it (eventually) into resolv.conf
@@ -510,49 +510,49 @@ else
 
 		if [ "${IS_WINDOWS_WSL}" != "1" ]; then
 
-			# show "${ETC_RESOLVCONF}" file (configuration before-start)
-			echo -e "\n""Info:  Calling [cat \"${ETC_RESOLVCONF}\"]";
-			echo "${DASHES}"; cat "${ETC_RESOLVCONF}"; echo "${DASHES}";
+      # show "${ETC_RESOLVCONF}" file (configuration before-start)
+      echo -e "\n""Info:  Calling [cat \"${ETC_RESOLVCONF}\"]";
+      echo "${DASHES}"; cat "${ETC_RESOLVCONF}"; echo "${DASHES}";
 
-			# show DNS_NAMESRVR_1,2,3 & Domain-search vars
-			echo -e "\n""Info:  Attempting to configure $(hostname) to use the following DNS Next-Hops:";
-			echo "${DASHES}";
-			echo "DNS_NAMESRVR_1 = \"${DNS_NAMESRVR_1}\"";
-			echo "DNS_NAMESRVR_2 = \"${DNS_NAMESRVR_2}\"";
-			echo "DNS_NAMESRVR_3 = \"${DNS_NAMESRVR_3}\"";
-			echo "DNS_SEARCH_DOMAIN = \"${DNS_SEARCH_DOMAIN}\"";
-			echo "${DASHES}";
+      # show DNS_NAMESRVR_1,2,3 & Domain-search vars
+      echo -e "\n""Info:  Attempting to configure $(hostname) to use the following DNS Next-Hops:";
+      echo "${DASHES}";
+      echo "DNS_NAMESRVR_1 = \"${DNS_NAMESRVR_1}\"";
+      echo "DNS_NAMESRVR_2 = \"${DNS_NAMESRVR_2}\"";
+      echo "DNS_NAMESRVR_3 = \"${DNS_NAMESRVR_3}\"";
+      echo "DNS_SEARCH_DOMAIN = \"${DNS_SEARCH_DOMAIN}\"";
+      echo "${DASHES}";
 
-			# Create the eth0 config file (if it is a valid filepath yet doesnt exist)
-			if [ -n "${DEBIAN_NETWORK_CONF}" ] && [ ! -f "${DEBIAN_NETWORK_CONF}" ]; then
+      # Create the eth0 config file (if it is a valid filepath yet doesnt exist)
+      if [ -n "${DEBIAN_NETWORK_CONF}" ] && [ ! -f "${DEBIAN_NETWORK_CONF}" ]; then
         echo -e "\n""Info:  Calling [echo \"\" > \"${DEBIAN_NETWORK_CONF}\";]...";
         echo "" > "${DEBIAN_NETWORK_CONF}";
-			fi;
+      fi;
 
-			THIS_HYPERVISOR="/sys/hypervisor/uuid";
-			AWS_HV_STARTS_WITH="ec2";
-			if [ ! -v DNS_SEARCH_DOMAIN ] && [ -f "${THIS_HYPERVISOR}" ]; then
+      THIS_HYPERVISOR="/sys/hypervisor/uuid";
+      AWS_HV_STARTS_WITH="ec2";
+      if [ ! -v DNS_SEARCH_DOMAIN ] && [ -f "${THIS_HYPERVISOR}" ]; then
         if [[ "$(cat ${THIS_HYPERVISOR})" == "${AWS_HV_STARTS_WITH}"* ]] && [ -n "${DOMAIN}" ]; then
           DNS_SEARCH_DOMAIN="${DOMAIN}";
         fi;
-			fi;
+      fi;
 
-			DNS_LOOKUP_1=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_1});
-			DNS_LOOKUP_2=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_2});
-			DNS_LOOKUP_3=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_3});
+      DNS_LOOKUP_1=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_1});
+      DNS_LOOKUP_2=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_2});
+      DNS_LOOKUP_3=$(cat ${DEBIAN_NETWORK_CONF} | grep ${DNS_NAMESRVR_3});
 
-			REFRESH_DNS_FILE="0";
+      REFRESH_DNS_FILE="0";
 
-			ACTION_DOMAIN_RESOLUTION="";
-			DOMAIN_RESOLUTION_CONFIGURED="$(cat ${DEBIAN_NETWORK_CONF} | grep 'search ')";
-			if [ -n "${DNS_SEARCH_DOMAIN}" ]; then
+      ACTION_DOMAIN_RESOLUTION="";
+      DOMAIN_RESOLUTION_CONFIGURED="$(cat ${DEBIAN_NETWORK_CONF} | grep 'search ')";
+      if [ -n "${DNS_SEARCH_DOMAIN}" ]; then
         DOMAIN_RESOLUTION_CONFIGURED="$(echo ${DOMAIN_RESOLUTION_CONFIGURED} | grep ${DNS_SEARCH_DOMAIN};)";
         if [ ! -n "${DOMAIN_RESOLUTION_CONFIGURED}" ]; then
           ACTION_DOMAIN_RESOLUTION="SET"; # Need to configure local domain-name resolution
         fi;
-			fi;
+      fi;
 
-			if [ ${USE_STATIC_IPV4} -eq 1 ]; then
+      if [ ${USE_STATIC_IPV4} -eq 1 ]; then
         if [ -z "${SET_STATIC_IPV4}" ]; then
           SET_STATIC_IPV4="${THIS_LAN_IPV4}";
         fi;
@@ -593,13 +593,13 @@ else
             echo "static domain_name_servers=${DNS_NAMESRVR_1}" >> "${ETC_DHCPCD_CONF}";
           fi;
         fi;
-			fi;
+      fi;
 
-			if [ -n "${DNS_LOOKUP_1}" ] && [ -n "${DNS_LOOKUP_2}" ] && [ -n "${DNS_LOOKUP_3}" ] && [ -n "${ACTION_DOMAIN_RESOLUTION}" ]; then # all variables are not null
+      if [ -n "${DNS_LOOKUP_1}" ] && [ -n "${DNS_LOOKUP_2}" ] && [ -n "${DNS_LOOKUP_3}" ] && [ -n "${ACTION_DOMAIN_RESOLUTION}" ]; then # all variables are not null
 
         echo -e "\n""Info:  \"${DEBIAN_NETWORK_CONF}\"'s DNS settings are up-to-date";
         
-			else # at least one DNS-IP/Hostname is missing
+      else # at least one DNS-IP/Hostname is missing
 
         echo -e "\n""Info:  Updating DNS Servers which build out of file \"${DEBIAN_NETWORK_CONF}\"";
         
@@ -636,12 +636,12 @@ else
         
         REFRESH_DNS_FILE="1";
 
-			fi;
+      fi;
 
-			SystemResolveConf="/etc/systemd/resolved.conf";
-			SystemNetworkConfDir="/etc/systemd/network";
+      SystemResolveConf="/etc/systemd/resolved.conf";
+      SystemNetworkConfDir="/etc/systemd/network";
 
-			if [ -f "${SystemResolveConf}" ]; then
+      if [ -f "${SystemResolveConf}" ]; then
 
         echo "Updating Hostname-Resolving Service \"systemd-resolve\" via associated config-file \"${SystemResolveConf}\" ...";
         CAN_USE_SYSRESOLVE_STATUS="$(systemd-resolve --help | grep status)";
@@ -673,10 +673,10 @@ else
           done;
         fi;
         REFRESH_DNS_FILE="1";
-			fi;
+      fi;
 
 
-			if [ "${REFRESH_DNS_FILE}" == "1" ]; then
+      if [ "${REFRESH_DNS_FILE}" == "1" ]; then
         # Take down the main network interface & bring it back up (in one statement)
         echo -e "\n""Info:  Calling [ ifdown -a && ifup -a; ] (takes down the main network interface & bring it back up, in one statement)...";
         echo "${DASHES}"; ifdown -a && ifup -a; echo "${DASHES}";
@@ -712,7 +712,7 @@ else
             echo "${DASHES}"; echo "$(systemd-resolve --status)"; echo "${DASHES}"; ## Must use echo "$(systemd-resolve --status)" to avoid scroll-lock (which holds up entire program)
           fi;
         fi;
-			fi;
+      fi;
 
 		fi;
 	
diff --git a/usr/local/sbin/update_from_git_repo b/usr/local/sbin/update_from_git_repo
--- a/usr/local/sbin/update_from_git_repo
+++ b/usr/local/sbin/update_from_git_repo
@@ -43,12 +43,12 @@ else
 		WIN32_HOMEDIR=$(find /mnt/*/Users/${WIN32_USERNAME} -mindepth 0 -maxdepth 0 -type d);
 		WIN32_USR_LOCAL=$(find ${WIN32_HOMEDIR}/Documents -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
 		if [ ! -n "${WIN32_USR_LOCAL}" ]; then
-			echo "";
-			echo "Unable to locate directory matching 'cloud-infrastructure/usr/local' within win32-user's documents @ '${WIN32_USERNAME}'";
-			exit 1;
+      echo "";
+      echo "Unable to locate directory matching 'cloud-infrastructure/usr/local' within win32-user's documents @ '${WIN32_USERNAME}'";
+      exit 1;
 		else
-			DIR_REPO_USR="$(dirname ${WIN32_USR_LOCAL})";
-			DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
+      DIR_REPO_USR="$(dirname ${WIN32_USR_LOCAL})";
+      DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
 		fi;
 
 	else
@@ -60,12 +60,12 @@ else
 		SOURCE_DIR_ERRS=$?;
 
 		if [ "${SOURCE_DIR_ERRS}" != "0" ] && [ -n "${SUDO_USER}" ]; then
-			#  Linux OS - Locate source directory from amongst Non-Sudo User's files
-			SUDOER_HOME_DIR="$(getent passwd ${SUDO_USER} | cut --delimiter=: --fields=6)";
-			SUDOER_USR_LOCAL=$(find ${SUDOER_HOME_DIR} -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
-			DIR_REPO_USR="$(dirname ${SUDOER_USR_LOCAL})";
-			DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
-			SOURCE_DIR_ERRS=$?;
+      #  Linux OS - Locate source directory from amongst Non-Sudo User's files
+      SUDOER_HOME_DIR="$(getent passwd ${SUDO_USER} | cut --delimiter=: --fields=6)";
+      SUDOER_USR_LOCAL=$(find ${SUDOER_HOME_DIR} -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
+      DIR_REPO_USR="$(dirname ${SUDOER_USR_LOCAL})";
+      DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
+      SOURCE_DIR_ERRS=$?;
 		fi;
 	
 	fi;
@@ -82,12 +82,12 @@ else
 		EXIT_CODE=1;
 
 		if [ ! -d "${DIR_REPO_BASE}/usr/local/bin/" ]; then
-			echo "";
-			echo "Error: Directory not-found: [ ${DIR_REPO_BASE}/usr/local/bin/ ]";
+      echo "";
+      echo "Error: Directory not-found: [ ${DIR_REPO_BASE}/usr/local/bin/ ]";
 		fi;
 		if [ ! -d "${DIR_REPO_BASE}/usr/local/sbin/" ]; then
-			echo "";
-			echo "Error: Directory not-found: [ ${DIR_REPO_BASE}/usr/local/sbin/ ]";
+      echo "";
+      echo "Error: Directory not-found: [ ${DIR_REPO_BASE}/usr/local/sbin/ ]";
 		fi;
 
 	else
@@ -133,16 +133,16 @@ else
 		#   NOTE: Linux usernames cannot be longer than 32 chars (according to useradd man page)
 		USERNAMES_MOSTCHARS=0;
 		for EACH_SSH_USER in ${LINUX_BASH_USERS}; do
-			EACH_USERNAME_LENGTH=${#EACH_SSH_USER};
-			if (( ${EACH_USERNAME_LENGTH} > ${USERNAMES_MOSTCHARS} )); then
+      EACH_USERNAME_LENGTH=${#EACH_SSH_USER};
+      if (( ${EACH_USERNAME_LENGTH} > ${USERNAMES_MOSTCHARS} )); then
         USERNAMES_MOSTCHARS=${EACH_USERNAME_LENGTH};
-			fi;
+      fi;
 		done;
 		echo "";
 		echo "❖ Syncing Bash-Config & Terminal-Formatting files for SSH-Enabled users...";
 		# Begin copying files to SSH-Enabled User-Home Directories
 		for EACH_FILE in ${FILES_TO_COPY}; do
-			if [[ ! -z "${EACH_FILE// }" ]]; then # Ignore blank/empty filenames
+      if [[ ! -z "${EACH_FILE// }" ]]; then # Ignore blank/empty filenames
         echo "    ↪ \"${EACH_FILE}\" (Home-Directory File)";
         SRC_FULLPATH="${COPY_FROM_SOURCE}/${EACH_FILE}";
         for EACH_SSH_USER in ${LINUX_BASH_USERS}; do
@@ -169,7 +169,7 @@ else
             echo "${USERNAME_RPAD} ✅  [ ${DEST_FULLPATH} ]";
           fi;
         done;
-			fi;
+      fi;
 		done;
 		echo "";
 
