Update docker_create_jenkins

diff --git a/usr/local/bin/docker_create_jenkins b/usr/local/bin/docker_create_jenkins
--- a/usr/local/bin/docker_create_jenkins
+++ b/usr/local/bin/docker_create_jenkins
@@ -5,10 +5,10 @@
 REQUIRED_PKG="jq"; if [ -z "$(which ${REQUIRED_PKG})" ]; then apt-get update -y; apt-get install -y ${REQUIRED_PKG}; fi;
 
 
-IMAGE_NAME="jenkinsci/blueocean";
-DOCKER_IMAGE_TAGS=$(curl -s -S "https://registry.hub.docker.com/v1/repositories/${IMAGE_NAME}/tags" | jq -r ".[].name" 2>"/dev/null";); ERRORS_TAG_LOOKUP=$?;
+DOCKER_IMAGE_NAME="jenkinsci/blueocean";
+DOCKER_IMAGE_TAGS=$(curl -s -S "https://registry.hub.docker.com/v1/repositories/${DOCKER_IMAGE_NAME}/tags" | jq -r ".[].name" 2>"/dev/null";); ERRORS_TAG_LOOKUP=$?;
 if [ ${ERRORS_TAG_LOOKUP} -ne 0 ]; then
-	echo "Error: No docker images found to match \"${IMAGE_NAME}\"";
+	echo "Error: No docker images found to match \"${DOCKER_IMAGE_NAME}\"";
 	exit 1;
 else
 	DOCKER_IMAGE_TAGS_SORTED_REV=$(echo "${DOCKER_IMAGE_TAGS}" | sort -r);
@@ -18,7 +18,6 @@ else
 
 	unset ARR_TAG_OPTIONS; declare -A ARR_TAG_OPTIONS; # Re-instantiate bash array
 
-	unset ARR_OPTIONS_MENU; declare -A ARR_OPTIONS_MENU; # Re-instantiate bash array
 	EACH_KEY=0;
 	MIN_KEY=$((EACH_KEY+1));
 	for EACH_TAG in ${DOCKER_IMAGE_TAGS_SORTED[@]}; do
@@ -39,7 +38,7 @@ else
 
 		for EACH_KEY in "${!ARR_TAG_OPTIONS[@]}"; do
 			EACH_TAG="${ARR_TAG_OPTIONS[${EACH_KEY}]}";
-			echo "	${EACH_KEY}  |  ${IMAGE_NAME}:${EACH_TAG}";
+			echo "	${EACH_KEY}  |  ${DOCKER_IMAGE_NAME}:${EACH_TAG}";
 		done;
 
 		ERROR_SUGGEST_HELP="  |--> Expected user-input to be of type [ integer ], with value between [ ${MIN_KEY} ] and [ ${MAX_KEY} ], inclusive";
@@ -56,11 +55,26 @@ else
 			else
 				E1="LINES=$(tput lines)";
 				E2="COLUMNS=$(tput cols)";
-				CONTAINER_ID="${ARR_TAG_OPTIONS[${USER_SELECTION_KEY}]}";
-				DOCKER_IMAGE="${ARR_DOCKER_IMAGES[${USER_SELECTION_KEY}]}";
-				echo "        |----> ID: \"${CONTAINER_ID}\"";
-				echo "        |-> Image: \"${DOCKER_IMAGE}\"";
-				docker exec -e "${E1}" -e "${E2}" -it "${CONTAINER_ID}" "/bin/bash";
+				DOCKER_IMAGE_WITH_TAG="${DOCKER_IMAGE_NAME}:${ARR_TAG_OPTIONS[${USER_SELECTION_KEY}]}";
+
+				unset DOCKER_RUN_ARR; declare DOCKER_RUN_ARR; # [Re-]instantiate bash array
+				DOCKER_RUN_ARR+=("-u root"); \
+				DOCKER_RUN_ARR+=("--rm"); \
+				DOCKER_RUN_ARR+=("-d"); \
+				DOCKER_RUN_ARR+=("-p 8080:8080"); \
+				DOCKER_RUN_ARR+=("-p 50000:50000"); \
+				DOCKER_RUN_ARR+=("-v \"jenkins-data:/var/jenkins_home\""); \
+				DOCKER_RUN_ARR+=("-v \"/var/run/docker.sock:/var/run/docker.sock\"");
+				DOCKER_RUN_ARR+=("${DOCKER_IMAGE_WITH_TAG}");
+				
+				ROLLBACK_IFS="${IFS}"; IFS=" "; # Backup the global delimiter (to restore later), then set it as-intended ### $'\n'
+				DOCKER_RUN_PARAMS="${DOCKER_RUN_ARR[@]}";
+				IFS="${ROLLBACK_IFS}"; # Restore the global delimiter
+
+				echo "";
+				echo "Info: Calling [ docker run \"${DOCKER_RUN_PARAMS}\" ]";
+				docker run "${DOCKER_RUN_PARAMS}";
+				# docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v "jenkins-data:/var/jenkins_home" -v "/var/run/docker.sock:/var/run/docker.sock" --name "${docker_name}" "jenkinsci/blueocean";
 			fi;
 		elif [ ${READ_RET_CODE} -gt 128 ]; then
 			# Error - Timeout reached for User-input ( from [ read --help ]: "The exit status is greater than 128 if the timeout is exceeded" )
