replace lines starting with tabs with spaces (tab count 2)

diff --git a/usr/local/bin/docker_create_jenkins b/usr/local/bin/docker_create_jenkins
--- a/usr/local/bin/docker_create_jenkins
+++ b/usr/local/bin/docker_create_jenkins
@@ -25,8 +25,8 @@ else
 	# MIN_KEY=$((EACH_KEY+1));
 	MIN_KEY=${EACH_KEY};
 	for EACH_TAG in ${DOCKER_IMAGE_TAGS_SORTED[@]}; do
-		ARR_TAG_OPTIONS+=(["${EACH_KEY}"]="${EACH_TAG}");
-		EACH_KEY=$((EACH_KEY+1));
+    ARR_TAG_OPTIONS+=(["${EACH_KEY}"]="${EACH_TAG}");
+    EACH_KEY=$((EACH_KEY+1));
 	done;
 	MAX_KEY=$((${EACH_KEY}-1));
 
@@ -39,24 +39,24 @@ else
 	# echo "${IMAGES_MENU_OPTIONS}";
 
 	if [ ${CHOICE_KEY} -le 0 ]; then
-		echo "Error: No Containers found to be running - Please start a container then rerun \"${0}\"";
+    echo "Error: No Containers found to be running - Please start a container then rerun \"${0}\"";
 	else
-		
-		ARR_TAG_OPTIONS_NO_DUPES=($(echo "${ARR_TAG_OPTIONS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
-		for EACH_KEY in "${!ARR_TAG_OPTIONS_NO_DUPES[@]}"; do
+    
+    ARR_TAG_OPTIONS_NO_DUPES=($(echo "${ARR_TAG_OPTIONS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
+    for EACH_KEY in "${!ARR_TAG_OPTIONS_NO_DUPES[@]}"; do
       EACH_TAG="${ARR_TAG_OPTIONS_NO_DUPES[${EACH_KEY}]}";
       echo "   ${EACH_KEY}	|  ${DOCKER_IMAGE_NAME}:${EACH_TAG}";
-		done;
+    done;
 
-		ERROR_SUGGEST_HELP="  |--> Expected user-input to be of type [ integer ], with value between [ ${MIN_KEY} ] and [ ${MAX_KEY} ], inclusive";
-		
-		# Let the user determine which tag (image-revision) to build-from
-		read -p "Select which Tag to build:  " -t 60 -r; READ_RET_CODE=$?;
-		if [ ${READ_RET_CODE} -gt 128 ]; then
+    ERROR_SUGGEST_HELP="  |--> Expected user-input to be of type [ integer ], with value between [ ${MIN_KEY} ] and [ ${MAX_KEY} ], inclusive";
+    
+    # Let the user determine which tag (image-revision) to build-from
+    read -p "Select which Tag to build:  " -t 60 -r; READ_RET_CODE=$?;
+    if [ ${READ_RET_CODE} -gt 128 ]; then
       # Error: Timeout reached for User-input ( from [ read --help ]: "The exit status is greater than 128 if the timeout is exceeded" )
       echo -e "Error: Response timed out""\n""${ERROR_SUGGEST_HELP}";
 
-		elif [ -n "${REPLY}" ] && [[ ${REPLY} =~ ^-?[0-9]+$ ]] && [ ${REPLY} -ge ${MIN_KEY} ] && [ ${REPLY} -le ${MAX_KEY} ]; then
+    elif [ -n "${REPLY}" ] && [[ ${REPLY} =~ ^-?[0-9]+$ ]] && [ ${REPLY} -ge ${MIN_KEY} ] && [ ${REPLY} -le ${MAX_KEY} ]; then
       USER_SELECTION_KEY=$((0+${REPLY}));
       if [ -z "${ARR_TAG_OPTIONS_NO_DUPES[${USER_SELECTION_KEY}]}" ]; then
         # Error: User-input key not found as an index within the Docker-Image-Tags array
@@ -84,11 +84,11 @@ else
 
       fi;
 
-		else
+    else
       # Error: Malformed User-input (didn't meet criteria, above)
       echo -e "Error: Invalid/empty User-input""\n""${ERROR_SUGGEST_HELP}";
 
-		fi;
+    fi;
 	fi;
 
 	# docker_name="jenkins_$(date +'%s')";
diff --git a/usr/local/bin/get_permissions b/usr/local/bin/get_permissions
--- a/usr/local/bin/get_permissions
+++ b/usr/local/bin/get_permissions
@@ -26,34 +26,34 @@ if [ -z "${STAT_PATH}" ]; then
 else
 
 	if [[ -r "${STAT_PATH}" ]]; then # canonicalize symbolic links
-		STAT_SYMLINK="1";
-		STAT_ENDPOINT=$(readlink -f "${STAT_PATH}");
+    STAT_SYMLINK="1";
+    STAT_ENDPOINT=$(readlink -f "${STAT_PATH}");
 	else
-		STAT_ENDPOINT="${STAT_PATH}";
+    STAT_ENDPOINT="${STAT_PATH}";
 	fi;
 
 	if [ ! -e "${STAT_ENDPOINT}" ]; then
 
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: path not found: \"${STAT_ENDPOINT}\"";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: path not found: \"${STAT_ENDPOINT}\"";
 
 	else
 
-		STAT_EXISTS="1";
+    STAT_EXISTS="1";
 
-		if [[ -r "${STAT_ENDPOINT}" ]]; then
+    if [[ -r "${STAT_ENDPOINT}" ]]; then
       STAT_READABLE="1";
       if [[ -w "${STAT_ENDPOINT}" ]]; then
         STAT_WRITABLE="1";
       fi;
-		fi;
+    fi;
 
-		INFO=($(stat --dereference --format="%h %a %u %U %g %G %h" "${STAT_ENDPOINT}"));
+    INFO=($(stat --dereference --format="%h %a %u %U %g %G %h" "${STAT_ENDPOINT}"));
 
-		if [ "$?" != "0" ]; then
+    if [ "$?" != "0" ]; then
 
       echo "$(date +'%Y-%m-%d %H:%M:%S') | Error thrown while attempting to stat: \"${STAT_ENDPOINT}\"";
 
-		else
+    else
 
       STAT_TYPES=$(stat --dereference --format="%F" "${STAT_ENDPOINT}");
       STAT_CANONICALIZE=$(readlink -f "${STAT_ENDPOINT}");
@@ -110,7 +110,7 @@ else
 
       echo "";
 
-		fi;
+    fi;
 
 	fi;
 
diff --git a/usr/local/bin/get_subdomains b/usr/local/bin/get_subdomains
--- a/usr/local/bin/get_subdomains
+++ b/usr/local/bin/get_subdomains
@@ -37,49 +37,49 @@ else
 
 	SMOKE_TEST=$(curl -L -s "https://api.hackertarget.com/hostsearch/?q=${1}" | head -n 1;);
 	if [ "${SMOKE_TEST}" == "error check your search parameter" ]; then
-		echo -e "\nError in call to \"get_subdomains\"\n  -->  Hostname not found:  \"${1}\"\n";
-		exit 1;
+    echo -e "\nError in call to \"get_subdomains\"\n  -->  Hostname not found:  \"${1}\"\n";
+    exit 1;
 
 	else
 
-		INDEX_RESULTS_BY="IPV4";
-		if [ -n "${2}" ]; then
+    INDEX_RESULTS_BY="IPV4";
+    if [ -n "${2}" ]; then
       if [ "${2}" == "-fqdn" ] || [ "${2}" == "--fqdn" ]; then
         INDEX_RESULTS_BY="FQDN";
       fi;
-		fi;
+    fi;
 
-		# [Re-]Instantiate bash array via unset + declare
-		test -v ARR_IPV4_IDX && unset ARR_IPV4_IDX; declare -A ARR_IPV4_IDX;
-		test -v ARR_FQDN_IDX && unset ARR_FQDN_IDX; declare -A ARR_FQDN_IDX;
+    # [Re-]Instantiate bash array via unset + declare
+    test -v ARR_IPV4_IDX && unset ARR_IPV4_IDX; declare -A ARR_IPV4_IDX;
+    test -v ARR_FQDN_IDX && unset ARR_FQDN_IDX; declare -A ARR_FQDN_IDX;
 
-		# Resolved IPv4 addresses for given domain ( as ${1} )
-		curl -L -s "https://api.hackertarget.com/hostsearch/?q=${1}" | sort | while read EACH_LINE; do
+    # Resolved IPv4 addresses for given domain ( as ${1} )
+    curl -L -s "https://api.hackertarget.com/hostsearch/?q=${1}" | sort | while read EACH_LINE; do
       EACH_FQDN=$(echo ${EACH_LINE} | cut -d, -f 1;);
       EACH_IPV4=$(echo ${EACH_LINE} | cut -d, -f 2;);
       test -v ARR_IPV4_IDX["${EACH_IPV4}"] && ARR_IPV4_IDX+=(["${EACH_IPV4}"]+=", ");
       test -v ARR_IPV4_IDX["${EACH_FQDN}"] && ARR_IPV4_IDX+=(["${EACH_FQDN}"]+=", ");
       ARR_FQDN_IDX+=(["${EACH_FQDN}"]+="${EACH_IPV4}");
       ARR_IPV4_IDX+=(["${EACH_IPV4}"]+="${EACH_FQDN}");
-		done;
+    done;
 
-		# Sort the table by IPv4 address
-		ROLLBACK_IFS="${IFS}";
-		IFS=$'\n'; # Set the global delimiter
-		if [ "${INDEX_RESULTS_BY}" == "FQDN" ]; then
+    # Sort the table by IPv4 address
+    ROLLBACK_IFS="${IFS}";
+    IFS=$'\n'; # Set the global delimiter
+    if [ "${INDEX_RESULTS_BY}" == "FQDN" ]; then
       # Group & Sort by FQDN
       ARR_SORTED_RESULTS=($(sort <<<"${!ARR_FQDN_IDX[*]}"));
-		else
+    else
       # Group & Sort by IPv4
       ARR_SORTED_RESULTS=($(sort <<<"${!ARR_IPV4_IDX[*]}"));
-		fi;
-		IFS="${ROLLBACK_IFS}"; # Restore the global delimiter
+    fi;
+    IFS="${ROLLBACK_IFS}"; # Restore the global delimiter
 
-		# Display the results
-		echo "";
-		echo "   IPv4            | FQDN              ";
-		echo "  -----------------|-------------------";
-		for EACH_KEY in "${ARR_SORTED_RESULTS[@]}"; do
+    # Display the results
+    echo "";
+    echo "   IPv4            | FQDN              ";
+    echo "  -----------------|-------------------";
+    for EACH_KEY in "${ARR_SORTED_RESULTS[@]}"; do
       # if [ "${INDEX_RESULTS_BY}" == "FQDN" ]; then
       # 	EACH_VAL="${ARR_FQDN_IDX[${EACH_KEY}]}";
       # else
@@ -89,10 +89,10 @@ else
       EACH_KEY_RPAD="${EACH_KEY_RPAD:0:15}";
       echo "   ${EACH_KEY_RPAD} | ${EACH_VAL}";
       echo "                   | ";
-		done;
-		echo "";
+    done;
+    echo "";
 
-		exit 0;
+    exit 0;
 
 	fi;
 
diff --git a/usr/local/bin/git_init b/usr/local/bin/git_init
--- a/usr/local/bin/git_init
+++ b/usr/local/bin/git_init
@@ -46,17 +46,17 @@ FAIL_MSG="";
 # If acting as the "root" user and the "git" module is not installed, then attempt to install git
 if [ -z "$(which git 2>'/dev/null';)" ] && [ "$(id -un)" == "root" ]; then
 	if [ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]; then
-		# Ubuntu
-		echo -e "$(date '+%Y-%m-%d %H:%M:%S') | Git not installed (Ubuntu Linux) - Attempting to install via:";
-		echo -e "$(date '+%Y-%m-%d %H:%M:%S') | ---> apt -y update && apt -y install --ignore-missing git;";
-		apt -qq -y update && apt -qq -y install --ignore-missing git;
+    # Ubuntu
+    echo -e "$(date '+%Y-%m-%d %H:%M:%S') | Git not installed (Ubuntu Linux) - Attempting to install via:";
+    echo -e "$(date '+%Y-%m-%d %H:%M:%S') | ---> apt -y update && apt -y install --ignore-missing git;";
+    apt -qq -y update && apt -qq -y install --ignore-missing git;
 	else
-		if [ $(cat /etc/*release | grep -i debian | wc -l) -gt 0 ]; then
+    if [ $(cat /etc/*release | grep -i debian | wc -l) -gt 0 ]; then
       # Debian
       echo -e "$(date '+%Y-%m-%d %H:%M:%S') | Git not installed (Debian Linux) - Attempting to install via:";
       echo -e "$(date '+%Y-%m-%d %H:%M:%S') | ---> apt -y update && apt -y install --ignore-missing git;";
       apt -qq -y update && apt -qq -y install --ignore-missing git;
-		else
+    else
       if [ $(cat /etc/*release | grep -i centos | wc -l) -gt 0 ]; then
         # CentOS
         echo -e "$(date '+%Y-%m-%d %H:%M:%S') | Git not installed (CentOS Linux) - Attempting to install via:";
@@ -70,7 +70,7 @@ if [ -z "$(which git 2>'/dev/null';)" ] && [ "$(id -un)" == "root" ]; then
           apk update && apk add git;
         fi;
       fi;
-		fi;
+    fi;
 	fi;
 fi;
 
@@ -89,7 +89,7 @@ if [ -z "${REMOTE_HOST}" ]; then
 	read -p "  Remote Host/IPv4?  (e.g. github.com)  :  " -t 60 -r;
 	REMOTE_HOST="${REPLY}";
 	if [ -z "${REMOTE_HOST}" ]; then
-		FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_HOST is empty.\n";
+    FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_HOST is empty.\n";
 	fi;
 fi;
 
@@ -98,7 +98,7 @@ if [ -z "${REMOTE_OWNER}" ]; then
 	read -p "  Remote Repo's Owner? (username/company-name which owns repo)  :  " -t 60 -r;
 	REMOTE_OWNER="${REPLY}";
 	if [ -z "${REMOTE_OWNER}" ]; then
-		FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_OWNER is empty.\n";
+    FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_OWNER is empty.\n";
 	fi;
 fi;
 
@@ -107,7 +107,7 @@ if [ -z "${REMOTE_REPOSITORY}" ]; then
 	read -p "  Remote Repo's Basename? (e.g. name of the repository)  :  " -t 60 -r;
 	REMOTE_REPOSITORY="${REPLY}";
 	if [ -z "${REMOTE_REPOSITORY}" ]; then
-		FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_REPOSITORY is empty.\n";
+    FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_REPOSITORY is empty.\n";
 	fi;
 fi;
 
@@ -117,9 +117,9 @@ if [ -z "${REMOTE_PRIVATE_KEY}" ]; then
 	read -p "  Private-Key for Remote Repo? (e.g. fullpath to RSA key)  :  " -t 60 -r;
 	REMOTE_PRIVATE_KEY="${REPLY}";
 	if [ -z "${REMOTE_PRIVATE_KEY}" ]; then
-		FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_PRIVATE_KEY is empty.\n"; 
+    FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: Required variable \$REMOTE_PRIVATE_KEY is empty.\n"; 
 	elif [ ! -f "${REMOTE_PRIVATE_KEY}" ]; then
-		FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: File not found: \$REMOTE_PRIVATE_KEY=\"${REMOTE_PRIVATE_KEY}\".\n";
+    FAIL_MSG="${FAIL_MSG}$(date '+%Y-%m-%d %H:%M:%S') | Error: File not found: \$REMOTE_PRIVATE_KEY=\"${REMOTE_PRIVATE_KEY}\".\n";
 	fi;
 fi;
 
@@ -331,7 +331,7 @@ if [ -n "${COMMIT_USER_FULLNAME}" ]; then
 	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git config user.name \"${COMMIT_USER_FULLNAME}\"";
 	${GIT_CLI} config user.name "${COMMIT_USER_FULLNAME}";
 	if [ "${COMMIT_USER_FULLNAME}" != "${CURRENT_LOCAL_GIT_FULLNAME}" ]; then
-		echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> Info:  Previous value = \"${CURRENT_LOCAL_GIT_FULLNAME}\"";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> Info:  Previous value = \"${CURRENT_LOCAL_GIT_FULLNAME}\"";
 	fi;
 fi;
 
@@ -341,7 +341,7 @@ if [ -n "${COMMIT_USER_EMAIL}" ]; then
 	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git config user.email \"${COMMIT_USER_EMAIL}\"";
 	${GIT_CLI} config user.email "${COMMIT_USER_EMAIL}";
 	if [ "${COMMIT_USER_EMAIL}" != "${CURRENT_LOCAL_GIT_USER_EMAIL}" ]; then
-		echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> Info:  Previous value = \"${CURRENT_LOCAL_GIT_USER_EMAIL}\"";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> Info:  Previous value = \"${CURRENT_LOCAL_GIT_USER_EMAIL}\"";
 	fi;
 fi;
 
@@ -364,41 +364,41 @@ if [ "${FIRST_CLONE_OF_REPO}" == "1" ]; then
 	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> FIRST_CLONE_OF_REPO == 1";
 	# get default branch(es)
 	if [ -n "${CHECKOUT_BRANCH}" ]; then
-		TRY_BRANCH="${CHECKOUT_BRANCH}";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
-		${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
-		if [ ${CHECKOUT_ERROR_CODE} -eq 0 ]; then
+    TRY_BRANCH="${CHECKOUT_BRANCH}";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
+    ${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
+    if [ ${CHECKOUT_ERROR_CODE} -eq 0 ]; then
       BRANCH_CHECKED_OUT=1;
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Successfully checked out branch \"${TRY_BRANCH}\"";
-		else
+    else
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Error: Failed to check out branch \"${TRY_BRANCH}\"";
-		fi;
+    fi;
 	fi;
 	if [ ${BRANCH_CHECKED_OUT} -eq 0 ]; then
-		TRY_BRANCH="main";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
-		${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
-		if [ ${CHECKOUT_ERROR_CODE} -eq 0 ]; then
+    TRY_BRANCH="main";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
+    ${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
+    if [ ${CHECKOUT_ERROR_CODE} -eq 0 ]; then
       BRANCH_CHECKED_OUT=1;
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Successfully checked out branch \"${TRY_BRANCH}\"";
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Setting variable \${CHECKOUT_BRANCH} to value \"${TRY_BRANCH}\"";
       CHECKOUT_BRANCH="${TRY_BRANCH}";
-		else
+    else
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Error: Failed to check out branch \"${TRY_BRANCH}\"";
-		fi;
+    fi;
 	fi;
 	if [ ${BRANCH_CHECKED_OUT} -eq 0 ]; then
-		TRY_BRANCH="master";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
-		${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
-		if [ ${CHECKOUT_ERROR_CODE} -eq 0 ]; then
+    TRY_BRANCH="master";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Attempting to checkout branch \"${TRY_BRANCH}\" via [ git checkout -f \"${TRY_BRANCH}\"; ]";
+    ${GIT_CLI} checkout -f "${TRY_BRANCH}"; CHECKOUT_ERROR_CODE=$?;
+    if [ ${CHECKOUT_ERROR_CODE} -eq 0 ]; then
       BRANCH_CHECKED_OUT=1;
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Successfully checked out branch \"${TRY_BRANCH}\"";
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Setting variable \${CHECKOUT_BRANCH} to value \"${TRY_BRANCH}\"";
       CHECKOUT_BRANCH="${TRY_BRANCH}";
-		else
+    else
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Error: Failed to check out branch \"${TRY_BRANCH}\"";
-		fi;
+    fi;
 	fi;
 	echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> Info: Pulling branch \"${CHECKOUT_BRANCH}\"";
 	# echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} pull -v";
@@ -414,23 +414,23 @@ echo "${LOCAL_CURRENT_BRANCH}";
 if [ -n "${LOCAL_CURRENT_BRANCH}" ]; then
 	REMOTE_BRANCH_EXISTS=$(${GIT_CLI} branch -a | awk '{print $1}' | grep -w remotes/origin/${CHECKOUT_BRANCH});
 	if [ -n "${REMOTE_BRANCH_EXISTS}" ]; then
-		# checkout specific branch if not already on it
-		if [ "${CHECKOUT_BRANCH}" != "${LOCAL_CURRENT_BRANCH}" ]; then
+    # checkout specific branch if not already on it
+    if [ "${CHECKOUT_BRANCH}" != "${LOCAL_CURRENT_BRANCH}" ]; then
       # echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} checkout -f ${CHECKOUT_BRANCH}";
       echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git checkout -f ${CHECKOUT_BRANCH}";
       ${GIT_CLI} checkout -f "${CHECKOUT_BRANCH}";
-		else
+    else
       echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: SKIPPING CHECKOUT - Already on branch \"${CHECKOUT_BRANCH}\"";
-		fi;
-		# echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} reset --hard \"origin/${CHECKOUT_BRANCH}\"";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git reset --hard \"origin/${CHECKOUT_BRANCH}\"";
-		${GIT_CLI} reset --hard "origin/${CHECKOUT_BRANCH}";
+    fi;
+    # echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} reset --hard \"origin/${CHECKOUT_BRANCH}\"";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> git reset --hard \"origin/${CHECKOUT_BRANCH}\"";
+    ${GIT_CLI} reset --hard "origin/${CHECKOUT_BRANCH}";
 	else
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | Error: Branch \"${CHECKOUT_BRANCH}\" not found on remote.";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Exiting after 20s...";
-		# ${GIT_CLI} checkout -b "${CHECKOUT_BRANCH}"; <-- CREATES BRANCH
-		sleep 20;
-		exit 1;
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | Error: Branch \"${CHECKOUT_BRANCH}\" not found on remote.";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Exiting after 20s...";
+    # ${GIT_CLI} checkout -b "${CHECKOUT_BRANCH}"; <-- CREATES BRANCH
+    sleep 20;
+    exit 1;
 	fi;
 else
 	# echo "$(date '+%Y-%m-%d %H:%M:%S') | ---> ${GIT_CLI} checkout -f ${CHECKOUT_BRANCH}";
@@ -457,15 +457,15 @@ echo "$(date '+%Y-%m-%d %H:%M:%S') | ${LINE_BREAK}";
 FINAL_PARENT_DIR="${HOME}/Documents/GitHub";
 if [ -d "${WINDOWS_GITHUB_LOCAL_CEILING}" ]; then
 	if [ ! -d "${WINDOWS_GITHUB_WORK_TREE}" ]; then
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Attempting to relocate the git repository's root directory...";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> from \"${GIT_WORK_TREE}\"";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> to \"${WINDOWS_GITHUB_WORK_TREE}\"";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | mv \"${GIT_WORK_TREE}\" \"${WINDOWS_GITHUB_WORK_TREE}\"";
-		mv "${GIT_WORK_TREE}" "${WINDOWS_GITHUB_WORK_TREE}";
-		GIT_WORK_TREE="${WINDOWS_GITHUB_WORK_TREE}";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Attempting to relocate the git repository's root directory...";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> from \"${GIT_WORK_TREE}\"";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') |  |--> to \"${WINDOWS_GITHUB_WORK_TREE}\"";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | mv \"${GIT_WORK_TREE}\" \"${WINDOWS_GITHUB_WORK_TREE}\"";
+    mv "${GIT_WORK_TREE}" "${WINDOWS_GITHUB_WORK_TREE}";
+    GIT_WORK_TREE="${WINDOWS_GITHUB_WORK_TREE}";
 	else
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | Error: Directory already exists (unable to relocate git work tree to):";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | --> \"${WINDOWS_GITHUB_WORK_TREE}\"";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | Error: Directory already exists (unable to relocate git work tree to):";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | --> \"${WINDOWS_GITHUB_WORK_TREE}\"";
 
 	fi;
 	echo "$(date '+%Y-%m-%d %H:%M:%S') | ${LINE_BREAK}";
diff --git a/usr/local/sbin/add_user b/usr/local/sbin/add_user
--- a/usr/local/sbin/add_user
+++ b/usr/local/sbin/add_user
@@ -40,12 +40,12 @@ else
 
 	# If no username given, ask terminal user for username
 	while [ -z "${USER_NAME}" ]; do
-		echo "";
-		read -p " Create a user with what username?   " -t 60 -r;
-		USER_NAME="${REPLY}";
-		if [ -n "${USER_NAME}" ]; then
+    echo "";
+    read -p " Create a user with what username?   " -t 60 -r;
+    USER_NAME="${REPLY}";
+    if [ -n "${USER_NAME}" ]; then
       break;
-		fi;
+    fi;
 	done;
 
 	ROLLBACK_IFS="${IFS}";
@@ -79,52 +79,52 @@ else
 	# ------------------------------------------------------------
 
 	if [ -z "${USER_NAME}" ]; then
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  \$USER_NAME is empty/unset";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
-		exit 1;
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  \$USER_NAME is empty/unset";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
+    exit 1;
 
 	elif [ ${SET_SYSTEM_USER} -eq 1 ] && [ -v USER_UID ]; then
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Invalid argument combination: [ User ID ] & [ System User ]";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Best practice dictates that the system should allocate User IDs for System users";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
-		exit 1;
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Invalid argument combination: [ User ID ] & [ System User ]";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Best practice dictates that the system should allocate User IDs for System users";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
+    exit 1;
 
 	elif [ ${SET_SYSTEM_USER} -eq 1 ] && [ -v USER_GID ]; then
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Invalid argument combination: [ Group ID ] & [ System User ]";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Best practice dictates that the system should allocate Group IDs for System users";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
-		exit 1;
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Invalid argument combination: [ Group ID ] & [ System User ]";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Best practice dictates that the system should allocate Group IDs for System users";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
+    exit 1;
 
 	elif [[ -v USER_NAME ]] \
       && [[ -v USER_UID ]] \
       && [[ "${USER_UID}" =~ ^-?[0-9]+$ ]] \
       && [ "$(id -u ${USER_UID} >/dev/null 2>&1; echo $?;)" == "0" ] \
       && [ "$(id -un ${USER_UID})" != "${USER_NAME}" ]; then
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  User ID \"${USER_UID}\" is already taken by user \"$(id -un ${USER_UID})\"";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
-		exit 1;
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  User ID \"${USER_UID}\" is already taken by user \"$(id -un ${USER_UID})\"";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
+    exit 1;
 
 	elif [[ -v USER_GNAME ]] \
       && [[ -v USER_GID ]] \
       && [[ "${USER_GID}" =~ ^-?[0-9]+$ ]] \
       && [ $(getent group ${USER_GID} >/dev/null 2>&1; echo $?;) -eq 0 ] \
       && [ "$(getent group ${USER_GID} | cut -d: -f1;)" != "${USER_GNAME}" ]; then
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Group-ID \"${USER_GID}\" resolved to Group Name \"$(id -gn ${USER_GID})\", which is NOT equal to the declared Group-Name value of \"${USER_GNAME}\"";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
-		exit 1;
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Group-ID \"${USER_GID}\" resolved to Group Name \"$(id -gn ${USER_GID})\", which is NOT equal to the declared Group-Name value of \"${USER_GNAME}\"";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Exiting...";
+    exit 1;
 
 	elif [ "${CREATE_HOME}" == "1" ] && [ -d "${DIR_USER_HOME}" ]; then
 
-		echo "Home Directory already exists: \"${DIR_USER_HOME}\".";
-		echo "If you still want to use this directory, set \$CREATE_HOME to \"0\" and re-run this script.";
-		exit 1;
+    echo "Home Directory already exists: \"${DIR_USER_HOME}\".";
+    echo "If you still want to use this directory, set \$CREATE_HOME to \"0\" and re-run this script.";
+    exit 1;
 
 	else
 
-		# ------------------------------------------------------------
-		# GROUP-CREATION
+    # ------------------------------------------------------------
+    # GROUP-CREATION
 
-		if [ -v SET_SYSTEM_USER ] && [ ${SET_SYSTEM_USER} -ne 1 ]; then
+    if [ -v SET_SYSTEM_USER ] && [ ${SET_SYSTEM_USER} -ne 1 ]; then
       # Non System Users
       if [[ -v USER_GNAME ]] && [ $(getent group "${USER_GNAME}" >/dev/null 2>&1; echo $?;) -ne 0 ]; then
         # Group-Add Command
@@ -140,31 +140,31 @@ else
         ${GROUPADD_ARR[@]};
         USER_GID=$(getent group "${USER_GNAME}" | cut -d: -f3;);
       fi;
-		fi;
+    fi;
 
-		# ------------------------------------------------------------
-		# USER-CREATION
-		USERADD_ARR=();
-		USERADD_ARR+=(useradd);
+    # ------------------------------------------------------------
+    # USER-CREATION
+    USERADD_ARR=();
+    USERADD_ARR+=(useradd);
 
-		# User Home-Directory
-		if [[ -v DIR_USER_HOME ]] && [ -n "${DIR_USER_HOME}" ]; then
+    # User Home-Directory
+    if [[ -v DIR_USER_HOME ]] && [ -n "${DIR_USER_HOME}" ]; then
       USERADD_ARR+=(--home-dir "${DIR_USER_HOME}");
-		fi;
+    fi;
 
-		# Create Home-Directory (y/n)
-		if [[ -v CREATE_HOME ]] && [ "${CREATE_HOME}" == "1" ]; then
+    # Create Home-Directory (y/n)
+    if [[ -v CREATE_HOME ]] && [ "${CREATE_HOME}" == "1" ]; then
       USERADD_ARR+=(--create-home);
-		fi;
+    fi;
 
-		if [ -v SET_SYSTEM_USER ] && [ ${SET_SYSTEM_USER} -eq 1 ]; then
+    if [ -v SET_SYSTEM_USER ] && [ ${SET_SYSTEM_USER} -eq 1 ]; then
       # System Users
       USERADD_ARR+=(--system);
 
 
-		else
+    else
       # Non System Users
-		
+    
       # User ID
       if [[ -v USER_UID ]] && [[ "${USER_UID}" =~ ^-?[0-9]+$ ]]; then
         USERADD_ARR+=(--uid ${USER_UID});
@@ -177,28 +177,28 @@ else
         USERADD_ARR+=(--gid "${USER_GNAME}");
       fi;
 
-		fi;
+    fi;
 
-		# User Shell
-		if [[ -v USER_SHELL ]] && [ -n "${USER_SHELL}" ]; then
+    # User Shell
+    if [[ -v USER_SHELL ]] && [ -n "${USER_SHELL}" ]; then
       USERADD_ARR+=(--shell "${USER_SHELL}");
-		fi;
+    fi;
 
-		USERADD_ARR+=("${USER_NAME}");
+    USERADD_ARR+=("${USER_NAME}");
 
-		# Create the User
-		echo "Calling [ ${USERADD_ARR[@]}; ] ..."
-		${USERADD_ARR[@]};
+    # Create the User
+    echo "Calling [ ${USERADD_ARR[@]}; ] ..."
+    ${USERADD_ARR[@]};
 
-		# if [ "${CREATE_HOME_SSH}" == "1" ] && [ ! -d "${DIR_USER_SSH}" ]; then
-		# 	# Create user's SSH directory "~/.ssh"
-		# 	mkdir "${DIR_USER_SSH}";
-		# 	chmod 0700 "${DIR_USER_SSH}";
-		# 	chown "${USER_UID}" "${DIR_USER_SSH}";
-		# fi;
+    # if [ "${CREATE_HOME_SSH}" == "1" ] && [ ! -d "${DIR_USER_SSH}" ]; then
+    # 	# Create user's SSH directory "~/.ssh"
+    # 	mkdir "${DIR_USER_SSH}";
+    # 	chmod 0700 "${DIR_USER_SSH}";
+    # 	chown "${USER_UID}" "${DIR_USER_SSH}";
+    # fi;
 
-		# Make user a sudoer (able to run as root using 'sudo' command)
-		if [ "${ADD_USER_TO_SUDOERS}" == "1" ]; then
+    # Make user a sudoer (able to run as root using 'sudo' command)
+    if [ "${ADD_USER_TO_SUDOERS}" == "1" ]; then
 
       # Add user to the "sudo" usergroup (if not already in it)
       SUDO_GROUP="sudo";
@@ -220,23 +220,23 @@ else
 
       # Refer to "/etc/ssh/sshd_config" for more-advanced SSH config
 
-		fi;
+    fi;
 
 
-		if [ "${SET_USER_PASSWORD}" != "0" ]; then
+    if [ "${SET_USER_PASSWORD}" != "0" ]; then
       passwd "${USER_NAME}";
       #				[Enter password] > ENTER
       #			[Confirm password] > ENTER
-		fi;
+    fi;
 
-		echo -e "\n ==---  New User Stats  ---===";
-		echo -e "\n > User-Name:        \"${USER_NAME}\" (uid=$(id -u ${USER_NAME};))";
-		echo -e "\n > User-Home:      \"$(getent passwd ${USER_NAME} | cut --delimiter=: --fields=6;)\"";
-		echo -e "\n > Default-Group:    \"$(id -gn ${USER_NAME};)\" (gid=$(id -g ${USER_NAME};))";
-		echo -e "\n > Default-Shell:   \"$(getent passwd ${USER_NAME} | cut --delimiter=: --fields=7;)\"";
-		echo -e "\n";
+    echo -e "\n ==---  New User Stats  ---===";
+    echo -e "\n > User-Name:        \"${USER_NAME}\" (uid=$(id -u ${USER_NAME};))";
+    echo -e "\n > User-Home:      \"$(getent passwd ${USER_NAME} | cut --delimiter=: --fields=6;)\"";
+    echo -e "\n > Default-Group:    \"$(id -gn ${USER_NAME};)\" (gid=$(id -g ${USER_NAME};))";
+    echo -e "\n > Default-Shell:   \"$(getent passwd ${USER_NAME} | cut --delimiter=: --fields=7;)\"";
+    echo -e "\n";
 
-		exit 0;
+    exit 0;
 
 	fi;
 
diff --git a/usr/local/sbin/archive_logs b/usr/local/sbin/archive_logs
--- a/usr/local/sbin/archive_logs
+++ b/usr/local/sbin/archive_logs
@@ -41,37 +41,37 @@ else
 	DIR_ARCH="/var/archived_logs";
 
 	if [ ! -d "${DIR_LOGS}/${SERVICE_NAME}" ]; then
-		echo "";
-		echo "ERROR:";
-		echo "  Logs-dir not found for service \"${SERVICE_NAME}\" at path \"${DIR_LOGS}/${SERVICE_NAME}\" ";
-		echo "";
-		exit 1;
+    echo "";
+    echo "ERROR:";
+    echo "  Logs-dir not found for service \"${SERVICE_NAME}\" at path \"${DIR_LOGS}/${SERVICE_NAME}\" ";
+    echo "";
+    exit 1;
 	
 
 	elif [ ! -h "${DIR_ARCH}" ]; then
 
-		echo "";
-		echo "ERROR:";
-		echo "  Symlink not found at path \"${DIR_ARCH}\" ";
-		echo "  Please create a symbolic link from \"${DIR_ARCH}\" to your desired backup directory (ideally on a separate mount point)";
-		echo "";
-		echo "EXAMPLE:";
-		echo "  ln -sf \"/REPLACE_WITH_YOUR_BACKUP_DIRECTORY/\" \"${DIR_ARCH}\"";
-		echo "";
-		exit 1;
+    echo "";
+    echo "ERROR:";
+    echo "  Symlink not found at path \"${DIR_ARCH}\" ";
+    echo "  Please create a symbolic link from \"${DIR_ARCH}\" to your desired backup directory (ideally on a separate mount point)";
+    echo "";
+    echo "EXAMPLE:";
+    echo "  ln -sf \"/REPLACE_WITH_YOUR_BACKUP_DIRECTORY/\" \"${DIR_ARCH}\"";
+    echo "";
+    exit 1;
 
 	else
 
-		# Stop the target service
-		/usr/sbin/service "${SERVICE_NAME}" stop; RET_CODE=$?;
-		if [ "${RET_CODE}" != "0" ]; then
+    # Stop the target service
+    /usr/sbin/service "${SERVICE_NAME}" stop; RET_CODE=$?;
+    if [ "${RET_CODE}" != "0" ]; then
       echo "";
       echo "ERROR:";
       echo "  Unable to stop service \"${SERVICE_NAME}\" - Exiting...";
       echo "";
       exit 1;
-		
-		else
+    
+    else
       # Create the new logs dir
       if [ ! -d "${DIR_ARCH}/${SERVICE_NAME}" ]; then
         mkdir -p "${DIR_ARCH}/${SERVICE_NAME}";
@@ -99,7 +99,7 @@ else
       # 	fi;
       # done;
 
-		fi;
+    fi;
 
 	fi;
 
diff --git a/usr/local/sbin/certbot_add_wildcard b/usr/local/sbin/certbot_add_wildcard
--- a/usr/local/sbin/certbot_add_wildcard
+++ b/usr/local/sbin/certbot_add_wildcard
@@ -34,16 +34,16 @@ else
 	# Use $1 as domain name for wildcard cert
 	#
 	if [ -z "$1" ]; then
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Missing domain name - Please try again using first argument (\$1) as domain name";
-		exit 1;
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Missing domain name - Please try again using first argument (\$1) as domain name";
+    exit 1;
 	else
-		DOMAIN_NAME="$1";
-		if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+    DOMAIN_NAME="$1";
+    if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
       echo "";
       echo "Info:  Calling [ which certbot; ]...";
       which certbot;
-		else
+    else
       echo "";
       echo "Info:  Required package(s):  [ python-certbot-nginx ]";
       echo "  |";
@@ -57,9 +57,9 @@ else
           apt-get -y update; apt-get -y install python-certbot-nginx;
         fi;
       fi;
-		fi;
-		# Create the SSL (TLS/HTTPS) certificate
-		if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
+    fi;
+    # Create the SSL (TLS/HTTPS) certificate
+    if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
       echo "";
       echo "------------------------------------------------------------";
       echo " !!!";
@@ -79,7 +79,7 @@ else
       echo "";
       # echo "Info:  Calling [ certbot certonly --manual --manual-public-ip-logging-ok --server https://acme-v02.api.letsencrypt.org/directory --preferred-challenges dns-01 -d \"${DOMAIN_NAME}\" -d \"*.${DOMAIN_NAME}\"; certbot certificates -d \"${DOMAIN_NAME}\"; test -x \"/usr/local/sbin/reload_nginx\" && /usr/local/sbin/reload_nginx; ]...";
       # certbot certonly --manual --manual-public-ip-logging-ok --server https://acme-v02.api.letsencrypt.org/directory --preferred-challenges dns-01 -d "${DOMAIN_NAME}" -d "*.${DOMAIN_NAME}"; certbot certificates -d "${DOMAIN_NAME}"; test -x "/usr/local/sbin/reload_nginx" && /usr/local/sbin/reload_nginx;
-		fi;
+    fi;
 	fi;
 fi;
 
diff --git a/usr/local/sbin/certbot_renew_all b/usr/local/sbin/certbot_renew_all
--- a/usr/local/sbin/certbot_renew_all
+++ b/usr/local/sbin/certbot_renew_all
@@ -32,31 +32,31 @@ else
 	# ------------------------------------------------------------
 	# Require that certbot be installed, already
 	if [ $(which certbot 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
-		# ------------------------------------------------------------
-		if [ -n "$1" ] && [ "$1" == "-y" || "$1" == "--yes" || "$1" == "--force" ]; then
+    # ------------------------------------------------------------
+    if [ -n "$1" ] && [ "$1" == "-y" || "$1" == "--yes" || "$1" == "--force" ]; then
       # Allow a force-command to skip dry-run mode
       echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Calling  [ certbot renew --noninteractive --force-renewal; ]  ...";
       certbot renew --noninteractive --force-renewal;
-		else
+    else
       # Fallback to dry-run mode, otherwise (default method)
       echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Calling  [ certbot renew --noninteractive --force-renewal --dry-run; ]  ...";
       certbot renew --noninteractive --force-renewal --dry-run;
-		fi;
-		# Show status of installed certificate(s)
-		certbot certificates;
-		# Reload NGINX to bring new certificates into its cache
-		if [ -x "/usr/local/sbin/reload_nginx" ]; then
+    fi;
+    # Show status of installed certificate(s)
+    certbot certificates;
+    # Reload NGINX to bring new certificates into its cache
+    if [ -x "/usr/local/sbin/reload_nginx" ]; then
       /usr/local/sbin/reload_nginx;
-		fi;
+    fi;
 	else
-		# ------------------------------------------------------------
-		# Error - certbot command not command
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Command 'certbot' not found";
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Please install certbot, then re-run this script";
-		echo "";
-		exit 1;
+    # ------------------------------------------------------------
+    # Error - certbot command not command
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Command 'certbot' not found";
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Info:  Please install certbot, then re-run this script";
+    echo "";
+    exit 1;
 	fi;
 
 fi;
diff --git a/usr/local/sbin/create_ssl_directory b/usr/local/sbin/create_ssl_directory
--- a/usr/local/sbin/create_ssl_directory
+++ b/usr/local/sbin/create_ssl_directory
@@ -38,54 +38,54 @@ if [ "$(id -un)" != "root" ]; then
 else
 
 	if [ -z "${1}" ] || [ -z "${2}" ] || [ -z "${3}" ]; then
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Must call [ create_ssl_directory ] with two arguments:";
-		echo "  \$1:  The DNS signing authority for given certificate(s), such as 'letsencrypt' or 'godaddy'";
-		echo "  \$2:  The domain secured by given certificate(s), such as 'example.com' or 'localdomain.tld'";
-		echo "  \$3:  The nickname for your given certificate(s), such as 'wildcard.example.com_exp-2039-01-01'";
-		echo "";
-		exit 1;
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error:  Must call [ create_ssl_directory ] with two arguments:";
+    echo "  \$1:  The DNS signing authority for given certificate(s), such as 'letsencrypt' or 'godaddy'";
+    echo "  \$2:  The domain secured by given certificate(s), such as 'example.com' or 'localdomain.tld'";
+    echo "  \$3:  The nickname for your given certificate(s), such as 'wildcard.example.com_exp-2039-01-01'";
+    echo "";
+    exit 1;
 
 	else
 
-		DNS_AUTHORITY="$1";
-		DOMAIN_NAME="$2";
-		EPITHET="$3";
-		mkdir -p "/etc/${DNS_AUTHORITY}/archive/${DOMAIN_NAME}/";
-		mkdir -p "/etc/${DNS_AUTHORITY}/live/${DOMAIN_NAME}/";
+    DNS_AUTHORITY="$1";
+    DOMAIN_NAME="$2";
+    EPITHET="$3";
+    mkdir -p "/etc/${DNS_AUTHORITY}/archive/${DOMAIN_NAME}/";
+    mkdir -p "/etc/${DNS_AUTHORITY}/live/${DOMAIN_NAME}/";
 
-		### Place SSL Certificate files in the "archive" certs directory:
-		ARCH_CHAIN="/etc/${DNS_AUTHORITY}/archive/${DOMAIN_NAME}/${EPITHET}.chain.pem"; vi "${ARCH_CHAIN}";
-		ARCH_FULLCHAIN="/etc/${DNS_AUTHORITY}/archive/${DOMAIN_NAME}/${EPITHET}.fullchain.pem"; vi "${ARCH_FULLCHAIN}";
-		ARCH_PRIVKEY="/etc/${DNS_AUTHORITY}/archive/${DOMAIN_NAME}/${EPITHET}.privkey.pem"; vi "${ARCH_PRIVKEY}";
+    ### Place SSL Certificate files in the "archive" certs directory:
+    ARCH_CHAIN="/etc/${DNS_AUTHORITY}/archive/${DOMAIN_NAME}/${EPITHET}.chain.pem"; vi "${ARCH_CHAIN}";
+    ARCH_FULLCHAIN="/etc/${DNS_AUTHORITY}/archive/${DOMAIN_NAME}/${EPITHET}.fullchain.pem"; vi "${ARCH_FULLCHAIN}";
+    ARCH_PRIVKEY="/etc/${DNS_AUTHORITY}/archive/${DOMAIN_NAME}/${EPITHET}.privkey.pem"; vi "${ARCH_PRIVKEY}";
 
-		### Onces certificates have been placed as-intended, create STATIC symbolic links to them from the "live" certs directory:
-		LIVE_CHAIN="/etc/${DNS_AUTHORITY}/live/${DOMAIN_NAME}/chain.pem"; ln -sf "${ARCH_CHAIN}" "${LIVE_CHAIN}";
-		LIVE_FULLCHAIN="/etc/${DNS_AUTHORITY}/live/${DOMAIN_NAME}/fullchain.pem"; ln -sf "${ARCH_FULLCHAIN}" "${LIVE_FULLCHAIN}";
-		LIVE_PRIVKEY="/etc/${DNS_AUTHORITY}/live/${DOMAIN_NAME}/privkey.pem"; ln -sf "${ARCH_PRIVKEY}" "${LIVE_PRIVKEY}";
+    ### Onces certificates have been placed as-intended, create STATIC symbolic links to them from the "live" certs directory:
+    LIVE_CHAIN="/etc/${DNS_AUTHORITY}/live/${DOMAIN_NAME}/chain.pem"; ln -sf "${ARCH_CHAIN}" "${LIVE_CHAIN}";
+    LIVE_FULLCHAIN="/etc/${DNS_AUTHORITY}/live/${DOMAIN_NAME}/fullchain.pem"; ln -sf "${ARCH_FULLCHAIN}" "${LIVE_FULLCHAIN}";
+    LIVE_PRIVKEY="/etc/${DNS_AUTHORITY}/live/${DOMAIN_NAME}/privkey.pem"; ln -sf "${ARCH_PRIVKEY}" "${LIVE_PRIVKEY}";
 
-		### Set file/directory permissions & ownership
-		find "/etc/${DNS_AUTHORITY}" -type d -print0 | xargs -0 chmod 0755; # Set directory permissions
-		find "/etc/${DNS_AUTHORITY}" -type f -print0 | xargs -0 chmod 0644; # Set file permissions
-		find "/etc/${DNS_AUTHORITY}" -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 chmod 0700; # Match permissions approach used by Let's Encrypt / CertBot
-		find "/etc/${DNS_AUTHORITY}" -type f -iname '*privkey*' -print0 | xargs -0 chmod 0600; # Set private-key permissions
-		chown -R "root:root" "/etc/${DNS_AUTHORITY}/";
+    ### Set file/directory permissions & ownership
+    find "/etc/${DNS_AUTHORITY}" -type d -print0 | xargs -0 chmod 0755; # Set directory permissions
+    find "/etc/${DNS_AUTHORITY}" -type f -print0 | xargs -0 chmod 0644; # Set file permissions
+    find "/etc/${DNS_AUTHORITY}" -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 chmod 0700; # Match permissions approach used by Let's Encrypt / CertBot
+    find "/etc/${DNS_AUTHORITY}" -type f -iname '*privkey*' -print0 | xargs -0 chmod 0600; # Set private-key permissions
+    chown -R "root:root" "/etc/${DNS_AUTHORITY}/";
 
-		echo "";
-		echo "------------------------------------------------------------";
-		echo "The SSL certificate(s) may be referenced in a local NGINX server { ... } block via:";
-		echo "";
-		echo "	ssl_certificate \"${LIVE_FULLCHAIN}\"; ";
-		echo "	ssl_certificate_key \"${LIVE_PRIVKEY}\"; ";
-		echo "	ssl_trusted_certificate \"${LIVE_CHAIN}\"; ";
-		echo "";
-		echo "------------------------------------------------------------";
-		echo "";
+    echo "";
+    echo "------------------------------------------------------------";
+    echo "The SSL certificate(s) may be referenced in a local NGINX server { ... } block via:";
+    echo "";
+    echo "	ssl_certificate \"${LIVE_FULLCHAIN}\"; ";
+    echo "	ssl_certificate_key \"${LIVE_PRIVKEY}\"; ";
+    echo "	ssl_trusted_certificate \"${LIVE_CHAIN}\"; ";
+    echo "";
+    echo "------------------------------------------------------------";
+    echo "";
 
 	fi;
 
 	if [ -n "$(which reload_nginx 2>'/dev/null';)" ]; then
-		reload_nginx;
+    reload_nginx;
 	fi;
 
 fi;
diff --git a/usr/local/sbin/ddns_ufw_update b/usr/local/sbin/ddns_ufw_update
--- a/usr/local/sbin/ddns_ufw_update
+++ b/usr/local/sbin/ddns_ufw_update
@@ -47,13 +47,13 @@ else
 
 	# Determine if running in debug-mode (increases verbosity-level of script's output, e.g. shows all info/notices/details/etc. and not just warnings/errors)
 	if [ -n "${DEBUG_MODE}" ] && [[ "${DEBUG_MODE}" =~ ^-?[0-9]+$ ]] && (("${DEBUG_MODE}" >= "1")); then
-		DEBUG_MODE=1;
+    DEBUG_MODE=1;
 	elif [ -n "${VERBOSITY}" ] && [[ "${VERBOSITY}" =~ ^-?[0-9]+$ ]] && (("${VERBOSITY}" >= "1")); then
-		DEBUG_MODE=1;
+    DEBUG_MODE=1;
 	elif [ -n "${VERBOSE}" ] && [[ "${VERBOSE}" =~ ^-?[0-9]+$ ]] && (("${VERBOSE}" >= "1")); then
-		DEBUG_MODE=1;
+    DEBUG_MODE=1;
 	else
-		DEBUG_MODE=0;
+    DEBUG_MODE=0;
 	fi;
 
 	# Script's working-directory
@@ -86,7 +86,7 @@ else
 
 	# Create the DDNS NGINX directory only if the NGINX parent directory already exists
 	if [ -d "${ETC_NGINX}" ] && [ ! -d "${NGINX_CONF_DDNS}" ]; then
-		mkdir -p "${NGINX_CONF_DDNS}";
+    mkdir -p "${NGINX_CONF_DDNS}";
 	fi;
 
 	# Defaults for UFW (out-of-the-box)
@@ -106,7 +106,7 @@ else
 	#
 	ADD_RULE_SKIPPED=0;
 	add_rule() {
-		if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
+    if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
       local proto=$1;
       local port=$2;
       local ip=$3;
@@ -141,7 +141,7 @@ else
       if [ ${DEBUG_MODE} -eq 1 ]; then
         echo "            |-->  ADD_RULE_SKIPPED = [ ${ADD_RULE_SKIPPED} ]";
       fi;
-		fi;
+    fi;
 	}
 
 
@@ -151,7 +151,7 @@ else
 	#
 	DELETE_RULE_SKIPPED=0;
 	delete_rule() {
-		if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
+    if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
       local proto=$1;
       local port=$2;
       local ip=$3;
@@ -187,7 +187,7 @@ else
       if [ ${DEBUG_MODE} -eq 1 ]; then
         echo "            |-->  DELETE_RULE_SKIPPED = [ ${DELETE_RULE_SKIPPED} ]";
       fi;
-		fi;
+    fi;
 	}
 
 
@@ -196,7 +196,7 @@ else
 	# Main Runtime
 	#
 	if [ $(which ufw 2>'/dev/null' | wc -l;) -gt 0 ]; then
-		if [ -f "${UFW_CONFIG_FILEPATH}" ]; then
+    if [ -f "${UFW_CONFIG_FILEPATH}" ]; then
       
       # Set UFW Defaults --> Incoming Requests
       CURRENT_DEFAULT_INPUT_POLICY=$(sed --regexp-extended --quiet --expression='s/^DEFAULT_INPUT_POLICY="(.+)"$/\1/p' "${UFW_CONFIG_FILEPATH}";);
@@ -228,7 +228,7 @@ else
         fi;
       fi;
 
-		fi;
+    fi;
 	fi;
 
 	# Array to store store CIDRv4 addresses which are newly-resolved as-of this script's runtime
@@ -242,7 +242,7 @@ else
 
 	# HOTFIX (TO-REMOVE-AFTER-2020-05-01) - Cleanup ddns double-deep (duplicated) depth directory
 	if [ -d "/etc/nginx/conf.ddns/conf.ddns" ]; then
-		rm -rf "/etc/nginx/conf.ddns/conf.ddns";
+    rm -rf "/etc/nginx/conf.ddns/conf.ddns";
 	fi;
 
 	# ------------------------------------------------------------
@@ -251,22 +251,22 @@ else
 	#
 	for EACH_SERVICE_NAME in "${!RUNTIME_SERVICE_USERS[@]}"; do
 
-		# File containing hosts to allow through UFW
-		#  |--> All lines in given whitelist file must be in a specific format/syntax
-		#        |
-		#        |--> Syntax:    tcp/udp:PORT:SUBDOMAIN.DOMAIN.TLD
-		#        |--> Example:   tcp:22:demo.example.com
-		#
-		EACH_RUNTIME_USER="${RUNTIME_SERVICE_USERS[${EACH_SERVICE_NAME}]}";
-		
-		NGINX_DDNS_CONF="${NGINX_CONF_DDNS}/${EACH_SERVICE_NAME}";
-		NGINX_DDNS_RESULTS="";
+    # File containing hosts to allow through UFW
+    #  |--> All lines in given whitelist file must be in a specific format/syntax
+    #        |
+    #        |--> Syntax:    tcp/udp:PORT:SUBDOMAIN.DOMAIN.TLD
+    #        |--> Example:   tcp:22:demo.example.com
+    #
+    EACH_RUNTIME_USER="${RUNTIME_SERVICE_USERS[${EACH_SERVICE_NAME}]}";
+    
+    NGINX_DDNS_CONF="${NGINX_CONF_DDNS}/${EACH_SERVICE_NAME}";
+    NGINX_DDNS_RESULTS="";
 
-		EACH_WHITELIST_FILE="${DIRNAME_LOCAL_CONFIG}/${EACH_SERVICE_NAME}"; # Define the location for the whitelist config-files
+    EACH_WHITELIST_FILE="${DIRNAME_LOCAL_CONFIG}/${EACH_SERVICE_NAME}"; # Define the location for the whitelist config-files
 
-		# Only whitelist services which are in-use by this machine
-		SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${EACH_SERVICE_NAME}.service" | grep "^${EACH_SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
-		if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service exists locally & is currently active
+    # Only whitelist services which are in-use by this machine
+    SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${EACH_SERVICE_NAME}.service" | grep "^${EACH_SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
+    if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service exists locally & is currently active
 
       MATCHED_PROCS_PS=$(ps --format "pid,fname,user,%cpu,%mem,maj_flt,cmd" --no-headers -U "${EACH_RUNTIME_USER}" | wc -l;);
 
@@ -484,10 +484,10 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
 
       fi;
 
-		fi;
+    fi;
 
-		# Update the NGINX conf.ddns script with final string (containing all resolved hosts for this service)
-		if [ "${EACH_SERVICE_NAME}" == "nginx" ] && [ -d "${NGINX_CONF_DDNS}" ] && [ -n "${NGINX_DDNS_RESULTS}" ]; then
+    # Update the NGINX conf.ddns script with final string (containing all resolved hosts for this service)
+    if [ "${EACH_SERVICE_NAME}" == "nginx" ] && [ -d "${NGINX_CONF_DDNS}" ] && [ -n "${NGINX_DDNS_RESULTS}" ]; then
       if [ ${DEBUG_MODE} -eq 1 ]; then
         echo "Debug:  NGINX_CONF_DDNS = [ ${NGINX_CONF_DDNS} ]";
         echo "Debug:  NGINX_DDNS_CONF = [ ${NGINX_DDNS_CONF} ]";
@@ -495,7 +495,7 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
       fi;
       echo -e "Info:  Calling  [ echo -e \"${NGINX_DDNS_RESULTS}\" > \"${NGINX_DDNS_CONF}\" ]...";
       echo -e "${NGINX_DDNS_RESULTS}" > "${NGINX_DDNS_CONF}";
-		fi;
+    fi;
 	
 	done;
 
@@ -504,9 +504,9 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
 
 	# Foreach on resolved (valid) CIDRv4 addresses
 	if [ ${DEBUG_MODE} -eq 1 ]; then
-		echo "************************************************************";
-		echo "Debug:  !RESOLVED_CIDRv4_ARR[@] = [ ${!RESOLVED_CIDRv4_ARR[@]} ]";
-		echo "Debug:  RESOLVED_CIDRv4_ARR[@] = [ ${RESOLVED_CIDRv4_ARR[@]} ]";
+    echo "************************************************************";
+    echo "Debug:  !RESOLVED_CIDRv4_ARR[@] = [ ${!RESOLVED_CIDRv4_ARR[@]} ]";
+    echo "Debug:  RESOLVED_CIDRv4_ARR[@] = [ ${RESOLVED_CIDRv4_ARR[@]} ]";
 	fi;
 
 	# for EACH_RESOLVED_CIDRv4 in "${!RESOLVED_CIDRv4_ARR[@]}"; do
@@ -547,21 +547,21 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
 	RULESET_UFW="$(ufw status | sed /^To*/d | sed /^Status*/d | sed /^--*/d | grep '\S';)";
 	ROLLBACK_IFS="${IFS}"; IFS=$'\n';
 	for EACH_UFW_LINE in ${RULESET_UFW}; do
-		EACH_UFW_CIDRv4="$(echo "${EACH_UFW_LINE}" | awk '{print $3}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
-		EACH_UFW_IPv4=$(echo ${EACH_UFW_CIDRv4} | cut -d"/" -f1);
-		EACH_UFW_PORT="$(echo "${EACH_UFW_LINE}" | awk '{print $1}' | cut -d'/' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
-		EACH_UFW_PROTO="$(echo "${EACH_UFW_LINE}" | awk '{print $1}' | cut -d'/' -f2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
+    EACH_UFW_CIDRv4="$(echo "${EACH_UFW_LINE}" | awk '{print $3}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
+    EACH_UFW_IPv4=$(echo ${EACH_UFW_CIDRv4} | cut -d"/" -f1);
+    EACH_UFW_PORT="$(echo "${EACH_UFW_LINE}" | awk '{print $1}' | cut -d'/' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
+    EACH_UFW_PROTO="$(echo "${EACH_UFW_LINE}" | awk '{print $1}' | cut -d'/' -f2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//;';)";
 
-		if [ ${DEBUG_MODE} -eq 1 ]; then
+    if [ ${DEBUG_MODE} -eq 1 ]; then
       echo "-- Debug:  EACH_UFW_LINE = [ ${EACH_UFW_LINE} ]";
       echo "Debug:  EACH_UFW_CIDRv4 = [ ${EACH_UFW_CIDRv4} ]";
       echo "Debug:  EACH_UFW_IPv4 = [ ${EACH_UFW_IPv4} ]";
       echo "Debug:  EACH_UFW_PORT = [ ${EACH_UFW_PORT} ]";
       echo "Debug:  EACH_UFW_PROTO = [ ${EACH_UFW_PROTO} ]";
-		fi;
-		
-		DELETE_RULE=1;
-		for (( i=0; i<${#RESOLVED_CIDRv4_1D[@]}; i++ )); do
+    fi;
+    
+    DELETE_RULE=1;
+    for (( i=0; i<${#RESOLVED_CIDRv4_1D[@]}; i++ )); do
       # EACH_WHITELIST_HOST+=("${RESOLVED_HOSTS_1D[$i]}");
       # EACH_RESOLVED_IPv4+=("${RESOLVED_IPv4_1D[$i]}");
       EACH_RESOLVED_CIDRv4+=("${RESOLVED_CIDRv4_1D[$i]}");
@@ -576,64 +576,64 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
           fi;
         fi;
       fi;
-		done;
+    done;
 
-		# Check resolved array for a value matching these values (Port, Protocol, CIDRv4), exactly - otherwise, delete the rule
-		#
-		# VALID_CIDRv4_PORT_PROTO="";
-		# if [ ${RESOLVED_CIDRv4_ARR[${EACH_UFW_CIDRv4}]+X} ]; then # Matched on valid CIDRv4
-		# 	VALID_CIDRv4_PORT_PROTO="${RESOLVED_CIDRv4_ARR[${EACH_UFW_CIDRv4}]}";
-		# 	if [ ${DEBUG_MODE} -eq 1 ]; then
-		# 		echo "Debug:  Matched on CIDRv4 index of \${RESOLVED_CIDRv4_ARR[${EACH_UFW_CIDRv4}]}";
-		# 		echo "Debug:  VALID_CIDRv4_PORT_PROTO = [ ${VALID_CIDRv4_PORT_PROTO} ]";
-		# 	fi;
-		# elif [ ${RESOLVED_CIDRv4_ARR[${EACH_UFW_IPv4}]+X} ]; then # Matched on valid CIDRv4
-		# 	VALID_CIDRv4_PORT_PROTO="${RESOLVED_CIDRv4_ARR[${EACH_UFW_IPv4}]}";
-		# 	if [ ${DEBUG_MODE} -eq 1 ]; then
-		# 		echo "Debug:  Matched on IPv4 index of \${RESOLVED_CIDRv4_ARR[${EACH_UFW_IPv4}]}";
-		# 		echo "Debug:  VALID_CIDRv4_PORT_PROTO = [ ${VALID_CIDRv4_PORT_PROTO} ]";
-		# 	fi;
-		# fi;
-		#
-		# if [ -n "${VALID_CIDRv4_PORT_PROTO}" ]; then
-		# 	RESOLVED_PORT_PROTOS="${VALID_CIDRv4_PORT_PROTO}";
-		# 	if [ ${DEBUG_MODE} -eq 1 ]; then
-		# 		echo "Debug:  Matched on valid CIDRv4";
-		# 		echo "Debug:  RESOLVED_PORT_PROTOS = [ ${RESOLVED_PORT_PROTOS} ]";
-		# 	fi;
-		# 	for EACH_PORT_PROTO in $(echo ${RESOLVED_PORT_PROTOS} | sed "s/,/\n/g"); do # For each substring in a comma delimited string
-		# 		RESOLVED_PORT="$(echo "${EACH_PORT_PROTO}" | cut -d'/' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')";
-		# 		RESOLVED_PROTOCOL="$(echo "${EACH_PORT_PROTO}" | cut -d'/' -f2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')";
-		# 		if [ ${DEBUG_MODE} -eq 1 ]; then
-		# 			echo "Debug:  RESOLVED_PORT = [ ${RESOLVED_PORT} ]";
-		# 			echo "Debug:  RESOLVED_PROTOCOL = [ ${RESOLVED_PROTOCOL} ]";
-		# 		fi;
-		# 		if [ "${EACH_UFW_PORT}" == "${RESOLVED_PORT}" ]; then # Matched on valid Port
-		# 			if [ "${EACH_UFW_PROTO}" == "${RESOLVED_PROTOCOL}" ]; then # Matched on valid Protocol
-		# 				# All 3 of the CIDRv4, Port, and Protocol match (do not delete this rule as it is being used as-intended)
-		# 				DELETE_RULE=0;
-		# 				if [ ${DEBUG_MODE} -eq 1 ]; then
-		# 					echo "Debug:  Match success (CIDRv4 + Port + Proto) - [ \"${EACH_UFW_PROTO}\" == \"${RESOLVED_PROTOCOL}\" ] returned false";
-		# 				fi;
-		# 				break;
-		# 			else
-		# 				if [ ${DEBUG_MODE} -eq 1 ]; then
-		# 					echo "Debug:  Match failed (protocol) - [ \"${EACH_UFW_PROTO}\" == \"${RESOLVED_PROTOCOL}\" ] returned false";
-		# 				fi;
-		# 			fi;
-		# 		else
-		# 			if [ ${DEBUG_MODE} -eq 1 ]; then
-		# 				echo "Debug:  Match failed (port) - [ \"${EACH_UFW_PORT}\" == \"${RESOLVED_PORT}\" ] returned false";
-		# 			fi;
-		# 		fi;
-		# 	done;
-		# else
-		# 	if [ ${DEBUG_MODE} -eq 1 ]; then
-		# 		echo "Debug:  Existing rule [ \"${EACH_UFW_LINE}\" ] does not match any live resolved [ CIDRv4 + Port + Proto ] combinations";
-		# 	fi;
-		# fi;
+    # Check resolved array for a value matching these values (Port, Protocol, CIDRv4), exactly - otherwise, delete the rule
+    #
+    # VALID_CIDRv4_PORT_PROTO="";
+    # if [ ${RESOLVED_CIDRv4_ARR[${EACH_UFW_CIDRv4}]+X} ]; then # Matched on valid CIDRv4
+    # 	VALID_CIDRv4_PORT_PROTO="${RESOLVED_CIDRv4_ARR[${EACH_UFW_CIDRv4}]}";
+    # 	if [ ${DEBUG_MODE} -eq 1 ]; then
+    # 		echo "Debug:  Matched on CIDRv4 index of \${RESOLVED_CIDRv4_ARR[${EACH_UFW_CIDRv4}]}";
+    # 		echo "Debug:  VALID_CIDRv4_PORT_PROTO = [ ${VALID_CIDRv4_PORT_PROTO} ]";
+    # 	fi;
+    # elif [ ${RESOLVED_CIDRv4_ARR[${EACH_UFW_IPv4}]+X} ]; then # Matched on valid CIDRv4
+    # 	VALID_CIDRv4_PORT_PROTO="${RESOLVED_CIDRv4_ARR[${EACH_UFW_IPv4}]}";
+    # 	if [ ${DEBUG_MODE} -eq 1 ]; then
+    # 		echo "Debug:  Matched on IPv4 index of \${RESOLVED_CIDRv4_ARR[${EACH_UFW_IPv4}]}";
+    # 		echo "Debug:  VALID_CIDRv4_PORT_PROTO = [ ${VALID_CIDRv4_PORT_PROTO} ]";
+    # 	fi;
+    # fi;
+    #
+    # if [ -n "${VALID_CIDRv4_PORT_PROTO}" ]; then
+    # 	RESOLVED_PORT_PROTOS="${VALID_CIDRv4_PORT_PROTO}";
+    # 	if [ ${DEBUG_MODE} -eq 1 ]; then
+    # 		echo "Debug:  Matched on valid CIDRv4";
+    # 		echo "Debug:  RESOLVED_PORT_PROTOS = [ ${RESOLVED_PORT_PROTOS} ]";
+    # 	fi;
+    # 	for EACH_PORT_PROTO in $(echo ${RESOLVED_PORT_PROTOS} | sed "s/,/\n/g"); do # For each substring in a comma delimited string
+    # 		RESOLVED_PORT="$(echo "${EACH_PORT_PROTO}" | cut -d'/' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')";
+    # 		RESOLVED_PROTOCOL="$(echo "${EACH_PORT_PROTO}" | cut -d'/' -f2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')";
+    # 		if [ ${DEBUG_MODE} -eq 1 ]; then
+    # 			echo "Debug:  RESOLVED_PORT = [ ${RESOLVED_PORT} ]";
+    # 			echo "Debug:  RESOLVED_PROTOCOL = [ ${RESOLVED_PROTOCOL} ]";
+    # 		fi;
+    # 		if [ "${EACH_UFW_PORT}" == "${RESOLVED_PORT}" ]; then # Matched on valid Port
+    # 			if [ "${EACH_UFW_PROTO}" == "${RESOLVED_PROTOCOL}" ]; then # Matched on valid Protocol
+    # 				# All 3 of the CIDRv4, Port, and Protocol match (do not delete this rule as it is being used as-intended)
+    # 				DELETE_RULE=0;
+    # 				if [ ${DEBUG_MODE} -eq 1 ]; then
+    # 					echo "Debug:  Match success (CIDRv4 + Port + Proto) - [ \"${EACH_UFW_PROTO}\" == \"${RESOLVED_PROTOCOL}\" ] returned false";
+    # 				fi;
+    # 				break;
+    # 			else
+    # 				if [ ${DEBUG_MODE} -eq 1 ]; then
+    # 					echo "Debug:  Match failed (protocol) - [ \"${EACH_UFW_PROTO}\" == \"${RESOLVED_PROTOCOL}\" ] returned false";
+    # 				fi;
+    # 			fi;
+    # 		else
+    # 			if [ ${DEBUG_MODE} -eq 1 ]; then
+    # 				echo "Debug:  Match failed (port) - [ \"${EACH_UFW_PORT}\" == \"${RESOLVED_PORT}\" ] returned false";
+    # 			fi;
+    # 		fi;
+    # 	done;
+    # else
+    # 	if [ ${DEBUG_MODE} -eq 1 ]; then
+    # 		echo "Debug:  Existing rule [ \"${EACH_UFW_LINE}\" ] does not match any live resolved [ CIDRv4 + Port + Proto ] combinations";
+    # 	fi;
+    # fi;
 
-		if [ ${DELETE_RULE} -eq 1 ]; then
+    if [ ${DELETE_RULE} -eq 1 ]; then
       if [ ${DEBUG_MODE} -eq 1 ]; then
         echo "Debug:  Deleting existing rule [ \"${EACH_UFW_LINE}\" ] - not found to match any [ CIDRv4 + Port + Proto ] combinations";
       fi;
@@ -644,12 +644,12 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
       if [ ${DELETE_RULE_SKIPPED} -eq 0 ]; then
         UFW_CHANGES_UNDO_ARR+=(["/usr/sbin/ufw allow proto ${EACH_UFW_PROTO} from ${EACH_UFW_CIDRv4} to any port ${EACH_UFW_PORT};"]="");
       fi;
-		else
+    else
       # Keep the firewall rule
       if [ ${DEBUG_MODE} -eq 1 ]; then
         echo "Debug:  Keeping existing rule [ ${EACH_UFW_LINE} ] - matched by [ CIDRv4 + Port + Proto ] combination to resolved values";
       fi;
-		fi;
+    fi;
 	done;
 	IFS="${ROLLBACK_IFS}";
 
@@ -660,7 +660,7 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
 	echo " !!    list of undo-commands created for this session   !!  ";
 	echo "";
 	for EACH_UNDO_COMMAND in "${!UFW_CHANGES_UNDO_ARR[@]}"; do
-		echo "${EACH_UNDO_COMMAND}";
+    echo "${EACH_UNDO_COMMAND}";
 	done;
 	echo "------------------------------------------------------------";
 	echo "------------------------  UFW STATUS  ----------------------";
@@ -669,19 +669,19 @@ add_rule "${RESOLVED_PROTO}" "${RESOLVED_PORT}" "${RESOLVED_CIDRv4}";
 
 	# Cleanup log files outside of the retention-policy's max-age
 	if [ -z "${LOGDIR}" ]; then
-		LOGDIR="/var/log/ddns_ufw_update";
+    LOGDIR="/var/log/ddns_ufw_update";
 	fi;
 	if [ -d "${LOGDIR}" ]; then
-		# MAX_RETENTION_DAYS=14;
-		# find "${LOGDIR}" -type f -mtime +${MAX_RETENTION_DAYS} -exec rm -- "{}" ";";
-		echo -e "\n""Info:  Cleaning logs older than 14 days old from directory \"${LOGDIR}\"";
-		find "${LOGDIR}" -type f -mtime +14 -exec rm -- '{}' \;;
+    # MAX_RETENTION_DAYS=14;
+    # find "${LOGDIR}" -type f -mtime +${MAX_RETENTION_DAYS} -exec rm -- "{}" ";";
+    echo -e "\n""Info:  Cleaning logs older than 14 days old from directory \"${LOGDIR}\"";
+    find "${LOGDIR}" -type f -mtime +14 -exec rm -- '{}' \;;
 	fi;
 
 
 	# Set ownership & privileges for the logging directory & its sub contents
 	if [ $(id "syslog" 1>/dev/null 2>&1; echo $?;) -eq 0 ] && [ $(groups "adm" 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
-		chown -R "syslog:adm" "${LOGDIR}";
+    chown -R "syslog:adm" "${LOGDIR}";
 	fi;
 	find "${LOGDIR}" -type d -print0 | xargs -0 chmod 0750; # directories 
 	find "${LOGDIR}" -type f -print0 | xargs -0 chmod 0640; # files
diff --git a/usr/local/sbin/install_jenkins b/usr/local/sbin/install_jenkins
--- a/usr/local/sbin/install_jenkins
+++ b/usr/local/sbin/install_jenkins
@@ -75,46 +75,46 @@ else
 	# Walk through any inline-arguments passed to this function
 	for (( i=0;i<$ARGS_COUNT;i++ )); do
 
-		EACH_ARG=${ARGS[${i}]};
+    EACH_ARG=${ARGS[${i}]};
 
-		# Check if this is the last inline-argument or if there are more to follow
-		if [ $((${i}+1)) -eq ${ARGS_COUNT} ]; then # if this is the last argument
+    # Check if this is the last inline-argument or if there are more to follow
+    if [ $((${i}+1)) -eq ${ARGS_COUNT} ]; then # if this is the last argument
       NEXT_ARG="";
-		else
+    else
       NEXT_ARG=${ARGS[$((${i}+1))]};
       if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
         NEXT_ARG="";
       fi;
-		fi;
+    fi;
 
-		if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
+    if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
 
       if [ "${EACH_ARG}" == "-y" ] || [ "${EACH_ARG}" == "--yes" ] || [ "${EACH_ARG}" == "-force" ] || [ "${EACH_ARG}" == "--force" ]; then
         ARGS_FORCE_AGREE=1; # Do not require user-confirmation for things like opening firewall ports required by the install service(s)
       fi;
 
-		fi;
+    fi;
 
 	done;
 
 	if [ ${ARGS_FORCE_AGREE} -eq 0 ]; then
-		echo "------------------------------------------------------------";
-		echo "";
-		echo "Info:  This will install the Jenkins CI/CD service";
-		# echo "Info:  This will install the Jenkins service and open firewall port 8080 (outgoing)";
-		echo "";
-		READ_TIMEOUT=60; read -p "Continue? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
-		echo "";
-		if [ ${RETURN_CODE_READ} -gt 128 ]; then
+    echo "------------------------------------------------------------";
+    echo "";
+    echo "Info:  This will install the Jenkins CI/CD service";
+    # echo "Info:  This will install the Jenkins service and open firewall port 8080 (outgoing)";
+    echo "";
+    READ_TIMEOUT=60; read -p "Continue? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
+    echo "";
+    if [ ${RETURN_CODE_READ} -gt 128 ]; then
       echo -e "Response timed out after ${READ_TIMEOUT}s";
       exit 1;
-		elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
+    elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
       echo -e "\n""Proceeding...\n";
       sleep 1;
-		else
+    else
       echo "Denied - Skipping the \"${SERVICE_NAME}\" service install";
       exit 1;
-		fi;
+    fi;
 	fi;
 
 	# ------------------------------------------------------------
@@ -128,66 +128,66 @@ else
 	# ------------------------------------------------------------
 	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Distros: Debian, Ubuntu, etc.
 
-		# ------------------------------------------------------------
-		# Install Java
-		wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java" -O "/usr/local/sbin/install_java" -q;
-		chmod 0755 "/usr/local/sbin/install_java";
-		/usr/local/sbin/install_java;
+    # ------------------------------------------------------------
+    # Install Java
+    wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java" -O "/usr/local/sbin/install_java" -q;
+    chmod 0755 "/usr/local/sbin/install_java";
+    /usr/local/sbin/install_java;
 
 
-		# ------------------------------------------------------------
-		# Install Fonts (Requirement for Jenkins)
-		PACKAGE_APT="ttf-dejavu"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Fonts
-		PACKAGE_APT="xvfb"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Fonts
+    # ------------------------------------------------------------
+    # Install Fonts (Requirement for Jenkins)
+    PACKAGE_APT="ttf-dejavu"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Fonts
+    PACKAGE_APT="xvfb"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Fonts
 
 
-		# ------------------------------------------------------------
-		# Install Jenkins
-		wget -q -O - "https://pkg.jenkins.io/debian-stable/jenkins.io.key" | sudo apt-key add -; # Import Jenkins' official GPG Key
-		deb "https://pkg.jenkins.io/debian-stable" binary/; # Add Jenkins' package repository
-		PACKAGE_APT="jenkins"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Jenkins
+    # ------------------------------------------------------------
+    # Install Jenkins
+    wget -q -O - "https://pkg.jenkins.io/debian-stable/jenkins.io.key" | sudo apt-key add -; # Import Jenkins' official GPG Key
+    deb "https://pkg.jenkins.io/debian-stable" binary/; # Add Jenkins' package repository
+    PACKAGE_APT="jenkins"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Jenkins
 
 
 	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
 
-		# ------------------------------------------------------------
-		# Install Java
-		wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java" -O "/usr/local/sbin/install_java" -q;
-		chmod 0755 "/usr/local/sbin/install_java";
-		/usr/local/sbin/install_java;
+    # ------------------------------------------------------------
+    # Install Java
+    wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java" -O "/usr/local/sbin/install_java" -q;
+    chmod 0755 "/usr/local/sbin/install_java";
+    /usr/local/sbin/install_java;
 
 
-		# ------------------------------------------------------------
-		# Install Fonts (Requirement for Jenkins)
-		PACKAGE_YUM="dejavu-sans-fonts";
-		if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
+    # ------------------------------------------------------------
+    # Install Fonts (Requirement for Jenkins)
+    PACKAGE_YUM="dejavu-sans-fonts";
+    if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
       yum -y check-update;
       yum -y install "${PACKAGE_YUM}";
-		fi;
-		PACKAGE_YUM="fontconfig";
-		if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
+    fi;
+    PACKAGE_YUM="fontconfig";
+    if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
       yum -y check-update;
       yum -y install "${PACKAGE_YUM}";
-		fi;
-		PACKAGE_YUM="xorg-x11-server-Xvfb";
-		if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
+    fi;
+    PACKAGE_YUM="xorg-x11-server-Xvfb";
+    if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
       yum -y check-update;
       yum -y install "${PACKAGE_YUM}";
-		fi;
-		# PACKAGE_YUM="openldap*";
-		if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
+    fi;
+    # PACKAGE_YUM="openldap*";
+    if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
       yum -y check-update;
       yum -y install openldap*;
-		fi;
+    fi;
 
-		# ------------------------------------------------------------
-		# Install Jenkins
-		PACKAGE_YUM="jenkins";
-		if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
+    # ------------------------------------------------------------
+    # Install Jenkins
+    PACKAGE_YUM="jenkins";
+    if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
       wget -O "/etc/yum.repos.d/jenkins.repo" "https://pkg.jenkins.io/redhat-stable/jenkins.repo";  # Add Jenkins' package repository
       rpm --import "https://pkg.jenkins.io/redhat-stable/jenkins.io.key" 2>'/dev/null'; # Import Jenkins' official GPG Key
       yum -y check-update; yum -y install "${PACKAGE_YUM}"; # Install Jenkins
-		fi;
+    fi;
 
 	fi;
 
@@ -195,37 +195,37 @@ else
 	# Autostart the service on bootup (as well as right now)
 	#
 	if \
-		[ "$(systemctl is-enabled ${SERVICE_NAME}.service 2>/dev/null;)" != "enabled" ] || \
-		[ "$(systemctl is-active ${SERVICE_NAME}.service 2>/dev/null;)" != "active" ] || \
-		[ $(systemctl is-enabled ${SERVICE_NAME}.service 1>/dev/null 2>&1; echo $?;) -ne 0 ] || \
-		[ $(systemctl is-active ${SERVICE_NAME}.service 1>/dev/null 2>&1; echo $?;) -ne 0 ]; \
+    [ "$(systemctl is-enabled ${SERVICE_NAME}.service 2>/dev/null;)" != "enabled" ] || \
+    [ "$(systemctl is-active ${SERVICE_NAME}.service 2>/dev/null;)" != "active" ] || \
+    [ $(systemctl is-enabled ${SERVICE_NAME}.service 1>/dev/null 2>&1; echo $?;) -ne 0 ] || \
+    [ $(systemctl is-active ${SERVICE_NAME}.service 1>/dev/null 2>&1; echo $?;) -ne 0 ]; \
 	then
-		echo "Info:  Service \"${SERVICE_NAME}\" is not both \"enabled\" and \"active\", currently";
-		echo "Info:  Calling  [ systemctl enable \"${SERVICE_NAME}.service\" --now; ]  ...";
-		systemctl enable "${SERVICE_NAME}.service" --now; # "enable --now" autostarts service at bootup && starts service immediately
+    echo "Info:  Service \"${SERVICE_NAME}\" is not both \"enabled\" and \"active\", currently";
+    echo "Info:  Calling  [ systemctl enable \"${SERVICE_NAME}.service\" --now; ]  ...";
+    systemctl enable "${SERVICE_NAME}.service" --now; # "enable --now" autostarts service at bootup && starts service immediately
 	fi;
 
 
 	# ------------------------------------------------------------
 	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
 	if [ ${SERVICE_RET_CODE} -eq 0 ]; then
-		EXIT_CODE=0;
+    EXIT_CODE=0;
 
-		# Show Jenkins' service status
-		echo -e "\n""Info:  Showing Jenkins' Service-Status";
-		echo -e "  |--> Calling  [ /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full; ]  ...""\n";
-		/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
+    # Show Jenkins' service status
+    echo -e "\n""Info:  Showing Jenkins' Service-Status";
+    echo -e "  |--> Calling  [ /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full; ]  ...""\n";
+    /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
 
-		# Show Jenkins' networking ports
-		echo -e "\n""Info:  Showing Jenkins' Ports which are in-use";
-		echo -e "  |--> Calling  [ ps aux | grep -v 'grep' | grep 'jenkins' | grep -v 'color=auto' | grep 'httpPort'; ]  ...""\n";
-		ps aux | grep -v 'grep' | grep 'jenkins' | grep -v 'color=auto' | grep 'httpPort';
-		echo "";
+    # Show Jenkins' networking ports
+    echo -e "\n""Info:  Showing Jenkins' Ports which are in-use";
+    echo -e "  |--> Calling  [ ps aux | grep -v 'grep' | grep 'jenkins' | grep -v 'color=auto' | grep 'httpPort'; ]  ...""\n";
+    ps aux | grep -v 'grep' | grep 'jenkins' | grep -v 'color=auto' | grep 'httpPort';
+    echo "";
 
-		# Configure the Firewall as-needed
-		FIREWALL_SERVICE="firewalld";
-		SERVICE_RET_CODE=$(/usr/sbin/service "${FIREWALL_SERVICE}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
-		if [ ${SERVICE_RET_CODE} -eq 0 ]; then
+    # Configure the Firewall as-needed
+    FIREWALL_SERVICE="firewalld";
+    SERVICE_RET_CODE=$(/usr/sbin/service "${FIREWALL_SERVICE}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
+    if [ ${SERVICE_RET_CODE} -eq 0 ]; then
       SERVICE_ENABLED_GREP=$(/usr/sbin/service "${FIREWALL_SERVICE}" status --no-pager --full | grep '; enabled');
       if [ -n "${SERVICE_ENABLED_GREP}" ]; then
         # Open necessary firewall port(s)
@@ -258,12 +258,12 @@ else
         firewall-cmd --reload;
         firewall-cmd --list-all;
       fi;
-		fi;
+    fi;
 
 	else
-		EXIT_CODE=1;
-		# ERROR - Jenkins Service STILL not detected after install-attempt
-		echo -e "\n""Error:  Jenkins service not detected after install attempt";
+    EXIT_CODE=1;
+    # ERROR - Jenkins Service STILL not detected after install-attempt
+    echo -e "\n""Error:  Jenkins service not detected after install attempt";
 
 	fi;
 
@@ -272,34 +272,34 @@ else
 	# Sync jenkins-config to cloud-infrastructure repo (require user confirmation)
 	JENKINS_CONFIG_PATH="";
 	if [ -f "/etc/default/jenkins" ]; then
-		JENKINS_CONFIG_PATH="/etc/default/jenkins";
+    JENKINS_CONFIG_PATH="/etc/default/jenkins";
 	elif [ -f "/etc/sysconfig/jenkins" ]; then
-		JENKINS_CONFIG_PATH="/etc/sysconfig/jenkins";
+    JENKINS_CONFIG_PATH="/etc/sysconfig/jenkins";
 	fi;
 
 	if [ -n "${JENKINS_CONFIG_PATH}" ]; then
-		if [ ${ARGS_FORCE_AGREE} -eq 0 ]; then
+    if [ ${ARGS_FORCE_AGREE} -eq 0 ]; then
       # Not Forced
       echo "";
       READ_TIMEOUT=60; read -p "Sync Jenkins config-file \"${JENKINS_CONFIG_PATH}\" to \"cloud-infrastructure\" repo, now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
       echo "";
-		else
+    else
       # Forced (Skipped)
       RETURN_CODE_READ=0;
       REPLY="y";
-		fi;
-		if [ ${RETURN_CODE_READ} -gt 128 ]; then
+    fi;
+    if [ ${RETURN_CODE_READ} -gt 128 ]; then
       echo -e "Response timed out after ${READ_TIMEOUT}s";
-		elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
+    elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
       CLOUD_SYNC_URL="https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/etc/default/jenkins";
       echo -e "\n""Info:  Downloading & Syncing Jenkins config from \"cloud-infrastructure\" repository";
       echo -e "  |--> Backing-up existing Jenkins config-file to \"${JENKINS_CONFIG_PATH}.${START_TIMESTAMP}.bak\"""\n";
       mv "${JENKINS_CONFIG_PATH}" "${JENKINS_CONFIG_PATH}.${START_TIMESTAMP}.bak";
       wget "${CLOUD_SYNC_URL}" -O "${JENKINS_CONFIG_PATH}" -q;
       chmod 0644 "${JENKINS_CONFIG_PATH}";
-		else
+    else
       echo "Denied - Skipping Jenkins config-file sync";
-		fi;
+    fi;
 	fi;
 
 	# Start/Restart the service (will build the Jenkins service from the ground-up if it was just installed)
@@ -337,8 +337,8 @@ else
 	ESCAPED_ASTERISKS="\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*";
 
 	while [ ! -f "${SERVICE_TOKEN_FILEPATH}" ] && [ ${CURRENT_WAIT_DURATION} -lt ${MAX_WAIT_DURATION} ]; do
-		CURRENT_WAIT_DURATION=$((${CURRENT_WAIT_DURATION}+1));
-		sleep 1;
+    CURRENT_WAIT_DURATION=$((${CURRENT_WAIT_DURATION}+1));
+    sleep 1;
 	done;
 	sleep 1;
 
@@ -347,40 +347,40 @@ else
 	SERVICE_INITIAL_TOKEN="";
 	SERVICE_TOKEN_ECHO="";
 	if [ -f "${SERVICE_TOKEN_FILEPATH}" ]; then
-		# Read-in the initial token
-		SERVICE_INITIAL_TOKEN=$(cat "${SERVICE_TOKEN_FILEPATH}");
-		SERVICE_TOKEN_ECHO="
+    # Read-in the initial token
+    SERVICE_INITIAL_TOKEN=$(cat "${SERVICE_TOKEN_FILEPATH}");
+    SERVICE_TOKEN_ECHO="
 Contents of \"${SERVICE_TOKEN_FILEPATH}\":
 ${SERVICE_INITIAL_TOKEN}
 ";
 	elif [ -n "$(cat ${SERVICE_LOGFILE} | grep ${ESCAPED_ASTERISKS};)" ]; then
-		# Attempt to parse the token from Jenkins' logfile
-		JENKINS_LOG_SETUP_FIRST_LINE=$(cat -n "${SERVICE_LOGFILE}" | grep ${ESCAPED_ASTERISKS} | awk '{print $1}' | head -n 1;);
-		JENKINS_LOG_SETUP_LAST_LINE=$(cat -n "${SERVICE_LOGFILE}" |  grep ${ESCAPED_ASTERISKS} | awk '{print $1}' | tail -n 1;);
-		SERVICE_TOKEN_ECHO="$(sed -n ${JENKINS_LOG_SETUP_FIRST_LINE},${JENKINS_LOG_SETUP_LAST_LINE}p ${SERVICE_LOGFILE};)";
-		# SERVICE_INITIAL_TOKEN="$(sed -n ${JENKINS_LOG_SETUP_FIRST_LINE},${JENKINS_LOG_SETUP_LAST_LINE}p ${SERVICE_LOGFILE};)";
+    # Attempt to parse the token from Jenkins' logfile
+    JENKINS_LOG_SETUP_FIRST_LINE=$(cat -n "${SERVICE_LOGFILE}" | grep ${ESCAPED_ASTERISKS} | awk '{print $1}' | head -n 1;);
+    JENKINS_LOG_SETUP_LAST_LINE=$(cat -n "${SERVICE_LOGFILE}" |  grep ${ESCAPED_ASTERISKS} | awk '{print $1}' | tail -n 1;);
+    SERVICE_TOKEN_ECHO="$(sed -n ${JENKINS_LOG_SETUP_FIRST_LINE},${JENKINS_LOG_SETUP_LAST_LINE}p ${SERVICE_LOGFILE};)";
+    # SERVICE_INITIAL_TOKEN="$(sed -n ${JENKINS_LOG_SETUP_FIRST_LINE},${JENKINS_LOG_SETUP_LAST_LINE}p ${SERVICE_LOGFILE};)";
 	fi;
 
 	if [ -n "${SERVICE_TOKEN_ECHO}" ]; then
 
-		# ------------------------------------------------------------
-		# Display the IPv4 of this server as a suggestion to help the user to get logged into Jenkins
-		echo "";
-		echo "*************************************************************";
-		echo "";
-		if [ -f "$(which get_ipv4_lan)" ]; then
+    # ------------------------------------------------------------
+    # Display the IPv4 of this server as a suggestion to help the user to get logged into Jenkins
+    echo "";
+    echo "*************************************************************";
+    echo "";
+    if [ -f "$(which get_ipv4_lan)" ]; then
       echo "To begin using Jenkins, open a web browser to http://$(get_ipv4_lan):8080";
       echo "";
-		fi;
+    fi;
 
-		# Find the default admin password for the user (so they don't have to go digging through a logfile for it)
-		echo "Initial admin token (required to activate new Jenkins service):";
-		echo -e "${SERVICE_TOKEN_ECHO}";
-		echo "";
+    # Find the default admin password for the user (so they don't have to go digging through a logfile for it)
+    echo "Initial admin token (required to activate new Jenkins service):";
+    echo -e "${SERVICE_TOKEN_ECHO}";
+    echo "";
 	else
-		EXIT_CODE=1;
-		# ERROR - Jenkins initial admin token not found
-		echo -e "\n""Error:  Unable to locate jenkins token (required to activate new Jenkins service)";
+    EXIT_CODE=1;
+    # ERROR - Jenkins initial admin token not found
+    echo -e "\n""Error:  Unable to locate jenkins token (required to activate new Jenkins service)";
 
 	fi;
 
diff --git a/usr/local/sbin/install_kdump b/usr/local/sbin/install_kdump
--- a/usr/local/sbin/install_kdump
+++ b/usr/local/sbin/install_kdump
@@ -27,88 +27,88 @@ else
 	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
 	echo "------------------------------------------------------------";
 	if [ ${SERVICE_RET_CODE} -eq 0 ]; then # Service FOUND locally
-		echo "";
-		echo "Info:  Service \"kdump\" found to exist locally (skipping package-install)";
-		/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
+    echo "";
+    echo "Info:  Service \"kdump\" found to exist locally (skipping package-install)";
+    /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
 	else # Service NOT found locally
-		echo "";
-		echo "Warning:  Service \"${SERVICE_NAME}\" not found locally";
-		echo "";
-		echo "Info:  Attempting to install the \"kdump\" package (for kernel crash dump logging) ...";
-		if [ $(which kdump 2>'/dev/null' | wc -l;) -eq 0 ]; then
+    echo "";
+    echo "Warning:  Service \"${SERVICE_NAME}\" not found locally";
+    echo "";
+    echo "Info:  Attempting to install the \"kdump\" package (for kernel crash dump logging) ...";
+    if [ $(which kdump 2>'/dev/null' | wc -l;) -eq 0 ]; then
       if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
         apt-get -y install linux-crashdump;
       elif [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
         yum -y install kexec-tools;
       fi;
-		fi;
+    fi;
 	fi;
 
 
 	if [ -f "/etc/default/grub" ]; then
-		#
-		# Enabling Grub2's "crashkernel" setting
-		#
-		if [ $(cat '/etc/default/grub' | grep '^GRUB_CMDLINE_LINUX' | grep 'crashkernel=auto' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
+    #
+    # Enabling Grub2's "crashkernel" setting
+    #
+    if [ $(cat '/etc/default/grub' | grep '^GRUB_CMDLINE_LINUX' | grep 'crashkernel=auto' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
       # Let user know config was already setup correctly
       echo "Info:  Skipping update for config file \"/etc/default/grub\" as it already contains 'GRUB_CMDLINE_LINUX=\"... crashkernel=auto ...\"' ";
-		elif [ $(cat '/etc/default/grub' | grep '^GRUB_CMDLINE_LINUX' | grep 'crashkernel=' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
+    elif [ $(cat '/etc/default/grub' | grep '^GRUB_CMDLINE_LINUX' | grep 'crashkernel=' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
       # crashkernel already configured - replace it with auto
       sed -i".$(date +'%Y%m%d_%H%M%S').bak" -re "s/^(GRUB_CMDLINE_LINUX=\".*)crashkernel=[a-zA-Z0-9:,:@\-]+(.*\")\$/\1crashkernel=auto\2/" "/etc/default/grub";
-		else
+    else
       # Add inline argument "... crashkernel=auto ..." to grub startup options
       sed -i".$(date +'%Y%m%d_%H%M%S').bak" -re "s/^(GRUB_CMDLINE_LINUX=\".+)\"\$/\1 crashkernel=auto\"/" "/etc/default/grub";
-		fi;
+    fi;
 	fi;
 
 
 	if [ -f "/etc/kdump.conf" ]; then
-		#
-		# Enabling KDump's "path" setting
-		#
-		if [ $(cat '/etc/kdump.conf' | grep '^path /var/crash' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
+    #
+    # Enabling KDump's "path" setting
+    #
+    if [ $(cat '/etc/kdump.conf' | grep '^path /var/crash' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
       # Let user know config was already setup correctly
       echo "Info:  Skipping update for config file \"/etc/kdump.conf\" as it already contains 'path /var/crash' ";
-		elif [ $(cat '/etc/kdump.conf' | grep '^path' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
+    elif [ $(cat '/etc/kdump.conf' | grep '^path' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
       # crashkernel already configured - replace it with /var/crash
       sed -i".$(date +'%Y%m%d_%H%M%S').bak" -re '/^#?path/d' "/etc/kdump.conf";
       echo "path /var/crash" > "/etc/kdump.conf";
-		else
+    else
       # Add inline argument "... crashkernel=auto ..." to grub startup options
       echo "path /var/crash" > "/etc/kdump.conf";
-		fi;
+    fi;
 
-		#
-		# Enabling KDump's "default" setting
-		#
-		if [ $(cat '/etc/kdump.conf' | grep '^default dump_to_rootfs' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
+    #
+    # Enabling KDump's "default" setting
+    #
+    if [ $(cat '/etc/kdump.conf' | grep '^default dump_to_rootfs' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
       # Let user know config was already setup correctly
       echo "Info:  Skipping update for config file \"/etc/kdump.conf\" as it already contains 'default dump_to_rootfs' ";
-		elif [ $(cat '/etc/kdump.conf' | grep '^default' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
+    elif [ $(cat '/etc/kdump.conf' | grep '^default' 1>/dev/null 2>&1; echo $?;) -eq 0 ]; then
       # crashkernel already configured - replace it with dump_to_rootfs
       sed -i".$(date +'%Y%m%d_%H%M%S').bak" -re '/^#?default/d' "/etc/kdump.conf";
       echo "default dump_to_rootfs" > "/etc/kdump.conf";
-		else
+    else
       # Add inline argument "... crashkernel=auto ..." to grub startup options
       echo "default dump_to_rootfs" > "/etc/kdump.conf";
-		fi;
+    fi;
 	fi;
 
 	
 	# Verify that taget service is enabled
 	if [ "$(systemctl is-enabled ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" == "0" ]; then
-		echo "Info:  Service \"kdump\" is enabled (skipping enable-service)";
+    echo "Info:  Service \"kdump\" is enabled (skipping enable-service)";
 	else
-		echo "Warning:  Service \"kdump\" is not enabled --> Enabling it, now...";
-		systemctl enable ${SERVICE_NAME};
+    echo "Warning:  Service \"kdump\" is not enabled --> Enabling it, now...";
+    systemctl enable ${SERVICE_NAME};
 	fi;
 
 	# Verify that taget service is active
 	if [ "$(systemctl is-active ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" == "0" ]; then
-		echo "Info:  Service \"kdump\" is active (skipping start-service)";
+    echo "Info:  Service \"kdump\" is active (skipping start-service)";
 	else
-		echo "Warning:  Service \"kdump\" is not active --> Starting it, now...";
-		systemctl start ${SERVICE_NAME};
+    echo "Warning:  Service \"kdump\" is not active --> Starting it, now...";
+    systemctl start ${SERVICE_NAME};
 	fi;
 
 
diff --git a/usr/local/sbin/install_ssh_server b/usr/local/sbin/install_ssh_server
--- a/usr/local/sbin/install_ssh_server
+++ b/usr/local/sbin/install_ssh_server
@@ -23,13 +23,13 @@ else
 	SERVICE_NAME="java";
 
 	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
-		PACKAGE_NAME="openssh-server"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Distros: Debian, Ubuntu, etc.
+    PACKAGE_NAME="openssh-server"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Distros: Debian, Ubuntu, etc.
 	# elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
 	# 	PACKAGE_NAME="openssh-server"; yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
 	else
-		echo "";
-		echo "Error:  Environment not (yet) supported, exiting...";
-		exit 1;
+    echo "";
+    echo "Error:  Environment not (yet) supported, exiting...";
+    exit 1;
 	fi;
 
 	# ------------------------------------------------------------
diff --git a/usr/local/sbin/jenkins_diag_info b/usr/local/sbin/jenkins_diag_info
--- a/usr/local/sbin/jenkins_diag_info
+++ b/usr/local/sbin/jenkins_diag_info
@@ -28,23 +28,23 @@ else
 	#  |--> Many of these commands are tools which may be found in the Java Developer's Toolkit
 	#
 	if [ -z "$(which jcmd 2>'/dev/null')" ] || [ -z "$(which jps 2>'/dev/null')" ] || [ -z "$(which jmap 2>'/dev/null')" ]; then
-		READ_TIMEOUT=60;
-		echo "";
-		echo "Error:  One or more required commands from the 'Java Development Toolkit' were not found, locally";
-		echo "         (Required commands:  jcmd, jps, jmap)";
-		echo "";
-		read -p "Install the Java Developer Toolkit, now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
-		echo "";
-		if [ ${RETURN_CODE_READ} -gt 128 ]; then
+    READ_TIMEOUT=60;
+    echo "";
+    echo "Error:  One or more required commands from the 'Java Development Toolkit' were not found, locally";
+    echo "         (Required commands:  jcmd, jps, jmap)";
+    echo "";
+    read -p "Install the Java Developer Toolkit, now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
+    echo "";
+    if [ ${RETURN_CODE_READ} -gt 128 ]; then
       echo "Error:  Response timed out after ${READ_TIMEOUT}s";
       exit 1;
-		elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
+    elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
       # install_java - Instals Java + Java Developer Toolkit
       curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java?t=$(date +'%s.%N')" | bash;
-		else
+    else
       echo "Info:  Required package-install denied  -->  Exiting...";
       exit 1;
-		fi;
+    fi;
 	fi;
 
 	# ------------------------------------------------------------
@@ -54,29 +54,29 @@ else
 
 	#   jcmd  -->  Sends diagnostic command requests to a running Java Virtual Machine (JVM).
 	if [ 1 ]; then
-		# Note: In Cent-OS7, (as-of Apr-2020), YOU MUST CALL jcmd WHILST EITHER LOGGED-IS-AS OR MASQUERADING-AS THE SERVICE USER
-		SERVICE_USER="jenkins";
-		# Note: Command 'VM.system_properties' seems to sum things up nicely without TOO much extra info (athough it's still a lot of info)
-		# DIAG_REQUEST="VM.classloader_stats";
-		# DIAG_REQUEST="VM.classloaders";
-		# DIAG_REQUEST="VM.command_line";
-		# DIAG_REQUEST="VM.dynlibs";
-		# DIAG_REQUEST="VM.flags";
-		# DIAG_REQUEST="VM.info";
-		# DIAG_REQUEST="VM.log";
-		# DIAG_REQUEST="VM.metaspace";
-		# DIAG_REQUEST="VM.native_memory";
-		# DIAG_REQUEST="VM.print_touched_methods";
-		# DIAG_REQUEST="VM.set_flag";
-		# DIAG_REQUEST="VM.start_java_debugging";
-		# DIAG_REQUEST="VM.stringtable";
-		# DIAG_REQUEST="VM.symboltable";
-		DIAG_REQUEST="VM.system_properties";
-		# DIAG_REQUEST="VM.uptime";
-		# DIAG_REQUEST="VM.version";
-		# DIAG_REQUEST="ManagementAgent.status";
-		DIAG_OUTPUT="$(sudo -u ${SERVICE_USER} jcmd $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}') ${DIAG_REQUEST})";
-		echo -e "\n${DIAG_OUTPUT}\n";
+    # Note: In Cent-OS7, (as-of Apr-2020), YOU MUST CALL jcmd WHILST EITHER LOGGED-IS-AS OR MASQUERADING-AS THE SERVICE USER
+    SERVICE_USER="jenkins";
+    # Note: Command 'VM.system_properties' seems to sum things up nicely without TOO much extra info (athough it's still a lot of info)
+    # DIAG_REQUEST="VM.classloader_stats";
+    # DIAG_REQUEST="VM.classloaders";
+    # DIAG_REQUEST="VM.command_line";
+    # DIAG_REQUEST="VM.dynlibs";
+    # DIAG_REQUEST="VM.flags";
+    # DIAG_REQUEST="VM.info";
+    # DIAG_REQUEST="VM.log";
+    # DIAG_REQUEST="VM.metaspace";
+    # DIAG_REQUEST="VM.native_memory";
+    # DIAG_REQUEST="VM.print_touched_methods";
+    # DIAG_REQUEST="VM.set_flag";
+    # DIAG_REQUEST="VM.start_java_debugging";
+    # DIAG_REQUEST="VM.stringtable";
+    # DIAG_REQUEST="VM.symboltable";
+    DIAG_REQUEST="VM.system_properties";
+    # DIAG_REQUEST="VM.uptime";
+    # DIAG_REQUEST="VM.version";
+    # DIAG_REQUEST="ManagementAgent.status";
+    DIAG_OUTPUT="$(sudo -u ${SERVICE_USER} jcmd $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}') ${DIAG_REQUEST})";
+    echo -e "\n${DIAG_OUTPUT}\n";
 	fi;
 
 
@@ -96,18 +96,18 @@ else
 
 	# WARNING:  CLSTATS OFTEN LOCKS UP THE MACHINE & ITS SERVICE(S)
 	if [ 0 -eq 1 ]; then
-		echo "Info:  Calling  [ jmap -clstats ]  which  [ Prints class loader wise statistics of Java heap. For each class loader, its name, how active it is, address, parent class loader, and the number and size of classes it has loaded are printed. ]";
-		SERVICE_USER="jenkins";
-		JMAP_CLSTATS="$(jmap -clstats -F $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}');)";
-		echo "${JMAP_CLSTATS}";
+    echo "Info:  Calling  [ jmap -clstats ]  which  [ Prints class loader wise statistics of Java heap. For each class loader, its name, how active it is, address, parent class loader, and the number and size of classes it has loaded are printed. ]";
+    SERVICE_USER="jenkins";
+    JMAP_CLSTATS="$(jmap -clstats -F $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}');)";
+    echo "${JMAP_CLSTATS}";
 	fi;
 
 	# WARNING:  HISTO OFTEN LOCKS UP THE MACHINE & ITS SERVICE(S)
 	if [ 0 -eq 1 ]; then
-		echo "Info:  Calling  [ jmap -histo ]  which  [ Prints a histogram of the heap. For each Java class, the number of objects, memory size in bytes, and the fully qualified class names are printed. The JVM internal class names are printed with an asterisk (*) prefix. ]";
-		SERVICE_USER="jenkins";
-		JMAP_HISTO="$(jmap -histo -F $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}');)";
-		echo "${JMAP_HISTO}";
+    echo "Info:  Calling  [ jmap -histo ]  which  [ Prints a histogram of the heap. For each Java class, the number of objects, memory size in bytes, and the fully qualified class names are printed. The JVM internal class names are printed with an asterisk (*) prefix. ]";
+    SERVICE_USER="jenkins";
+    JMAP_HISTO="$(jmap -histo -F $(ps u -C 'java' | grep -vEi ^USER | grep -Ei ^${SERVICE_USER} | awk '{print $2}');)";
+    echo "${JMAP_HISTO}";
 	fi;
 	
 
diff --git a/usr/local/sbin/jenkins_log_cleanup b/usr/local/sbin/jenkins_log_cleanup
--- a/usr/local/sbin/jenkins_log_cleanup
+++ b/usr/local/sbin/jenkins_log_cleanup
@@ -38,22 +38,22 @@ else
 	echo -e "\n\n${DASHES}\n";
 
 	if [ -z "${JENKINS_UNAME}" ]; then # jenkins process not found
-		echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - No processes found which match text \"${PS_AUX_CONTAINS}\"";
-		exit 1;
-		
+    echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - No processes found which match text \"${PS_AUX_CONTAINS}\"";
+    exit 1;
+    
 	elif [ -n "$(id -u ${JENKINS_UNAME} | grep 'no such user')" ]; then # jenkins user not found
-		echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - No users found with name \"${JENKINS_UNAME}\"";
-		exit 1;
+    echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - No users found with name \"${JENKINS_UNAME}\"";
+    exit 1;
 
 	else
-		
-		JENKINS_UHOME=$(getent passwd ${JENKINS_UNAME} | cut --delimiter=: --fields=6);
+    
+    JENKINS_UHOME=$(getent passwd ${JENKINS_UNAME} | cut --delimiter=: --fields=6);
 
-		if [ ! -d "${JENKINS_UHOME}" ]; then # jenkins home-dir not found
+    if [ ! -d "${JENKINS_UHOME}" ]; then # jenkins home-dir not found
       echo -e "$(date +'%Y-%m-%d %H:%M:%S')\nError - Jenkins home-directory not found: \"${JENKINS_UHOME}\"";
       exit 1;
 
-		else # good to go - begin deleting dirs
+    else # good to go - begin deleting dirs
 
       FIND_PARENT="${JENKINS_UHOME}/jobs/";
       FIND_REGEX="^${FIND_PARENT}.+/builds/[0-9]+$";
@@ -70,7 +70,7 @@ else
         -mtime +${MAX_AGE_DAYS} \
         -exec rm -rf -- '{}' \;
 
-		fi;
+    fi;
 
 	fi;
 
@@ -81,10 +81,10 @@ else
 	echo "  Filepath starts with: \"${FIND_PARENT}\"";
 
 	find "${FIND_PARENT}" \
-		-mindepth 1 \
-		-maxdepth 10 \
-		-mtime +${MAX_AGE_DAYS} \
-		-exec rm -rf -- '{}' \;
+    -mindepth 1 \
+    -maxdepth 10 \
+    -mtime +${MAX_AGE_DAYS} \
+    -exec rm -rf -- '{}' \;
 
 
 	# # NGINX - Reload
diff --git a/usr/local/sbin/motd_status b/usr/local/sbin/motd_status
--- a/usr/local/sbin/motd_status
+++ b/usr/local/sbin/motd_status
@@ -35,17 +35,17 @@ else
 
 	# Walk through any inline-arguments passed to this function
 	for (( i=0;i<$COUNT_ARGS;i++ )); do
-		EACH_ARG=${ARGS[${i}]};
-		# Check if this is the last inline-argument or if there are more to follow
-		if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
+    EACH_ARG=${ARGS[${i}]};
+    # Check if this is the last inline-argument or if there are more to follow
+    if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
       NEXT_ARG="";
-		else
+    else
       NEXT_ARG=${ARGS[$((${i}+1))]};
       if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
         NEXT_ARG="";
       fi;
-		fi;
-		if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
+    fi;
+    if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
       # ------------------------------------------------------------
 
       if [ "${EACH_ARG}" == "--enable" ] || [ "${EACH_ARG}" == "-enable" ] || [ "${EACH_ARG}" == "enable" ]; then
@@ -56,40 +56,40 @@ else
       fi;
 
       # ------------------------------------------------------------
-		fi;
+    fi;
 
 	done;
 
 	if [ -z "$(which sed 2>'/dev/null';)" ]; then
-		# Missing required package
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error -> Package not found: \"sed\" - Please install this package, then re-run this script";
-		echo -e "${EXAMPLE_VALID_CALL}";
-		exit 1;
+    # Missing required package
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error -> Package not found: \"sed\" - Please install this package, then re-run this script";
+    echo -e "${EXAMPLE_VALID_CALL}";
+    exit 1;
 
 	else
 
-		if [ ${ENABLE_MOTD} -eq 1 ]; then
+    if [ ${ENABLE_MOTD} -eq 1 ]; then
       MOTD_ENABLED_VALUE=1;
-		elif [ ${DISABLE_MOTD} -eq 1 ]; then
+    elif [ ${DISABLE_MOTD} -eq 1 ]; then
       MOTD_ENABLED_VALUE=0;
-		fi;
+    fi;
 
-		if [ ! -v MOTD_ENABLED_VALUE ]; then
+    if [ ! -v MOTD_ENABLED_VALUE ]; then
       # ERROR - Required argument(s) are empty/undefined
       echo "$(date +'%Y-%m-%d %H:%M:%S') | Info -> To disable MOTD (Message of the Day), use the '--disable' directive via: >  motd_status --disable";
       echo "$(date +'%Y-%m-%d %H:%M:%S') | Info -> To enable MOTD (Message of the Day), use the '--enable' directive via: >  motd_status --enable";
-		
-		elif [ ${ENABLE_MOTD} -eq 1 ] && [ ${DISABLE_MOTD} -eq 1 ]; then
+    
+    elif [ ${ENABLE_MOTD} -eq 1 ] && [ ${DISABLE_MOTD} -eq 1 ]; then
       # ERROR - Conflicting arguments
       echo "$(date +'%Y-%m-%d %H:%M:%S') | Error -> Please select only enable or disable (and not both) directives";
 
-		elif [ $(find /etc/update-motd.d/*motd-news* 2>'/dev/null' | wc -l) -eq 0 ] && [ $(find /etc/default/*motd-news* 2>'/dev/null' | wc -l) -eq 0 ]; then
+    elif [ $(find /etc/update-motd.d/*motd-news* 2>'/dev/null' | wc -l) -eq 0 ] && [ $(find /etc/default/*motd-news* 2>'/dev/null' | wc -l) -eq 0 ]; then
         # ERROR - Missing required file(s)
         echo "$(date +'%Y-%m-%d %H:%M:%S') | Error -> No file(s) found which match glob-pattern [ /etc/update-motd.d/*motd-news* ] or [ /etc/default/*motd-news* ]";
         echo -e "${EXAMPLE_VALID_CALL}";
         exit 1;
 
-		else
+    else
 
       # Success - Update each associated config-file
       echo "Replacing lines starting with \"ENABLED=\" to, instead, be \"ENABLED=${MOTD_ENABLED_VALUE}\"";
@@ -102,7 +102,7 @@ else
         sed --in-place -e "/^ENABLED=/c\ENABLED=${MOTD_ENABLED_VALUE}" "${EACH_FILE}";
       done;
 
-		fi;
+    fi;
 
 	fi;
 
diff --git a/usr/local/sbin/remove_service b/usr/local/sbin/remove_service
--- a/usr/local/sbin/remove_service
+++ b/usr/local/sbin/remove_service
@@ -28,22 +28,22 @@ else
 
 	if [ -z "${1}" ]; then
 
-		# Required variable empty
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: No value given for first parameter (\$1)";
-		echo "Please set \$1 to [ service-name-to-remove ]\" & re-run this script";
-		echo "  ( e.g. ${0} \"wget\"; )";
-		echo "";
-		exit 1;
+    # Required variable empty
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: No value given for first parameter (\$1)";
+    echo "Please set \$1 to [ service-name-to-remove ]\" & re-run this script";
+    echo "  ( e.g. ${0} \"wget\"; )";
+    echo "";
+    exit 1;
 
 	else
 
-		SERVICE_NAME="$1";
+    SERVICE_NAME="$1";
 
-		echo "";
-		read -p "$(date +'%Y-%m-%d %H:%M:%S') Remove service \"${SERVICE_NAME}\", now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
-		echo "";
+    echo "";
+    read -p "$(date +'%Y-%m-%d %H:%M:%S') Remove service \"${SERVICE_NAME}\", now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
+    echo "";
 
-		if [[ $REPLY =~ ^[Yy]$ ]]; then
+    if [[ $REPLY =~ ^[Yy]$ ]]; then
 
       echo "$(date +'%Y-%m-%d %H:%M:%S') Confirmed - Removing service \"${SERVICE_NAME}\"...";
 
@@ -64,15 +64,15 @@ else
       # Reset the 'failed' state of all services
       /bin/systemctl reset-failed;
 
-		else
+    else
 
       echo "$(date +'%Y-%m-%d %H:%M:%S') Cancelled - No Action Taken";
 
-		fi;
+    fi;
 
-		echo "$(date +'%Y-%m-%d %H:%M:%S') Finished - Exiting...";
-		echo "";
-		exit;
+    echo "$(date +'%Y-%m-%d %H:%M:%S') Finished - Exiting...";
+    echo "";
+    exit;
 
 	fi;
 
diff --git a/usr/local/sbin/set_hostname b/usr/local/sbin/set_hostname
--- a/usr/local/sbin/set_hostname
+++ b/usr/local/sbin/set_hostname
@@ -47,20 +47,20 @@ else
 	# Walk through any inline-arguments passed to this function
 	for (( i=0;i<$COUNT_ARGS;i++ )); do
 
-		EACH_ARG=${ARGS[${i}]};
-		# BASH_ARG_NUMBER=$((${i}+1)); # Bash arg-number is one greater than the ARGS arg-number -> this is due-to bash's ${0} arg, which contains the base-command
+    EACH_ARG=${ARGS[${i}]};
+    # BASH_ARG_NUMBER=$((${i}+1)); # Bash arg-number is one greater than the ARGS arg-number -> this is due-to bash's ${0} arg, which contains the base-command
 
-		# Check if this is the last inline-argument or if there are more to follow
-		if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
+    # Check if this is the last inline-argument or if there are more to follow
+    if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
       NEXT_ARG="";
-		else
+    else
       NEXT_ARG=${ARGS[$((${i}+1))]};
       if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
         NEXT_ARG="";
       fi;
-		fi;
+    fi;
 
-		if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
+    if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
 
       # Parse inline hostname
       if [ ${i} -eq 0 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then # Allow the first argument to be the hostname (without needing --hostname before it)
@@ -94,7 +94,7 @@ else
         DRY_RUN="0";
       fi;
 
-		fi;
+    fi;
 	done;
 
 	# ------------------------------------------------------------
@@ -103,86 +103,86 @@ else
 	CURRENT_HOSTNAME="$(hostname)";
 	CURRENT_LAN_IPV4="$(hostname -i | awk '{print $1}')";
 	if [ "$(hostname -d;)" != "(none)" ]; then
-		CURRENT_DOMAIN="$(hostname -d;)";
+    CURRENT_DOMAIN="$(hostname -d;)";
 	fi;
 
 
 	# ------------------------------------------------------------
 	if [ -z "${INPUT_HOSTNAME}" ]; then
-		# Error - Required variable empty: INPUT_HOSTNAME
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Command \"$(realpath ${0};)\" called with empty hostname";
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --hostname FQDN ]";
-		exit 1;
+    # Error - Required variable empty: INPUT_HOSTNAME
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Command \"$(realpath ${0};)\" called with empty hostname";
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --hostname FQDN ]";
+    exit 1;
 
 	elif [ "${INPUT_HOSTNAME}" != "$(echo ${INPUT_HOSTNAME} | grep --extended-regexp '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$';)" ]; then
-		# Error - Hostname contains one or more invalid characters
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Command \"$(realpath ${0};)\" called with invalid hostname:  \"${INPUT_HOSTNAME}\"";
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --hostname VALID-HOSTNAME ]";
-		exit 1;
+    # Error - Hostname contains one or more invalid characters
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') Error:  Command \"$(realpath ${0};)\" called with invalid hostname:  \"${INPUT_HOSTNAME}\"";
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --hostname VALID-HOSTNAME ]";
+    exit 1;
 
 	else
 
-		SUBSTRING_ONLY_PERIODS="${INPUT_HOSTNAME//[^.]}";
-		FQDN_COUNT_PERIODS="${#SUBSTRING_ONLY_PERIODS}";
-		if [ "${FQDN_COUNT_PERIODS}" == "0" ]; then
+    SUBSTRING_ONLY_PERIODS="${INPUT_HOSTNAME//[^.]}";
+    FQDN_COUNT_PERIODS="${#SUBSTRING_ONLY_PERIODS}";
+    if [ "${FQDN_COUNT_PERIODS}" == "0" ]; then
       # Hostname includes no periods - use it as-is
       SET_HOSTNAME="${INPUT_HOSTNAME}";
       if [ -v CURRENT_DOMAIN ] && [ -n "${CURRENT_DOMAIN}" ]; then
         SET_DOMAIN="${CURRENT_DOMAIN}";
       fi;
-		else
+    else
       # Hostname has at least one period in it --> parse the domain name out from the hostname
       SET_HOSTNAME=$(echo "${INPUT_HOSTNAME}" | cut --delimiter="." --fields=1 --only-delimited;);
       SET_DOMAIN=$(echo "${INPUT_HOSTNAME}" | cut --delimiter="." --fields=1 --complement --only-delimited;);
-		fi;
+    fi;
 
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  SET_HOSTNAME:   \"${SET_HOSTNAME}\"";
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  SET_DOMAIN:   \"${SET_DOMAIN}\"";
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  SET_HOSTNAME:   \"${SET_HOSTNAME}\"";
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  SET_DOMAIN:   \"${SET_DOMAIN}\"";
 
-		# ------------------------------------------------------------
-		# Determine Linux distro
-		#
+    # ------------------------------------------------------------
+    # Determine Linux distro
+    #
 
-		IS_CENTOS=$(if [[ $(cat /etc/*release | grep -i centos | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
-		IS_UBUNTU=$(if [[ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
-		IS_ALPINE=$(if [[ $(cat /etc/*release | grep -i alpine | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
-		IS_DEBIAN=$(if [[ $(cat /etc/*release | grep -i debian | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
-		THIS_LINUX_DISTRO="$(if [[ ${IS_CENTOS} -gt 0 ]]; then echo CENTOS; elif [[ ${IS_UBUNTU} -gt 0 ]]; then echo UBUNTU; elif [[ ${IS_ALPINE} -gt 0 ]]; then echo ALPINE; elif [[ ${IS_DEBIAN} -gt 0 ]]; then echo DEBIAN; else echo UNKNOWN; fi; )";
+    IS_CENTOS=$(if [[ $(cat /etc/*release | grep -i centos | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
+    IS_UBUNTU=$(if [[ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
+    IS_ALPINE=$(if [[ $(cat /etc/*release | grep -i alpine | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
+    IS_DEBIAN=$(if [[ $(cat /etc/*release | grep -i debian | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
+    THIS_LINUX_DISTRO="$(if [[ ${IS_CENTOS} -gt 0 ]]; then echo CENTOS; elif [[ ${IS_UBUNTU} -gt 0 ]]; then echo UBUNTU; elif [[ ${IS_ALPINE} -gt 0 ]]; then echo ALPINE; elif [[ ${IS_DEBIAN} -gt 0 ]]; then echo DEBIAN; else echo UNKNOWN; fi; )";
 
-		# ------------------------------------------------------------
-		# External server(s) to resolve WAN-IP through
-		#
-		RESOLVER_1="https://icanhazip.com";
-		RESOLVER_2="https://ipecho.net/plain";
-		RESOLVER_3="https://ident.me";
-		RESOLVER_4="https://bot.whatismyipaddress.com";
+    # ------------------------------------------------------------
+    # External server(s) to resolve WAN-IP through
+    #
+    RESOLVER_1="https://icanhazip.com";
+    RESOLVER_2="https://ipecho.net/plain";
+    RESOLVER_3="https://ident.me";
+    RESOLVER_4="https://bot.whatismyipaddress.com";
 
-		### Get WAN-Outgoing IPv4
-		if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_1}"); fi; RESOLVER_USED="${RESOLVER_1}";
-		if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_2}"); fi; RESOLVER_USED="${RESOLVER_2}";
-		if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_3}"); fi; RESOLVER_USED="${RESOLVER_3}";
-		if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_4}"); fi; RESOLVER_USED="${RESOLVER_4}";
+    ### Get WAN-Outgoing IPv4
+    if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_1}"); fi; RESOLVER_USED="${RESOLVER_1}";
+    if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_2}"); fi; RESOLVER_USED="${RESOLVER_2}";
+    if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_3}"); fi; RESOLVER_USED="${RESOLVER_3}";
+    if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_4}"); fi; RESOLVER_USED="${RESOLVER_4}";
 
-		### Get LAN-Local's Gateway IPv4
-		THIS_GATEWAY_IPV4=$(ip route|grep 'default via '|sed -rne "s/^default\s+via\s+([0-9a-fA-F\:\.]+)\s+[a-zA-Z0-9]+\s+([a-zA-Z0-9]+).+$/\1/p");
+    ### Get LAN-Local's Gateway IPv4
+    THIS_GATEWAY_IPV4=$(ip route|grep 'default via '|sed -rne "s/^default\s+via\s+([0-9a-fA-F\:\.]+)\s+[a-zA-Z0-9]+\s+([a-zA-Z0-9]+).+$/\1/p");
 
-		### Get LAN-Local IPv4(s) - One per NIC
-		THIS_LAN_NIC=$(ip route|grep 'default via '|sed -rne "s/^default\s+via\s+([0-9a-fA-F\:\.]+)\s+[a-zA-Z0-9]+\s+([a-zA-Z0-9]+).+$/\2/p");
+    ### Get LAN-Local IPv4(s) - One per NIC
+    THIS_LAN_NIC=$(ip route|grep 'default via '|sed -rne "s/^default\s+via\s+([0-9a-fA-F\:\.]+)\s+[a-zA-Z0-9]+\s+([a-zA-Z0-9]+).+$/\2/p");
 
-		### Get LAN-Local IPv4, as well as LAN-Local IPv6 (if exists)
-		THIS_LAN_IPV4=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\.' 2>'/dev/null';);
-		if [ -z "${THIS_LAN_IPV4}" ]; then
+    ### Get LAN-Local IPv4, as well as LAN-Local IPv6 (if exists)
+    THIS_LAN_IPV4=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\.' 2>'/dev/null';);
+    if [ -z "${THIS_LAN_IPV4}" ]; then
       THIS_LAN_IPV4=$(hostname -i | awk '{print $1}' 2>'/dev/null';);
-		fi;
-		THIS_LAN_IPV6=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\:' 2>'/dev/null';);
+    fi;
+    THIS_LAN_IPV6=$(ip addr show ${THIS_LAN_NIC} | grep 'inet' | grep 'scope global' | awk '{ print $2; }' | sed 's/\/.*$//' | grep '\:' 2>'/dev/null';);
 
-		if [ ${USE_WAN_IPV4} -ne 0 ]; then
+    if [ ${USE_WAN_IPV4} -ne 0 ]; then
       ### Show Resolved WAN IPv4
       if [ -n "${THIS_WAN_IPV4}" ]; then
         echo "";
@@ -194,44 +194,44 @@ else
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ env THIS_WAN_IPV4=\"127.0.0.1\" ${0} ]  (replacing 127.0.0.1 with machine's WAN IPv4)";
         exit 1;
       fi;
-		else
+    else
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Optional) Resolve hostname requests to WAN IPv4 (instead of LAN) using syntax  [ ${0} --wan ]";
-		fi;
+    fi;
 
-		### Show Resolved Gateway IPv4
-		if [ -n "${THIS_GATEWAY_IPV4}" ]; then
+    ### Show Resolved Gateway IPv4
+    if [ -n "${THIS_GATEWAY_IPV4}" ]; then
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Gateway IPv4 resolved to \"${THIS_GATEWAY_IPV4}\"";
-		else 
+    else 
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Warning:  Unable to resolve LAN's Gateway-IPv4.";
-		fi;
+    fi;
 
-		### Show Resolved LAN IPv4
-		if [ -n "${THIS_LAN_IPV4}" ]; then
+    ### Show Resolved LAN IPv4
+    if [ -n "${THIS_LAN_IPV4}" ]; then
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Local IPv4 resolved to \"${THIS_LAN_IPV4}\"";
-		else 
+    else 
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Error: Unable to resolve LAN Local IPv4 Address  - If you wish to manually set it, please set \${THIS_LAN_IPV4} to your desired value, then re-run this script";
       exit 1;
-		fi;
+    fi;
 
-		### Show Resolved LAN IPv6
-		if [ -n "${THIS_LAN_IPV6}" ]; then
+    ### Show Resolved LAN IPv6
+    if [ -n "${THIS_LAN_IPV6}" ]; then
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  LAN Local IPv6 resolved to \"${THIS_LAN_IPV6}\"";
-		else 
+    else 
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Warning:  Unable to resolve LAN Local IPv6 Address";
-		fi;
+    fi;
 
-		# ------------------------------------------------------------
-		#	If Dry-Run mode is off, require user to confirm changes
-		#
+    # ------------------------------------------------------------
+    #	If Dry-Run mode is off, require user to confirm changes
+    #
 
-		if [[ "${DRY_RUN}" == "0" ]]; then
+    if [[ "${DRY_RUN}" == "0" ]]; then
       echo ""; read -p "Update hostname, now? (y/n)  " -n 1 -t 60 -r; echo "";
       if [[ $REPLY =~ ^[Yy]$ ]]; then
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info: - Confirmed by user - Proceeding with changes to hostname & domain-name...";
@@ -239,14 +239,14 @@ else
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info: - Cancelled by user - exiting...";
         exit 1;
       fi;
-		fi;
-		echo "";
+    fi;
+    echo "";
 
-		# ------------------------------------------------------------
-		# /etc/hostname
-		#
-		HOSTNAME_FILE="/etc/hostname";
-		if [[ -f "${HOSTNAME_FILE}" ]]; then
+    # ------------------------------------------------------------
+    # /etc/hostname
+    #
+    HOSTNAME_FILE="/etc/hostname";
+    if [[ -f "${HOSTNAME_FILE}" ]]; then
       if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Calling [ cat \"${HOSTNAME_FILE}\"; ]  (before edits, $(date +'%Y-%m-%d %H:%M:%S'))";
@@ -267,18 +267,18 @@ else
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Skipping update for hostname file \"${HOSTNAME_FILE}\" (already matches desired hostname)";
         fi;
       fi;
-		fi;
+    fi;
 
-		# ------------------------------------------------------------
-		# /etc/hosts
-		#
-		# ------------------------------------------------------------
-		# To set the DNS domainname edit /etc/hosts file and ensure that:
-		#	 |--> 1. There is a line <machine's primary, non-loopback IP address> <hostname>.<domainname> <hostname> there
-		#	 |--> 2. There are NO other lines with <some IP> <hostname>, and this includes lines with 127.0.0.1 and ::1 (IPv6) addresses.
-		# ------------------------------------------------------------
-		HOSTS_FILE="/etc/hosts";
-		if [[ -f "${HOSTS_FILE}" ]]; then
+    # ------------------------------------------------------------
+    # /etc/hosts
+    #
+    # ------------------------------------------------------------
+    # To set the DNS domainname edit /etc/hosts file and ensure that:
+    #	 |--> 1. There is a line <machine's primary, non-loopback IP address> <hostname>.<domainname> <hostname> there
+    #	 |--> 2. There are NO other lines with <some IP> <hostname>, and this includes lines with 127.0.0.1 and ::1 (IPv6) addresses.
+    # ------------------------------------------------------------
+    HOSTS_FILE="/etc/hosts";
+    if [[ -f "${HOSTS_FILE}" ]]; then
 
       echo "";
       if [ ${USE_WAN_IPV4} -ne 0 ]; then
@@ -342,12 +342,12 @@ else
       fi;
       rm -f "${TEMP_HOSTS}";
       
-		fi;
+    fi;
 
-		# ------------------------------------------------------------
-		# centos 6
-		#
-		if [[ -f "/etc/sysconfig/network" ]]; then
+    # ------------------------------------------------------------
+    # centos 6
+    #
+    if [[ -f "/etc/sysconfig/network" ]]; then
       if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
 
         if [ -n "${SET_DOMAIN}" ]; then
@@ -364,43 +364,43 @@ else
           echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ sed -i -e \"/^HOSTNAME=/c\HOSTNAME=${SET_HOSTNAME}\" \"/etc/sysconfig/network\"; ]";
         fi;
       fi;
-		fi;
+    fi;
 
-		# ------------------------------------------------------------
-		# debian 7 / slackware / ubuntu 14.04
-		#
-		if [[ -f "/etc/init.d/hostname.sh" ]]; then
+    # ------------------------------------------------------------
+    # debian 7 / slackware / ubuntu 14.04
+    #
+    if [[ -f "/etc/init.d/hostname.sh" ]]; then
       if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         /etc/init.d/hostname.sh;
       else # dry-run
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ /etc/init.d/hostname.sh; ]";
       fi;
-		fi;
+    fi;
 
-		# ------------------------------------------------------------
-		# arch / centos 7 / debian 8 / fedora / ubuntu 16.04 and above
-		#
-		if [[ $(hostnamectl | wc -l) -gt 0 ]]; then
+    # ------------------------------------------------------------
+    # arch / centos 7 / debian 8 / fedora / ubuntu 16.04 and above
+    #
+    if [[ $(hostnamectl | wc -l) -gt 0 ]]; then
       if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         hostnamectl set-hostname "${SET_HOSTNAME}";
       else # dry-run
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping call  [ hostnamectl set-hostname \"${SET_HOSTNAME}\" ]";
       fi;
-		fi;
+    fi;
 
-		if [ ${DRY_RUN} -eq 1 ]; then
+    if [ ${DRY_RUN} -eq 1 ]; then
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Dry-Run mode is ON - No changes will be made to existing network settings or stored configurations";
       echo "";
       echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  Please call again using syntax  [ ${0} --dry-run 0 ]  or  [ ${0} --force ]";
-		fi;
+    fi;
 
-		# ------------------------------------------------------------
-		# Apply Changes
-		#
-		if [[ -f "/etc/init.d/network" ]]; then # CentOS-RHEL distros
+    # ------------------------------------------------------------
+    # Apply Changes
+    #
+    if [[ -f "/etc/init.d/network" ]]; then # CentOS-RHEL distros
       if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         echo "";
         echo "Network Manager must be restarted to apply changes ( required command  [ /etc/init.d/network restart ]  )";
@@ -419,7 +419,7 @@ else
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping network manager restart";
       fi;
-		else # [other] distros
+    else # [other] distros
       if [[ "${DRY_RUN}" == "0" ]]; then # NOT a dry-run
         echo "";
         echo "System restart required to apply changes to hostname";
@@ -438,8 +438,8 @@ else
       # 	echo "";
       # 	echo "$(date +'%Y-%m-%d %H:%M:%S') Info:  (Dry-Run Enabled) Skipping restart";
       fi;
-		fi;
-		echo "";
+    fi;
+    echo "";
 
 	fi;
 
diff --git a/usr/local/sbin/sudoer_status b/usr/local/sbin/sudoer_status
--- a/usr/local/sbin/sudoer_status
+++ b/usr/local/sbin/sudoer_status
@@ -48,19 +48,19 @@ else
 	# Walk through any inline-arguments passed to this function
 	for (( i=0;i<$COUNT_ARGS;i++ )); do
 
-		EACH_ARG=${ARGS[${i}]};
+    EACH_ARG=${ARGS[${i}]};
 
-		# Check if this is the last inline-argument or if there are more to follow
-		if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
+    # Check if this is the last inline-argument or if there are more to follow
+    if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
       NEXT_ARG="";
-		else
+    else
       NEXT_ARG=${ARGS[$((${i}+1))]};
       if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
         NEXT_ARG="";
       fi;
-		fi;
+    fi;
 
-		if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
+    if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
 
       # ------------------------------------------------------------
       if [ "${EACH_ARG}" == "--allow" ] || [ "${EACH_ARG}" == "--grant" ] || [ "${EACH_ARG}" == "--add" ] || [ "${EACH_ARG}" == "--deny" ] || [ "${EACH_ARG}" == "--revoke" ] || [ "${EACH_ARG}" == "--remove" ]; then
@@ -103,7 +103,7 @@ else
 
       # ------------------------------------------------------------
 
-		fi;
+    fi;
 
 	done;
 
@@ -111,30 +111,30 @@ else
 	# Verify validity of argument(s) passed to script
 	if [ -z "${TARGET_USER}" ]; then 
 
-		# Error: Empty/Unset target-user
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Target-user empty / unset";
-		echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
+    # Error: Empty/Unset target-user
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> Target-user empty / unset";
+    echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
 
 	elif [ $(id -u ${TARGET_USER} > /dev/null 2>&1; echo $?) -eq 1 ]; then
 
-		# Error: User not found
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found: \"${TARGET_USER}\"";
-		echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
+    # Error: User not found
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error --> User not found: \"${TARGET_USER}\"";
+    echo -e "${EXAMPLE_VALID_CALL}"; exit 1;
 
 	else
 
-		SUDOERS_D="";
-		if [ -d "/etc/sudoers.d" ]; then
+    SUDOERS_D="";
+    if [ -d "/etc/sudoers.d" ]; then
       SUDOERS_D="/etc/sudoers.d";
-		elif [ -d "/etc/local/sudoers.d" ]; then
+    elif [ -d "/etc/local/sudoers.d" ]; then
       SUDOERS_D="/etc/local/sudoers.d";
-		fi;
+    fi;
 
-		if [ -z "${SUDOERS_D}" ]; then
+    if [ -z "${SUDOERS_D}" ]; then
       echo "";
       echo "Error:  No sudoers.d directory found amongst \"/etc/sudoers.d/\" and \"/etc/local/sudoers.d\"";
 
-		else
+    else
       
       # ------------------------------------------------------------
       if [ "${EDIT_ACTION}" == "ALLOW" ]; then 
@@ -183,14 +183,14 @@ else
 
       fi;
 
-		# ------------------------------------------------------------
-		# Show sudoer status for target user
-		sudo -l -U "${TARGET_USER}";
+    # ------------------------------------------------------------
+    # Show sudoer status for target user
+    sudo -l -U "${TARGET_USER}";
 
-		fi;
+    fi;
 
 
-		# ------------------------------------------------------------
+    # ------------------------------------------------------------
 	fi;
 
 fi;
diff --git a/usr/local/sbin/ufw_ipv6_setup b/usr/local/sbin/ufw_ipv6_setup
--- a/usr/local/sbin/ufw_ipv6_setup
+++ b/usr/local/sbin/ufw_ipv6_setup
@@ -31,13 +31,13 @@ else
 	SERVICE_NAME="ufw";
 	SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
 	if [ ${SERVICE_RET_CODE} -eq 0 ]; then
-		# ------------------------------------------------------------
-		#
-		# UFW | IPv6 Pinging
-		#  |--> Check whether UFW currently allows IPv6 Ping requests or not, then asks to enable/disable it (depending on status)
-		#
-		ALLOW_ICMPv6_ECHO=$(cat "/etc/ufw/before6.rules" | sed --regexp-extended --quiet --expression='s/^-A ufw6-before-input -p icmpv6 --icmpv6-type echo-request -j ACCEPT$/\0/p');
-		if [ -n "${ALLOW_ICMPv6_ECHO}" ]; then
+    # ------------------------------------------------------------
+    #
+    # UFW | IPv6 Pinging
+    #  |--> Check whether UFW currently allows IPv6 Ping requests or not, then asks to enable/disable it (depending on status)
+    #
+    ALLOW_ICMPv6_ECHO=$(cat "/etc/ufw/before6.rules" | sed --regexp-extended --quiet --expression='s/^-A ufw6-before-input -p icmpv6 --icmpv6-type echo-request -j ACCEPT$/\0/p');
+    if [ -n "${ALLOW_ICMPv6_ECHO}" ]; then
       echo -e "\n""IPv6 Pinging is currently ENABLED";
       read -p "DISABLE IPv6 Pinging, Now? ( y/n )  " -n 1 -t 20 -r; echo ""; # Await single keypress
       if [[ $REPLY =~ ^[Yy]$ ]]; then
@@ -49,7 +49,7 @@ else
           "/etc/ufw/before6.rules";
         RESTART_SERVICE_UFW=1;
       fi;
-		else
+    else
       echo -e "\n""IPv6 Pinging is currently DISABLED"; read -p "ENABLE IPv6 Pinging, Now? ( y/n )  " -n 1 -t 20 -r;
       if [[ $REPLY =~ ^[Yy]$ ]]; then
         sed \
@@ -60,14 +60,14 @@ else
           "/etc/ufw/before6.rules";
         RESTART_SERVICE_UFW=1;
       fi;
-		fi;
-		# ------------------------------------------------------------
-		#
-		# UFW | IPv6 Multicast
-		#  |--> Check whether UFW currently allows IPv6 Multicast requests or not, then asks to enable/disable it (depending on status)
-		#
-		ALLOW_ICMPv6_MULTICAST=$(cat "/etc/ufw/before6.rules" | sed --regexp-extended --quiet --expression='s/^-A ufw6-before-input -p icmpv6 --icmpv6-type 130 -j ACCEPT$/\0/p');
-		if [ -n "${ALLOW_ICMPv6_MULTICAST}" ]; then
+    fi;
+    # ------------------------------------------------------------
+    #
+    # UFW | IPv6 Multicast
+    #  |--> Check whether UFW currently allows IPv6 Multicast requests or not, then asks to enable/disable it (depending on status)
+    #
+    ALLOW_ICMPv6_MULTICAST=$(cat "/etc/ufw/before6.rules" | sed --regexp-extended --quiet --expression='s/^-A ufw6-before-input -p icmpv6 --icmpv6-type 130 -j ACCEPT$/\0/p');
+    if [ -n "${ALLOW_ICMPv6_MULTICAST}" ]; then
       echo -e "\n""IPv6 Multicast is currently ENABLED";
       read -p "DISABLE IPv6 Multicast, Now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
       echo "";
@@ -80,7 +80,7 @@ else
           "/etc/ufw/before6.rules";
         RESTART_SERVICE_UFW=1;
       fi;
-		else
+    else
       echo -e "\n""IPv6 Multicast is currently DISABLED";
       read -p "ENABLE IPv6 Multicast, Now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
       echo "";
@@ -93,18 +93,18 @@ else
           "/etc/ufw/before6.rules";
         RESTART_SERVICE_UFW=1;
       fi;
-		fi;
-		# ------------------------------------------------------------
-		# Restart necessary service(s)
-		# ------------------------------------------------------------
-		if [ ${RESTART_SERVICE_UFW} -eq 1 ]; then
+    fi;
+    # ------------------------------------------------------------
+    # Restart necessary service(s)
+    # ------------------------------------------------------------
+    if [ ${RESTART_SERVICE_UFW} -eq 1 ]; then
       SERVICE_NAME="ufw";
       /usr/sbin/service "${SERVICE_NAME}" restart;
       # /usr/sbin/service "${SERVICE_NAME}" status;
-		fi;
+    fi;
 	else
-		echo "Error: Service \"${SERVICE_NAME}\" NOT found as a local service";
-		exit 1;
+    echo "Error: Service \"${SERVICE_NAME}\" NOT found as a local service";
+    exit 1;
 	fi;
 fi;
 
diff --git a/usr/local/sbin/update_dns_config b/usr/local/sbin/update_dns_config
--- a/usr/local/sbin/update_dns_config
+++ b/usr/local/sbin/update_dns_config
@@ -51,20 +51,20 @@ else
 	# Walk through any inline-arguments passed to this function
 	for (( i=0;i<$COUNT_ARGS;i++ )); do
 
-		EACH_ARG=${ARGS[${i}]};
-		# BASH_ARG_NUMBER=$((${i}+1)); # Bash arg-number is one greater than the ARGS arg-number -> this is due-to bash's ${0} arg, which contains the base-command
+    EACH_ARG=${ARGS[${i}]};
+    # BASH_ARG_NUMBER=$((${i}+1)); # Bash arg-number is one greater than the ARGS arg-number -> this is due-to bash's ${0} arg, which contains the base-command
 
-		# Check if this is the last inline-argument or if there are more to follow
-		if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
+    # Check if this is the last inline-argument or if there are more to follow
+    if [ $((${i}+1)) -eq ${COUNT_ARGS} ]; then # if this is the last argument
       NEXT_ARG="";
-		else
+    else
       NEXT_ARG=${ARGS[$((${i}+1))]};
       if [[ "${NEXT_ARG}" == "--"* ]]; then # Do not allow inline-arguments starting with "--..." to use the next bash-argument as an associated value if it, also, starts with "--..."
         NEXT_ARG="";
       fi;
-		fi;
+    fi;
 
-		if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
+    if [ -n "${EACH_ARG}" ]; then # Parse each non-empty inline argument
 
       # Parse inline hostname
       if [ ${i} -eq 0 ] && [ -n "${EACH_ARG}" ] && [[ "${EACH_ARG}" != "-"* ]]; then # Allow the first argument to be the hostname (without needing --hostname before it)
@@ -125,17 +125,17 @@ else
         fi;
       fi;
 
-		fi;
+    fi;
 	done;
 
 	# ------------------------------------------------------------
 
 	if [ $(which nmcli 2>'/dev/null' | wc -l;) -gt 0 ]; then
-		#
-		# Prioritize DHCP DNS Nameservers from nmcli (NetworkManager), where available
-		#
-		DNSV4_SERVERS=$(nmcli device show | grep 'IP4.DNS' | awk '{print $2}');
-		if [ -n "${DNSV4_SERVERS}" ]; then
+    #
+    # Prioritize DHCP DNS Nameservers from nmcli (NetworkManager), where available
+    #
+    DNSV4_SERVERS=$(nmcli device show | grep 'IP4.DNS' | awk '{print $2}');
+    if [ -n "${DNSV4_SERVERS}" ]; then
       for EACH_DNSV4_SERVER in ${DNSV4_SERVERS}; do
         if [ -z "${DHCP_NAMESRVR_1}" ]; then
           DHCP_NAMESRVR_1="${EACH_DNSV4_SERVER}"; # Set primary DNS Server
@@ -145,7 +145,7 @@ else
           DHCP_NAMESRVR_3="${EACH_DNSV4_SERVER}"; # Set tertiary DNS Server
         fi;
       done;
-		fi;
+    fi;
 	fi;
 
 
@@ -215,11 +215,11 @@ else
 	IS_LINUX=$(if [[ $(uname -s | grep Linux | wc -l) -gt 0 ]]; then echo 1; else echo 0; fi; );
 	IS_WINDOWS_WSL=$(if [[ "$(< /proc/version)" == *@(Microsoft|WSL)* ]]; then echo 1; else echo 0; fi; );
 	if [ "${IS_LINUX}" != "1" ]; then
-		echo -e "\n""Error:  Must run in a Linux-based environment";
-		exit 1;
+    echo -e "\n""Error:  Must run in a Linux-based environment";
+    exit 1;
 
 	elif [ "${IS_WINDOWS_WSL}" != "1" ]; then
-		if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
+    if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
 
       #
       # Required package:
@@ -264,10 +264,10 @@ else
         echo ""; exit 1;
       fi;
 
-		else
+    else
       echo "Error:  Linux kernel/distro not supported";
       exit 1;
-		fi;
+    fi;
 	fi;
 
 	# Network config filepaths
@@ -282,14 +282,14 @@ else
 
 	if [ -n "${NMCLI_CONF}" ]; then
 
-		# NetworkManager Device Configuration
+    # NetworkManager Device Configuration
 
-		if [ ! -f "${NMCLI_CONF}" ]; then 
+    if [ ! -f "${NMCLI_CONF}" ]; then 
 
       echo "ERROR: DNS Config-File not found @ path \"${NMCLI_CONF}\" - exiting...";
       exit 1;
 
-		else
+    else
 
       if [ ${USE_STATIC_IPV4} -eq 1 ]; then
 
@@ -459,56 +459,56 @@ else
         exit 1;
       fi;
 
-		fi;
+    fi;
 
 	else # ------------------------------------------------------------
 
-		/usr/bin/networkctl status;
+    /usr/bin/networkctl status;
 
-		# Resolv.conf
+    # Resolv.conf
 
-		FILE_DNS_BUILDER_BASE="/etc/resolvconf/resolv.conf.d/base";
-		FILE_DNS_BUILDER_TAIL="/etc/resolvconf/resolv.conf.d/base";
-		FILE_NETWORK_RESOLVER="${FILE_DNS_BUILDER_BASE}";
-		FILE_NETWORK_RESOLVER="${FILE_DNS_BUILDER_TAIL}";
-		if [ "${IS_WINDOWS_WSL}" == "1" ]; then
+    FILE_DNS_BUILDER_BASE="/etc/resolvconf/resolv.conf.d/base";
+    FILE_DNS_BUILDER_TAIL="/etc/resolvconf/resolv.conf.d/base";
+    FILE_NETWORK_RESOLVER="${FILE_DNS_BUILDER_BASE}";
+    FILE_NETWORK_RESOLVER="${FILE_DNS_BUILDER_TAIL}";
+    if [ "${IS_WINDOWS_WSL}" == "1" ]; then
       FILE_NETWORK_RESOLVER="${ETC_RESOLVCONF}"; # Windows subsystem for linux - wipe all of resolver (for testing-only as it is rebuilt on WSL-close, or 'shut down' from its perspective)
-		fi;
+    fi;
 
-		# Backup-filepaths
-		BACKUP_CONFIGS_DIR="/root/backup/update_dns_config";
-		OLD_BACKUP_CONFIGS_DIR="/root/backup_network_configs";
-		if [ -d "${OLD_BACKUP_CONFIGS_DIR}" ]; then
+    # Backup-filepaths
+    BACKUP_CONFIGS_DIR="/root/backup/update_dns_config";
+    OLD_BACKUP_CONFIGS_DIR="/root/backup_network_configs";
+    if [ -d "${OLD_BACKUP_CONFIGS_DIR}" ]; then
       mkdir -p $(dirname "${BACKUP_CONFIGS_DIR}");
       mv "${OLD_BACKUP_CONFIGS_DIR}" "${BACKUP_CONFIGS_DIR}";
-		else
+    else
       mkdir -p "${BACKUP_CONFIGS_DIR}";
-		fi;
-		chmod 700 "${BACKUP_CONFIGS_DIR}"; chown "root:root" "${BACKUP_CONFIGS_DIR}";
+    fi;
+    chmod 700 "${BACKUP_CONFIGS_DIR}"; chown "root:root" "${BACKUP_CONFIGS_DIR}";
 
-		# Backup necesarry config file(s), if-existent
-		FILE_TO_BACKUP="${ETC_RESOLVCONF}";
-		if [ -f "${FILE_TO_BACKUP}" ]; then
+    # Backup necesarry config file(s), if-existent
+    FILE_TO_BACKUP="${ETC_RESOLVCONF}";
+    if [ -f "${FILE_TO_BACKUP}" ]; then
       BASENAME_TO_BACKUP=$(basename "${FILE_TO_BACKUP}");
       echo -e "\n""Info:  Calling [ cp -f \"${FILE_TO_BACKUP}\" \"${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak\"; ]...";
       cp -f "${FILE_TO_BACKUP}" "${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak";
-		fi;
-		FILE_TO_BACKUP="${DEBIAN_NETWORK_CONF}";
-		if [ -f "${FILE_TO_BACKUP}" ]; then
+    fi;
+    FILE_TO_BACKUP="${DEBIAN_NETWORK_CONF}";
+    if [ -f "${FILE_TO_BACKUP}" ]; then
       BASENAME_TO_BACKUP=$(basename "${FILE_TO_BACKUP}");
       echo -e "\n""Info:  Calling [ cp -f \"${FILE_TO_BACKUP}\" \"${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak\"; ]...";
       cp -f "${FILE_TO_BACKUP}" "${BACKUP_CONFIGS_DIR}/${START_TIMESTAMP}_${BASENAME_TO_BACKUP}.bak";
-		fi;
+    fi;
 
-		# Setup the nameserver info to make it (eventually) into resolv.conf
-		echo "" > "${FILE_NETWORK_RESOLVER}";
-		if [ -n "${DNS_NAMESRVR_1}" ]; then echo "nameserver ${DNS_NAMESRVR_1}" >> "${FILE_NETWORK_RESOLVER}"; fi;
-		if [ -n "${DNS_NAMESRVR_2}" ]; then echo "nameserver ${DNS_NAMESRVR_2}" >> "${FILE_NETWORK_RESOLVER}"; fi;
-		if [ -n "${DNS_NAMESRVR_3}" ]; then echo "nameserver ${DNS_NAMESRVR_3}" >> "${FILE_NETWORK_RESOLVER}"; fi;
-		if [ -n "${DNS_SEARCH_DOMAIN}" ]; then echo "search ${DNS_SEARCH_DOMAIN}" >> "${FILE_NETWORK_RESOLVER}"; fi;
-		echo "" >> "${FILE_NETWORK_RESOLVER}";
+    # Setup the nameserver info to make it (eventually) into resolv.conf
+    echo "" > "${FILE_NETWORK_RESOLVER}";
+    if [ -n "${DNS_NAMESRVR_1}" ]; then echo "nameserver ${DNS_NAMESRVR_1}" >> "${FILE_NETWORK_RESOLVER}"; fi;
+    if [ -n "${DNS_NAMESRVR_2}" ]; then echo "nameserver ${DNS_NAMESRVR_2}" >> "${FILE_NETWORK_RESOLVER}"; fi;
+    if [ -n "${DNS_NAMESRVR_3}" ]; then echo "nameserver ${DNS_NAMESRVR_3}" >> "${FILE_NETWORK_RESOLVER}"; fi;
+    if [ -n "${DNS_SEARCH_DOMAIN}" ]; then echo "search ${DNS_SEARCH_DOMAIN}" >> "${FILE_NETWORK_RESOLVER}"; fi;
+    echo "" >> "${FILE_NETWORK_RESOLVER}";
 
-		if [ "${IS_WINDOWS_WSL}" != "1" ]; then
+    if [ "${IS_WINDOWS_WSL}" != "1" ]; then
 
       # show "${ETC_RESOLVCONF}" file (configuration before-start)
       echo -e "\n""Info:  Calling [cat \"${ETC_RESOLVCONF}\"]";
@@ -714,7 +714,7 @@ else
         fi;
       fi;
 
-		fi;
+    fi;
 	
 	fi;
 
@@ -731,16 +731,16 @@ else
 	sleep 2;
 
 	if [ -f "${DEBIAN_NETWORK_CONF}" ]; then
-		echo -e "\n""Info:  Calling [cat \"${DEBIAN_NETWORK_CONF}\"]";
-		echo "${DASHES}"; cat "${DEBIAN_NETWORK_CONF}"; echo "${DASHES}";
+    echo -e "\n""Info:  Calling [cat \"${DEBIAN_NETWORK_CONF}\"]";
+    echo "${DASHES}"; cat "${DEBIAN_NETWORK_CONF}"; echo "${DASHES}";
 	elif [ -f "${NMCLI_CONF}" ]; then
-		echo -e "\n""Info:  Calling [cat \"${NMCLI_CONF}\"]";
-		echo "${DASHES}"; cat "${NMCLI_CONF}"; echo "${DASHES}";
+    echo -e "\n""Info:  Calling [cat \"${NMCLI_CONF}\"]";
+    echo "${DASHES}"; cat "${NMCLI_CONF}"; echo "${DASHES}";
 	fi;
 
 	if [ -f "${ETC_RESOLVCONF}" ]; then
-		echo -e "\n""Info:  Calling [cat \"${ETC_RESOLVCONF}\"]";
-		echo "${DASHES}"; cat "${ETC_RESOLVCONF}"; echo "${DASHES}";
+    echo -e "\n""Info:  Calling [cat \"${ETC_RESOLVCONF}\"]";
+    echo "${DASHES}"; cat "${ETC_RESOLVCONF}"; echo "${DASHES}";
 	fi;
 
 fi;
diff --git a/usr/local/sbin/update_from_git_repo b/usr/local/sbin/update_from_git_repo
--- a/usr/local/sbin/update_from_git_repo
+++ b/usr/local/sbin/update_from_git_repo
@@ -27,7 +27,7 @@ else
 
 	# Make sure required runtime(s) are installed
 	if [ -z "$(which dos2unix 2>'/dev/null')" ]; then
-		apt-get-update -y; apt-get install -y dos2unix;
+    apt-get-update -y; apt-get install -y dos2unix;
 	fi;
 	
 	DIR_REPO_BASE="";
@@ -35,113 +35,113 @@ else
 	# Detect & handle WSL instance(s)
 	WSL_CHECK_EXISTS=$(which get_username_windows_wsl 2>'/dev/null');
 	if [ -n "${WSL_CHECK_EXISTS}" ]; then
-		WIN32_USERNAME=$(get_username_windows_wsl);
-		WIN32_USER_ERRORS="$?";
+    WIN32_USERNAME=$(get_username_windows_wsl);
+    WIN32_USER_ERRORS="$?";
 	fi;
 	if [ -n "${WIN32_USER_ERRORS}" ] && [ "${WIN32_USER_ERRORS}" == "0" ]; then
-		#  Windows OS running WSL (Windows Subsystem for Linux) - Locate source directory from amongst Win32-Host-User's files
-		WIN32_HOMEDIR=$(find /mnt/*/Users/${WIN32_USERNAME} -mindepth 0 -maxdepth 0 -type d);
-		WIN32_USR_LOCAL=$(find ${WIN32_HOMEDIR}/Documents -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
-		if [ ! -n "${WIN32_USR_LOCAL}" ]; then
+    #  Windows OS running WSL (Windows Subsystem for Linux) - Locate source directory from amongst Win32-Host-User's files
+    WIN32_HOMEDIR=$(find /mnt/*/Users/${WIN32_USERNAME} -mindepth 0 -maxdepth 0 -type d);
+    WIN32_USR_LOCAL=$(find ${WIN32_HOMEDIR}/Documents -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
+    if [ ! -n "${WIN32_USR_LOCAL}" ]; then
       echo "";
       echo "Unable to locate directory matching 'cloud-infrastructure/usr/local' within win32-user's documents @ '${WIN32_USERNAME}'";
       exit 1;
-		else
+    else
       DIR_REPO_USR="$(dirname ${WIN32_USR_LOCAL})";
       DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
-		fi;
+    fi;
 
 	else
 
-		WHOAMI_HOME_DIR="$(getent passwd $(id -un) | cut --delimiter=: --fields=6)";
-		WHOAMI_USR_LOCAL=$(find ${WHOAMI_HOME_DIR} -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
-		DIR_REPO_USR="$(dirname ${WHOAMI_USR_LOCAL})";
-		DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
-		SOURCE_DIR_ERRS=$?;
+    WHOAMI_HOME_DIR="$(getent passwd $(id -un) | cut --delimiter=: --fields=6)";
+    WHOAMI_USR_LOCAL=$(find ${WHOAMI_HOME_DIR} -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
+    DIR_REPO_USR="$(dirname ${WHOAMI_USR_LOCAL})";
+    DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
+    SOURCE_DIR_ERRS=$?;
 
-		if [ "${SOURCE_DIR_ERRS}" != "0" ] && [ -n "${SUDO_USER}" ]; then
+    if [ "${SOURCE_DIR_ERRS}" != "0" ] && [ -n "${SUDO_USER}" ]; then
       #  Linux OS - Locate source directory from amongst Non-Sudo User's files
       SUDOER_HOME_DIR="$(getent passwd ${SUDO_USER} | cut --delimiter=: --fields=6)";
       SUDOER_USR_LOCAL=$(find ${SUDOER_HOME_DIR} -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');
       DIR_REPO_USR="$(dirname ${SUDOER_USR_LOCAL})";
       DIR_REPO_BASE="$(dirname ${DIR_REPO_USR})";
       SOURCE_DIR_ERRS=$?;
-		fi;
+    fi;
 	
 	fi;
 
 	if [ -z "${DIR_REPO_BASE}" ]; then
-		# Error-out if any required variable(s) are empty/unset
-		EXIT_CODE=1;
+    # Error-out if any required variable(s) are empty/unset
+    EXIT_CODE=1;
 
-		echo "";
-		echo "Error: Required variable found to be empty/unset: \${DIR_REPO_BASE}";
+    echo "";
+    echo "Error: Required variable found to be empty/unset: \${DIR_REPO_BASE}";
 
 	elif [ ! -d "${DIR_REPO_BASE}/usr/local/bin/" ] || [ ! -d "${DIR_REPO_BASE}/usr/local/sbin/" ]; then
-		# Error-out if any required source directories are missing
-		EXIT_CODE=1;
+    # Error-out if any required source directories are missing
+    EXIT_CODE=1;
 
-		if [ ! -d "${DIR_REPO_BASE}/usr/local/bin/" ]; then
+    if [ ! -d "${DIR_REPO_BASE}/usr/local/bin/" ]; then
       echo "";
       echo "Error: Directory not-found: [ ${DIR_REPO_BASE}/usr/local/bin/ ]";
-		fi;
-		if [ ! -d "${DIR_REPO_BASE}/usr/local/sbin/" ]; then
+    fi;
+    if [ ! -d "${DIR_REPO_BASE}/usr/local/sbin/" ]; then
       echo "";
       echo "Error: Directory not-found: [ ${DIR_REPO_BASE}/usr/local/sbin/ ]";
-		fi;
+    fi;
 
 	else
-		# Required source directories exist - Update local runtimes from them
-		EXIT_CODE=0;
+    # Required source directories exist - Update local runtimes from them
+    EXIT_CODE=0;
 
-		# ------------------------------------------------------------
-		# Sync [ /usr/local/bin ] files (e.g. non-admin commands)
-		# ------------------------------------------------------------
-		echo "";
-		echo "Copying files from '${DIR_REPO_BASE}/usr/local/bin/*' to '/usr/local/bin/.' ...";
-		cp --verbose --force ${DIR_REPO_BASE}/usr/local/bin/* /usr/local/bin/.;
-		chown "root:root" /usr/local/bin/*;
-		chmod 0755 /usr/local/bin/*;
-		dos2unix --quiet /usr/local/bin/*;
+    # ------------------------------------------------------------
+    # Sync [ /usr/local/bin ] files (e.g. non-admin commands)
+    # ------------------------------------------------------------
+    echo "";
+    echo "Copying files from '${DIR_REPO_BASE}/usr/local/bin/*' to '/usr/local/bin/.' ...";
+    cp --verbose --force ${DIR_REPO_BASE}/usr/local/bin/* /usr/local/bin/.;
+    chown "root:root" /usr/local/bin/*;
+    chmod 0755 /usr/local/bin/*;
+    dos2unix --quiet /usr/local/bin/*;
 
-		# ------------------------------------------------------------
-		# Sync [ /usr/local/sbin ] files (e.g. admin-only commands)
-		# ------------------------------------------------------------
-		echo "";
-		echo "Copying files from '${DIR_REPO_BASE}/usr/local/sbin/*' to '/usr/local/sbin/.' ...";
-		cp --verbose --force ${DIR_REPO_BASE}/usr/local/sbin/* /usr/local/sbin/.;
-		chown "root:root" /usr/local/sbin/*;
-		chmod 0755 /usr/local/sbin/*;
-		dos2unix --quiet /usr/local/sbin/*;
+    # ------------------------------------------------------------
+    # Sync [ /usr/local/sbin ] files (e.g. admin-only commands)
+    # ------------------------------------------------------------
+    echo "";
+    echo "Copying files from '${DIR_REPO_BASE}/usr/local/sbin/*' to '/usr/local/sbin/.' ...";
+    cp --verbose --force ${DIR_REPO_BASE}/usr/local/sbin/* /usr/local/sbin/.;
+    chown "root:root" /usr/local/sbin/*;
+    chmod 0755 /usr/local/sbin/*;
+    dos2unix --quiet /usr/local/sbin/*;
 
-		echo "";
-		echo "Local bin & sbin are now synced with 'origin/master'";
-		echo "";
+    echo "";
+    echo "Local bin & sbin are now synced with 'origin/master'";
+    echo "";
 
-		# ------------------------------------------------------------
-		# Sync [ /home/USER/* ] files (e.g. bash-config & terminal-formatting files)
-		# ------------------------------------------------------------
+    # ------------------------------------------------------------
+    # Sync [ /home/USER/* ] files (e.g. bash-config & terminal-formatting files)
+    # ------------------------------------------------------------
 
-		# Get list of files to Copy into Home-Dirs
-		COPY_FROM_SOURCE="${DIR_REPO_BASE}/root";
-		FILES_TO_COPY=$(ls -hAl "${COPY_FROM_SOURCE}/" | awk '{print $9}');
+    # Get list of files to Copy into Home-Dirs
+    COPY_FROM_SOURCE="${DIR_REPO_BASE}/root";
+    FILES_TO_COPY=$(ls -hAl "${COPY_FROM_SOURCE}/" | awk '{print $9}');
 
-		# User-List whose Home-Dirs will be updated
-		LINUX_BASH_USERS=$(cat /etc/passwd | grep /bin/bash | awk -F':' '{ print $1}');
+    # User-List whose Home-Dirs will be updated
+    LINUX_BASH_USERS=$(cat /etc/passwd | grep /bin/bash | awk -F':' '{ print $1}');
 
-		# Determine longest Username to enhance log-readability by left-padding (right-aligning) output text, below
-		#   NOTE: Linux usernames cannot be longer than 32 chars (according to useradd man page)
-		USERNAMES_MOSTCHARS=0;
-		for EACH_SSH_USER in ${LINUX_BASH_USERS}; do
+    # Determine longest Username to enhance log-readability by left-padding (right-aligning) output text, below
+    #   NOTE: Linux usernames cannot be longer than 32 chars (according to useradd man page)
+    USERNAMES_MOSTCHARS=0;
+    for EACH_SSH_USER in ${LINUX_BASH_USERS}; do
       EACH_USERNAME_LENGTH=${#EACH_SSH_USER};
       if (( ${EACH_USERNAME_LENGTH} > ${USERNAMES_MOSTCHARS} )); then
         USERNAMES_MOSTCHARS=${EACH_USERNAME_LENGTH};
       fi;
-		done;
-		echo "";
-		echo "❖ Syncing Bash-Config & Terminal-Formatting files for SSH-Enabled users...";
-		# Begin copying files to SSH-Enabled User-Home Directories
-		for EACH_FILE in ${FILES_TO_COPY}; do
+    done;
+    echo "";
+    echo "❖ Syncing Bash-Config & Terminal-Formatting files for SSH-Enabled users...";
+    # Begin copying files to SSH-Enabled User-Home Directories
+    for EACH_FILE in ${FILES_TO_COPY}; do
       if [[ ! -z "${EACH_FILE// }" ]]; then # Ignore blank/empty filenames
         echo "    ↪ \"${EACH_FILE}\" (Home-Directory File)";
         SRC_FULLPATH="${COPY_FROM_SOURCE}/${EACH_FILE}";
@@ -170,13 +170,13 @@ else
           fi;
         done;
       fi;
-		done;
-		echo "";
+    done;
+    echo "";
 
-		# ------------------------------------------------------------
-		# Remove old/renamed scripts (if found to exist)
-		# ------------------------------------------------------------
-		TO_DEL="/usr/local/sbin/jenkins_war_update"; if [ -f "${TO_DEL}" ] && [ ! -h "${TO_DEL}" ]; then rm -f "${TO_DEL}"; fi;
+    # ------------------------------------------------------------
+    # Remove old/renamed scripts (if found to exist)
+    # ------------------------------------------------------------
+    TO_DEL="/usr/local/sbin/jenkins_war_update"; if [ -f "${TO_DEL}" ] && [ ! -h "${TO_DEL}" ]; then rm -f "${TO_DEL}"; fi;
 
 
 	fi;
diff --git a/usr/local/sbin/update_jenkins_warfile b/usr/local/sbin/update_jenkins_warfile
--- a/usr/local/sbin/update_jenkins_warfile
+++ b/usr/local/sbin/update_jenkins_warfile
@@ -28,48 +28,48 @@ else
 	JENKINS_DIRNAME_B="/usr/lib/jenkins";
 
 	if [ -f "${JENKINS_DIRNAME_A}/jenkins.war" ]; then
-		JENKINS_RUNTIME_SYSTEM="${JENKINS_DIRNAME_A}/jenkins.war";
+    JENKINS_RUNTIME_SYSTEM="${JENKINS_DIRNAME_A}/jenkins.war";
 	elif [ -f "${JENKINS_DIRNAME_B}/jenkins.war" ]; then
-		JENKINS_RUNTIME_SYSTEM="${JENKINS_DIRNAME_B}/jenkins.war";
+    JENKINS_RUNTIME_SYSTEM="${JENKINS_DIRNAME_B}/jenkins.war";
 	fi;
 
 	if [ -v JENKINS_RUNTIME_SYSTEM ] && [ -n "${JENKINS_RUNTIME_SYSTEM}" ] && [ -f "${JENKINS_RUNTIME_SYSTEM}" ]; then
 
-		# Backup the current Jenkins main-executable (jenkins.war)
-		JENKINS_RUNTIME_BACKUP="${JENKINS_RUNTIME_SYSTEM}.$(date +'%Y%m%d_%H%M%S').bak";
-		JENKINS_RUNTIME_DOWNLOADED="${JENKINS_RUNTIME_SYSTEM}.$(date +'%Y%m%d_%H%M%S').wget";
+    # Backup the current Jenkins main-executable (jenkins.war)
+    JENKINS_RUNTIME_BACKUP="${JENKINS_RUNTIME_SYSTEM}.$(date +'%Y%m%d_%H%M%S').bak";
+    JENKINS_RUNTIME_DOWNLOADED="${JENKINS_RUNTIME_SYSTEM}.$(date +'%Y%m%d_%H%M%S').wget";
 
-		# Download an updated version of the Jenkins main-executable (jenkins.war)
-		echo "";
-		echo "$(date +'%D  %r')   Downloading Latest version of Jenkins...";
-		WGET_LOGFILE="${LOGFILE}.wget";
-		if [ -f "${WGET_LOGFILE}" ]; then
+    # Download an updated version of the Jenkins main-executable (jenkins.war)
+    echo "";
+    echo "$(date +'%D  %r')   Downloading Latest version of Jenkins...";
+    WGET_LOGFILE="${LOGFILE}.wget";
+    if [ -f "${WGET_LOGFILE}" ]; then
       rm -f "${WGET_LOGFILE}";
-		fi;
-		DOWNLOAD_URL="https://updates.jenkins-ci.org/latest/jenkins.war";
-		wget --quiet --server-response --output-document="${JENKINS_RUNTIME_DOWNLOADED}" --output-file="${WGET_LOGFILE}" "${DOWNLOAD_URL}";
+    fi;
+    DOWNLOAD_URL="https://updates.jenkins-ci.org/latest/jenkins.war";
+    wget --quiet --server-response --output-document="${JENKINS_RUNTIME_DOWNLOADED}" --output-file="${WGET_LOGFILE}" "${DOWNLOAD_URL}";
 
-		# Log the relevant info from the version which was just downloaded
-		cat "${WGET_LOGFILE}";
-		# printf "$(date +'%D  %r')   " && cat "${WGET_LOGFILE}" | grep "Location: ${DOWNLOAD_URL}";
-		# printf "$(date +'%D  %r')   " && cat "${WGET_LOGFILE}" | grep "Last-Modified: ";
-		rm -f "${WGET_LOGFILE}";
+    # Log the relevant info from the version which was just downloaded
+    cat "${WGET_LOGFILE}";
+    # printf "$(date +'%D  %r')   " && cat "${WGET_LOGFILE}" | grep "Location: ${DOWNLOAD_URL}";
+    # printf "$(date +'%D  %r')   " && cat "${WGET_LOGFILE}" | grep "Last-Modified: ";
+    rm -f "${WGET_LOGFILE}";
 
-		# Verify that download actually downloaded more than 0 bytes
-		DOWNLOAD_FILESIZE=$(du -sh "${JENKINS_RUNTIME_DOWNLOADED}" | awk '{print $1}');
+    # Verify that download actually downloaded more than 0 bytes
+    DOWNLOAD_FILESIZE=$(du -sh "${JENKINS_RUNTIME_DOWNLOADED}" | awk '{print $1}');
 
-		# Compare Jenkins Versions
-		JENKINS_VERSION_SYSTEM=$(java -jar "${JENKINS_RUNTIME_SYSTEM}" --version | sed -rn --expression='s/^([0-9]{1,10}\.?)+[0-9]{1,10}$/\0/p');
-		JENKINS_VERSION_DOWNLOADED=$(java -jar "${JENKINS_RUNTIME_DOWNLOADED}" --version | sed -rn --expression='s/^([0-9]{1,10}\.?)+[0-9]{1,10}$/\0/p'); 
+    # Compare Jenkins Versions
+    JENKINS_VERSION_SYSTEM=$(java -jar "${JENKINS_RUNTIME_SYSTEM}" --version | sed -rn --expression='s/^([0-9]{1,10}\.?)+[0-9]{1,10}$/\0/p');
+    JENKINS_VERSION_DOWNLOADED=$(java -jar "${JENKINS_RUNTIME_DOWNLOADED}" --version | sed -rn --expression='s/^([0-9]{1,10}\.?)+[0-9]{1,10}$/\0/p'); 
 
-		echo "";
-		echo "$(date +'%D  %r')   DOWNLOAD_FILESIZE = \"${DOWNLOAD_FILESIZE}\"";
-		if [ ! -n "${JENKINS_VERSION_DOWNLOADED}" ] || [ "${JENKINS_VERSION_DOWNLOADED}" == "" ]; then
+    echo "";
+    echo "$(date +'%D  %r')   DOWNLOAD_FILESIZE = \"${DOWNLOAD_FILESIZE}\"";
+    if [ ! -n "${JENKINS_VERSION_DOWNLOADED}" ] || [ "${JENKINS_VERSION_DOWNLOADED}" == "" ]; then
       echo "";
       echo "$(date +'%D  %r')   Empty runtime detected: \"${JENKINS_RUNTIME_SYSTEM}\"";
       echo "$(date +'%D  %r')   Reverting to previous runtime: \"${JENKINS_RUNTIME_BACKUP}\"";
 
-		else
+    else
       # Compare Jenkins Versions
       JENKINS_VERSION_SYSTEM=$(java -jar "${JENKINS_RUNTIME_SYSTEM}" --version);
       JENKINS_VERSION_DOWNLOADED=$(java -jar "${JENKINS_RUNTIME_DOWNLOADED}" --version);
@@ -153,17 +153,17 @@ else
 
       fi;
 
-		fi;
+    fi;
 
-		# Exit Gracefully
-		echo "";
-		echo "$(date +'%D  %r')   Finished ${0}";
-		exit 0;
+    # Exit Gracefully
+    echo "";
+    echo "$(date +'%D  %r')   Finished ${0}";
+    exit 0;
 
 	else
-		# Error:  File Not Found: Jenkins Warfile (System Runtime File)
-		echo "Error:  File Not Found: Jenkins Warfile (System Runtime File)";
-		exit 1;
+    # Error:  File Not Found: Jenkins Warfile (System Runtime File)
+    echo "Error:  File Not Found: Jenkins Warfile (System Runtime File)";
+    exit 1;
 
 	fi;
 fi;
diff --git a/usr/local/sbin/update_text_editor b/usr/local/sbin/update_text_editor
--- a/usr/local/sbin/update_text_editor
+++ b/usr/local/sbin/update_text_editor
@@ -29,27 +29,27 @@ else
 	DESIRED_EDITOR_NAME="vi";
 	
 	if [ -z "$(which ${DESIRED_EDITOR_NAME} 2>'/dev/null' 2>'/dev/null')" ]; then
-		# Desired editor NOT installed --> Attempt to install it
-		apt-get update -y;
-		apt-get install -y "${DESIRED_EDITOR_NAME}";
+    # Desired editor NOT installed --> Attempt to install it
+    apt-get update -y;
+    apt-get install -y "${DESIRED_EDITOR_NAME}";
 	fi;
 
 	if [ -z "$(which ${DESIRED_EDITOR_NAME} 2>'/dev/null' 2>'/dev/null')" ]; then
-		# Desired editor STILL not installed (unable to be installed)
-		echo "";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Unable to install \"${DESIRED_EDITOR_NAME}\"";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Global editor setting \"${SYSTEM_EDITOR_1_PATH}\" will remain set to: \"${SYSTEM_EDITOR_1_RESOLVED}\"";
-		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Global editor setting \"${SYSTEM_EDITOR_2_PATH}\" will remain set to: \"${SYSTEM_EDITOR_2_RESOLVED}\"";
-		exit 1;
+    # Desired editor STILL not installed (unable to be installed)
+    echo "";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Unable to install \"${DESIRED_EDITOR_NAME}\"";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Global editor setting \"${SYSTEM_EDITOR_1_PATH}\" will remain set to: \"${SYSTEM_EDITOR_1_RESOLVED}\"";
+    echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Global editor setting \"${SYSTEM_EDITOR_2_PATH}\" will remain set to: \"${SYSTEM_EDITOR_2_RESOLVED}\"";
+    exit 1;
 
 	else
-		# Desired editor IS installed
-		declare -a EDITOR_PATHS_TO_UPDATE=( \
+    # Desired editor IS installed
+    declare -a EDITOR_PATHS_TO_UPDATE=( \
       "${SYSTEM_EDITOR_1_PATH}" \
       "${SYSTEM_EDITOR_2_PATH}" \
-		);
-		# Replace each editor with desired editor (if needed
-		for EACH_EDITOR_PATH in "${EDITOR_PATHS_TO_UPDATE[@]}"; do
+    );
+    # Replace each editor with desired editor (if needed
+    for EACH_EDITOR_PATH in "${EDITOR_PATHS_TO_UPDATE[@]}"; do
       if [ ! -e "${EACH_EDITOR_PATH}" ]; then
         # Editor filepath doesn't exist, yet
         echo "";
@@ -75,13 +75,13 @@ else
         echo "";
         echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Skipped - \"${EACH_EDITOR_PATH}\" already points to \"$(realpath $(which ${DESIRED_EDITOR_NAME} 2>'/dev/null'))\"";
       fi;
-		done;
+    done;
 
-		# Exit Gracefully
-		echo "";
-		echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Finished \"$(basename ${0})\"";
-		echo "";
-		exit 0;
+    # Exit Gracefully
+    echo "";
+    echo "$(date '+%Y-%m-%d %H:%M:%S') | Info: Finished \"$(basename ${0})\"";
+    echo "";
+    exit 0;
 
 	fi;
 fi;
diff --git a/usr/local/sbin/wsl_shutdown b/usr/local/sbin/wsl_shutdown
--- a/usr/local/sbin/wsl_shutdown
+++ b/usr/local/sbin/wsl_shutdown
@@ -27,22 +27,22 @@ else
 	#       terminals, otherwise the linux environment persists the background as a service (essentially hidden)
 	#
 	if [ -f "/usr/local/bin/get_os" ] && [ $("/usr/local/bin/get_os" | grep 'WSL' | wc -l;) -eq 1 ]; then
-		source /usr/local/bin/get_os 1>'/dev/null' 2>&1;
+    source /usr/local/bin/get_os 1>'/dev/null' 2>&1;
 
-		echo "";
-		echo "Info:  Creating file \"/var/run/reboot-required\"...";
-		sudo touch "/var/run/reboot-required";
+    echo "";
+    echo "Info:  Creating file \"/var/run/reboot-required\"...";
+    sudo touch "/var/run/reboot-required";
 
-		echo "";
-		echo "Info:  Press CTRL+D (may need to press more than once) to finish WSL shutdown";
-		echo "";
+    echo "";
+    echo "Info:  Press CTRL+D (may need to press more than once) to finish WSL shutdown";
+    echo "";
 
 	else
-		# Non-WSL Environment detected
-		echo "";
-		echo "Info:  Skipping shutdown (unable to detect WSL environment)";
-		echo "";
-		exit 1;
+    # Non-WSL Environment detected
+    echo "";
+    echo "Info:  Skipping shutdown (unable to detect WSL environment)";
+    echo "";
+    exit 1;
 
 	fi;
 fi;
