Update docker_create_jenkins

diff --git a/usr/local/bin/docker_create_jenkins b/usr/local/bin/docker_create_jenkins
--- a/usr/local/bin/docker_create_jenkins
+++ b/usr/local/bin/docker_create_jenkins
@@ -51,10 +51,10 @@ else
 		ERROR_SUGGEST_HELP="  |--> Expected user-input to be of type [ integer ], with value between [ ${MIN_KEY} ] and [ ${MAX_KEY} ], inclusive";
 		
 		# Let the user determine which tag (image-revision) to build-from
-		MAX_READ_WAIT=60; read -p "Select which Tag to build:  " -t ${MAX_READ_WAIT} -r; READ_RET_CODE=$?;
+		read -p "Select which Tag to build:  " -t 60 -r; READ_RET_CODE=$?;
 		if [ ${READ_RET_CODE} -gt 128 ]; then
 			# Error - Timeout reached for User-input ( from [ read --help ]: "The exit status is greater than 128 if the timeout is exceeded" )
-			echo -e "Error: Response timed out after ${MAX_READ_WAIT}s""\n""${ERROR_SUGGEST_HELP}";
+			echo -e "Error: Response timed out""\n""${ERROR_SUGGEST_HELP}";
 
 		elif [ -n "${REPLY}" ] && [[ ${REPLY} =~ ^-?[0-9]+$ ]] && [ ${REPLY} -ge ${MIN_KEY} ] && [ ${REPLY} -le ${MAX_KEY} ]; then
 			USER_SELECTION_KEY=$((0+${REPLY}));
