Update docker_sniper

diff --git a/usr/local/bin/docker_sniper b/usr/local/bin/docker_sniper
--- a/usr/local/bin/docker_sniper
+++ b/usr/local/bin/docker_sniper
@@ -14,7 +14,7 @@ DOCKER_NAME="pihole"; curl -H 'Cache-Control: no-cache' -s "https://raw.githubus
 fi;
 # ------------------------------------------------------------
 #
-#    Docker Snipe   -   by Cavalol
+#    Docker Sniper   -   by Cavalol
 #       Requires a single argument ($1): The name of the docker to snipe
 #         1.  Stops Instances similar to '$1'
 #         2.  Removes Containers similar to '$1'
@@ -24,17 +24,21 @@ fi;
 
 THIS_SCRIPT="docker_sniper";
 
+EXIT_CODE=0;
+
 # Header
-echo -e "\nStarting ${THIS_SCRIPT} at [ $(date +'%Y-%m-%dT%H:%M:%S%z')] "
+echo -e "\nStarting ${THIS_SCRIPT} at [ $(date +'%Y-%m-%dT%H:%M:%S%z')] ";
 
 if [ "$#" -ne 1 ]; then
   # Program was called with anything other than a single parameter
-  printf "\n   Error: '${THIS_SCRIPT}' Requires [1] Parameter (Docker-Substring-Target), Received [${#}] Parameters\n";
+  echo -e "\nError: '${THIS_SCRIPT}' Requires [1] Parameter (Docker-Substring-Target), Received [${#}] Parameters";
+  EXIT_CODE=1;
+
 else 
 
   # Correct # of parameters (just $1) - holds the name of dockers to stop
   DOCKER_NAME="${DOCKER_NAME:-${1}}";
-  printf "\nDocker Snipe - \"${DOCKER_NAME}\"\n"
+  echo -e "\nDocker Sniper - \"${DOCKER_NAME}\"";
   
   docker_ps_count=$(docker ps | grep ${DOCKER_NAME} | awk '{print $1}' | wc -l);
   docker_ps_all_count=$(docker ps --all | grep ${DOCKER_NAME} | awk '{print $1}' | wc -l);
@@ -45,57 +49,57 @@ else
   HEAD_TEXT="matching \"${DOCKER_NAME}\" stored locally - ";
   
   # Dockers Instances - Stop all running-Instances whichmatch the given Search-String
-  printf "[ ${docker_ps_count} ] Instances ${HEAD_TEXT}";
+  echo -n "[ ${docker_ps_count} ] Instances ${HEAD_TEXT}";
   if [ $docker_ps_count -gt 0 ]; then
-    printf "STOPPING via \"docker stop ...\":\n";
+    echo "STOPPING via \"docker stop ...\":";
     docker ps | grep ${DOCKER_NAME};
-    docker stop $(docker ps | grep ${DOCKER_NAME} | awk '{print $1}')
-    printf "\n";
+    docker stop $(docker ps | grep ${DOCKER_NAME} | awk '{print $1}';);
+    echo "";
   else
-    printf "No Action Necessary\n";
+    echo "No Action Necessary";
   fi;
   
   # Docker Containers - Remove all Containers which match the given Search-String
-  printf "[ ${docker_ps_all_count} ] Containers ${HEAD_TEXT}";
+  echo -n "[ ${docker_ps_all_count} ] Containers ${HEAD_TEXT}";
   if [ $docker_ps_all_count -gt 0 ]; then
-    printf "FORCE-REMOVING via \"docker rm --force ...\":\n";
+    echo  "FORCE-REMOVING via \"docker rm --force ...\":\n";
     docker ps --all | grep ${DOCKER_NAME};
     docker rm --force $(docker ps --all | grep ${DOCKER_NAME} | awk '{print $1}');
-    printf "\n";
+    echo "";
   else
-    printf "No Action Necessary\n";
+    echo "No Action Necessary";
   fi;
   
   # Kill Images
-  printf "[ ${docker_images_all_count} ] Images ${HEAD_TEXT}";
+  echo -n "[ ${docker_images_all_count} ] Images ${HEAD_TEXT}";
   if [ $docker_images_all_count -gt 0 ]; then
-    printf "FORCE-REMOVING via \"docker rmi --force ...\":\n";
+    echo "FORCE-REMOVING via \"docker rmi --force ...\":";
     docker images --all | grep ${DOCKER_NAME};
     # docker rmi --force $(docker images --all | grep ${DOCKER_NAME} | grep -v 'centos' | grep -v 'node' | awk '{print $3}');
     docker rmi --force $(docker images --all | grep ${DOCKER_NAME} | awk '{print $3}');
-    printf "\n";
+    echo "";
   else
-    printf "No Action Necessary\n";
+    echo "No Action Necessary";
   fi;
   
   # Kill Networks
-  printf "[ ${docker_networks_all_count} ] Networks ${HEAD_TEXT}";
+  echo -n "[ ${docker_networks_all_count} ] Networks ${HEAD_TEXT}";
   if [ $docker_networks_all_count -gt 0 ]; then
-    printf "FORCE-REMOVING via \"docker network rm ...\":\n";
+    echo "FORCE-REMOVING via \"docker network rm ...\":";
     docker network ls --format='{{.ID}}  {{.Name}}' | grep -v 'bridge' | grep -v 'host' | grep -v 'none' | grep ${DOCKER_NAME};
     docker network rm $(docker network ls --format='{{.ID}}  {{.Name}}' | grep -v 'bridge' | grep -v 'host' | grep -v 'none' | grep ${DOCKER_NAME} | awk '{print $1}');
-    printf "\n";
+    echo "";
   else
-    printf "No Action Necessary\n";
+    echo "No Action Necessary";
   fi;
   
   # Prune System
-  printf "[ - ] Clean up - Running generic sweep \"docker system prune --filter 'label=\"${DOCKER_NAME}\"' --force\":\n";
-  docker system prune --force --filter 'label="'${DOCKER_NAME}'"' --force;
+  echo "[ - ] Pruning (removing unused) containers, networks, images & volumes matching filter \"label='${DOCKER_NAME}'\"";
+  echo "      $(docker system prune --force --filter 'label="'${DOCKER_NAME}'"' --force;)" | grep -v '0B';
   
 fi;
   
 # Footer
-echo -e "\nFinished ${THIS_SCRIPT} at [ $(date +'%Y-%m-%dT%H:%M:%S%z')]"
+echo -e "\nFinished ${THIS_SCRIPT} at [ $(date +'%Y-%m-%dT%H:%M:%S%z')]";
 echo "";
-exit 0;
+exit ${EXIT_CODE};
