Update get_wan_ipv4

diff --git a/usr/local/bin/get_wan_ipv4 b/usr/local/bin/get_wan_ipv4
--- a/usr/local/bin/get_wan_ipv4
+++ b/usr/local/bin/get_wan_ipv4
@@ -20,33 +20,50 @@ fi;
 # Determine WAN IPv4
 #
 
-START_TIMESTAMP="$(date +'%Y%m%d_%H%M%S')";
 
-# ------------------------------------------------------------
-# External server(s) to resolve WAN-IP through
-#
-RESOLVER_1="https://icanhazip.com";
-RESOLVER_2="https://ipecho.net/plain";
-RESOLVER_3="https://ident.me";
-RESOLVER_4="https://bot.whatismyipaddress.com";
-
-### Get WAN-Outgoing IPv4
-if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_1}"); fi; RESOLVER_USED="${RESOLVER_1}";
-if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_2}"); fi; RESOLVER_USED="${RESOLVER_2}";
-if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_3}"); fi; RESOLVER_USED="${RESOLVER_3}";
-if [ -z "${THIS_WAN_IPV4}" ]; then THIS_WAN_IPV4=$(curl -4 -L -s "${RESOLVER_4}"); fi; RESOLVER_USED="${RESOLVER_4}";
-
+# START_TIMESTAMP="$(date +'%Y%m%d_%H%M%S')";
 # REGEX_IPV4='(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))';
 
-# ------------------------------------------------------------
-# Exit with appropriate return-code
-#
+# External servers to resolve WAN-IP through
+unset IP_RESOLVERS; declare -a IP_RESOLVERS; # [Re-]Instantiate bash array
+IP_RESOLVERS+=("https://icanhazip.com");
+IP_RESOLVERS+=("https://ipecho.net/plain");
+IP_RESOLVERS+=("https://ident.me");
+IP_RESOLVERS+=("https://bot.whatismyipaddress.com");
 
-if [ -v THIS_WAN_IPV4 ] && [ -n "${THIS_WAN_IPV4}" ]; then
-	echo -n "${THIS_WAN_IPV4}";
-	exit 0;
-else
+THIS_WAN_IPv4="";
+RESPONSE_SRVR="";
+LENGTH_WAN_IP="";
+
+# Get current WAN IPv4
+for EACH_SRVR in "${IP_RESOLVERS[@]}"; do
+	if [ -z "${THIS_WAN_IPv4}" ] || (( ${LENGTH_WAN_IP} > 15 )); then
+		RESPONSE_SRVR="${!EACH_SRVR}";
+		THIS_WAN_IPv4=$(curl -L -s "${RESPONSE_SRVR}");
+		LENGTH_WAN_IP=$(echo -n "${THIS_WAN_IPv4}" | wc -c);
+	fi;
+done;
+
+# Output Status: PASS or FAIL
+if [ -z "${THIS_WAN_IPv4}" ] || (( ${LENGTH_WAN_IP} > 15 )); then
+	# Error: Clear Variables
+	RESPONSE_SRVR="";
+	THIS_WAN_IPv4="";
+	LENGTH_WAN_IP="";
+	# Error: Show Message
+	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Unable to resolve WAN-IP";
+	# Error: Throw 'bad' return-code
 	exit 1;
+else
+	# Success - Show Message
+	if [ "${1}" == "verbose" ]; then
+		echo "";
+		echo "$(date +'%Y-%m-%d %H:%M:%S') | Resolved WAN-IP to \"${THIS_WAN_IPv4}\" via \"${RESPONSE_SRVR}\" ";
+		echo "";
+	fi;
+	echo -n "${THIS_WAN_IPv4}";
+	# Success - Throw 'good' return-code
+	exit 0;
 fi;
 
 #------------------------------------------------------------
