Update list_installed_packages

diff --git a/usr/local/bin/list_installed_packages b/usr/local/bin/list_installed_packages
--- a/usr/local/bin/list_installed_packages
+++ b/usr/local/bin/list_installed_packages
@@ -6,9 +6,26 @@
 
 if [ -n "$(which yum 2>'/dev/null';)" ]; then
 
-	INSTALLED_PACKAGES=$(yum list installed | sed -rne 's/^([a-zA-Z0-9\.\_\-]+)\.(x86_64|noarch)\s+.+$/\1/p';);
+	RET_CODE=1; # Default to error-ing out (return code of 1)
 
-	echo "${INSTALLED_PACKAGES}";
+	if [ $# -gt 0 ]; then
+		# Determine if argument $1 (if given) exists/is-installed as a local package
+		CHECK_FOR_LOCAL_PKG=$(yum list installed | sed -rne "s/^(${1})\.(x86_64|noarch)\s+.+$/\1/p";);
+		if [ -n "${CHECK_FOR_LOCAL_PKG}" ]; then
+			echo "Package \"${1}\" not found, locally";
+			RET_CODE=1;
+		else
+			echo "Package \"${1}\" already exists locally";
+			RET_CODE=0;
+		fi;
+	else
+		# If no arguments were passed to this function, then list all installed packages (without x86_64 / noarch extension after each)
+		INSTALLED_PACKAGES=$(yum list installed | sed -rne "s/^([a-zA-Z0-9\.\_\-]+)\.(x86_64|noarch)\s+.+$/\1/p";);
+		echo "${INSTALLED_PACKAGES}";
+		RET_CODE=2; # Don't report a success unnecesarilly (to avoid mixups with the single-package search, above
+	fi;
+
+	exit ${RET_CODE};
 
 fi;
 
