Update wsl_get_windows_username

diff --git a/usr/local/bin/wsl_get_windows_username b/usr/local/bin/wsl_get_windows_username
--- a/usr/local/bin/wsl_get_windows_username
+++ b/usr/local/bin/wsl_get_windows_username
@@ -1,10 +1,9 @@
 #!/bin/bash
-
-POTENTIAL_USERS_FILE="/tmp/potential_wsl_hosts_$(date +'%s%N')"; if [ -f "${POTENTIAL_USERS_FILE}" ]; then rm -f "${POTENTIAL_USERS_FILE}"; fi;
-INVALID_USERS_FILE="/tmp/invalid_wsl_hosts_$(date +'%s%N')"; if [ -f "${INVALID_USERS_FILE}" ]; then rm -f "${INVALID_USERS_FILE}"; fi;
-
-EXACT_MATCH="";
-
+#
+PotentialUsersFile="/tmp/potential_wsl_hosts_$(date +'%s%N')"; if [ -f "${PotentialUsersFile}" ]; then rm -f "${PotentialUsersFile}"; fi;
+#
+InvalidUsersFile="/tmp/invalid_wsl_hosts_$(date +'%s%N')"; if [ -f "${InvalidUsersFile}" ]; then rm -f "${InvalidUsersFile}"; fi;
+#
 find "/mnt/c/Users" \
 -mindepth 1 \
 -maxdepth 1 \
@@ -13,58 +12,47 @@ find "/mnt/c/Users" \
 -not -path "/mnt/c/Users/Default" \
 -not -path "/mnt/c/Users/Public" \
 -print0 \
-| while IFS= read -r -d $'\0' EACH_USER_DIR; do
-
-	LAST_EXIT_CODE=$([[ -r "${EACH_USER_DIR}/Documents" ]]; echo $?);
-
-	if [ "${LAST_EXIT_CODE}" == "0" ]; then
-	#	echo "PASS - Can read \"${EACH_USER_DIR}\" - Current session has sufficient privilege(s)";
-		echo "$(basename ${EACH_USER_DIR})" >> "${POTENTIAL_USERS_FILE}";
-
+| while IFS= read -r -d $'\0' EachUserDir; do
+	LastExitCode=$([[ -r "${EachUserDir}/Documents" ]]; echo $?);
+	if [ "${LastExitCode}" == "0" ]; then
+		if [ "${1}" == "verbose" ]; then echo "PASS - Can read \"${EachUserDir}\" - Current session has sufficient privilege(s)"; fi;
+		echo "$(basename ${EachUserDir})" >> "${PotentialUsersFile}";
 	else
-	#	echo "FAIL - Cannot read \"${EACH_USER_DIR}\" - Current session lacks sufficient privilege(s)";
-		echo "$(basename ${EACH_USER_DIR})" >> "${INVALID_USERS_FILE}";
-
+		if [ "${1}" == "verbose" ]; then echo "FAIL - Cannot read \"${EachUserDir}\" - Current session lacks sufficient privilege(s)"; fi;
+		echo "$(basename ${EachUserDir})" >> "${InvalidUsersFile}";
 	fi;
-
 done;
-
-USER_COUNT="$(cat ${POTENTIAL_USERS_FILE} | wc -l)";
-
-if [ $(echo "${USER_COUNT} >= 1" | bc) -eq 1 ]; then
-	#
-	# Matched more than 1 user - show them all
-	#
-	echo -e "\n";
-	echo "User-Documents directory is accessible for [ ${USER_COUNT} ] Windows User(s):";
-
-	cat "${POTENTIAL_USERS_FILE}" | while read EACH_MATCHED_USERNAME; do
-		echo "  ${EACH_MATCHED_USERNAME}";
-	done;
-
-	if [ $(echo "${USER_COUNT} == 1" | bc) -eq 1 ]; then
-		#
-		# Matched exactly 1 user - set user as "exact-match" host
-		#
-		EXACT_MATCH="$(cat ${POTENTIAL_USERS_FILE})";
-
+#
+if [ -f "${PotentialUsersFile}" ] then
+	CountMatchedUsers="$(cat ${PotentialUsersFile} | wc -l)";
+else
+	CountMatchedUsers="0";
+fi;
+#
+if [ $(echo "${CountMatchedUsers} == 1" | bc) -eq 1 ]; then # Matched exactly 1 user - output the user
+	if [ "${1}" == "verbose" ]; then
+		echo -e "\nFound [ ${CountMatchedUsers} ] potential WSL hosts-user(s):";
 	fi;
-
+	cat "${PotentialUsersFile}";
+	exit 0;
+elif [ $(echo "${CountMatchedUsers} > 1" | bc) -eq 1 ]; then # Matched more than 1 user - output the first-found
+	if [ "${1}" == "verbose" ]; then
+		echo -e "\nFound [ ${CountMatchedUsers} ] potential WSL hosts-user(s):";
+		cat "${PotentialUsersFile}" | while read EachMatchedUser; do
+			echo "${EachMatchedUser}";
+		done;
+	fi;
+	read -r FirstPotentialUser < "${PotentialUsersFile}";
+	echo "${FirstPotentialUser}";
+	exit 0;
 else
-	echo "No User-Documents found to be readable.";
+	echo "Error - No User-Documents found to be readable";
+	exit 1;
 fi;
-
-if [ -n "${EXACT_MATCH}" ]; then
+#
+if [ "${1}" == "verbose" ]; then
 	echo -e "\n";
-	echo "Current Linux-Instance hosted by Windows-User \"${EXACT_MATCH}\"";
-	export WSL_HOST_USERNAME="${EXACT_MATCH}";
-else
-	export WSL_HOST_USERNAME="";
 fi;
-
-
-echo -e "\n";
-
 #
 # Citation(s)
 #	
